// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Order (shop::commerce::Order)
// Customize via Order.extra.ts in this directory (additional queries, custom logic).
import { eq } from "drizzle-orm";

import type { BaseSQLiteDatabase } from "drizzle-orm/sqlite-core";
type Db = BaseSQLiteDatabase<"sync" | "async", unknown>;

import { type Order, OrderInsertSchema, orders } from "./Order";
export async function findOrderById(db: Db, id: number): Promise<Order | null> {
  const [order] = await db
    .select()
    .from(orders)
    .where(eq(orders.id, id))
    .limit(1);
  return order ?? null;
}
export async function listOrders(
  db: Db,
  opts?: { limit?: number; offset?: number },
): Promise<Order[]> {
  let q = db.select().from(orders).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createOrder(db: Db, data: unknown): Promise<Order> {
  const validated = OrderInsertSchema.parse(data);
  const [order] = await db.insert(orders).values(validated).returning();
  return order!;
}
export async function updateOrder(
  db: Db,
  id: number,
  data: unknown,
): Promise<Order | null> {
  const validated = OrderInsertSchema.partial().parse(data);
  const [order] = await db
    .update(orders)
    .set(validated)
    .where(eq(orders.id, id))
    .returning();
  return order ?? null;
}
export async function deleteOrderById(db: Db, id: number): Promise<boolean> {
  // Use .returning() unconditionally — supported on SQLite ≥3.35 (covers D1, libsql/Turso)
  // and Postgres. Result is an array of deleted rows; presence implies success.
  const deleted = await db.delete(orders).where(eq(orders.id, id)).returning();
  return deleted.length > 0;
}
