// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Order (shop::commerce::Order)
// Customize via Order.extra.tsx (custom layouts, per-field components, etc.).
import { Order, OrderInsertSchema } from "./Order";
import type { Order as OrderRow } from "./Order";
import { useEntityForm } from "@metaobjectsdev/react";
import type { ReactElement } from "react";
import type { SubmitHandler } from "react-hook-form";

export interface OrderFormProps {
  onSubmit: SubmitHandler<Partial<OrderRow>>;
  defaultValues?: Partial<OrderRow>;
  submitLabel?: string;
  className?: string;
}

/**
 * Generated React form for Order. All field metadata (name, label,
 * placeholder, html input type, RHF validation rules) comes from the
 * Order constants emitted alongside this file. Validation uses the
 * generated Zod schema, shared with the server-side Fastify route.
 *
 * Customize: this file is regenerated on every `forge gen`. If you need a
 * custom layout, write your own component using useEntityForm + the
 * Order constants directly.
 */
export function OrderForm(props: OrderFormProps): ReactElement {
  const form = useEntityForm(
    Order,
    OrderInsertSchema,
    props.defaultValues !== undefined ? { defaultValues: props.defaultValues } : {},
  );
  return (
    <form
      className={props.className ?? "metaobjects-form"}
      data-entity={Order.$entity}
      onSubmit={form.handleSubmit(props.onSubmit as never)}
    >
      <div className="metaobjects-field" key="customerId">
        <label className="metaobjects-field-label" htmlFor={Order.customerId.name}>{Order.customerId.label}</label>
        <input className="metaobjects-field-input" {...form.input.customerId} />
        {form.formState.errors.customerId !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.customerId?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="productId">
        <label className="metaobjects-field-label" htmlFor={Order.productId.name}>{Order.productId.label}</label>
        <input className="metaobjects-field-input" {...form.input.productId} />
        {form.formState.errors.productId !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.productId?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="quantity">
        <label className="metaobjects-field-label" htmlFor={Order.quantity.name}>{Order.quantity.label}</label>
        <input className="metaobjects-field-input" {...form.input.quantity} />
        {form.formState.errors.quantity !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.quantity?.message ?? "")}
          </span>
        )}
      </div>
      <button type="submit" disabled={form.formState.isSubmitting}>{props.submitLabel ?? "Submit"}</button>
    </form>
  );
}
