// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: Product (shop::commerce::Product)
// Customize via Product.extra.tsx (custom layouts, per-field components, etc.).
import { Product, ProductInsertSchema } from "./Product";
import type { Product as ProductRow } from "./Product";
import { useEntityForm } from "@metaobjects/react";
import type { ReactElement } from "react";
import type { SubmitHandler } from "react-hook-form";

export interface ProductFormProps {
  onSubmit: SubmitHandler<Partial<ProductRow>>;
  defaultValues?: Partial<ProductRow>;
  submitLabel?: string;
  className?: string;
}

/**
 * Generated React form for Product. All field metadata (name, label,
 * placeholder, html input type, RHF validation rules) comes from the
 * Product constants emitted alongside this file. Validation uses the
 * generated Zod schema, shared with the server-side Fastify route.
 *
 * Customize: this file is regenerated on every `forge gen`. If you need a
 * custom layout, write your own component using useEntityForm + the
 * Product constants directly.
 */
export function ProductForm(props: ProductFormProps): ReactElement {
  const form = useEntityForm(
    Product,
    ProductInsertSchema,
    props.defaultValues !== undefined ? { defaultValues: props.defaultValues } : {},
  );
  return (
    <form
      className={props.className ?? "metaobjects-form"}
      data-entity={Product.$entity}
      onSubmit={form.handleSubmit(props.onSubmit as never)}
    >
      <div className="metaobjects-field" key="name">
        <label className="metaobjects-field-label" htmlFor={Product.name.name}>{Product.name.label}</label>
        <input className="metaobjects-field-input" {...form.input.name} />
        {form.formState.errors.name !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.name?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="tagId">
        <label className="metaobjects-field-label" htmlFor={Product.tagId.name}>{Product.tagId.label}</label>
        <input className="metaobjects-field-input" {...form.input.tagId} />
        {form.formState.errors.tagId !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.tagId?.message ?? "")}
          </span>
        )}
      </div>
      <button type="submit" disabled={form.formState.isSubmitting}>{props.submitLabel ?? "Submit"}</button>
    </form>
  );
}
