"""Relationship subtype vocabulary (colocated)."""
from ....shared.base_types import SUBTYPE_BASE

RELATIONSHIP_SUBTYPE_ASSOCIATION = "association"
RELATIONSHIP_SUBTYPE_AGGREGATION = "aggregation"
RELATIONSHIP_SUBTYPE_COMPOSITION = "composition"

RELATIONSHIP_SUBTYPES = (
    SUBTYPE_BASE,
    RELATIONSHIP_SUBTYPE_ASSOCIATION,
    RELATIONSHIP_SUBTYPE_AGGREGATION,
    RELATIONSHIP_SUBTYPE_COMPOSITION,
)

RELATIONSHIP_ATTR_OBJECT_REF = "objectRef"
RELATIONSHIP_ATTR_CARDINALITY = "cardinality"
RELATIONSHIP_ATTR_FK_FIELD = "fkField"
RELATIONSHIP_ATTR_PARENT_FIELD = "parentField"
RELATIONSHIP_ATTR_JOIN_ENTITY = "joinEntity"
RELATIONSHIP_ATTR_JOIN_FIELDS = "joinFields"
