// AUTO-GENERATED by scripts/generate-embedded-metamodel.ts — DO NOT EDIT.
// Canonical source: repo-root spec/metamodel/ui.json
// Regenerate: bun run scripts/generate-embedded-metamodel.ts
//
// Embeds the canonical FR-033 ProviderDefinition so the provider can register
// itself wherever the on-disk spec/ tree is unavailable (bundled builds).
import type { ProviderDefinition } from "../../provider-data.js";

export const UI_DEFINITION: ProviderDefinition = {
  "provider": "metaobjects-ui",
  "extends": [
    {
      "type": "field",
      "subType": "*",
      "children": [
        {
          "type": "attr",
          "subType": "boolean",
          "name": "filterable",
          "min": 0,
          "max": 1,
          "description": "When true, the field is exposed in generated CRUD filter allowlists (Project D filter layer)."
        },
        {
          "type": "attr",
          "subType": "boolean",
          "name": "sortable",
          "min": 0,
          "max": 1,
          "description": "When true, the field is exposed in generated CRUD sort allowlists. Inherits from @filterable by default; set false to opt out."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "sortableDefaultOrder",
          "min": 0,
          "max": 1,
          "allowedValues": [
            "asc",
            "desc"
          ],
          "description": "Default sort direction applied when this field is the default sort field."
        }
      ]
    }
  ]
};
