// AUTO-GENERATED by scripts/generate-embedded-metamodel.ts — DO NOT EDIT.
// Canonical source: repo-root spec/metamodel/requirement.json
// Regenerate: bun run scripts/generate-embedded-metamodel.ts
//
// Embeds the canonical FR-033 ProviderDefinition so the provider can register
// itself wherever the on-disk spec/ tree is unavailable (bundled builds).
import type { ProviderDefinition } from "../../provider-data.js";

export const REQUIREMENT_DEFINITION: ProviderDefinition = {
  "provider": "metaobjects-core-types",
  "types": [
    {
      "type": "requirement",
      "subType": "functional",
      "description": "What the product does for a user, stated as one violable claim. Its check is EXISTENCE: it fails when nothing implements it. Hierarchy is nesting — an L1 solution contains its L2 segments, which contain L3 services, and so on down to the levels that reference the model.",
      "whenToUse": "Something exists because someone asked for it. Levels: 1 solution, 2 segment (an application or library), 3 service, 4 object, 5 member. Only L4 and L5 carry @implementedBy — L1-L3 are organisational and never reference the model.",
      "children": [
        {
          "type": "attr",
          "subType": "int",
          "name": "level",
          "min": 1,
          "max": 1,
          "description": "1 solution, 2 segment (application/library), 3 service, 4 object, 5 member. Nesting depth must agree with it."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "status",
          "min": 1,
          "max": 1,
          "allowedValues": [
            "live",
            "partial",
            "abandoned",
            "superseded"
          ],
          "description": "live implemented and in use; partial implemented with known gaps; abandoned built then deliberately retired; superseded replaced by a different mechanism. A dangling @implementedBy is an ERROR on live/partial (the model moved, the requirement is stale) and ALLOWED on abandoned/superseded (those nodes are meant to be gone — that is the entry doing its job)."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "statement",
          "min": 1,
          "max": 1,
          "description": "What the capability is, in one sentence."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "violation",
          "min": 1,
          "max": 1,
          "description": "What breaking it looks like, in one sentence. A requirement MUST be violable: 'every entity has a uuid primary key' is (point at one with a composite string key); 'things are persisted' is not, and is a description rather than a requirement."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "implementedBy",
          "isArray": true,
          "min": 0,
          "max": 1,
          "description": "FQN references to the model nodes realising this requirement. Legal on level 4 (an object) and level 5 (a field, view or identity) only; an organisational level carrying it is ERR_REQUIREMENT_LINK_ABOVE_FLOOR. Many-to-many by construction — several requirements may name the same node."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "verifiedBy",
          "isArray": true,
          "min": 0,
          "max": 1,
          "description": "Names of the tests proving the behaviour. verify checks each exists and is not skipped; it never runs them."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "supersededBy",
          "min": 0,
          "max": 1,
          "description": "The requirement that replaced this one. Expected on status=superseded."
        },
        {
          "type": "requirement",
          "subType": "*",
          "name": "*",
          "min": 0,
          "max": null,
          "description": "Nested child requirements. Hierarchy IS nesting — an L1 solution contains its L2 segments, which contain L3 services — so regrouping moves a node rather than editing a parent string, and a requirement is addressable by the same dotted child-name path as every other node."
        }
      ]
    },
    {
      "type": "requirement",
      "subType": "architectural",
      "description": "How the system is built, applied uniformly across the model. Its check is UNIVERSALITY: it fails when something VIOLATES it, which is the opposite polarity to a functional requirement. Carries no level and no parent — levels come from object-in-focus decomposition and an architectural requirement is object-independent by definition.",
      "whenToUse": "Something exists because every entity here looks like this — a uuid primary key, an @autoSet createdAt, a change-attribution column, tenant scoping. The discriminator is mechanical: did this exist because someone asked for something, or because it is the architecture?",
      "children": [
        {
          "type": "attr",
          "subType": "string",
          "name": "status",
          "min": 1,
          "max": 1,
          "allowedValues": [
            "live",
            "partial",
            "abandoned",
            "superseded"
          ],
          "description": "As on requirement.functional. A live or partial architectural requirement claimed by NOTHING is an error: a policy declared and applied to nothing."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "statement",
          "min": 1,
          "max": 1,
          "description": "The policy, in one sentence."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "violation",
          "min": 1,
          "max": 1,
          "description": "What breaking it looks like — the node that would contradict it. This is what makes universality checkable."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "implementedBy",
          "isArray": true,
          "min": 0,
          "max": 1,
          "description": "FQN references to the nodes applying this policy. High fan-out is normal and expected: one uuid-primary-key requirement is claimed by every entity."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "supersededBy",
          "min": 0,
          "max": 1,
          "description": "The requirement that replaced this one. Expected on status=superseded."
        }
      ]
    }
  ]
};
