// JsonbFixture — schema-provisioning + seed for the #98 jsonb open-bag api-contract
// lanes (reference + generated). One `documents` table whose `payload` column is a
// native Postgres `jsonb` (the open-JSON bag). The DDL mirrors what the Document
// entity's generators describe: id bigserial-style identity, title VARCHAR(200)
// NOT NULL, payload jsonb (nullable). The seed is jsonb/seed.json — payload rows are
// JSON objects bound as jsonb.

using System.Text.Json;
using System.Text.Json.Nodes;
using Npgsql;
using NpgsqlTypes;

namespace MetaObjects.IntegrationTests.Api;

internal static class JsonbFixture
{
    // BIGINT GENERATED BY DEFAULT AS IDENTITY so the seed can insert explicit ids and
    // a later implicit insert (create) lands past the seeded max. payload is native
    // jsonb — Npgsql materializes it into the generated entity's JsonDocument property.
    public const string SchemaDdl = """
        CREATE TABLE "documents" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "title" VARCHAR(200) NOT NULL,
          "payload" jsonb,
          CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
        );
        """;

    /// <summary>Create the single `documents` table on a fresh container.</summary>
    public static async Task ProvisionSchemaAsync(string connString)
    {
        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();
        await using var cmd = c.CreateCommand();
        cmd.CommandText = SchemaDdl;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Truncate + apply jsonb/seed.json (explicit ids; payload bound as jsonb), then
    /// bump the identity sequence past the seeded max so a later create lands at
    /// max(id)+1 (the create-201 contract depends on a deterministic next id).
    /// </summary>
    public static async Task ApplySeedAsync(string connString, string seedPath)
    {
        var root = JsonNode.Parse(File.ReadAllText(seedPath)) as JsonObject
            ?? throw new InvalidOperationException($"{seedPath}: top-level must be an object");

        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();

        await using (var trunc = c.CreateCommand())
        {
            trunc.CommandText = "TRUNCATE TABLE \"documents\" RESTART IDENTITY";
            await trunc.ExecuteNonQueryAsync();
        }

        if (root["rows"] is JsonArray rows)
        {
            foreach (var rowNode in rows)
            {
                if (rowNode is not JsonObject row) continue;
                await using var ins = c.CreateCommand();
                ins.CommandText =
                    "INSERT INTO \"documents\" (\"id\", \"title\", \"payload\") VALUES (@id, @title, @payload)";
                ins.Parameters.AddWithValue("@id", row["id"]!.GetValue<long>());
                ins.Parameters.AddWithValue("@title", row["title"]!.GetValue<string>());
                // payload is a JSON object/array/scalar — serialize it and bind as jsonb.
                var payload = row["payload"];
                if (payload is null || payload.GetValueKind() == JsonValueKind.Null)
                    ins.Parameters.Add(new NpgsqlParameter("@payload", NpgsqlDbType.Jsonb) { Value = DBNull.Value });
                else
                    ins.Parameters.Add(new NpgsqlParameter("@payload", NpgsqlDbType.Jsonb) { Value = payload.ToJsonString() });
                await ins.ExecuteNonQueryAsync();
            }
        }

        await using var bump = c.CreateCommand();
        bump.CommandText =
            "SELECT setval(pg_get_serial_sequence('documents', 'id'), COALESCE((SELECT MAX(id) FROM \"documents\"), 1))";
        await bump.ExecuteScalarAsync();
    }
}
