// M2mFixture — shared schema-provisioning + seed for the FR-018 M:N api-contract
// lanes (reference + generated). The six tables (posts/tags/post_tags +
// people/follows/friendships) match the persistence-conformance canonical schema
// (literal column naming, composite-PK junctions). The seed is the multi-table
// m2m/seed.json (keyed by table name — distinct from the single-table author seed).
//
// FW-8 (FR-018 x FR-017): plus the `accounts` TPH discriminator base (Account /
// MemberAccount / GuestAccount share ONE physical table — "kind" is the
// discriminator column; "karma" and "invitedBy" are subtype-only, so both are
// NULLABLE — a Guest row never sets karma, a Member row never sets invitedBy) and
// its four M:N junction tables (account_tags / scoped_account_tags /
// member_account_tags / post_reviewers).

using System.Text.Json;        // JsonValueKind
using System.Text.Json.Nodes;  // JsonNode / JsonObject / JsonArray
using Npgsql;

namespace MetaObjects.IntegrationTests.Api;

internal static class M2mFixture
{
    // The six-table DDL, identical to fixtures/persistence-conformance/canonical/
    // schema.postgres.sql (the M:N slice). BIGINT GENERATED BY DEFAULT AS IDENTITY so
    // the seed can insert explicit ids; composite PKs on the three junction tables.
    public const string SchemaDdl = """
        CREATE TABLE "posts" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "title" VARCHAR(200) NOT NULL,
          CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
        );
        CREATE TABLE "tags" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "name" VARCHAR(80) NOT NULL,
          CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
        );
        CREATE TABLE "post_tags" (
          "postId" BIGINT NOT NULL,
          "tagId" BIGINT NOT NULL,
          CONSTRAINT "post_tags_pkey" PRIMARY KEY ("postId", "tagId")
        );
        CREATE TABLE "people" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "name" VARCHAR(80) NOT NULL,
          CONSTRAINT "people_pkey" PRIMARY KEY ("id")
        );
        CREATE TABLE "follows" (
          "followerId" BIGINT NOT NULL,
          "followeeId" BIGINT NOT NULL,
          CONSTRAINT "follows_pkey" PRIMARY KEY ("followerId", "followeeId")
        );
        CREATE TABLE "friendships" (
          "personAId" BIGINT NOT NULL,
          "personBId" BIGINT NOT NULL,
          CONSTRAINT "friendships_pkey" PRIMARY KEY ("personAId", "personBId")
        );
        CREATE TABLE "accounts" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "kind" VARCHAR(20) NOT NULL,
          "handle" VARCHAR(80) NOT NULL,
          "karma" INTEGER,
          "invitedBy" VARCHAR(80),
          CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
        );
        CREATE TABLE "account_tags" (
          "accountId" BIGINT NOT NULL,
          "tagId" BIGINT NOT NULL,
          CONSTRAINT "account_tags_pkey" PRIMARY KEY ("accountId", "tagId")
        );
        CREATE TABLE "scoped_account_tags" (
          "accountId" BIGINT NOT NULL,
          "tagId" BIGINT NOT NULL,
          CONSTRAINT "scoped_account_tags_pkey" PRIMARY KEY ("accountId", "tagId")
        );
        CREATE TABLE "member_account_tags" (
          "accountId" BIGINT NOT NULL,
          "tagId" BIGINT NOT NULL,
          CONSTRAINT "member_account_tags_pkey" PRIMARY KEY ("accountId", "tagId")
        );
        CREATE TABLE "post_reviewers" (
          "postId" BIGINT NOT NULL,
          "accountId" BIGINT NOT NULL,
          CONSTRAINT "post_reviewers_pkey" PRIMARY KEY ("postId", "accountId")
        );
        ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_postId_fk" FOREIGN KEY ("postId") REFERENCES "posts" ("id");
        ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tagId_fk" FOREIGN KEY ("tagId") REFERENCES "tags" ("id");
        ALTER TABLE "follows" ADD CONSTRAINT "follows_followerId_fk" FOREIGN KEY ("followerId") REFERENCES "people" ("id");
        ALTER TABLE "follows" ADD CONSTRAINT "follows_followeeId_fk" FOREIGN KEY ("followeeId") REFERENCES "people" ("id");
        ALTER TABLE "friendships" ADD CONSTRAINT "friendships_personAId_fk" FOREIGN KEY ("personAId") REFERENCES "people" ("id");
        ALTER TABLE "friendships" ADD CONSTRAINT "friendships_personBId_fk" FOREIGN KEY ("personBId") REFERENCES "people" ("id");
        ALTER TABLE "account_tags" ADD CONSTRAINT "account_tags_accountId_fk" FOREIGN KEY ("accountId") REFERENCES "accounts" ("id");
        ALTER TABLE "account_tags" ADD CONSTRAINT "account_tags_tagId_fk" FOREIGN KEY ("tagId") REFERENCES "tags" ("id");
        ALTER TABLE "scoped_account_tags" ADD CONSTRAINT "scoped_account_tags_accountId_fk" FOREIGN KEY ("accountId") REFERENCES "accounts" ("id");
        ALTER TABLE "scoped_account_tags" ADD CONSTRAINT "scoped_account_tags_tagId_fk" FOREIGN KEY ("tagId") REFERENCES "tags" ("id");
        ALTER TABLE "member_account_tags" ADD CONSTRAINT "member_account_tags_accountId_fk" FOREIGN KEY ("accountId") REFERENCES "accounts" ("id");
        ALTER TABLE "member_account_tags" ADD CONSTRAINT "member_account_tags_tagId_fk" FOREIGN KEY ("tagId") REFERENCES "tags" ("id");
        ALTER TABLE "post_reviewers" ADD CONSTRAINT "post_reviewers_postId_fk" FOREIGN KEY ("postId") REFERENCES "posts" ("id");
        ALTER TABLE "post_reviewers" ADD CONSTRAINT "post_reviewers_accountId_fk" FOREIGN KEY ("accountId") REFERENCES "accounts" ("id");
        """;

    // Per-table column lists for the INSERTs (matches m2m/seed.json keys). Insert
    // order matters for FKs: base tables (posts/tags/people/accounts) before the
    // junction tables that reference them.
    private static readonly (string Table, string[] Cols)[] Tables =
    {
        ("posts",                new[] { "id", "title" }),
        ("tags",                 new[] { "id", "name" }),
        ("people",               new[] { "id", "name" }),
        ("accounts",             new[] { "id", "kind", "handle", "karma", "invitedBy" }),
        ("post_tags",            new[] { "postId", "tagId" }),
        ("follows",              new[] { "followerId", "followeeId" }),
        ("friendships",          new[] { "personAId", "personBId" }),
        ("account_tags",         new[] { "accountId", "tagId" }),
        ("scoped_account_tags",  new[] { "accountId", "tagId" }),
        ("member_account_tags",  new[] { "accountId", "tagId" }),
        ("post_reviewers",       new[] { "postId", "accountId" }),
    };

    /// <summary>Create the six tables on a fresh container.</summary>
    public static async Task ProvisionSchemaAsync(string connString)
    {
        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();
        await using var cmd = c.CreateCommand();
        cmd.CommandText = SchemaDdl;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Apply the multi-table m2m seed (m2m/seed.json) — explicit ids, in FK-safe
    /// order (base tables before junctions). Bumps the identity sequences on the two
    /// base tables so any later implicit insert is past the seeded max.
    /// </summary>
    public static async Task ApplySeedAsync(string connString, string seedPath)
    {
        var root = JsonNode.Parse(File.ReadAllText(seedPath)) as JsonObject
            ?? throw new InvalidOperationException($"{seedPath}: top-level must be an object");

        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();

        foreach (var (table, cols) in Tables)
        {
            if (root[table] is not JsonArray rows) continue;
            foreach (var rowNode in rows)
            {
                if (rowNode is not JsonObject row) continue;
                var colList = string.Join(", ", cols.Select(c2 => "\"" + c2 + "\""));
                var paramList = string.Join(", ", cols.Select((_, i) => "@p" + i));
                await using var ins = c.CreateCommand();
                ins.CommandText = $"INSERT INTO \"{table}\" ({colList}) VALUES ({paramList})";
                for (int i = 0; i < cols.Length; i++)
                {
                    var v = row[cols[i]];
                    object? val = v is null ? DBNull.Value
                        : v.GetValueKind() == JsonValueKind.Number ? v.GetValue<long>()
                        : v.GetValue<string>();
                    ins.Parameters.AddWithValue("@p" + i, val ?? DBNull.Value);
                }
                await ins.ExecuteNonQueryAsync();
            }
        }

        foreach (var table in new[] { "posts", "tags", "people", "accounts" })
        {
            await using var bump = c.CreateCommand();
            bump.CommandText =
                $"SELECT setval(pg_get_serial_sequence('{table}', 'id'), " +
                $"COALESCE((SELECT MAX(id) FROM \"{table}\"), 1))";
            await bump.ExecuteScalarAsync();
        }
    }
}
