// ProjectionFixture — schema-provisioning + seed for the F22 view-only-projection
// api-contract GENERATED lane. Provisions the writable `invoices` base table AND the
// read-only SQL view `v_invoice_summary` the InvoiceSummary projection is mapped to
// (the generated DbContext calls .ToView, so the view must physically exist before a
// single GET can answer). The seed is the table-keyed projection/seed.json — only
// `invoices` is ever seeded, because the view derives.
//
// Column spellings are the LITERAL ones (amountCents, not amount_cents) because this
// lane generates with ColumnNamingStrategy.Literal, as the other C# generated lanes
// do. Each port's harness writes its own DDL for exactly this reason; there is no one
// view definition the five could share.

using System.Text.Json;        // JsonValueKind
using System.Text.Json.Nodes;  // JsonNode / JsonObject / JsonArray
using Npgsql;

namespace MetaObjects.IntegrationTests.Api;

internal static class ProjectionFixture
{
    public const string SchemaDdl = """
        CREATE TABLE "invoices" (
          "id"          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "reference"   VARCHAR(40) NOT NULL,
          "status"      VARCHAR(20) NOT NULL,
          "amountCents" BIGINT NOT NULL,
          CONSTRAINT "invoices_pkey" PRIMARY KEY ("id")
        );
        CREATE VIEW "v_invoice_summary" AS
          SELECT i."id"          AS "id",
                 i."reference"   AS "reference",
                 i."status"      AS "status",
                 i."amountCents" AS "amountCents"
          FROM "invoices" i;
        """;

    private static readonly string[] InvoiceCols = { "id", "reference", "status", "amountCents" };

    /// <summary>Create the base table + the read-only view on a fresh container.</summary>
    public static async Task ProvisionSchemaAsync(string connString)
    {
        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();
        await using var cmd = c.CreateCommand();
        cmd.CommandText = SchemaDdl;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Apply the table-keyed projection seed. The view is never seeded — it derives
    /// from `invoices`, which is the whole point of the subcorpus.
    /// </summary>
    public static async Task ApplySeedAsync(string connString, string seedPath)
    {
        var root = JsonNode.Parse(File.ReadAllText(seedPath)) as JsonObject
            ?? throw new InvalidOperationException($"{seedPath}: top-level must be an object");

        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();

        if (root["invoices"] is JsonArray rows)
        {
            var colList = string.Join(", ", InvoiceCols.Select(col => "\"" + col + "\""));
            var paramList = string.Join(", ", InvoiceCols.Select((_, i) => "@p" + i));
            foreach (var rowNode in rows)
            {
                if (rowNode is not JsonObject row) continue;
                await using var ins = c.CreateCommand();
                ins.CommandText = $"INSERT INTO \"invoices\" ({colList}) VALUES ({paramList})";
                for (int i = 0; i < InvoiceCols.Length; i++)
                {
                    var v = row[InvoiceCols[i]];
                    object val = v is null ? DBNull.Value
                        : v.GetValueKind() == JsonValueKind.Number ? v.GetValue<long>()
                        : v.GetValue<string>();
                    ins.Parameters.AddWithValue("@p" + i, val);
                }
                await ins.ExecuteNonQueryAsync();
            }
        }

        await using var bump = c.CreateCommand();
        bump.CommandText =
            "SELECT setval(pg_get_serial_sequence('invoices', 'id'), " +
            "COALESCE((SELECT MAX(id) FROM \"invoices\"), 1))";
        await bump.ExecuteScalarAsync();
    }
}
