// TphFixture — shared schema-provisioning + seed for the FR-017 TPH api-contract
// lanes (reference + generated). One physical `auths` table holds every subtype;
// subtype-only columns (quantity / copayAmount / approver) are nullable. The DDL
// mirrors fixtures/persistence-conformance/canonical/schema.postgres.sql's `auths`
// table (literal column naming — `copayAmount` stays camelCase under the C# literal
// strategy). The seed is tph/seed.json (rows keyed under the `auths` table name).

using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;
using Npgsql;

namespace MetaObjects.IntegrationTests.Api;

internal static class TphFixture
{
    // Single-table TPH DDL — id bigserial PK, `type` discriminator text + CHECK,
    // reference NOT NULL, the three subtype-only columns nullable. BIGINT GENERATED
    // BY DEFAULT AS IDENTITY so the seed can insert explicit ids and a later implicit
    // insert (create) lands past the seeded max.
    //
    // #203 / ADR-0045 — autoCreatedAt/autoUpdatedAt (field.timestamp @autoSet) are
    // TIMESTAMPTZ, not plain TIMESTAMP: a default field.timestamp (no @localTime) is an
    // absolute instant (ADR-0036 Wave 2), so the GENERATED lane's EF model binds them to
    // DateTimeOffset with .HasColumnType("timestamp with time zone") — this schema is
    // shared by BOTH the reference and generated lanes (unlike the vanilla api-contract
    // corpus, where each lane provisions its own schema), so the physical column here
    // must match what the generated AppDbContext expects.
    public const string SchemaDdl = """
        CREATE TABLE "auths" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "type" TEXT,
          "reference" VARCHAR(80) NOT NULL,
          "quantity" INTEGER,
          "copayAmount" NUMERIC(10,2),
          "approver" VARCHAR(80),
          -- FR-037 R1: the @mutability "writeOnce" column, declared on the TPH BASE so
          -- every subtype inherits it.
          "issuedCurrency" VARCHAR(3),
          "autoCreatedAt" TIMESTAMPTZ,
          "autoUpdatedAt" TIMESTAMPTZ,
          CONSTRAINT "auths_pkey" PRIMARY KEY ("id"),
          CONSTRAINT "auths_type_chk" CHECK (type IN ('Bridge', 'Copay', 'PriorAuth'))
        );
        """;

    private static readonly string[] Cols =
        { "id", "type", "reference", "quantity", "copayAmount", "approver", "issuedCurrency", "autoCreatedAt", "autoUpdatedAt" };

    /// <summary>Create the single `auths` table on a fresh container.</summary>
    public static async Task ProvisionSchemaAsync(string connString)
    {
        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();
        await using var cmd = c.CreateCommand();
        cmd.CommandText = SchemaDdl;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Truncate + apply tph/seed.json (explicit ids; subtype-only columns null for
    /// rows of other subtypes), then bump the identity sequence past the seeded max so
    /// a later create lands at max(id)+1.
    /// </summary>
    public static async Task ApplySeedAsync(string connString, string seedPath)
    {
        var root = JsonNode.Parse(File.ReadAllText(seedPath)) as JsonObject
            ?? throw new InvalidOperationException($"{seedPath}: top-level must be an object");

        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();

        await using (var trunc = c.CreateCommand())
        {
            trunc.CommandText = "TRUNCATE TABLE \"auths\" RESTART IDENTITY";
            await trunc.ExecuteNonQueryAsync();
        }

        if (root["auths"] is JsonArray rows)
        {
            foreach (var rowNode in rows)
            {
                if (rowNode is not JsonObject row) continue;
                var colList = string.Join(", ", Cols.Select(c2 => "\"" + c2 + "\""));
                var paramList = string.Join(", ", Cols.Select((_, i) => "@p" + i));
                await using var ins = c.CreateCommand();
                ins.CommandText = $"INSERT INTO \"auths\" ({colList}) VALUES ({paramList})";
                for (int i = 0; i < Cols.Length; i++)
                {
                    var v = row[Cols[i]];
                    object val = v is null || v.GetValueKind() == JsonValueKind.Null
                        ? DBNull.Value
                        : Cols[i] switch
                        {
                            "id" or "quantity" => v.GetValue<long>(),
                            // copayAmount is authored as a string ("12.50") to preserve scale.
                            "copayAmount" => decimal.Parse(v.GetValue<string>(), System.Globalization.CultureInfo.InvariantCulture),
                            // #203 / ADR-0045 — the seed writes the OLD @autoSet sentinel VERBATIM
                            // (a direct insert, NOT a stamping create) so the seeded row keeps the
                            // old value; the offset-less wire form is interpreted as UTC (the
                            // cross-port instant-field contract), matching a timestamptz column.
                            "autoCreatedAt" or "autoUpdatedAt" => ParseInstant(v.GetValue<string>()),
                            _ => v.GetValue<string>(),
                        };
                    ins.Parameters.AddWithValue("@p" + i, val);
                }
                await ins.ExecuteNonQueryAsync();
            }
        }

        await using var bump = c.CreateCommand();
        bump.CommandText =
            "SELECT setval(pg_get_serial_sequence('auths', 'id'), COALESCE((SELECT MAX(id) FROM \"auths\"), 1))";
        await bump.ExecuteScalarAsync();
    }

    // #203 / ADR-0045 — parse an offset-less wire instant ("2000-01-01T00:00:00") as UTC
    // (Offset=0), the only offset Npgsql accepts when writing a DateTimeOffset into a
    // timestamptz column.
    private static DateTimeOffset ParseInstant(string s) =>
        DateTimeOffset.Parse(s, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal);
}
