// WriteThroughFixture — schema-provisioning + seed for the #214 write-through
// api-contract GENERATED lane. Provisions the customers + orders base tables AND
// the replica SQL view v_order_with_customer (the generated OrderView read-model is
// mapped to it via EF .ToView, so the view must physically exist for the create's
// re-read + GET to return the derived customerName). The seed is the table-keyed
// write-through/seed.json (customers + one pre-seeded order).

using System.Text.Json;        // JsonValueKind
using System.Text.Json.Nodes;  // JsonNode / JsonObject / JsonArray
using Npgsql;

namespace MetaObjects.IntegrationTests.Api;

internal static class WriteThroughFixture
{
    // Base tables (BIGINT GENERATED BY DEFAULT AS IDENTITY so the seed can insert
    // explicit ids AND the generated create can omit id for a server-assigned value)
    // PLUS the replica view. The view's column aliases (id / customerId / customerName)
    // match the generated OrderView's [Column(...)] names under Literal naming, so a
    // read routed through it carries the derived customerName.
    public const string SchemaDdl = """
        CREATE TABLE "customers" (
          "id"   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "name" VARCHAR(80) NOT NULL,
          CONSTRAINT "customers_pkey" PRIMARY KEY ("id")
        );
        CREATE TABLE "orders" (
          "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
          "customerId" BIGINT NOT NULL,
          CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
        );
        ALTER TABLE "orders" ADD CONSTRAINT "orders_customerId_fk"
          FOREIGN KEY ("customerId") REFERENCES "customers" ("id");
        CREATE VIEW "v_order_with_customer" AS
          SELECT o."id"         AS "id",
                 o."customerId" AS "customerId",
                 c."name"       AS "customerName"
          FROM "orders" o
          JOIN "customers" c ON o."customerId" = c."id";
        """;

    private static readonly (string Table, string[] Cols)[] Tables =
    {
        ("customers", new[] { "id", "name" }),
        ("orders",    new[] { "id", "customerId" }),
    };

    /// <summary>Create the two base tables + the replica view on a fresh container.</summary>
    public static async Task ProvisionSchemaAsync(string connString)
    {
        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();
        await using var cmd = c.CreateCommand();
        cmd.CommandText = SchemaDdl;
        await cmd.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Apply the table-keyed write-through seed (customers before orders — FK order).
    /// The derived customerName is never seeded (the view join produces it on read).
    /// Bumps the identity sequences so a later implicit insert is past the seeded max.
    /// </summary>
    public static async Task ApplySeedAsync(string connString, string seedPath)
    {
        var root = JsonNode.Parse(File.ReadAllText(seedPath)) as JsonObject
            ?? throw new InvalidOperationException($"{seedPath}: top-level must be an object");

        await using var c = new NpgsqlConnection(connString);
        await c.OpenAsync();

        foreach (var (table, cols) in Tables)
        {
            if (root[table] is not JsonArray rows) continue;
            foreach (var rowNode in rows)
            {
                if (rowNode is not JsonObject row) continue;
                var colList = string.Join(", ", cols.Select(c2 => "\"" + c2 + "\""));
                var paramList = string.Join(", ", cols.Select((_, i) => "@p" + i));
                await using var ins = c.CreateCommand();
                ins.CommandText = $"INSERT INTO \"{table}\" ({colList}) VALUES ({paramList})";
                for (int i = 0; i < cols.Length; i++)
                {
                    var v = row[cols[i]];
                    object? val = v is null ? DBNull.Value
                        : v.GetValueKind() == JsonValueKind.Number ? v.GetValue<long>()
                        : v.GetValue<string>();
                    ins.Parameters.AddWithValue("@p" + i, val ?? DBNull.Value);
                }
                await ins.ExecuteNonQueryAsync();
            }
        }

        foreach (var table in new[] { "customers", "orders" })
        {
            await using var bump = c.CreateCommand();
            bump.CommandText =
                $"SELECT setval(pg_get_serial_sequence('{table}', 'id'), " +
                $"COALESCE((SELECT MAX(id) FROM \"{table}\"), 1))";
            await bump.ExecuteScalarAsync();
        }
    }
}
