# @generated by metaobjects — DO NOT EDIT.
# Source metadata: AuthorBrief (acme::ai::AuthorBrief)
# Extend in your own module (e.g. AuthorBrief_extra.py) — nothing imports it for you.

from __future__ import annotations

from pydantic import BaseModel, Field

from .PostBrief import PostBrief, PostBriefCreate


class AuthorBrief(BaseModel):
    displayName: str
    posts: list[PostBrief] | None = None


class AuthorBriefCreate(BaseModel):
    """GENERATED — CREATE input: auto-gen PK / @mutability readOnly omitted (writeOnce is settable here, once); @default/@autoSet optional; present values validated (FR-036)."""

    displayName: str = Field(min_length=1)
    posts: list[PostBriefCreate] | None = None
