# @generated by metaobjects — DO NOT EDIT.
# Source metadata: AuthorBrief (AuthorBrief)
# Customize via AuthorBrief_extra.py in this directory.

from __future__ import annotations

from .PostBrief import PostBrief

from pydantic import BaseModel


class AuthorBrief(BaseModel):
    displayName: str
    posts: list[PostBrief] | None = None
