// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Customer
export const CustomerNames = {
  kind: "table",
  name: "customers",
  readOnly: false,
  fields: {
    email: { name: "email", column: "email" },
    id: { name: "id", column: "id" },
  },
} as const;
