// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: Customer (shop::users::Customer)
// Customize via Customer.extra.ts in this directory (e.g., auth, additional handlers).
import { db } from "../../../db";
import {
  Customer,
  CustomerFilterAllowlist,
  CustomerInsertSchema,
  customers,
  CustomerSortAllowlist,
  CustomerUpdateSchema,
} from "./Customer";
import { mountCrudRoutes } from "@metaobjects/runtime-ts/drizzle-fastify";
import type { FastifyInstance } from "fastify";

/**
 * Mount the 5 standard REST endpoints for Customer using Drizzle directly.
 *
 * Customize: register this as-is for stock CRUD, OR import the per-verb
 * helpers (mountListRoute, mountGetRoute, ...) from
 * @metaobjects/runtime-ts/drizzle-fastify and mix with your own handlers
 * (auth, side effects, etc.).
 */
export async function customerRoutes(fastify: FastifyInstance) {
  mountCrudRoutes({
    fastify,
    path: Customer.$path,
    db,
    table: customers,
    insertSchema: CustomerInsertSchema,
    updateSchema: CustomerUpdateSchema,
    filterAllowlist: CustomerFilterAllowlist,
    sortAllowlist: CustomerSortAllowlist,
    dialect: "sqlite",
  });
}
