// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Customer (shop::users::Customer)
// Customize via Customer.extra.ts in this directory.
import type { InferInsertModel, InferSelectModel } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { z } from "zod";
import { CustomerNames } from "./Customer.names";

export const customers = sqliteTable(CustomerNames.name, {
  id: integer(CustomerNames.fields.id.column).primaryKey({
    autoIncrement: true,
  }),
  email: text(CustomerNames.fields.email.column).notNull(),
});
export type Customer = InferSelectModel<typeof customers>;
export type CustomerInsert = InferInsertModel<typeof customers>;
export type CustomerUpdate = Partial<CustomerInsert>;
export const CustomerInsertSchema = z.object({
  email: z.string().min(1).max(255),
});

export const CustomerUpdateSchema = z.object({
  email: z.string().min(1).max(255).optional(),
});

/** Typed patch shape for Customer: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updateCustomer` call site. */
export type CustomerPatch = z.input<typeof CustomerUpdateSchema>;
/**
 * Metadata constants for Customer.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, optional htmlType/placeholder/helpText, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(Customer, CustomerInsertSchema);
 *   <input {...form.input.id} />
 */
export const Customer = {
  $entity: "Customer",
  $table: "customers",
  $path: "/customers",
  $apiPrefix: "",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  email: {
    name: "email",
    label: "Email",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Email is required",
      maxLength: { value: 255, message: "Must be 255 characters or fewer" },
    },
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const CustomerFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const CustomerSortAllowlist = {} as const satisfies SortAllowlist;
export type CustomerFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: CustomerFilter[];
  and?: CustomerFilter[];
};
