// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: Workout (Workout)
// Customize via Workout.extra.ts in this directory (e.g., auth, additional handlers).
import { db } from "~/server/db";
import {
  Workout,
  WorkoutFilterAllowlist,
  WorkoutInsertSchema,
  workouts,
  WorkoutSortAllowlist,
  WorkoutUpdateSchema,
} from "./Workout";
import { mountCrudRoutes } from "@metaobjects/runtime-ts/drizzle-fastify";
import type { FastifyInstance } from "fastify";

/**
 * Mount the 5 standard REST endpoints for Workout using Drizzle directly.
 *
 * Customize: register this as-is for stock CRUD, OR import the per-verb
 * helpers (mountListRoute, mountGetRoute, ...) from
 * @metaobjects/runtime-ts/drizzle-fastify and mix with your own handlers
 * (auth, side effects, etc.).
 */
export async function workoutRoutes(fastify: FastifyInstance) {
  mountCrudRoutes({
    fastify,
    path: Workout.$path,
    db,
    table: workouts,
    insertSchema: WorkoutInsertSchema,
    updateSchema: WorkoutUpdateSchema,
    filterAllowlist: WorkoutFilterAllowlist,
    sortAllowlist: WorkoutSortAllowlist,
    dialect: "postgres",
  });
}
