// @generated from templates/docs/*.mustache — DO NOT EDIT.
// Regenerate: bun run scripts/generate-embedded-templates.ts (or scripts/sync-doc-templates.sh).
//
// Embedded framework doc templates so they resolve inside the
// `bun build --compile` standalone `meta` binary, where the on-disk
// `templates/` directory is unavailable. Keys are provider resolve refs
// (path under templates/ minus the .mustache suffix).
export const EMBEDDED_FRAMEWORK_TEMPLATES: Record<string, string> = {
  "docs/entity-page.md": "{{{generatedMarker}}}\n\n# {{entity.name}}\n{{#descriptionQuote}}\n\n{{{.}}}\n{{/descriptionQuote}}\n\n{{{preambleHeader}}}\n{{#hasStorage}}\n\n## Storage\n\n{{{storage.tableHeader}}}\n{{#storage.rows}}\n{{{rowLine}}}\n{{/storage.rows}}\n{{/hasStorage}}\n{{#hasIdentities}}\n\n## Identity\n\n{{#identities}}\n- {{{bullet}}}\n{{/identities}}\n{{/hasIdentities}}\n{{#hasRelationships}}\n\n## Relationships\n\n{{#relationships}}\n- {{{bullet}}}\n{{/relationships}}\n{{/hasRelationships}}\n{{#constraints.hasConstraints}}\n\n## Constraints\n\n| Field | Required | Type | Limits | Rules |\n|---|---|---|---|---|\n{{#constraints.rows}}\n| {{{field}}} | {{required}} | {{{type}}} | {{limits}} | {{{rules}}} |\n{{/constraints.rows}}\n{{/constraints.hasConstraints}}\n{{#hasUsedBy}}\n\n## Used by\n\n{{#usedBy}}\n- {{{bullet}}}\n{{/usedBy}}\n{{/hasUsedBy}}\n",
  "docs/template-page.md": "{{{generatedMarker}}}\n\n# {{name}}\n{{#descriptionQuote}}\n\n{{{.}}}\n{{/descriptionQuote}}\n\n**Kind:** {{kind}}\n\n## Output\n{{^isEmail}}\n\n- Format: `{{format}}`\n{{/isEmail}}\n{{#isEmail}}\n\nMultipart email — rendered as the following parts:\n\n| Part | Source | Format | Escaping |\n|---|---|---|---|\n{{#parts}}\n| {{label}} | `{{ref}}` | `{{format}}` | {{#escaped}}escaped{{/escaped}}{{^escaped}}raw{{/escaped}} |\n{{/parts}}\n{{/isEmail}}\n\n## Input\n\n- Payload: [`{{payload.name}}`]({{payload.link}})\n{{#hasRequiredTags}}\n- Required fields:{{#requiredTags}} `{{.}}`{{/requiredTags}}\n{{/hasRequiredTags}}\n\n## Render contract\n\n- Every field referenced by the template is validated against the payload at generation time; an unknown field fails generation.\n{{#maxChars}}\n- Maximum length: {{.}} characters (rendering longer output fails).\n{{/maxChars}}\n{{#hasRequiredTags}}\n- Required tags must be present:{{#requiredTags}} `{{.}}`{{/requiredTags}}\n{{/hasRequiredTags}}\n\n## Source\n\n{{#sourceRefs}}\n- `{{.}}`\n{{/sourceRefs}}\n\n## Capability\n\n{{capability}}\n",
};
