// Data-dict shapes for the docs templates — the public contract template
// authors consume. Versioned per MO major; deprecated before removal.
//
// Per the template-driven codegen design (D3 — data-shape stability), these
// types ARE a public API. Template authors who write custom Mustache files
// for `docs/entity-page.md` (or any of the partials) reference these keys.
//
// Today's docsFile() refactor populates EntityDocData from MetaObject + the
// existing column-mapper / source-detect / enum-meta helpers. Cross-port
// implementations (C#, Java, Kotlin, Python) emit the same shape so a single
// set of Mustache templates can drive every port's docs codegen.

/** One row in the Storage table — fully-rendered as a single Markdown table
 *  row. The escaping rules for pipe-inside-cell are non-trivial and live in
 *  the data builder, not the template, so templates stay trivial and the
 *  cross-port walk functions don't have to re-derive the rules. */
export interface StorageFieldDoc {
  name: string;                  // raw field name (without backticks)
  tsTypeCell: string;            // already-escaped TS type, with backticks
  sqlExprCell: string;           // already-escaped SQL expression, wrapped in backticks
  constraintsCell: string;       // already-formatted constraints text
  /** Pre-rendered full Markdown table row, e.g.
   *    "| `id` | `number` | `integer(\"id\")` | primary key |"
   *  Templates emit this verbatim via `{{{rowLine}}}`. */
  rowLine: string;
}

export interface IdentityDoc {
  /** Pre-formatted bullet text — e.g.
   *    "**Primary key:** `id` — generation: `increment`"
   *  (Carrying the fully-rendered string keeps the template trivial; the
   *  identity rendering rules are non-trivial and live in the builder.) */
  bullet: string;
}

export interface RelationshipDoc {
  /** Pre-formatted bullet text — e.g.
   *    "- `posts` — one-to-many → `Post` (composition)" */
  bullet: string;
}

export interface UsedByDoc {
  /** Pre-formatted bullet text. */
  bullet: string;
}

export interface GeneratedFileDoc {
  filename: string;              // "Author.ts"
  description: string;           // "Drizzle table, Zod schemas, ..."
}

export interface EntityDocData {
  /** Auto-emitted by the templateGenerator; templates may also echo it for
   *  human readers. Format: `<!-- @generated by @metaobjectsdev/codegen-ts —
   *  DO NOT EDIT. -->`. */
  generatedMarker: string;

  /** The entity preamble. */
  entity: {
    name: string;                // "Author"
    type: string;                // "object.entity"
    source?: string;             // "meta.blog.json"
    package?: string;            // "acme::blog"
    description?: string;        // raw description text (may be multi-line)
  };

  /** Description as a blockquote (one `> ` per line). Present iff description
   *  is present. Pre-rendered so multi-line descriptions don't have to be
   *  expressed as Mustache structural constructs. */
  descriptionQuote?: string;

  /** Multi-line preamble block: Type / Source? / Package?, one per line,
   *  in the exact order matching the legacy emitter. Always present. */
  preambleHeader: string;

  /** Storage section. Present iff the entity has a writable rdb source and
   *  is NOT object.value. */
  storage?: {
    /** Pre-rendered "| Field | ... |\n|---|---|---|---|" header pair. */
    tableHeader: string;
    rows: StorageFieldDoc[];
  };

  /** Identity section bullets — empty array iff section is omitted. Templates
   *  check `hasIdentities` (boolean) to decide whether to emit the section
   *  header; iterate `identities` for the bullets. (Splitting "is the section
   *  present?" from "iterate the bullets" works around Mustache's lack of an
   *  "is non-empty array" primitive.) */
  identities?: IdentityDoc[];
  hasIdentities?: boolean;

  /** Relationships section — same pattern as identities. */
  relationships?: RelationshipDoc[];
  hasRelationships?: boolean;

  /** Validation section — always emitted. */
  validation: {
    insertSchema: string;        // "AuthorInsertSchema"
    updateSchema: string;        // "AuthorUpdateSchema"
    entityFile: string;          // "Author.ts"
    lower: string;               // "author" (lowercased first letter)
  };

  /** "Used by" — present iff any templates declare @payloadRef → this entity. */
  usedBy?: UsedByDoc[];
  hasUsedBy?: boolean;

  /** Storage section presence flag — same pattern as identities. */
  hasStorage?: boolean;

  /** Generated-code section — always emitted (at minimum the entity file). */
  generated: GeneratedFileDoc[];
}
