// The Change union — produced by SchemaDiff, consumed by the dialect emitter.
// Each change carries a mutable Status set by the diff's status pass (destructive /
// lossy changes default to blocked unless the matching AllowOptions flag is set).
//
// Ported from typescript/packages/migrate-ts/src/types.ts. Rename changes are modeled
// + emitted for completeness, but the diff does not yet produce them (the rename
// heuristic is deferred — renames are a known cross-language divergence).

namespace MetaObjects.Codegen.Migrate;

/// <summary>Whether a change is allowed to run, or blocked with a reason.</summary>
public sealed record ChangeStatus(bool Allowed, string? BlockedReason = null)
{
    public static readonly ChangeStatus AllowedStatus = new(true);
    public static ChangeStatus Block(string reason) => new(false, reason);
}

/// <summary>A schema change bringing the actual schema toward the expected one.</summary>
public abstract record Change
{
    /// <summary>Set by the diff's status pass; defaults to allowed.</summary>
    public ChangeStatus Status { get; set; } = ChangeStatus.AllowedStatus;

    public sealed record CreateTable(TableDescriptor Table) : Change;
    public sealed record DropTable(string Table, string? Schema = null) : Change;
    public sealed record RenameTable(string From, string To, string? Schema = null) : Change;
    public sealed record AddColumn(string Table, ColumnDescriptor Column, string? Schema = null) : Change;
    public sealed record DropColumn(string Table, string Column, string? Schema = null) : Change;
    public sealed record RenameColumn(string Table, string From, string To, string? Schema = null) : Change;
    public sealed record ChangeColumnType(string Table, string Column, SqlType From, SqlType To, string? Schema = null) : Change;
    public sealed record ChangeColumnNullable(string Table, string Column, bool From, bool To, string? Schema = null) : Change;
    public sealed record ChangeColumnDefault(string Table, string Column, ColumnDefault? From, ColumnDefault? To, string? Schema = null) : Change;
    /// <summary>
    /// PG 10+ identity attach/detach (<c>ADD GENERATED BY DEFAULT AS IDENTITY</c> /
    /// <c>DROP IDENTITY IF EXISTS</c>). Only <see cref="IdentityKind.Increment"/>
    /// transitions emit DDL today; Uuid identity is expressed as a column default and
    /// changes via <see cref="ChangeColumnDefault"/>.
    /// </summary>
    public sealed record ChangeColumnIdentity(string Table, string Column, IdentityKind? From, IdentityKind? To, string? Schema = null) : Change;
    public sealed record AddIndex(string Table, IndexDescriptor Index, string? Schema = null) : Change;
    public sealed record DropIndex(string Table, string Index, string? Schema = null) : Change;
    public sealed record AddFk(string Table, FkDescriptor Fk, string? Schema = null) : Change;
    public sealed record DropFk(string Table, string Fk, string? Schema = null) : Change;
}

/// <summary>Destructive/lossy gates. Widening type changes are always allowed regardless of <see cref="TypeChange"/>.</summary>
public sealed record AllowOptions(
    bool DropColumn = false,
    bool DropTable = false,
    bool TypeChange = false,
    bool DropIndex = false,
    bool DropFk = false,
    bool NullableToNotNull = false);

/// <summary>The diff output: every change, plus the subset that came back blocked.</summary>
public sealed record DiffResult(IReadOnlyList<Change> Changes, IReadOnlyList<Change> Blocked);
