import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, readdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { FileMetaDataLoader } from "@metaobjectsdev/metadata/core";
import { runGen, defineConfig } from "@metaobjectsdev/codegen-ts";
import { entityFile, queriesFile, routesFile, barrel } from "@metaobjectsdev/codegen-ts/generators";
import { tanstackQuery, tanstackGrid } from "../src/index.js";

const MULTI_GRID = resolve(import.meta.dir, "fixtures", "multi-grid-entity.json");

let tmp: string;
beforeEach(() => { tmp = mkdtempSync(join(tmpdir(), "tanstack-integration-")); });
afterEach(() => { rmSync(tmp, { recursive: true, force: true }); });

describe("Full pipeline — Project A + Project B generators together", () => {
  test("emits Program.ts, Program.queries.ts, Program.routes.ts, Program.hooks.ts, Program.columns.tsx, index.ts", async () => {
    const { root } = await new FileMetaDataLoader().loadFiles([MULTI_GRID]);
    const out = await runGen({
      config: defineConfig({
        outDir: tmp, extStyle: "none", dbImport: "../db", dialect: "sqlite",
        generators: [
          entityFile(), queriesFile(), routesFile(),
          tanstackQuery(), tanstackGrid(),
          barrel(),
        ],
      }),
      metadata: root,
    });
    expect(out.warnings).toEqual([]);

    const files = readdirSync(tmp).sort();
    expect(files).toContain("Program.ts");
    expect(files).toContain("Program.queries.ts");
    expect(files).toContain("Program.routes.ts");
    expect(files).toContain("Program.hooks.ts");
    expect(files).toContain("Program.columns.tsx");
    expect(files).toContain("index.ts");

    // Spot-check the generated hooks file:
    const hooks = readFileSync(join(tmp, "Program.hooks.ts"), "utf-8");
    expect(hooks).toContain("export function usePrograms");
    expect(hooks).toContain("export function useCreateProgram");
    expect(hooks).toContain("programKeys");

    // Spot-check the generated columns file:
    const cols = readFileSync(join(tmp, "Program.columns.tsx"), "utf-8");
    expect(cols).toContain("programDefaultColumns");
    expect(cols).toContain("programCompactColumns");
    expect(cols).toContain("ColumnDef<ProgramRow>");
  });

  test("all generators emit their expected file kinds together (happy path)", async () => {
    const { root } = await new FileMetaDataLoader().loadFiles([MULTI_GRID]);
    const out = await runGen({
      config: defineConfig({
        outDir: tmp, extStyle: "none", dbImport: "../db", dialect: "sqlite",
        generators: [entityFile(), tanstackQuery(), tanstackGrid(), barrel()],
      }),
      metadata: root,
    });
    const files = readdirSync(tmp);
    expect(files).toContain("Program.ts");
    expect(files).toContain("Program.hooks.ts");
    expect(files).toContain("Program.columns.tsx");
    expect(files).toContain("index.ts");

    // Verify @generated headers are present
    const hooks = readFileSync(join(tmp, "Program.hooks.ts"), "utf-8");
    expect(hooks.split("\n")[0]).toContain("@generated by @metaobjectsdev/codegen-ts");

    const cols = readFileSync(join(tmp, "Program.columns.tsx"), "utf-8");
    expect(cols.split("\n")[0]).toContain("@generated by @metaobjectsdev/codegen-ts");
  });
});
