import { describe, test, expect } from "bun:test";
import { resolve } from "node:path";
import { tanstackQuery } from "../src/tanstack-query.js";
import { makeRenderContext } from "@metaobjectsdev/codegen-ts";
import { buildPkMap, buildRelationMap } from "@metaobjectsdev/codegen-ts";
import type { GenContext } from "@metaobjectsdev/codegen-ts";
import { MetaDataLoader, InMemoryStringSource, type MetaRoot } from "@metaobjectsdev/metadata";
import { FileSource } from "@metaobjectsdev/metadata/core";

// A model carrying the retired `@emitTanstack: false` — deliberately. The strict loader
// (`meta verify`) rejects it with ERR_UNKNOWN_ATTR; the non-strict loader `meta gen` runs
// accepts it, which is exactly the half-working state this deletion ends. Keeping a real
// carrier here is what makes the inertness assertions below real: a test that only checks
// the constant is gone would pass against a half-done deletion.
const STALE_ATTR_MODEL = JSON.stringify({
  "metadata.root": {
    children: [{
      "object.entity": {
        name: "Subscriber",
        "@emitTanstack": false,
        children: [
          { "source.rdb": { "@table": "subscribers" } },
          { "field.long": { name: "id", children: [
            { "identity.primary": { name: "id", "@fields": ["id"], "@generation": "increment" } },
          ] } },
          { "field.string": { name: "email" } },
          { "layout.dataGrid": { name: "default", "@columns": ["email"] } },
        ],
      },
    }],
  },
});

const FIXTURE = resolve(import.meta.dir, "fixtures", "single-entity.json");

async function buildCtx(genFilter?: (e: { name: string }) => boolean): Promise<GenContext> {
  const { root } = await new MetaDataLoader().load([new FileSource(FIXTURE)]);
  return ctxForRoot(root, genFilter);
}

async function ctxForRoot(
  root: MetaRoot,
  genFilter?: (e: { name: string }) => boolean,
): Promise<GenContext> {
  const entities = root.objects();
  const renderContext = makeRenderContext({
    dialect: "sqlite", loadedRoot: root, outDir: "/tmp",
    dbImport: "../db", extStyle: "none",
    pkMap: buildPkMap(root), relationMap: buildRelationMap(root),
  });
  return {
    entities, loadedRoot: root,
    matches: (e) => genFilter?.(e) ?? true,
    config: { outDir: "/tmp", extStyle: "none", dbImport: "../db", dialect: "sqlite" },
    renderContext,
    warn: () => {},
  };
}

const pick = (files: { path: string; content: string }[], suffix: string) => {
  const f = files.find((x) => x.path.endsWith(suffix));
  if (!f) throw new Error(`no emitted file ending in ${suffix} — got ${files.map((x) => x.path).join(", ")}`);
  return f;
};

describe("tanstackQuery() factory", () => {
  test("returns a Generator named 'tanstack-query'", () => {
    const gen = tanstackQuery();
    expect(gen.name).toBe("tanstack-query");
    expect(typeof gen.generate).toBe("function");
  });

  test("emits Subscriber.hooks.ts with the query-key factory and 5 hooks", async () => {
    const ctx = await buildCtx();
    const files = await tanstackQuery().generate(ctx);
        const file = pick(files, ".hooks.ts");
    expect(file.path).toBe("Subscriber.hooks.ts");
    expect(file.content).toContain("@generated by @metaobjectsdev/codegen-ts");
    // Query-key factory:
    expect(file.content).toContain("export const subscriberKeys");
    expect(file.content).toMatch(/all:\s*\(\)\s*=>\s*\["subscriber"\]/);
    expect(file.content).toMatch(/list:\s*\(filter/);
    expect(file.content).toMatch(/detail:\s*\(id/);
    // Hook names:
    expect(file.content).toContain("export function useSubscriber");
    expect(file.content).toContain("export function useSubscribers");
    expect(file.content).toContain("export function useCreateSubscriber");
    expect(file.content).toContain("export function useUpdateSubscriber");
    expect(file.content).toContain("export function useDeleteSubscriber");
  });

  test("mutation hooks invalidate via subscriberKeys.all()", async () => {
    const ctx = await buildCtx();
    const file = pick(await tanstackQuery().generate(ctx), ".hooks.ts");
    // Each mutation should call invalidateQueries with subscriberKeys.all().
    const matches = file.content.match(/invalidateQueries\(\{\s*queryKey:\s*subscriberKeys\.all\(\)/g);
    expect(matches?.length).toBe(3); // create, update, delete
  });

  test("each hook accepts an opts override parameter", async () => {
    const ctx = await buildCtx();
    const file = pick(await tanstackQuery().generate(ctx), ".hooks.ts");
    expect(file.content).toContain("opts?: Omit<UseQueryOptions");
    expect(file.content).toContain("opts?: Omit<UseMutationOptions");
  });

  test("uses Subscriber.$path from entity constants for URLs", async () => {
    const ctx = await buildCtx();
    const file = pick(await tanstackQuery().generate(ctx), ".hooks.ts");
    expect(file.content).toContain("Subscriber.$path");
  });

  test("emits entity-relative fetch URLs, never a baked base", async () => {
    const ctx = await buildCtx();
    const file = pick(await tanstackQuery().generate(ctx), ".hooks.ts");
    // Inverted from "prefixes fetch URLs with Subscriber.$apiPrefix". The base URL is
    // supplied once at runtime by `<EntityFetcherProvider baseUrl>`, so a hook that
    // baked one would double it — and freezing it at `meta gen` is what stopped one
    // bundle from serving two origins.
    expect(file.content).not.toContain("$apiPrefix");
    // The get-one pattern, now starting at $path. Asserted positively as well as
    // negatively: emitting no URL at all would satisfy the line above on its own.
    expect(file.content).toContain("${Subscriber.$path}/${id}");
  });

  // `@emitTanstack` was read by this filter but was NEVER registered metamodel
  // vocabulary: the strict loader `meta verify` runs rejects it with ERR_UNKNOWN_ATTR,
  // while `meta gen` loads non-strict and honoured it. The read is gone. These two tests
  // pin the deletion AND the replacement — a deletion proved only by an absent assertion
  // is not proved at all.
  test("@emitTanstack is INERT — a stale one no longer suppresses the hooks file", async () => {
    const { root } = await new MetaDataLoader().load([new InMemoryStringSource(STALE_ATTR_MODEL)]);
    const subscriber = root.objects().find((o) => o.name === "Subscriber")!;
    expect(subscriber.hasAttr("emitTanstack")).toBe(true);   // the adopter really wrote it …
    expect(tanstackQuery().filter?.(subscriber)).toBe(true); // … and it decides nothing.
    const files = await tanstackQuery().generate(await ctxForRoot(root, () => true));
    expect(pick(files, ".hooks.ts")).toBeDefined();
  });

  test("`filter` is how you narrow — it AND-composes with the built-in gates", async () => {
    const gen = tanstackQuery({ filter: (e) => e.name !== "Subscriber" });
    expect(await gen.generate(await buildCtx((e) => gen.filter?.(e as never) ?? true))).toEqual([]);
  });
});
