// Unit tests for the per-entity markdown emitter.
//
// These exercise the template directly with hand-built MetaData trees so each
// section's shape is asserted in isolation. Conformance fixture coverage lives
// in test/golden/docs-file-conformance.test.ts and asserts byte-equal output
// against an `expected/<Entity>.md` file.

import { describe, test, expect } from "bun:test";
import {
  TypeId,
  TYPE_IDENTITY,
  TYPE_VALIDATOR,
  FIELD_SUBTYPE_LONG,
  FIELD_SUBTYPE_STRING,
  FIELD_SUBTYPE_OBJECT,
  IDENTITY_SUBTYPE_PRIMARY,
  IDENTITY_SUBTYPE_SECONDARY,
  IDENTITY_SUBTYPE_REFERENCE,
  OBJECT_SUBTYPE_ENTITY,
  OBJECT_SUBTYPE_VALUE,
  VALIDATOR_SUBTYPE_REGEX,
} from "@metaobjectsdev/metadata";
import {
  meta,
  metaRoot,
  metaObject,
  metaField,
  attachRdbSource,
} from "../_meta-build.js";
import { renderDocsFile } from "../../src/templates/docs-file.js";

describe("renderDocsFile — preamble", () => {
  test("emits H1 + Type for a basic entity", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");
    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);
    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    // Generated marker lives in a hidden HTML comment ahead of the H1 so the
    // overwrite-policy treats the file as codegen-owned.
    expect(out).toStartWith("<!-- @generated by @metaobjectsdev/codegen-ts");
    expect(out).toContain("# Post\n");
    expect(out).toContain("**Type:** `object.entity`");
  });

  test("includes description as a quote block", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    post.setAttr("description", "A blog post");
    attachRdbSource(post, "posts");
    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);
    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    expect(out).toContain("> A blog post");
  });

  test("includes Package when set", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    post.package = "demo::blog";
    attachRdbSource(post, "posts");
    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);
    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    expect(out).toContain("**Package:** `demo::blog`");
  });
});

describe("renderDocsFile — Storage table (NEUTRAL physical mapping)", () => {
  // The Storage section is the NEUTRAL physical persistence MAPPING (ADR-0020):
  // Column / Type / Nullable / Key — declared metadata facts only, NO
  // TypeScript type and NO ORM DDL. Validation facts (CHECK sets, maxLength,
  // patterns) live in the Constraints table, not here.
  test("emits one neutral row per field with PK + nullable shapes", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");

    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);

    const title = metaField(FIELD_SUBTYPE_STRING, "title");
    title.setAttr("required", true);
    title.setAttr("maxLength", 200);
    post.addChild(title);

    const body = metaField(FIELD_SUBTYPE_STRING, "body");
    post.addChild(body);

    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });

    expect(out).toContain("## Storage");
    expect(out).toContain("| Column | Type | Nullable | Key |");
    // PK: not nullable, key role = primary key, neutral logical type.
    expect(out).toContain("| `id` | `long` | no | primary key |");
    // Required non-PK: not nullable, no key.
    expect(out).toContain("| `title` | `string` | no |  |");
    // Optional: nullable.
    expect(out).toContain("| `body` | `string` | yes |  |");

    // Neutrality: no TypeScript type, no ORM DDL.
    expect(out).not.toContain("TypeScript type");
    expect(out).not.toContain("integer(");
    expect(out).not.toContain("text(");
  });

  test("@column override surfaces as the physical Column name", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");

    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);

    const title = metaField(FIELD_SUBTYPE_STRING, "title");
    title.setAttr("required", true);
    title.setAttr("column", "post_title");
    post.addChild(title);

    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    // The physical column name (@column) is the value-add of the Storage table.
    expect(out).toContain("| `post_title` | `string` | no |  |");
  });

  test("@dbColumnType override surfaces as the physical Type (uppercased)", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");

    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);

    const ref = metaField(FIELD_SUBTYPE_STRING, "ref");
    ref.setAttr("dbColumnType", "uuid");
    post.addChild(ref);

    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    // The declared physical @dbColumnType override wins over the logical type.
    expect(out).toContain("| `ref` | `UUID` | yes |  |");
  });

  test("array field renders neutral [] type, no JSON-column DDL leak", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");

    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);

    const tags = metaField(FIELD_SUBTYPE_STRING, "tags");
    tags.isArray = true;
    post.addChild(tags);

    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    expect(out).toContain("| `tags` | `string[]` | yes |  |");
    // The "JSON column" wording was Drizzle-flavored physical detail — gone.
    expect(out).not.toContain("{ mode:");
  });

  test("foreign-key field surfaces the Key role", () => {
    const root = metaRoot();
    const author = metaObject(OBJECT_SUBTYPE_ENTITY, "Author");
    attachRdbSource(author, "authors");
    const aid = metaField(FIELD_SUBTYPE_LONG, "id");
    author.addChild(aid);
    const aPrimary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    aPrimary.setAttr("fields", ["id"]);
    aPrimary.setAttr("generation", "increment");
    author.addChild(aPrimary);
    root.addChild(author);

    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");
    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);
    const authorId = metaField(FIELD_SUBTYPE_LONG, "authorId");
    authorId.setAttr("required", true);
    post.addChild(authorId);
    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    const reference = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_REFERENCE), "author");
    reference.setAttr("fields", ["authorId"]);
    reference.setAttr("references", "Author");
    post.addChild(reference);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    expect(out).toContain("| `authorId` | `long` | no | foreign key → `Author` |");
  });

  test("regex validator surfaces pattern in constraints", () => {
    const root = metaRoot();
    const user = metaObject(OBJECT_SUBTYPE_ENTITY, "User");
    attachRdbSource(user, "users");

    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    user.addChild(id);

    const slug = metaField(FIELD_SUBTYPE_STRING, "slug");
    slug.setAttr("required", true);
    const regex = meta(new TypeId(TYPE_VALIDATOR, VALIDATOR_SUBTYPE_REGEX), "regex");
    regex.setAttr("pattern", "^[a-z0-9-]+$");
    slug.addChild(regex);
    user.addChild(slug);

    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    user.addChild(primary);
    root.addChild(user);

    const out = renderDocsFile(user, {
      dialect: "sqlite",
      loadedRoot: root,
    });
    expect(out).toContain("pattern `^[a-z0-9-]+$`");
  });
});

describe("renderDocsFile — Identity section", () => {
  test("primary + secondary + reference identities render", () => {
    const root = metaRoot();
    const author = metaObject(OBJECT_SUBTYPE_ENTITY, "Author");
    attachRdbSource(author, "authors");
    const aid = metaField(FIELD_SUBTYPE_LONG, "id");
    author.addChild(aid);
    const aPrimary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    aPrimary.setAttr("fields", ["id"]);
    aPrimary.setAttr("generation", "increment");
    author.addChild(aPrimary);
    root.addChild(author);

    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");
    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);
    const authorId = metaField(FIELD_SUBTYPE_LONG, "authorId");
    authorId.setAttr("required", true);
    post.addChild(authorId);
    const visitorId = metaField(FIELD_SUBTYPE_STRING, "visitorId");
    visitorId.setAttr("required", true);
    post.addChild(visitorId);

    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);

    const secondary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_SECONDARY), "byVisitor");
    secondary.setAttr("fields", ["visitorId"]);
    post.addChild(secondary);

    const reference = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_REFERENCE), "author");
    reference.setAttr("fields", ["authorId"]);
    reference.setAttr("references", "Author");
    post.addChild(reference);

    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });

    expect(out).toContain("## Identity");
    expect(out).toContain("**Primary key:** `id`");
    expect(out).toContain("**Secondary index:** `visitorId`");
    expect(out).toContain("**Reference:** `authorId` → `Author`");
  });
});

describe("renderDocsFile — Constraints", () => {
  test("always emits a neutral Constraints table (no language-specific sections)", () => {
    const root = metaRoot();
    const post = metaObject(OBJECT_SUBTYPE_ENTITY, "Post");
    attachRdbSource(post, "posts");
    const id = metaField(FIELD_SUBTYPE_LONG, "id");
    post.addChild(id);
    const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
    primary.setAttr("fields", ["id"]);
    primary.setAttr("generation", "increment");
    post.addChild(primary);
    root.addChild(post);

    const out = renderDocsFile(post, {
      dialect: "sqlite",
      loadedRoot: root,
    });

    expect(out).toContain("## Constraints");
    expect(out).toContain("| Field | Required | Type | Limits | Rules |");
    expect(out).toContain("| `id` |");
    // No language-specific leakage.
    expect(out).not.toContain("Zod");
    expect(out).not.toContain("## Generated code");
    expect(out).not.toMatch(/\.ts\b/);
  });
});

describe("renderDocsFile — object.value", () => {
  test("omits Storage / Identity / Relationships", () => {
    const root = metaRoot();
    const lens = metaObject(OBJECT_SUBTYPE_VALUE, "Lens");
    const name = metaField(FIELD_SUBTYPE_STRING, "name");
    name.setAttr("required", true);
    lens.addChild(name);
    root.addChild(lens);

    const out = renderDocsFile(lens, {
      dialect: "sqlite",
      loadedRoot: root,
    });

    expect(out).toContain("# Lens");
    expect(out).toContain("**Type:** `object.value`");
    expect(out).not.toContain("## Storage");
    expect(out).not.toContain("## Identity");
    expect(out).not.toContain("## Relationships");
    // The neutral Constraints table renders even for value objects with no
    // storage — built from the object's own field metadata.
    expect(out).toContain("## Constraints");
    expect(out).toContain('| <a id="field-name"></a>`name` | yes | `string` |');
    // No language-specific leakage.
    expect(out).not.toContain("## Generated code");
    expect(out).not.toMatch(/\.ts\b/);
  });
});
