// Composition-seam test (additive): the built-in template render functions must
// be reachable from the package PUBLIC surface — both the main entry
// (`@metaobjectsdev/codegen-ts`) and the per-template subpath
// (`@metaobjectsdev/codegen-ts/templates/entity-file`) — so an adopter can call
// a built-in, post-process its output, and add the wrapping Generator to
// `generators: [...]` WITHOUT forking the template.

import { describe, test, expect } from "bun:test";
import {
  TypeId, TYPE_IDENTITY,
  FIELD_SUBTYPE_LONG, FIELD_SUBTYPE_STRING,
  IDENTITY_SUBTYPE_PRIMARY, OBJECT_SUBTYPE_ENTITY,
} from "@metaobjectsdev/metadata";

// Public-surface imports — the bar this test enforces.
import {
  renderEntityFile,
  renderBarrel,
  renderFilterType,
  renderDrizzleSchema,
  renderInferredTypes,
  makeRenderContext,
  buildPkMap,
  buildRelationMap,
} from "@metaobjectsdev/codegen-ts";
import type {
  RenderEntityFileOpts,
  BarrelEntry,
  ResolvedTarget,
} from "@metaobjectsdev/codegen-ts";
// Subpath import — mirrors the existing `./templates/zod-validators` pattern.
import { renderEntityFile as renderEntityFileViaSubpath } from "@metaobjectsdev/codegen-ts/templates/entity-file";

import { meta, metaRoot, metaObject, metaField, attachRdbSource } from "../_meta-build.js";

function buildOrderCtx() {
  const root = metaRoot();
  const order = metaObject(OBJECT_SUBTYPE_ENTITY, "Order");
  order.addChild(metaField(FIELD_SUBTYPE_LONG, "id"));
  const sku = metaField(FIELD_SUBTYPE_STRING, "sku");
  sku.setAttr("filterable", true);
  order.addChild(sku);
  const primary = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
  primary.setAttr("fields", ["id"]);
  primary.setAttr("generation", "increment");
  order.addChild(primary);
  attachRdbSource(order, "orders");
  root.addChild(order);

  const ctx = makeRenderContext({
    dialect: "sqlite",
    loadedRoot: root,
    outDir: "/x",
    dbImport: "~/db",
    pkMap: buildPkMap(root),
    relationMap: buildRelationMap(root),
  });
  return { root, order, ctx };
}

describe("public template-export composition seam", () => {
  test("renderEntityFile is reachable from the package entry and returns emitted code", () => {
    const { order, ctx } = buildOrderCtx();
    const out = renderEntityFile(order, ctx);
    expect(typeof out).toBe("string");
    // Emitted code carries the @generated header + the Drizzle table.
    expect(out).toContain("@generated by @metaobjectsdev/codegen-ts");
    expect(out).toContain("sqliteTable");
    expect(out).toContain("OrderFilter");
  });

  test("the subpath export is the SAME function as the entry export", () => {
    expect(renderEntityFileViaSubpath).toBe(renderEntityFile);
  });

  test("RenderEntityFileOpts is honored through the public export (allowlists: false)", () => {
    const { order, ctx } = buildOrderCtx();
    const opts: RenderEntityFileOpts = { allowlists: false };
    const out = renderEntityFile(order, ctx, opts);
    expect(out).not.toContain("OrderFilterAllowlist");
    // The client filter type is always emitted regardless of allowlists.
    expect(out).toContain("OrderFilter");
  });

  test("an adopter can compose: call the built-in, then post-process WITHOUT forking", () => {
    const { order, ctx } = buildOrderCtx();
    // Simulate an adopter Generator body: call built-in, append a decorator banner.
    const base = renderEntityFile(order, ctx);
    const composed = `// @audited-by acme-codegen\n${base}`;
    expect(composed.startsWith("// @audited-by acme-codegen\n")).toBe(true);
    expect(composed).toContain(base);
  });

  test("other high-reuse template fns are reachable and emit", () => {
    const { order, ctx } = buildOrderCtx();
    expect(renderDrizzleSchema(order, ctx).toString()).toContain("sqliteTable");
    expect(renderInferredTypes(order).toString()).toContain("Order");
    expect(renderFilterType(order).toString()).toContain("OrderFilter");

    const entries: BarrelEntry[] = [{ name: "Order", package: undefined }];
    const target: ResolvedTarget = {
      name: "default",
      outDir: "/x",
      importBase: undefined,
      outputLayout: "flat",
      dbImport: "~/db",
      runtime: true,
    };
    const barrel = renderBarrel(entries, "none", target, target);
    expect(barrel).toContain("export * from");
    expect(barrel).toContain("Order");
  });
});
