// The metamodel reference, rendered for the site.
//
// Runs against markdown generated by the REAL CLI, once, into a temp directory — not
// against a committed copy. `--metamodel` is the surface an adopter runs, and rendering a
// checked-in fixture instead would keep passing after that surface broke.
//
// The markdown is deliberately not committed anywhere: it is derived from the registry, so
// a second copy is exactly the drift this program exists to remove. The COMMITTED artifact
// is the rendered HTML under site-reference/, and its freshness is a separate gate
// (`build-site-reference.ts --check`), so a rendering bug and a staleness bug cannot fail
// the same test.
import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { generateMarkdown, outputPath, renderReference } from "./reference.js";

const REPO = resolve(import.meta.dirname, "../..");
let MD_DIR = "";

beforeAll(() => {
  MD_DIR = mkdtempSync(join(tmpdir(), "mo-reference-md-"));
  generateMarkdown(MD_DIR);
});
afterAll(() => { if (MD_DIR !== "") rmSync(MD_DIR, { recursive: true, force: true }); });

const pages = () => renderReference(MD_DIR);

describe("outputPath", () => {
  // `/reference/` resolves to index.html over HTTP, and the generator emits INDEX.md.
  // A page set that keeps the generator's name 404s on the reference root while every
  // test naming a page explicitly still passes.
  test("INDEX.md becomes index.html, so /reference/ resolves", () => {
    expect(outputPath("INDEX.md")).toBe("index.html");
  });

  test("a nested page keeps its directory", () => {
    expect(outputPath("types/field.md")).toBe("types/field.html");
  });

  test("only the INDEX at the root is renamed", () => {
    // A `types/INDEX.md` would be a different page; renaming it too would collide with a
    // real `types/index.md` the generator already emits.
    expect(outputPath("types/index.md")).toBe("types/index.html");
  });
});

describe("renderReference", () => {
  test("renders every metamodel markdown page", () => {
    expect(existsSync(MD_DIR)).toBe(true);
    const p = pages();
    expect(Object.keys(p).length).toBe(16);
    expect(Object.keys(p)).toContain("index.html");
    expect(Object.keys(p)).toContain("types/field.html");
  });

  test("rewrites .md links to .html so navigation works", () => {
    const html = pages()["index.html"] ?? "";
    expect(html).toContain('href="types/field.html');
    // RELATIVE links only. The shell's footer links to the roadmap on GitHub, which is a
    // real `.md` URL and must survive untouched — a blanket "no .md anywhere" assertion
    // fails on the correct behaviour, which is what the first draft of this test did.
    expect(html).not.toMatch(/href="(?!https?:|\/|#)[^"]*\.md["#]/);
  });

  test("keeps the anchor when rewriting a deep link", () => {
    // The index links to `types/attr.md#attrbase`. Dropping the fragment would land every
    // one of the 69 vocabulary rows at the top of its family page.
    expect(pages()["index.html"] ?? "").toContain('href="types/attr.html#attrbase"');
  });

  test("leaves absolute and external links alone", () => {
    const html = pages()["index.html"] ?? "";
    expect(html).toContain('href="/styles.css"');
    expect(html).toContain('href="https://github.com/metaobjectsdev/metaobjects"');
  });

  test("uses the site shell, not a bare fragment", () => {
    const html = pages()["index.html"] ?? "";
    expect(html).toContain('<link rel="stylesheet" href="/styles.css">');
    expect(html).toContain('class="site-header"');
    expect(html).toContain("</html>");
  });

  test("emits no <script>, like the rest of the site", () => {
    for (const [path, html] of Object.entries(pages())) {
      expect({ path, script: html.includes("<script") }).toEqual({ path, script: false });
    }
  });

  test("titles each page from its own H1", () => {
    expect(pages()["index.html"] ?? "").toContain("<title>MetaObjects Metamodel — Index | MetaObjects</title>");
  });

  test("renders the attribute tables — the reason the page exists", () => {
    // A markdown renderer with tables disabled produces a page that looks fine and is
    // useless: the vocabulary IS the tables.
    const html = pages()["types/field.html"] ?? "";
    expect(html).toContain("<table>");
    expect(html).toContain("<td>");
  });

  test("refuses an empty directory", () => {
    expect(() => renderReference(resolve(REPO, "scripts/site"))).toThrow(/no markdown/);
  });

  test("refuses a directory with markdown but no INDEX rather than shipping a 404", () => {
    // This used to point at `scripts/site`, which holds NO .md at all — so it exercised
    // the empty-directory branch, and its regex accepted either message. The INDEX guard
    // could have been deleted with the test still green. It needs a directory that has
    // markdown and lacks the index.
    const d = mkdtempSync(join(tmpdir(), "mo-no-index-"));
    try {
      writeFileSync(join(d, "providers.md"), "# Providers\n");
      expect(() => renderReference(d)).toThrow(/no INDEX\.md/);
    } finally {
      rmSync(d, { recursive: true, force: true });
    }
  });
});
