import { describe, test, expect } from "bun:test";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { scanSourceForAntiPatterns } from "../src/lib/anti-patterns.js";

function scaffold(files: Record<string, string>): string {
  const root = mkdtempSync(join(tmpdir(), "metaobjects-antipat-"));
  for (const [rel, body] of Object.entries(files)) {
    const abs = join(root, rel);
    mkdirSync(join(abs, ".."), { recursive: true });
    writeFileSync(abs, body, "utf8");
  }
  return root;
}

describe("scanSourceForAntiPatterns", () => {
  test("flags a hand-written SQL aggregate (AVG) in authored source", () => {
    const root = scaffold({
      "src/routes/recipes.ts":
        "const rows = await db.execute(`SELECT recipe_id, AVG(value) FROM ratings GROUP BY recipe_id`);",
    });
    try {
      const found = scanSourceForAntiPatterns(root);
      expect(found.some((f) => f.rule === "hand-rolled-aggregate")).toBe(true);
      const f = found.find((f) => f.rule === "hand-rolled-aggregate")!;
      expect(f.construct).toBe("origin.aggregate");
      expect(f.file).toBe("src/routes/recipes.ts");
      expect(f.message).toContain("meta types origin.aggregate");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("flags a TS summation reduce (seed 0)", () => {
    const root = scaffold({
      "src/lib/stats.ts":
        "const avg = ratings.reduce((acc, r) => acc + r.value, 0) / ratings.length;",
    });
    try {
      const found = scanSourceForAntiPatterns(root);
      expect(found.some((f) => f.rule === "hand-rolled-aggregate")).toBe(true);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("flags hand money math (money word + minor-unit math on one line)", () => {
    const root = scaffold({
      "src/checkout.ts": "const totalCents = Math.round(price * 100);",
    });
    try {
      const found = scanSourceForAntiPatterns(root);
      const f = found.find((f) => f.rule === "money-float");
      expect(f).toBeDefined();
      expect(f!.construct).toBe("field.currency");
      expect(f!.message).toContain("meta types field.currency");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("flags a SQL CHECK ... IN (...) as a field.enum candidate", () => {
    const root = scaffold({
      "schema.sql": "status varchar NOT NULL CHECK (status IN ('open','closed')),",
    });
    try {
      const found = scanSourceForAntiPatterns(root);
      const f = found.find((f) => f.rule === "enum-check");
      expect(f).toBeDefined();
      expect(f!.construct).toBe("field.enum");
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("does NOT flag a file carrying the @generated header (it's metaobjects output)", () => {
    const root = scaffold({
      "generated/Recipe.queries.ts":
        "// @generated by MetaObjects — do not edit\nexport const q = `SELECT AVG(value) FROM ratings`;",
    });
    try {
      expect(scanSourceForAntiPatterns(root)).toEqual([]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("does NOT flag code that consumes a generated projection query (the right way)", () => {
    const root = scaffold({
      "src/routes/recipes.ts":
        "import { listRecipeWithRating } from '../generated/RecipeWithRating.queries.js';\n" +
        "const recipes = await listRecipeWithRating(db);",
    });
    try {
      expect(scanSourceForAntiPatterns(root)).toEqual([]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("ignores node_modules, dist, .metaobjects, and test files (low false-positive bar)", () => {
    const root = scaffold({
      "node_modules/pkg/index.ts": "SELECT AVG(x) FROM t",
      "dist/bundle.ts": "SELECT AVG(x) FROM t",
      ".metaobjects/cache.ts": "SELECT AVG(x) FROM t",
      "src/recipes.test.ts": "expect(ratings.reduce((a,b)=>a+b,0)).toBe(6)",
    });
    try {
      expect(scanSourceForAntiPatterns(root)).toEqual([]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("does NOT flag a plain COUNT(*) pagination total (common, not a derived metric)", () => {
    const root = scaffold({
      "src/list.ts": "const [{ count }] = await db.execute(`SELECT COUNT(*) AS count FROM recipes`);",
    });
    try {
      expect(scanSourceForAntiPatterns(root).filter((f) => f.rule === "hand-rolled-aggregate")).toEqual([]);
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });
});
