// test/agent-context/assemble.test.ts
import { test, expect, describe } from "bun:test";
import { join } from "node:path";
import { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { assemble } from "../../src/agent-context/assemble.js";
import { makeStack } from "../../src/agent-context/resolve.js";

const CONTENT_ROOT = join(import.meta.dir, "../../../../../../agent-context"); // test/agent-context/ → repo root is 6 levels up

function paths(files: { path: string }[]): string[] {
  return files.map((f) => f.path).sort();
}

describe("assemble", () => {
  test("emits AGENTS.md + CLAUDE.md with the stack line + codegen command substituted", () => {
    const stack = makeStack(["typescript"], ["react"]);
    const files = assemble({ contentRoot: CONTENT_ROOT, stack });
    const agents = files.find((f) => f.path === ".metaobjects/AGENTS.md")!;
    const claude = files.find((f) => f.path === ".metaobjects/CLAUDE.md")!;
    expect(agents).toBeDefined();
    expect(claude.contents).toBe(agents.contents);
    expect(agents.contents).not.toContain("{{stackLine}}");
    expect(agents.contents).not.toContain("{{codegenCommand}}");
    expect(agents.contents).toContain("npx meta gen");
    expect(agents.contents.toLowerCase()).toContain("typescript");
    expect(agents.contents.toLowerCase()).toContain("react");
  });

  test("the docs pointer names only the pages THIS stack's toolchain can produce", () => {
    // The `agent/` pages exist only where the Node `meta` toolchain runs over a
    // `metaobjects.config.ts` — a TypeScript server, or any stack with a web client (the
    // React/TanStack tiers are generated by `meta gen` whatever the backend is). A
    // port-only stack has none, and the pointer landed on it verbatim: four files, three of
    // which cannot exist, and `meta docs`, which cannot make them.
    const node = assemble({ contentRoot: CONTENT_ROOT, stack: makeStack(["typescript"], []) })
      .find((f) => f.path === ".metaobjects/AGENTS.md")!.contents;
    expect(node).toContain("`meta docs` writes four reference files");
    expect(node).toContain("**`agent/schema.md`**");
    expect(node).toContain("**`agent/requirements.md`**");

    const python = assemble({ contentRoot: CONTENT_ROOT, stack: makeStack(["python"], []) })
      .find((f) => f.path === ".metaobjects/AGENTS.md")!.contents;
    expect(python).toContain("`metaobjects docs` writes ONE reference file");
    expect(python).toContain("Not there? Run `metaobjects docs`.");
    // The three it cannot produce are still NAMED — as what they are and where they come
    // from — rather than silently dropped, so a reader is not left thinking they do not exist.
    expect(python).toContain("written by the Node `meta docs` command and need a");
    expect(python).not.toContain("Not there? Run `meta docs`.");

    // A Java backend serving React DOES run `meta gen`, so it gets the full pointer.
    const javaReact = assemble({ contentRoot: CONTENT_ROOT, stack: makeStack(["java"], ["react"]) })
      .find((f) => f.path === ".metaobjects/AGENTS.md")!.contents;
    expect(javaReact).toContain("`meta docs` writes four reference files");

    // No section tag survives substitution on any of them.
    for (const c of [node, python, javaReact]) {
      expect(c).not.toContain("{{#");
      expect(c).not.toContain("{{^");
      expect(c).not.toContain("{{/");
      expect(c).not.toContain("{{docsCommand}}");
    }
  });

  test("a malformed section tag THROWS rather than shipping into a file an agent reads", () => {
    // The mechanism resolves sections in one non-greedy pass, so a mistyped close tag, an
    // unclosed section and a nested pair all leave a literal `{{#…}}` behind. Passing that
    // through would put a broken tag into AGENTS.md — the exact failure this surface
    // exists to prevent — so a leftover tag is an error. Exercised through a temp content
    // root rather than the shipped template, which is (and must stay) well-formed.
    const root = mkdtempSync(join(tmpdir(), "assemble-tpl-"));
    try {
      cpSync(CONTENT_ROOT, root, { recursive: true });
      const tpl = join(root, "templates", "always-on.md.mustache");
      const good = readFileSync(tpl, "utf8");
      for (const broken of [
        good.replace("{{/nodeDocsSurface}}", "{{/nodeDocsSurfaces}}"), // mistyped close
        `${good}\n{{#nodeDocsSurface}}\nunclosed\n`, // never closed
      ]) {
        writeFileSync(tpl, broken);
        expect(() =>
          assemble({ contentRoot: root, stack: makeStack(["typescript"], []) }),
        ).toThrow(/unresolved template section tag/);
      }
    } finally {
      rmSync(root, { recursive: true, force: true });
    }
  });

  test("stack-scoped: installs only the stack's language/framework reference fragments", () => {
    const stack = makeStack(["typescript"], ["react"]); // a narrow stack...
    const p = paths(assemble({ contentRoot: CONTENT_ROOT, stack }));
    // ...gets only its own language's codegen reference, not the others:
    expect(p).toContain(".claude/skills/metaobjects-codegen/references/typescript.md");
    expect(p).not.toContain(".claude/skills/metaobjects-codegen/references/java.md");
    expect(p).not.toContain(".claude/skills/metaobjects-codegen/references/kotlin.md");
    expect(p).not.toContain(".claude/skills/metaobjects-codegen/references/csharp.md");
    expect(p).not.toContain(".claude/skills/metaobjects-codegen/references/python.md");
    // ...its client ref, not the client frameworks it doesn't use:
    expect(p).toContain(".claude/skills/metaobjects-runtime-ui/references/react.md");
    expect(p).not.toContain(".claude/skills/metaobjects-runtime-ui/references/tanstack.md");
    // universal (non-language) fragments always install:
    expect(p).toContain(".claude/skills/metaobjects-verify/references/migration.md");
    expect(p).toContain(".claude/skills/metaobjects-audit/references/capability-checklist.md");
    for (const s of ["authoring", "codegen", "runtime-ui", "prompts", "verify"]) {
      expect(p).toContain(`.claude/skills/metaobjects-${s}/SKILL.md`);
    }
  });

  test("a java-only stack gets its java references, not other languages or unused clients", () => {
    const p = paths(assemble({ contentRoot: CONTENT_ROOT, stack: makeStack(["java"], []) }));
    expect(p).toContain(".claude/skills/metaobjects-codegen/references/java.md");
    expect(p).not.toContain(".claude/skills/metaobjects-codegen/references/typescript.md");
    // its language fragment in every skill that has one:
    expect(p).toContain(".claude/skills/metaobjects-runtime-ui/references/java.md");
    // no client in the stack → no client-framework refs:
    expect(p).not.toContain(".claude/skills/metaobjects-runtime-ui/references/react.md");
    expect(p).not.toContain(".claude/skills/metaobjects-runtime-ui/references/tanstack.md");
    // universal fragments still present:
    expect(p).toContain(".claude/skills/metaobjects-verify/references/migration.md");
  });

  test("a kotlin-primary stack assembles without throwing and uses the kotlin codegen command", () => {
    const stack = makeStack(["kotlin"], []);
    const files = assemble({ contentRoot: CONTENT_ROOT, stack });
    const agents = files.find((f) => f.path === ".metaobjects/AGENTS.md")!;
    expect(agents.contents.toLowerCase()).toContain("kotlin");
    expect(agents.contents).toContain("mvn metaobjects:generate");
  });

  test("a stack whose primary server has no meta file falls back to a default codegen command (no throw)", () => {
    // csharp.meta.json exists now, but the guard must not throw even if a meta file were absent.
    const stack = makeStack(["csharp"], []);
    expect(() => assemble({ contentRoot: CONTENT_ROOT, stack })).not.toThrow();
  });

  test("requirements concern: the gated fragment installs only when the token is present", () => {
    const withReq = paths(assemble({ contentRoot: CONTENT_ROOT, stack: makeStack(["typescript"], [], ["requirements"]) }));
    const withoutReq = paths(assemble({ contentRoot: CONTENT_ROOT, stack: makeStack(["typescript"], []) }));
    expect(withReq).toContain(".claude/skills/metaobjects-authoring/references/requirements.md");
    expect(withoutReq).not.toContain(".claude/skills/metaobjects-authoring/references/requirements.md");
    // an unrelated stack-scoped fragment is unaffected by the concern axis:
    expect(withoutReq).toContain(".claude/skills/metaobjects-codegen/references/typescript.md");
  });

  test("output is deterministic (stable order + identical across runs)", () => {
    const stack = makeStack(["typescript"], ["react"]);
    const a = assemble({ contentRoot: CONTENT_ROOT, stack });
    const b = assemble({ contentRoot: CONTENT_ROOT, stack });
    expect(a).toEqual(b);
    expect(a.map((f) => f.path)).toEqual([...a.map((f) => f.path)].sort());
  });
});
