<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.metaobjects</groupId>
        <artifactId>metaobjects</artifactId>
        <version>7.22.1</version>
    </parent>

    <artifactId>metaobjects-omdb</artifactId>
    <packaging>jar</packaging>

    <name>MetaObjects :: ObjectManager :: RDB</name>
    <url>https://github.com/metaobjectsdev/metaobjects</url>
    <description>MetaObjects for Model-driven development - ObjectManager Relational Databases</description>

    <dependencies>
        <dependency>
            <groupId>com.metaobjects</groupId>
            <artifactId>metaobjects-om</artifactId>
        </dependency>
        <dependency>
            <groupId>com.metaobjects</groupId>
            <artifactId>metaobjects-metadata</artifactId>
        </dependency>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>${javaee.api.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.derby</groupId>
            <artifactId>derby</artifactId>
            <version>${derby.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.derby</groupId>
            <artifactId>derbyshared</artifactId>
            <version>${derby.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.derby</groupId>
            <artifactId>derbytools</artifactId>
            <version>${derby.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- JUnit for testing -->
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
