// api-doc-render — BYTE-EXACT golden tests for the two documentation FORMS the
// ApiModel feeds: the per-unit HUMAN reference page + the consolidated HUMAN
// index + the condensed AGENT/LLM form. All three render through the SHARED
// render() Mustache engine against the canonical templates under templates/api/
// (resolved via the framework provider — same mechanism as docs-file.ts).
//
// One ApiModel feeds all three forms (no duplicate derivation). The agent form
// is asserted to stay under a per-symbol byte budget — the condensation
// guarantee. Index links are asserted to resolve in BOTH flat and package
// layout via the collision-safe docPageHref helper.

import { describe, test, expect } from "bun:test";
import { MetaDataLoader, InMemoryStringSource } from "@metaobjectsdev/metadata";
import { buildApiModel, type ApiModel, type ApiUnitDoc } from "../../src/generators/api-model.js";
import {
  renderEntityApiPage,
  renderApiIndex,
  renderAgentApi,
} from "../../src/generators/api-doc-render.js";
import { frameworkTemplatesProvider } from "../../src/render-engine/framework-provider.js";

// A multi-entity model (a CRUD entity + a value object) plus a template unit —
// exercises every section kind (model / data-access / rest / validation /
// extractor / render) across the entity vs template grouping.
const CHILDREN = [
  {
    "object.entity": {
      name: "Product",
      children: [
        { "field.long": { name: "id" } },
        { "field.string": { name: "name" } },
        { "identity.primary": { "@fields": "id", "@generation": "increment" } },
        { "source.rdb": { "@table": "products" } },
      ],
    },
  },
  {
    "object.value": {
      name: "SummaryVO",
      children: [{ "field.string": { name: "headline", "@required": true } }],
    },
  },
  {
    "template.output": {
      name: "ProductSummary",
      "@kind": "document",
      "@payloadRef": "SummaryVO",
      "@textRef": "out/product-summary",
      "@format": "json",
    },
  },
];

async function loadModel(): Promise<{ model: ApiModel; root: Awaited<ReturnType<MetaDataLoader["load"]>>["root"] }> {
  const res = await new MetaDataLoader().load([
    new InMemoryStringSource(
      JSON.stringify({ "metadata.root": { package: "acme::shop", children: CHILDREN } }),
      { id: "meta.json", format: "json" },
    ),
  ]);
  expect(res.errors).toEqual([]);
  const root = res.root;
  return { model: buildApiModel(root, { loadedRoot: root }), root };
}

function unit(model: ApiModel, node: string): ApiUnitDoc {
  const u = model.units.find((x) => x.node === node);
  if (!u) throw new Error(`no unit ${node}`);
  return u;
}

const provider = frameworkTemplatesProvider;

// ---------------------------------------------------------------------------
// HUMAN per-unit page.
// ---------------------------------------------------------------------------

const EXPECTED_PRODUCT_PAGE = `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# Product API

## Model

### \`interface Product\`

The typed shape of a Product row, generated from its metadata.

## Data access

### \`findProductById(db: Db, id: number): Promise<Product | null>\`

Fetch a single Product by its primary key; null when not found.

### \`listProducts(db: Db, opts?: { limit?: number; offset?: number }): Promise<Product[]>\`

List Product rows with optional limit/offset paging.

### \`createProduct(db: Db, data: unknown): Promise<Product>\`

Validate (via ProductInsertSchema) and insert a new Product.

### \`updateProduct(db: Db, id: number, data: unknown): Promise<Product | null>\`

Partially update an existing Product by primary key; null when not found.

### \`deleteProductById(db: Db, id: number): Promise<boolean>\`

Delete a Product by primary key; true when a row was removed.

## REST

### \`GET /products\`

List Product (supports filter/sort/paging query params).

### \`GET /products/:id\`

Fetch a single Product by id (404 when not found).

### \`POST /products\`

Create a Product (body validated by ProductInsertSchema).

### \`PATCH /products/:id\`

Partially update a Product by id (body validated by ProductUpdateSchema).

### \`DELETE /products/:id\`

Delete a Product by id.

## Validation

### \`ProductInsertSchema: ZodType\`

Zod schema validating the body of a create<Product> / POST request (auto-generated PKs excluded).

### \`ProductUpdateSchema: ZodType\`

Zod schema validating the body of an update / PATCH request (all fields optional).
`;

describe("renderEntityApiPage — human per-unit page", () => {
  test("byte-exact: sections per present kind, signatures, ordered", async () => {
    const { model } = await loadModel();
    const out = renderEntityApiPage(unit(model, "Product"), provider);
    expect(out).toBe(EXPECTED_PRODUCT_PAGE);
  });

  test("sections appear in canonical order (Model → … → Validation)", async () => {
    const { model } = await loadModel();
    const out = renderEntityApiPage(unit(model, "Product"), provider);
    const order = ["## Model", "## Data access", "## REST", "## Validation"].map((h) =>
      out.indexOf(h),
    );
    expect(order.every((i) => i >= 0)).toBe(true);
    expect([...order].sort((a, b) => a - b)).toEqual(order);
  });

  test("a fuller example, when present, renders as a fenced ```ts block", () => {
    // Examples are optional on ApiSymbol; the template emits a fenced block only
    // when present. Hand-build a unit carrying one to gate that path byte-exact.
    const synthetic: ApiUnitDoc = {
      node: "Widget",
      nodeKind: "entity",
      symbols: [
        {
          name: "makeWidget",
          kind: "data-access",
          signature: "makeWidget(): Widget",
          usage: "Build one.",
          example: "const w = makeWidget();\nconsole.log(w);",
        },
      ],
    };
    const out = renderEntityApiPage(synthetic, provider);
    expect(out).toBe(
      `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# Widget API

## Data access

### \`makeWidget(): Widget\`

Build one.

\`\`\`ts
const w = makeWidget();
console.log(w);
\`\`\`
`,
    );
  });
});

// ---------------------------------------------------------------------------
// HUMAN index.
// ---------------------------------------------------------------------------

const EXPECTED_INDEX_FLAT = `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# API Reference

Generated public API surface, one page per entity and output template.

## Entities

- [Product](./Product.md) — model, 5 data access, 5 REST, 2 validation (13 symbols)
- [SummaryVO](./SummaryVO.md) — model (1 symbol)

## Templates

- [ProductSummary](./ProductSummary.md) — 2 extractor, render (3 symbols)
`;

describe("renderApiIndex — consolidated human index", () => {
  test("byte-exact: grouped entity vs template, per-unit summary + symbol count", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "flat", provider);
    expect(out).toBe(EXPECTED_INDEX_FLAT);
  });

  test("flat-layout links resolve to ./<node>.md", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "flat", provider);
    expect(out).toContain("(./Product.md)");
    expect(out).toContain("(./SummaryVO.md)");
    expect(out).toContain("(./ProductSummary.md)");
  });

  test("package-layout links fold under the package path (./acme/shop/<node>.md)", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "package", provider);
    expect(out).toContain("(./acme/shop/Product.md)");
    expect(out).toContain("(./acme/shop/SummaryVO.md)");
    expect(out).toContain("(./acme/shop/ProductSummary.md)");
    // No bare flat link leaked through in package layout.
    expect(out).not.toContain("(./Product.md)");
  });

  test("singular/plural symbol-count grammar", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "flat", provider);
    expect(out).toContain("(1 symbol)"); // SummaryVO — exactly one
    expect(out).toContain("(13 symbols)"); // Product — many
  });
});

// ---------------------------------------------------------------------------
// AGENT / LLM condensed form.
// ---------------------------------------------------------------------------

const EXPECTED_AGENT = `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# Agent API Reference

Generated API reference for this project; call these exactly as written.

## Product
- \`interface Product\` — The typed shape of a Product row, generated from its metadata.
- \`findProductById(db: Db, id: number): Promise<Product | null>\` — Fetch a single Product by its primary key; null when not found.
- \`listProducts(db: Db, opts?: { limit?: number; offset?: number }): Promise<Product[]>\` — List Product rows with optional limit/offset paging.
- \`createProduct(db: Db, data: unknown): Promise<Product>\` — Validate (via ProductInsertSchema) and insert a new Product.
- \`updateProduct(db: Db, id: number, data: unknown): Promise<Product | null>\` — Partially update an existing Product by primary key; null when not found.
- \`deleteProductById(db: Db, id: number): Promise<boolean>\` — Delete a Product by primary key; true when a row was removed.
- \`ProductInsertSchema: ZodType\` — Zod schema validating the body of a create<Product> / POST request (auto-generated PKs excluded).
- \`ProductUpdateSchema: ZodType\` — Zod schema validating the body of an update / PATCH request (all fields optional).
- \`GET /products\` — List Product (supports filter/sort/paging query params).
- \`GET /products/:id\` — Fetch a single Product by id (404 when not found).
- \`POST /products\` — Create a Product (body validated by ProductInsertSchema).
- \`PATCH /products/:id\` — Partially update a Product by id (body validated by ProductUpdateSchema).
- \`DELETE /products/:id\` — Delete a Product by id.

## SummaryVO
- \`interface SummaryVO\` — The typed shape of a SummaryVO row, generated from its metadata.

## ProductSummary
- \`extractProductSummary(root: MetaRoot, text: string): SummaryVO\` — Parse dirty LLM json text into a strict, fully-typed SummaryVO graph.
- \`extractLenientProductSummary(root: MetaRoot, text: string): ExtractionResult<ProductSummaryExtracted>\` — Never-throwing extract; inspect report for lost/defaulted fields.
- \`renderProductSummary(payload: SummaryVO, provider: Provider): string\` — Render the ProductSummary document from a typed SummaryVO payload.
`;

describe("renderAgentApi — condensed agent/LLM form", () => {
  test("byte-exact: one compact line per symbol, grouped by unit, no prose/examples", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    expect(out).toBe(EXPECTED_AGENT);
  });

  test("NO prose/examples leak in — no fenced code blocks, every symbol on its own bullet", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    expect(out).not.toContain("```"); // no example fences
    expect(out).not.toContain("### "); // no per-symbol headings (that's the human page)
    // Exactly one bullet line per symbol across the whole model.
    const totalSymbols = model.units.reduce((n, u) => n + u.symbols.length, 0);
    const bulletLines = out.split("\n").filter((l) => l.startsWith("- `")).length;
    expect(bulletLines).toBe(totalSymbols);
  });

  test("condensation guarantee: agent form stays under the per-symbol byte budget", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    const totalSymbols = model.units.reduce((n, u) => n + u.symbols.length, 0);
    // Budget: a generous per-symbol line bound + a small fixed header allowance.
    // The agent form is one line per symbol, so bytes scale ~linearly with the
    // symbol count; this bounds it well under the prose pages.
    const BUDGET = 256 * totalSymbols + 512;
    expect(out.length).toBeLessThan(BUDGET);
    // And materially SMALLER than the sum of the human pages it condenses.
    const humanBytes = model.units.reduce(
      (n, u) => n + renderEntityApiPage(u, provider).length,
      0,
    );
    expect(out.length).toBeLessThan(humanBytes);
  });
});

// ---------------------------------------------------------------------------
// ONE model feeds both forms.
// ---------------------------------------------------------------------------

describe("one ApiModel feeds every form (no duplicate derivation)", () => {
  test("entity page, index, and agent form all render from the SAME buildApiModel result", async () => {
    const { model } = await loadModel();
    // A single model object drives all three renderers without rebuilding.
    const page = renderEntityApiPage(unit(model, "Product"), provider);
    const index = renderApiIndex(model, "flat", provider);
    const agent = renderAgentApi(model, provider);
    expect(page).toBe(EXPECTED_PRODUCT_PAGE);
    expect(index).toBe(EXPECTED_INDEX_FLAT);
    expect(agent).toBe(EXPECTED_AGENT);
  });
});
