// api-doc-render — BYTE-EXACT golden tests for the two documentation FORMS the
// ApiModel feeds: the per-unit HUMAN reference page + the consolidated HUMAN
// index + the condensed AGENT/LLM form. All three render through the SHARED
// render() Mustache engine against the canonical templates under templates/api/
// (resolved via the framework provider — same mechanism as docs-file.ts).
//
// One ApiModel feeds all three forms (no duplicate derivation). The agent form
// is asserted to stay under a per-symbol byte budget — the condensation
// guarantee. Index links are asserted to resolve in BOTH flat and package
// layout via the collision-safe docPageHref helper.

import { describe, test, expect } from "bun:test";
import { MetaDataLoader, InMemoryStringSource } from "@metaobjectsdev/metadata";
import { buildApiModel, type ApiModel, type ApiUnitDoc } from "../../src/generators/api-model.js";
import {
  renderEntityApiPage,
  renderApiIndex,
  renderAgentApi,
} from "../../src/generators/api-doc-render.js";
import { frameworkTemplatesProvider } from "../../src/render-engine/framework-provider.js";

// A multi-entity model (a CRUD entity + a value object) plus a template unit —
// exercises every section kind (model / data-access / rest / validation /
// extractor / render) across the entity vs template grouping.
const CHILDREN = [
  {
    "object.entity": {
      name: "Product",
      children: [
        { "field.long": { name: "id" } },
        { "field.string": { name: "name" } },
        { "identity.primary": { "name": "id", "@fields": "id", "@generation": "increment" } },
        { "source.rdb": { "@table": "products" } },
      ],
    },
  },
  {
    "object.value": {
      name: "SummaryVO",
      children: [{ "field.string": { name: "headline", "@required": true } }],
    },
  },
  {
    "template.output": {
      name: "ProductSummary",
      "@kind": "document",
      "@payloadRef": "SummaryVO",
      "@textRef": "out/product-summary",
      "@format": "json",
    },
  },
];

async function loadModel(): Promise<{ model: ApiModel; root: Awaited<ReturnType<MetaDataLoader["load"]>>["root"] }> {
  const res = await new MetaDataLoader().load([
    new InMemoryStringSource(
      JSON.stringify({ "metadata.root": { package: "acme::shop", children: CHILDREN } }),
      { id: "meta.json", format: "json" },
    ),
  ]);
  expect(res.errors).toEqual([]);
  const root = res.root;
  return { model: buildApiModel(root, { loadedRoot: root }), root };
}

function unit(model: ApiModel, node: string): ApiUnitDoc {
  const u = model.units.find((x) => x.node === node);
  if (!u) throw new Error(`no unit ${node}`);
  return u;
}

const provider = frameworkTemplatesProvider;

// ---------------------------------------------------------------------------
// HUMAN per-unit page.
// ---------------------------------------------------------------------------

const EXPECTED_PRODUCT_PAGE = `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# Product API

> Import paths are relative to your generated-output directory.

## Setup

Obtain the runtime handles the calls below need:

- \`db\` — your Drizzle connection — the generated queries take \`db: Db\` (a \`PgDatabase\` / \`BaseSQLiteDatabase\` alias). Construct one over your own driver and pass any compatible Drizzle instance:

\`\`\`ts
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
const db = drizzle(new Pool({ connectionString: process.env.DATABASE_URL }));
\`\`\`

## Example

\`\`\`ts
import { createProduct, findProductById, updateProduct, deleteProductById } from "./Product.queries";

const created = await createProduct(db, { name: "…" });
const found = await findProductById(db, created.id);
const updated = await updateProduct(db, created.id, { name: "…" });
const removed = await deleteProductById(db, created.id);
\`\`\`

## Model

### \`interface Product\`

The typed shape of a Product row, generated from its metadata.

\`\`\`ts
import { Product } from "./Product"
\`\`\`

Fields:

| Field | Type | Required | Notes |
|---|---|---|---|
| \`id\` | \`number\` | yes |  |
| \`name\` | \`string\` |  |  |

## Data access

### \`findProductById(db: Db, id: number): Promise<Product | null>\`

Fetch a single Product by its primary key; null when not found.

\`\`\`ts
import { findProductById } from "./Product.queries"
\`\`\`

### \`listProducts(db: Db, opts?: { limit?: number; offset?: number }): Promise<Product[]>\`

List Product rows with optional limit/offset paging.

\`\`\`ts
import { listProducts } from "./Product.queries"
\`\`\`

### \`createProduct(db: Db, data: unknown): Promise<Product>\`

Validate (via ProductInsertSchema) and insert a new Product.

\`\`\`ts
import { createProduct } from "./Product.queries"
\`\`\`

Request body (data):

| Field | Type | Required | Notes |
|---|---|---|---|
| \`name\` | \`string\` |  |  |

Throws: ZodError when data fails ProductInsertSchema validation.

### \`updateProduct(db: Db, id: number, data: unknown): Promise<Product | null>\`

Partially update an existing Product by primary key; null when not found.

\`\`\`ts
import { updateProduct } from "./Product.queries"
\`\`\`

Request body (data):

| Field | Type | Required | Notes |
|---|---|---|---|
| \`name\` | \`string\` |  |  |

Throws: ZodError when data fails the partial ProductInsertSchema validation.

### \`deleteProductById(db: Db, id: number): Promise<boolean>\`

Delete a Product by primary key; true when a row was removed.

\`\`\`ts
import { deleteProductById } from "./Product.queries"
\`\`\`

## REST

### \`GET /products\`

List Product (supports filter/sort/paging query params).

\`\`\`ts
import { productRoutes } from "./Product.routes"
\`\`\`

Response body:

| Field | Type | Required | Notes |
|---|---|---|---|
| \`id\` | \`number\` | yes |  |
| \`name\` | \`string\` |  |  |

Mount: \`await productRoutes(fastify)\`

### \`GET /products/:id\`

Fetch a single Product by id (404 when not found).

\`\`\`ts
import { productRoutes } from "./Product.routes"
\`\`\`

Response body:

| Field | Type | Required | Notes |
|---|---|---|---|
| \`id\` | \`number\` | yes |  |
| \`name\` | \`string\` |  |  |

Mount: \`await productRoutes(fastify)\`

### \`POST /products\`

Create a Product (body validated by ProductInsertSchema).

\`\`\`ts
import { productRoutes } from "./Product.routes"
\`\`\`

Request body:

| Field | Type | Required | Notes |
|---|---|---|---|
| \`name\` | \`string\` |  |  |

Mount: \`await productRoutes(fastify)\`

### \`PATCH /products/:id\`

Partially update a Product by id (body validated by ProductUpdateSchema).

\`\`\`ts
import { productRoutes } from "./Product.routes"
\`\`\`

Request body:

| Field | Type | Required | Notes |
|---|---|---|---|
| \`name\` | \`string\` |  |  |

Mount: \`await productRoutes(fastify)\`

### \`DELETE /products/:id\`

Delete a Product by id.

\`\`\`ts
import { productRoutes } from "./Product.routes"
\`\`\`

Mount: \`await productRoutes(fastify)\`

## Validation

### \`ProductInsertSchema: ZodType\`

Zod schema validating the body of a create<Product> / POST request (auto-generated PKs excluded).

\`\`\`ts
import { ProductInsertSchema } from "./Product"
\`\`\`

Accepted fields:

| Field | Type | Required | Notes |
|---|---|---|---|
| \`name\` | \`string\` |  |  |

### \`ProductUpdateSchema: ZodType\`

Zod schema validating the body of an update / PATCH request (all fields optional).

\`\`\`ts
import { ProductUpdateSchema } from "./Product"
\`\`\`

Accepted fields:

| Field | Type | Required | Notes |
|---|---|---|---|
| \`name\` | \`string\` |  |  |
`;

describe("renderEntityApiPage — human per-unit page", () => {
  test("byte-exact: sections per present kind, signatures, ordered", async () => {
    const { model } = await loadModel();
    const out = renderEntityApiPage(unit(model, "Product"), provider);
    expect(out).toBe(EXPECTED_PRODUCT_PAGE);
  });

  test("each symbol shows its import; throwing symbols show a Throws line; REST shows the registrar mount", async () => {
    const { model } = await loadModel();
    const out = renderEntityApiPage(unit(model, "Product"), provider);
    // Import per symbol — the #1 actionability fix.
    expect(out).toContain(`import { findProductById } from "./Product.queries"`);
    expect(out).toContain(`import { Product } from "./Product"`);
    expect(out).toContain(`import { ProductInsertSchema } from "./Product"`);
    // REST wires through the route registrar (not an importable endpoint fn).
    expect(out).toContain(`import { productRoutes } from "./Product.routes"`);
    expect(out).toContain("Mount: `await productRoutes(fastify)`");
    // Computed-but-previously-dropped throws now surfaces on the human page.
    expect(out).toContain("Throws: ZodError when data fails ProductInsertSchema validation.");
  });

  test("sections appear in canonical order (Model → … → Validation)", async () => {
    const { model } = await loadModel();
    const out = renderEntityApiPage(unit(model, "Product"), provider);
    const order = ["## Model", "## Data access", "## REST", "## Validation"].map((h) =>
      out.indexOf(h),
    );
    expect(order.every((i) => i >= 0)).toBe(true);
    expect([...order].sort((a, b) => a - b)).toEqual(order);
  });

  test("a fuller example, when present, renders as a fenced ```ts block", () => {
    // Examples are optional on ApiSymbol; the template emits a fenced block only
    // when present. Hand-build a unit carrying one to gate that path byte-exact.
    const synthetic: ApiUnitDoc = {
      node: "Widget",
      nodeKind: "entity",
      symbols: [
        {
          name: "makeWidget",
          kind: "data-access",
          importPath: "Widget.queries",
          signature: "makeWidget(): Widget",
          usage: "Build one.",
          example: "const w = makeWidget();\nconsole.log(w);",
        },
      ],
    };
    const out = renderEntityApiPage(synthetic, provider);
    expect(out).toBe(
      `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# Widget API

> Import paths are relative to your generated-output directory.

## Data access

### \`makeWidget(): Widget\`

Build one.

\`\`\`ts
import { makeWidget } from "./Widget.queries"
\`\`\`

\`\`\`ts
const w = makeWidget();
console.log(w);
\`\`\`
`,
    );
  });
});

// ---------------------------------------------------------------------------
// HUMAN index.
// ---------------------------------------------------------------------------

const EXPECTED_INDEX_FLAT = `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# API Reference

Generated public API surface, one page per entity and output template.

## Entities

- [Product](./Product.md) — model, 5 data access, 5 REST, 2 validation (13 symbols)
- [SummaryVO](./SummaryVO.md) — model (1 symbol)

## Templates

- [ProductSummary](./ProductSummary.md) — 2 extractor, render (3 symbols)
`;

describe("renderApiIndex — consolidated human index", () => {
  test("byte-exact: grouped entity vs template, per-unit summary + symbol count", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "flat", provider);
    expect(out).toBe(EXPECTED_INDEX_FLAT);
  });

  test("flat-layout links resolve to ./<node>.md", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "flat", provider);
    expect(out).toContain("(./Product.md)");
    expect(out).toContain("(./SummaryVO.md)");
    expect(out).toContain("(./ProductSummary.md)");
  });

  test("package-layout links fold under the package path (./acme/shop/<node>.md)", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "package", provider);
    expect(out).toContain("(./acme/shop/Product.md)");
    expect(out).toContain("(./acme/shop/SummaryVO.md)");
    expect(out).toContain("(./acme/shop/ProductSummary.md)");
    // No bare flat link leaked through in package layout.
    expect(out).not.toContain("(./Product.md)");
  });

  test("singular/plural symbol-count grammar", async () => {
    const { model } = await loadModel();
    const out = renderApiIndex(model, "flat", provider);
    expect(out).toContain("(1 symbol)"); // SummaryVO — exactly one
    expect(out).toContain("(13 symbols)"); // Product — many
  });
});

// ---------------------------------------------------------------------------
// AGENT / LLM condensed form.
// ---------------------------------------------------------------------------

const EXPECTED_AGENT = `<!-- @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT. -->

# Agent API Reference

Generated API reference for this project; call these exactly as written. Imports are relative to your generated-output directory.

## Setup
- \`db\` — your Drizzle connection — the generated queries take \`db: Db\` (a \`PgDatabase\` / \`BaseSQLiteDatabase\` alias). Construct one over your own driver and pass any compatible Drizzle instance: \`import { drizzle } from "drizzle-orm/node-postgres"; import { Pool } from "pg"; const db = drizzle(new Pool({ connectionString: process.env.DATABASE_URL }))\`
- \`provider\` — the render \`Provider\` (resolves a template ref to text) — import it from \`@metaobjectsdev/render\`; \`InMemoryProvider\` is built in (or supply your own filesystem-backed \`Provider\`): \`import { InMemoryProvider } from "@metaobjectsdev/render"; const provider = new InMemoryProvider({ "group/source": "Hello {{name}}" })\`
- \`root\` — the loaded \`MetaRoot\` \`extract<Name>\` parses against — load your metadata via \`@metaobjectsdev/metadata\` (the result carries \`.root\`): \`import { loadDirectory } from "@metaobjectsdev/metadata"; const { root } = await loadDirectory("./metadata")\`

## Product

\`import { Product, ProductInsertSchema, ProductUpdateSchema } from "./Product"\`
- \`interface Product { id: number; name?: string }\` — The typed shape of a Product row, generated from its metadata.
- \`ProductInsertSchema: ZodType<{ name?: string }>\` — Zod schema validating the body of a create<Product> / POST request (auto-generated PKs excluded).
- \`ProductUpdateSchema: ZodType<{ name?: string }>\` — Zod schema validating the body of an update / PATCH request (all fields optional).

\`import { findProductById, listProducts, createProduct, updateProduct, deleteProductById } from "./Product.queries"\`
- \`findProductById(db: Db, id: number): Promise<Product | null>\` — Fetch a single Product by its primary key; null when not found.
- \`listProducts(db: Db, opts?: { limit?: number; offset?: number }): Promise<Product[]>\` — List Product rows with optional limit/offset paging.
- \`createProduct(db: Db, data: { name?: string }): Promise<Product>\` — Validate (via ProductInsertSchema) and insert a new Product. [throws: ZodError when data fails ProductInsertSchema validation.]
- \`updateProduct(db: Db, id: number, data: { name?: string }): Promise<Product | null>\` — Partially update an existing Product by primary key; null when not found. [throws: ZodError when data fails the partial ProductInsertSchema validation.]
- \`deleteProductById(db: Db, id: number): Promise<boolean>\` — Delete a Product by primary key; true when a row was removed.

\`import { productRoutes } from "./Product.routes"\`
- \`GET /products -> { id: number; name?: string }\` — List Product (supports filter/sort/paging query params).
- \`GET /products/:id -> { id: number; name?: string }\` — Fetch a single Product by id (404 when not found).
- \`POST /products body: { name?: string }\` — Create a Product (body validated by ProductInsertSchema).
- \`PATCH /products/:id body: { name?: string }\` — Partially update a Product by id (body validated by ProductUpdateSchema).
- \`DELETE /products/:id\` — Delete a Product by id.

Example:
\`\`\`ts
const created = await createProduct(db, { name: "…" });
const found = await findProductById(db, created.id);
const updated = await updateProduct(db, created.id, { name: "…" });
const removed = await deleteProductById(db, created.id);
\`\`\`

## SummaryVO

\`import { SummaryVO } from "./SummaryVO"\`
- \`interface SummaryVO { headline: string }\` — The typed shape of a SummaryVO row, generated from its metadata.

## ProductSummary

\`import { extractProductSummary, extractLenientProductSummary } from "./ProductSummary.extractor"\`
- \`extractProductSummary(root: MetaRoot, text: string): SummaryVO // SummaryVO: { headline: string }\` — Parse dirty LLM json text into a strict, fully-typed SummaryVO graph. [throws: Error when a @required field is lost (the strict opt-in gate).]
- \`extractLenientProductSummary(root: MetaRoot, text: string): ExtractionResult<ProductSummaryExtracted>\` — Never-throwing extract; inspect report for lost/defaulted fields.

\`import { renderProductSummary } from "./ProductSummary.render"\`
- \`renderProductSummary(payload: SummaryVO, provider: Provider): string\` — Render the ProductSummary document from a typed SummaryVO payload.

Example:
\`\`\`ts
const extracted = extractProductSummary(root, llmText);
const output = renderProductSummary({ headline: "…" }, provider);
\`\`\`
`;

describe("renderAgentApi — condensed agent/LLM form", () => {
  test("byte-exact: one compact line per symbol, grouped by unit, setup + one worked example per unit", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    expect(out).toBe(EXPECTED_AGENT);
  });

  test("condensed: no per-symbol headings; exactly one bullet per symbol plus the setup handles", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    expect(out).not.toContain("### "); // no per-symbol headings (that's the human page)
    // The agent form now carries ONE compact worked example per runnable unit
    // (the concrete call site an agent benefits most from) — a bounded number of
    // fenced blocks, NOT prose paragraphs.
    const fenceCount = (out.match(/```ts/g) ?? []).length;
    const runnableUnits = model.units.filter((u) => u.example !== undefined).length;
    expect(fenceCount).toBe(runnableUnits);
    expect(runnableUnits).toBeGreaterThan(0);
    // SYMBOL bullets stay one-per-symbol; the only OTHER bullets are the setup
    // handles (db/provider/root). So `- \`` lines == symbols + setup handles.
    const totalSymbols = model.units.reduce((n, u) => n + u.symbols.length, 0);
    const setupHandleCount = 3; // db (queries), provider (render), root (extract)
    const bulletLines = out.split("\n").filter((l) => l.startsWith("- `")).length;
    expect(bulletLines).toBe(totalSymbols + setupHandleCount);
  });

  test("setup preamble: db/provider/root handles are present with verified imports", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    expect(out).toContain("## Setup");
    // db — a real drizzle construction (adopter-supplied instance).
    expect(out).toContain(`import { drizzle } from "drizzle-orm/node-postgres"`);
    // provider — the only Provider impl @metaobjectsdev/render exports.
    expect(out).toContain(`import { InMemoryProvider } from "@metaobjectsdev/render"`);
    // root — the real loader shortcut; LoadResult carries `.root`.
    expect(out).toContain(`import { loadDirectory } from "@metaobjectsdev/metadata"`);
    expect(out).toContain(`const { root } = await loadDirectory("./metadata")`);
  });

  test("worked example uses the unit's REAL documented imports + a value derived from the field type", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    // The Product example calls the SAME helpers documented above it, in a
    // create→find→update→delete flow, with a string-typed field → "…".
    expect(out).toContain(`const created = await createProduct(db, { name: "…" });`);
    expect(out).toContain(`const found = await findProductById(db, created.id);`);
    // The example imports must match the symbols' importPath (no divergence).
    const productUnit = model.units.find((u) => u.node === "Product")!;
    const queriesSymbols = productUnit.symbols.filter((s) => s.importPath === "Product.queries");
    for (const s of queriesSymbols) {
      if (productUnit.example!.body.some((b) => b.includes(`${s.name}(`))) {
        expect(productUnit.example!.imports.join("\n")).toContain(`from "Product.queries"`);
      }
    }
  });

  test("actionability: a sample symbol carries BOTH its import module AND the symbol — an agent could write the call", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    // The import header names the module AND the importable identifier; the
    // bullet names the callable signature. Together an agent has the exact import
    // + the call shape for createProduct.
    expect(out).toContain(`import { findProductById, listProducts, createProduct, updateProduct, deleteProductById } from "./Product.queries"`);
    // T2: the agent form now inlines the create payload SHAPE in place of the
    // opaque `data: unknown`, so an agent knows what fields to pass.
    expect(out).toContain("`createProduct(db: Db, data: { name?: string }): Promise<Product>`");
    // REST endpoints are wired through the entity's route registrar import.
    expect(out).toContain(`import { productRoutes } from "./Product.routes"`);
  });

  test("throws is surfaced as a compact [throws: …] marker", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    expect(out).toContain("[throws: ZodError when data fails ProductInsertSchema validation.]");
  });

  test("condensation guarantee: agent form stays under the per-symbol byte budget", async () => {
    const { model } = await loadModel();
    const out = renderAgentApi(model, provider);
    const totalSymbols = model.units.reduce((n, u) => n + u.symbols.length, 0);
    // Budget: a generous per-symbol line bound + a fixed header allowance that
    // covers the one-time Setup preamble (db/provider/root). The agent form is
    // one line per symbol plus one bounded worked example per runnable unit, so
    // bytes still scale ~linearly with the symbol count and stay well under the
    // prose pages.
    const BUDGET = 256 * totalSymbols + 1536;
    expect(out.length).toBeLessThan(BUDGET);
    // And materially SMALLER than the sum of the human pages it condenses.
    const humanBytes = model.units.reduce(
      (n, u) => n + renderEntityApiPage(u, provider).length,
      0,
    );
    expect(out.length).toBeLessThan(humanBytes);
  });
});

// ---------------------------------------------------------------------------
// Worked example chains via the entity's REAL primary key — not a literal `id`.
// ---------------------------------------------------------------------------

// An entity whose primary key is the field `code` (NOT `id`). The find/update/
// delete chain in the worked example must read back `created.code`, because
// `created.id` would be a property the row does not have — an example that does
// not compile against the generated model.
const COUPON_PK_CODE = [
  {
    "object.entity": {
      name: "Coupon",
      children: [
        { "field.string": { name: "code" } },
        { "field.string": { name: "label" } },
        { "identity.primary": { "name": "id", "@fields": "code", "@generation": "assigned" } },
        { "source.rdb": { "@table": "coupons" } },
      ],
    },
  },
];

async function loadCouponModel(): Promise<ApiModel> {
  const res = await new MetaDataLoader().load([
    new InMemoryStringSource(
      JSON.stringify({ "metadata.root": { package: "acme::shop", children: COUPON_PK_CODE } }),
      { id: "meta.json", format: "json" },
    ),
  ]);
  expect(res.errors).toEqual([]);
  return buildApiModel(res.root, { loadedRoot: res.root });
}

describe("worked example chains via the entity's REAL primary key (not a literal `id`)", () => {
  test("a non-`id` PK (`code`) makes the find/update/delete chain read back `created.code`", async () => {
    const model = await loadCouponModel();
    const couponUnit = model.units.find((u) => u.node === "Coupon")!;
    const body = couponUnit.example!.body.join("\n");
    // Accurate-by-construction: the chain reads the real PK accessor.
    expect(body).toContain(`const found = await findCouponById(db, created.code);`);
    expect(body).toContain(`const updated = await updateCoupon(db, created.code,`);
    expect(body).toContain(`const removed = await deleteCouponById(db, created.code);`);
    // And NEVER the wrong `created.id` (the field this entity does not have).
    expect(body).not.toContain("created.id");
  });

  test("the rendered agent page surfaces the corrected `created.code` chain", async () => {
    const model = await loadCouponModel();
    const out = renderAgentApi(model, provider);
    expect(out).toContain(`const found = await findCouponById(db, created.code);`);
    expect(out).not.toContain("created.id");
  });
});

// ---------------------------------------------------------------------------
// ONE model feeds both forms.
// ---------------------------------------------------------------------------

describe("one ApiModel feeds every form (no duplicate derivation)", () => {
  test("entity page, index, and agent form all render from the SAME buildApiModel result", async () => {
    const { model } = await loadModel();
    // A single model object drives all three renderers without rebuilding.
    const page = renderEntityApiPage(unit(model, "Product"), provider);
    const index = renderApiIndex(model, "flat", provider);
    const agent = renderAgentApi(model, provider);
    expect(page).toBe(EXPECTED_PRODUCT_PAGE);
    expect(index).toBe(EXPECTED_INDEX_FLAT);
    expect(agent).toBe(EXPECTED_AGENT);
  });
});
