"""The base metamodel type names + the shared base/root subtype names."""
TYPE_METADATA = "metadata"
TYPE_OBJECT = "object"
TYPE_FIELD = "field"
TYPE_ATTR = "attr"
TYPE_VALIDATOR = "validator"
TYPE_IDENTITY = "identity"
TYPE_RELATIONSHIP = "relationship"
TYPE_VIEW = "view"
TYPE_LAYOUT = "layout"
TYPE_SOURCE = "source"
TYPE_ORIGIN = "origin"
TYPE_TEMPLATE = "template"

SUBTYPE_BASE = "base"
SUBTYPE_ROOT = "root"
