# @generated by metaobjects — DO NOT EDIT.
# Source metadata: Metric (acme::report::Metric)
# Customize via Metric_extra.py in this directory.

from __future__ import annotations

from pydantic import BaseModel


class Metric(BaseModel):
    label: str | None = None


class MetricCreate(BaseModel):
    """GENERATED — CREATE input: auto-gen PK / @mutability readOnly omitted (writeOnce is settable here, once); @default/@autoSet optional; present values validated (FR-036)."""

    label: str | None = None
