# @generated by metaobjects — DO NOT EDIT.
# Source metadata: Report (acme::report::Report)
# Extend in your own module (e.g. Report_extra.py) — nothing imports it for you.

from __future__ import annotations

import datetime
from decimal import Decimal

from pydantic import BaseModel

from .Metric import Metric, MetricCreate


class Report(BaseModel):
    generatedAt: datetime.datetime
    total: Decimal
    revenue: int
    metrics: list[Metric] | None = None


class ReportCreate(BaseModel):
    """GENERATED — CREATE input: auto-gen PK / @mutability readOnly omitted (writeOnce is settable here, once); @default/@autoSet optional; present values validated (FR-036)."""

    generatedAt: datetime.datetime
    total: Decimal
    revenue: int
    metrics: list[MetricCreate] | None = None
