# @generated by metaobjects — DO NOT EDIT.
# Source metadata: Report (acme::report::Report)
# Customize via Report_extra.py in this directory.

from __future__ import annotations

import datetime
from decimal import Decimal

from pydantic import BaseModel

from .Metric import Metric, MetricCreate


class Report(BaseModel):
    generatedAt: datetime.datetime
    total: Decimal
    revenue: int
    metrics: list[Metric] | None = None


class ReportCreate(BaseModel):
    """GENERATED — CREATE input: auto-gen PK / @readOnly omitted; @default/@autoSet optional; present values validated (FR-036)."""

    generatedAt: datetime.datetime
    total: Decimal
    revenue: int
    metrics: list[MetricCreate] | None = None
