"""Codegen-wide constants. The @generated marker drives the overwrite policy."""
from __future__ import annotations

GENERATED_MARKER = "@generated by metaobjects"


def generated_header(entity_name: str, fqn: str) -> str:
    """Line-1 header for every emitted module. Detected by the overwrite policy.

    Line 3 used to read ``Customize via <name>_extra.py in this directory``, the exact
    wording the TypeScript emitters carried. It asserted a plugin point no port has: a
    sibling module is safe because codegen only writes the paths it records, never
    because of its name, and nothing imports it for you. See #367 for what the TS
    spelling cost in a real build, and ``docs/features/own-your-codegen.md`` for the
    convention as it actually works. Keep this line and
    ``codegen-ts/src/constants.ts``'s ``sidecarLine`` saying the same thing.
    """
    return (
        f"# {GENERATED_MARKER} — DO NOT EDIT.\n"
        f"# Source metadata: {entity_name} ({fqn})\n"
        f"# Extend in your own module (e.g. {entity_name}_extra.py) — nothing imports it for you.\n"
    )


def generated_package_init() -> str:
    """Content for a generated package ``__init__.py``.

    A bare marker file that makes the codegen out dir an importable Python package —
    the emitted modules use package-relative imports (``from .x import ...``), so the
    consumer needs the package marker to import them. Carries the @generated marker so
    the overwrite policy re-writes it on regen and refuses to clobber a hand-authored
    ``__init__.py`` (which lacks the marker).
    """
    return (
        f"# {GENERATED_MARKER} — DO NOT EDIT.\n"
        f"# Package marker so the generated output directory is importable.\n"
    )
