import { describe, test, expect } from "bun:test";
import { resolve } from "node:path";
import { FileMetaDataLoader, TYPE_OBJECT, MetaObject, TypeId, OBJECT_SUBTYPE_ENTITY } from "@metaobjects/metadata";
import { tanstackQuery } from "../src/tanstack-query.js";
import { makeRenderContext } from "@metaobjects/codegen-ts";
import { buildPkMap, buildRelationMap } from "@metaobjects/codegen-ts";
import type { GenContext } from "@metaobjects/codegen-ts";

const FIXTURE = resolve(import.meta.dir, "fixtures", "single-entity.json");

async function buildCtx(genFilter?: (e: { name: string }) => boolean): Promise<GenContext> {
  const loader = new FileMetaDataLoader();
  const { root } = await loader.loadFiles([FIXTURE]);
  const entities = root.children().filter((c) => c.type === TYPE_OBJECT);
  const renderContext = makeRenderContext({
    dialect: "sqlite", loadedRoot: root, outDir: "/tmp",
    dbImport: "../db", extStyle: "none",
    pkMap: buildPkMap(root), relationMap: buildRelationMap(root),
  });
  return {
    entities, loadedRoot: root,
    matches: (e) => genFilter?.(e) ?? true,
    config: { outDir: "/tmp", extStyle: "none", dbImport: "../db", dialect: "sqlite" },
    renderContext,
    warn: () => {},
  };
}

describe("tanstackQuery() factory", () => {
  test("returns a Generator named 'tanstack-query'", () => {
    const gen = tanstackQuery();
    expect(gen.name).toBe("tanstack-query");
    expect(typeof gen.generate).toBe("function");
  });

  test("emits Subscriber.hooks.ts with the query-key factory and 5 hooks", async () => {
    const ctx = await buildCtx();
    const files = await tanstackQuery().generate(ctx);
    expect(files.length).toBe(1);
    const file = files[0]!;
    expect(file.path).toBe("Subscriber.hooks.ts");
    expect(file.content).toContain("@generated by @metaobjects/codegen-ts");
    // Query-key factory:
    expect(file.content).toContain("export const subscriberKeys");
    expect(file.content).toMatch(/all:\s*\(\)\s*=>\s*\["subscriber"\]/);
    expect(file.content).toMatch(/list:\s*\(filter/);
    expect(file.content).toMatch(/detail:\s*\(id/);
    // Hook names:
    expect(file.content).toContain("export function useSubscriber");
    expect(file.content).toContain("export function useSubscribers");
    expect(file.content).toContain("export function useCreateSubscriber");
    expect(file.content).toContain("export function useUpdateSubscriber");
    expect(file.content).toContain("export function useDeleteSubscriber");
  });

  test("mutation hooks invalidate via subscriberKeys.all()", async () => {
    const ctx = await buildCtx();
    const file = (await tanstackQuery().generate(ctx))[0]!;
    // Each mutation should call invalidateQueries with subscriberKeys.all().
    const matches = file.content.match(/invalidateQueries\(\{\s*queryKey:\s*subscriberKeys\.all\(\)/g);
    expect(matches?.length).toBe(3); // create, update, delete
  });

  test("each hook accepts an opts override parameter", async () => {
    const ctx = await buildCtx();
    const file = (await tanstackQuery().generate(ctx))[0]!;
    expect(file.content).toContain("opts?: Omit<UseQueryOptions");
    expect(file.content).toContain("opts?: Omit<UseMutationOptions");
  });

  test("uses Subscriber.$path from entity constants for URLs", async () => {
    const ctx = await buildCtx();
    const file = (await tanstackQuery().generate(ctx))[0]!;
    expect(file.content).toContain("Subscriber.$path");
  });

  test("prefixes fetch URLs with Subscriber.$apiPrefix", async () => {
    const ctx = await buildCtx();
    const file = (await tanstackQuery().generate(ctx))[0]!;
    // Every fetch URL should have $apiPrefix before $path so users can set apiPrefix once.
    expect(file.content).toContain("Subscriber.$apiPrefix");
    // Specifically the get-one pattern:
    expect(file.content).toContain("${Subscriber.$apiPrefix}${Subscriber.$path}");
  });

  test("respects @emitTanstack: false per entity", async () => {
    // Filter mimics what the runner does: AND-composes the generator's filter
    // with the entity's @emitTanstack attribute.
    const gen = tanstackQuery();
    // Build a fresh (unfrozen) MetaData with @emitTanstack: false.
    // The Loader freezes models after parsing, so we construct one in-memory.
    const ctx = await buildCtx();
    const optedOut = new MetaObject(new TypeId(TYPE_OBJECT, OBJECT_SUBTYPE_ENTITY), "Subscriber");
    optedOut.setAttr("emitTanstack", false);
    const ctx2: GenContext = {
      ...ctx,
      entities: [optedOut],
      matches: (e) => gen.filter?.(e) ?? true,
    };
    const files = await gen.generate(ctx2);
    expect(files).toEqual([]);
  });
});
