// The two doors that spell a column's physical type, asked the same question.
//
// codegen-ts emits a Drizzle column; migrate-ts emits the CREATE TABLE that
// column binds to. Both read the same `field.*` node, and nothing compared
// their answers — so when the increment-PK branch of the Drizzle template
// substituted `serial`/`bigserial` for the `integer`/`bigint` the column-mapper
// had already derived, the generated schema misrepresented the live primary key
// of every integer-keyed table migrate had created, and every gate stayed green.
//
// `serial` is not a type. It is historical sugar for `integer` + an owned
// sequence + a genuine `DEFAULT nextval(...)`. migrate emits
// `INTEGER GENERATED BY DEFAULT AS IDENTITY` — a column with no default and no
// droppable sequence. Two different columns, one metadata node.
//
// Neither side of this test spells a SQL type or a Drizzle function name. It
// asks drizzle-orm itself what the emitted column function produces
// (`getSQLType()`, through a real `pgTable`) and asks migrate-ts's own
// `columnTypeSql` — which delegates to the very function the DDL emitter uses —
// what the migration would write. A hand-kept mapping between the two would be
// the same defect one level up: a third place for the answer to disagree.
//
// It ranges over EVERY column of every table in the canonical corpus rather
// than a chosen case, so a subtype whose two doors drift apart later is caught
// without anyone remembering to add it here.

import { describe, expect, test } from "bun:test";
import * as pgCore from "drizzle-orm/pg-core";

import { buildExpectedSchema, columnTypeSql } from "@metaobjectsdev/migrate-ts";
import { mapColumnType, PG_IDENTITY_CAPABLE_FNS } from "@metaobjectsdev/codegen-ts";
import { isMetaObject, type MetaField, type MetaObject } from "@metaobjectsdev/metadata";

import { loadMetadataDir } from "../src/load-metadata.ts";
import { CANONICAL_DIR } from "../src/paths.ts";

const DIALECT = "postgres" as const;

/**
 * The SQL type drizzle-orm ACTUALLY produces for a column spec, obtained by
 * building the column and asking it — never by mapping a function name to a
 * type name here.
 */
function drizzleSqlType(spec: {
  fnName: string;
  fnOptions?: Record<string, unknown> | undefined;
}): string {
  const fn = (pgCore as unknown as Record<string, unknown>)[spec.fnName];
  if (typeof fn !== "function") {
    throw new Error(
      `codegen emitted the drizzle-orm/pg-core function '${spec.fnName}', which that ` +
        `module does not export. Generated code importing it would not compile.`,
    );
  }
  const builder =
    spec.fnOptions !== undefined && Object.keys(spec.fnOptions).length > 0
      ? (fn as (n: string, o: unknown) => unknown)("c", spec.fnOptions)
      : (fn as (n: string) => unknown)("c");
  const table = pgCore.pgTable("t", { c: builder as never });
  return (table.c as unknown as { getSQLType(): string }).getSQLType();
}

/**
 * PostgreSQL's OWN alias spellings, collapsed to one form.
 *
 * This is deliberately NOT a mapping between the two doors — that would be a
 * third place for the answer to live, and the defect one level up. Every pair
 * here is two spellings PostgreSQL itself accepts for a single type (`\d` shows
 * one, `format_type` the other): drizzle renders `timestamp with time zone`
 * where migrate writes `timestamptz`, and they are the same column. A type that
 * is not on this list must match exactly.
 *
 * Length/precision qualifiers are dropped: `VARCHAR(200)` and `varchar` are the
 * same TYPE, and the qualifier is carried by `fnOptions` and gated by the
 * golden output.
 */
const PG_TYPE_ALIASES: ReadonlyMap<string, string> = new Map([
  ["timestamp with time zone", "timestamptz"],
  ["timestamp without time zone", "timestamp"],
  ["time with time zone", "timetz"],
  ["time without time zone", "time"],
  ["character varying", "varchar"],
  ["character", "char"],
  ["double precision", "float8"],
  ["boolean", "bool"],
  ["integer", "int4"],
  ["int", "int4"],
  ["bigint", "int8"],
  ["smallint", "int2"],
  ["real", "float4"],
  ["decimal", "numeric"],
]);

function pgCanonicalType(sql: string): string {
  const bare = sql.toLowerCase().replace(/\(.*$/, "").replace(/\[\]$/, "").trim();
  return PG_TYPE_ALIASES.get(bare) ?? bare;
}

/** Every concrete entity in the loaded root, by name. */
function entitiesByName(root: { children(): unknown[] }): Map<string, MetaObject> {
  const out = new Map<string, MetaObject>();
  for (const child of root.children()) {
    if (isMetaObject(child)) out.set(child.name, child as MetaObject);
  }
  return out;
}

describe("codegen and migrate spell one column's physical type the same way", () => {
  test("every canonical table column: drizzle's SQL type == the migration's SQL type", async () => {
    const root = await loadMetadataDir(CANONICAL_DIR);
    const expected = buildExpectedSchema(root, { dialect: DIALECT });
    const byName = entitiesByName(root as unknown as { children(): unknown[] });

    // Proves the corpus reaches this code at all — a loop over an empty table
    // list passes vacuously and would hide the very drift this exists to catch.
    expect(expected.tables.length).toBeGreaterThan(0);

    const disagreements: string[] = [];
    let compared = 0;

    for (const table of expected.tables) {
      // The entity that produced this table, so its fields can be asked the
      // codegen question. Tables whose owning entity cannot be recovered by
      // name (projection views, junctions synthesised by migrate) are skipped
      // — they are not a codegen column emission.
      const entity = [...byName.values()].find(
        (e) => (e.dbTable ?? "") === table.name || e.name === table.name,
      );
      if (entity === undefined) continue;

      for (const col of table.columns) {
        const field = entity
          .fields()
          .find((f: MetaField) => (mapColumnType(f, DIALECT).dbName ?? f.name) === col.name);
        if (field === undefined) continue;

        const spec = mapColumnType(field, DIALECT);
        // An int-backed field.enum's column function is a LOCAL generated const,
        // not a pg-core export, so there is nothing to build here.
        if (spec.enumIntCustomType !== undefined) continue;
        // A scalar `@isArray` column emits `.array()` on top of the element
        // function; the element type is what both sides agree on and the
        // array-ness is asserted elsewhere.
        if (field.resolvedIsArray()) continue;

        compared++;
        const fromCodegen = drizzleSqlType(spec);
        const fromMigrate = columnTypeSql(col, DIALECT);
        if (pgCanonicalType(fromCodegen) !== pgCanonicalType(fromMigrate)) {
          disagreements.push(
            `${table.name}.${col.name} (field '${field.name}', ${field.subType}): ` +
              `codegen emits drizzle ${spec.fnName}() → '${fromCodegen}', ` +
              `migrate writes '${fromMigrate}'`,
          );
        }
      }
    }

    expect(compared).toBeGreaterThan(0);
    expect(disagreements).toEqual([]);
  });

  test("an increment PK keeps its mapped type and gains the identity clause", async () => {
    const root = await loadMetadataDir(CANONICAL_DIR);
    const expected = buildExpectedSchema(root, { dialect: DIALECT });

    const identityCols = expected.tables.flatMap((t) =>
      t.columns.filter((c) => c.identity === "increment").map((c) => ({ t, c })),
    );
    // The corpus must actually carry the case. Without this the loop below is
    // vacuous exactly when the fixture stops covering it.
    expect(identityCols.length).toBeGreaterThan(0);

    for (const { t, c } of identityCols) {
      const sqlType = columnTypeSql(c, DIALECT).toLowerCase();
      // migrate never writes `serial` for an identity column, and the whole
      // defect was codegen doing so. If migrate's own answer ever becomes
      // `serial` this assertion is the one that should be revisited first.
      expect(`${t.name}.${c.name}: ${sqlType}`).not.toContain("serial");
      // And the type it DOES write must be one drizzle can carry an identity
      // clause on — otherwise codegen has no way to spell this column at all.
      expect(
        [...PG_IDENTITY_CAPABLE_FNS].some((fn) =>
          sqlType.startsWith(fn === "integer" ? "int" : fn),
        ),
      ).toBe(true);
    }
  });
});
