// callable-generator — FR-015. Emits one <Entity>.callable.g.cs per entity backed by
// a callable source.rdb (@kind: "storedProc" | "tableFunction"): a static EF Core
// calling method that runs `SELECT * FROM <schema.>proc(<args...>)` via
// FromSqlInterpolated and returns the (read-only projection) entity rows.
//
// The call-site argument list is derived from the @parameterRef value-object's field
// children IN DECLARATION ORDER — the same order contract the TS reference uses
// (server/typescript/packages/codegen-ts/src/templates/callable-file.ts). A callable
// without @parameterRef emits a zero-argument method (no `args` parameter).
//
// Mirrors the TS callable generator's stable name ("callable") + return contract.

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Persistence.Source.SourceConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates a typed EF Core calling method per callable-source entity (FR-015).</summary>
public class CallableGenerator : PerEntityGenerator
{
    public override string Name => "callable-generator";

    /// <summary>Only entities whose primary source is a callable kind (storedProc / tableFunction).</summary>
    protected override bool Filter(MetaObject entity) => CallableSource(entity) is not null;

    // The callable source = the first OWN source whose effective kind is callable. A
    // callable entity is a read-only projection (no writable table), so the source is
    // declared on the entity itself.
    private static MetaSource? CallableSource(MetaObject entity) =>
        entity.OwnSources().FirstOrDefault(s => s.IsCallable());

    protected override EmittedFile GenerateOne(MetaObject entity, GenContext ctx)
    {
        var source = CallableSource(entity)
            ?? throw new InvalidOperationException(
                $"{Name}: entity \"{entity.Name}\" has no callable source.rdb (storedProc / tableFunction).");

        var cls = CSharpNaming.Pascal(entity.Name);

        // Schema-qualified physical proc/function name (e.g. analytics.fn_phase_summary).
        var physical = source.PhysicalName;
        var procName = string.IsNullOrEmpty(source.Schema) ? physical : $"{source.Schema}.{physical}";

        // Resolve the @parameterRef value-object (same root as the entity). Its field
        // children — in declaration order — are the call-site arguments.
        var argsObjectName = source.ParameterRef;
        MetaObject? argsObject = null;
        if (argsObjectName is not null)
        {
            argsObject = ctx.Root.FindObject(CSharpNaming.StripPkg(argsObjectName));
            if (argsObject is null)
                ctx.Warn(
                    $"{Name}: callable \"{entity.Name}\" @parameterRef \"{argsObjectName}\" did not resolve — " +
                    "emitting a zero-argument method.");
        }

        // Own fields preserve declaration order. The SQL binds {args.<Prop>} per field;
        // FromSqlInterpolated parameterises each interpolation hole safely.
        var argProps = argsObject is null
            ? []
            : argsObject.OwnFields().Select(f => CSharpNaming.Pascal(f.Name)).ToList();

        var sqlArgs = string.Join(", ", argProps.Select(p => $"{{args.{p}}}"));
        var hasArgs = argsObject is not null;
        var signature = hasArgs ? $"AppDbContext db, {argsObjectName} args" : "AppDbContext db";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects callable-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        // FR-021 — the callable's home namespace + the args VO's namespace, when split.
        // The callable file declares a `static class {cls}Callable` referencing the
        // result type and the args type; both can live in different per-package
        // namespaces from where AppDbContext lives.
        var callableNs = PackageBindingResolver.Resolve(ctx.Config, PackageBindingResolver.EffectivePackage(entity), entity.Name);
        var argsNs = argsObject is not null
            ? PackageBindingResolver.Resolve(ctx.Config, PackageBindingResolver.EffectivePackage(argsObject), argsObject.Name)
            : null;
        // The callable file lives in the default namespace (alongside AppDbContext);
        // pull in usings for both the entity's home and the args object's home when
        // they differ.
        var fileNs = ctx.Config.Namespace;
        foreach (var ns in new[] { callableNs, argsNs }
            .Where(n => !string.IsNullOrEmpty(n) && n != fileNs)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(n => n, StringComparer.Ordinal))
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        var kindNoun = source.EffectiveKind == SOURCE_KIND_STORED_PROC ? "stored procedure" : "table function";
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// FR-015: typed wrapper around the <c>{procName}</c> {kindNoun}. Arguments bind in");
        sb.AppendLine($"/// declaration order from the @parameterRef value-object{(hasArgs ? $" (<c>{argsObjectName}</c>)" : string.Empty)}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {cls}Callable");
        sb.AppendLine("{");
        sb.AppendLine($"    public static async Task<IReadOnlyList<{cls}>> Call({signature})");
        sb.AppendLine("    {");
        sb.AppendLine($"        return await db.Set<{cls}>()");
        sb.AppendLine($"            .FromSqlInterpolated($\"SELECT * FROM {procName}({sqlArgs})\")");
        sb.AppendLine("            .AsNoTracking()");
        sb.AppendLine("            .ToListAsync();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return new EmittedFile($"{cls}.callable.g.cs", sb.ToString());
    }
}
