// dbcontext-generator — emits a single EF Core DbContext: a DbSet per persisted
// object (tables + read-only projections) plus an OnModelCreating that maps each
// projection to its view (.ToView / .HasNoKey) and configures owned types for
// object-typed entity fields (@storage flattened → per-property column names;
// jsonb / subdocument / absent → a single json column via .ToJson).

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Core.Field.FieldConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates one <c>AppDbContext</c> over the entities + projections.</summary>
public sealed class DbContextGenerator : IGenerator
{
    public string Name => "dbcontext-generator";

    public IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        var objects = ctx.Entities
            .Where(o => o.IsEntity() || o.DbView is not null)
            .OrderBy(o => o.Name, StringComparer.Ordinal)
            .ToList();
        if (objects.Count == 0) yield break;

        // OnModelCreating body lines (8-space indented), in a stable order.
        var modelLines = new List<string>();
        foreach (var p in objects.Where(o => o.IsReadOnlyProjection()))
        {
            var name = CSharpNaming.Pascal(p.Name);
            var noKey = p.PrimaryIdentity() is null ? ".HasNoKey()" : string.Empty;
            modelLines.Add($"        modelBuilder.Entity<{name}>(){noKey}.ToView(\"{p.DbView}\");");
        }
        foreach (var e in objects.Where(o => o.IsEntity() && !o.IsReadOnlyProjection()))
            foreach (var f in e.Fields().Where(f => f.SubType == FIELD_SUBTYPE_OBJECT))
                if (OwnedTypeConfig(e, f, ctx) is { } cfg) modelLines.Add(cfg);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects dbcontext-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("public class AppDbContext : DbContext");
        sb.AppendLine("{");
        sb.AppendLine("    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }");
        sb.AppendLine();
        foreach (var o in objects)
        {
            var name = CSharpNaming.Pascal(o.Name);
            sb.AppendLine($"    public DbSet<{name}> {CSharpNaming.Pluralize(name)} {{ get; set; }} = default!;");
        }

        if (modelLines.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("    protected override void OnModelCreating(ModelBuilder modelBuilder)");
            sb.AppendLine("    {");
            foreach (var line in modelLines) sb.AppendLine(line);
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        yield return new EmittedFile("AppDbContext.g.cs", sb.ToString());
    }

    // Owned-type config for an object-typed entity field. @storage flattened maps each
    // nested scalar to "{parentCol}_{nestedCol}"; every other storage collapses to one
    // json column (.ToJson) — matching PostgresSchema's table DDL. null (with a warning)
    // when @objectRef can't be resolved.
    private string? OwnedTypeConfig(MetaObject entity, MetaField field, GenContext ctx)
    {
        if (field.ObjectRef is not { } oref || ctx.Root.FindObject(StripPkg(oref)) is not { } vo)
        {
            ctx.Warn($"{Name}: object-typed field \"{entity.Name}.{field.Name}\" has an unresolved @objectRef \"{field.ObjectRef}\" — no owned-type config emitted.");
            return null;
        }
        var owner = CSharpNaming.Pascal(entity.Name);
        var nav = CSharpNaming.Pascal(field.Name);
        var parentCol = field.DbColumn ?? field.Name;

        if (field.Storage != STORAGE_FLATTENED)
            return $"        modelBuilder.Entity<{owner}>().OwnsOne(x => x.{nav}, b => b.ToJson(\"{parentCol}\"));";

        var sb = new StringBuilder();
        sb.AppendLine($"        modelBuilder.Entity<{owner}>().OwnsOne(x => x.{nav}, b =>");
        sb.AppendLine("        {");
        foreach (var nf in vo.Fields().Where(n => CSharpNaming.ScalarFor(n.SubType) is not null))
        {
            var nestedCol = $"{parentCol}_{nf.DbColumn ?? nf.Name}";
            sb.AppendLine($"            b.Property(p => p.{CSharpNaming.Pascal(nf.Name)}).HasColumnName(\"{nestedCol}\");");
        }
        sb.Append("        });");
        return sb.ToString();
    }

    private static string StripPkg(string s)
    {
        var i = s.LastIndexOf("::", StringComparison.Ordinal);
        return i < 0 ? s : s[(i + 2)..];
    }
}
