// entity-generator — emits an EF Core entity class per object.entity.
//
// PascalCase properties (C# convention) mapped to the metadata field name as the
// DB column via [Column]; [Table] from the dbTable source (or entity name); [Key]
// (or class-level [PrimaryKey] for composites); [MaxLength]; nullability driven by
// @required + primary-identity membership. Object-typed fields are skipped in this
// generator (nested-type handling lands with the storage/owned-type work).

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Core.Field.FieldConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates an EF Core entity class for each <c>object.entity</c>.</summary>
public sealed class EntityGenerator : PerEntityGenerator
{
    public override string Name => "entity-generator";

    // Generate for tables (object.entity) and read-only projections (any object
    // with a dbView). Plain value objects with no source are skipped.
    protected override bool Filter(MetaObject entity) => entity.IsEntity() || entity.DbView is not null;

    protected override EmittedFile GenerateOne(MetaObject entity, GenContext ctx)
    {
        var className = CSharpNaming.Pascal(entity.Name);
        var pk = entity.PrimaryIdentity();
        var pkFields = pk?.Fields ?? [];
        // Read-only projections map to a view (configured in the DbContext via
        // .ToView); they carry no [Table]. Tables / write-through carry [Table].
        var isProjection = entity.IsReadOnlyProjection();

        var scalarFields = entity.Fields()
            .Where(f => CSharpNaming.ScalarFor(f.SubType) is not null)
            .ToList();
        foreach (var f in entity.Fields().Where(f => CSharpNaming.ScalarFor(f.SubType) is null))
            ctx.Warn($"{Name}: skipping object-typed field \"{entity.Name}.{f.Name}\" (nested-type emit not yet supported).");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects entity-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();

        // Composite primary key -> class-level [PrimaryKey(...)] (EF Core 7+).
        if (pkFields.Count > 1)
        {
            var names = string.Join(", ", pkFields.Select(f => $"nameof({CSharpNaming.Pascal(f)})"));
            sb.AppendLine($"[PrimaryKey({names})]");
        }
        if (!isProjection)
            sb.AppendLine($"[Table(\"{entity.DbTable ?? entity.Name}\")]");
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        for (int i = 0; i < scalarFields.Count; i++)
        {
            var field = scalarFields[i];
            var baseType = CSharpNaming.ScalarFor(field.SubType)!;
            var required = CSharpNaming.IsRequired(entity, field);
            var isValue = CSharpNaming.IsValueType(baseType);
            var propName = CSharpNaming.Pascal(field.Name);
            var column = field.DbColumn ?? field.Name;

            // Single-column PK -> [Key]; composite handled at class level above.
            if (pkFields.Count == 1 && pkFields[0] == field.Name)
                sb.AppendLine("    [Key]");
            sb.AppendLine($"    [Column(\"{column}\")]");
            if (baseType == "string" && field.MaxLength is long max)
                sb.AppendLine($"    [MaxLength({max})]");
            if (required && !isValue)
                sb.AppendLine("    [Required]");

            string type = required ? baseType : baseType + "?";
            string init = required && !isValue ? " = default!;" : string.Empty;
            sb.AppendLine($"    public {type} {propName} {{ get; set; }}{init}");
            if (i < scalarFields.Count - 1) sb.AppendLine();
        }

        sb.AppendLine("}");
        return new EmittedFile($"{className}.g.cs", sb.ToString());
    }
}
