// entity-generator — emits an EF Core entity class per object.entity / projection,
// plus a plain POCO for each value object an object-typed field nests.
//
// PascalCase properties (C# convention) mapped to the metadata field name as the
// DB column via [Column]; [Table] from the dbTable source (or entity name); [Key]
// (or class-level [PrimaryKey] for composites); [MaxLength]; nullability driven by
// @required + primary-identity membership. Object-typed fields on entities become
// owned-type navigation properties (the column mapping — flattened vs. jsonb — is
// configured in the DbContext); the referenced value object is emitted as a POCO.
// Enum-typed fields emit a nested C# enum + a property typed by it; EF Core
// HasConversion<string>() is wired in the DbContext.
// Object-typed fields on read-only projections (collection origins) are not mapped
// here — that is a separate projection-materialization concern.

using System.Text;
using MetaObjects.Codegen.Docs;
using MetaObjects.Meta;
using static MetaObjects.Core.Field.FieldConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates EF Core entity/projection classes + value-object POCOs.</summary>
public sealed class EntityGenerator : IGenerator
{
    public string Name => "entity-generator";

    public IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        // Entities + read-only projections get the full EF mapping.
        var mapped = ctx.Entities
            .Where(o => o.IsEntity() || o.DbView is not null)
            .OrderBy(o => o.Name, StringComparer.Ordinal)
            .ToList();

        // Plain value objects targeted by an entity object-field become POCOs so the
        // owned-type navigation properties compile.
        var valueObjects = ReferencedValueObjects(mapped, ctx);

        var files = new List<EmittedFile>();
        foreach (var e in mapped)
            files.Add(EmitMappedClass(e, ctx));
        foreach (var vo in valueObjects)
            files.Add(EmitValueObjectPoco(vo, ctx));
        return files;
    }

    // EF Core entity (table) or projection (view) class.
    private EmittedFile EmitMappedClass(MetaObject entity, GenContext ctx)
    {
        var className = CSharpNaming.Pascal(entity.Name);
        var pk = entity.PrimaryIdentity();
        var pkFields = pk?.Fields ?? [];
        // Read-only projections map to a view (configured in the DbContext via
        // .ToView); they carry no [Table]. Tables / write-through carry [Table].
        var isProjection = entity.IsReadOnlyProjection();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects entity-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();

        // XML doc + [Obsolete] FIRST — XML doc-extraction tools (docfx,
        // Sandcastle, IDE hover-doc) require the doc comment to immediately
        // precede the declaration, before any attributes.
        XmlDocBuilder.AppendTo(sb, entity);
        // Composite primary key -> class-level [PrimaryKey(...)] (EF Core 7+).
        if (pkFields.Count > 1)
        {
            var names = string.Join(", ", pkFields.Select(f => $"nameof({CSharpNaming.Pascal(f)})"));
            sb.AppendLine($"[PrimaryKey({names})]");
        }
        if (!isProjection)
            sb.AppendLine($"[Table(\"{CSharpNaming.Table(entity)}\")]");
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        // Nested enum declarations (before the class properties, as C# enum members
        // must be declared before they are referenced by property types).
        var enumDecls = CollectEnumDecls(entity);

        // Members in declared order: scalar columns + enum-typed props + (entities only) owned-type navs.
        var members = new List<string>();
        foreach (var field in entity.Fields())
        {
            string? member = null;
            if (CSharpNaming.ScalarFor(field.SubType) is not null)
            {
                member = ScalarProperty(entity, field, pkFields, withAttributes: true);
            }
            else if (field.SubType == FIELD_SUBTYPE_ENUM)
            {
                member = EnumProperty(entity, field);
            }
            else if (field.SubType == FIELD_SUBTYPE_OBJECT)
            {
                // Owned-type navigation only on entities; projection collection
                // origins are materialized elsewhere.
                if (isProjection)
                {
                    ctx.Warn($"{Name}: skipping object-typed field \"{entity.Name}.{field.Name}\" on projection (collection materialization not emitted here).");
                    continue;
                }
                member = ObjectNavProperty(entity, field, ctx);
            }
            if (member is null) continue;
            members.Add(XmlDocBuilder.Prepend(member, field, "    "));
        }

        if (enumDecls.Count > 0)
        {
            sb.Append(string.Join("\n", enumDecls));
            sb.AppendLine();
        }
        sb.Append(string.Join("\n", members));
        sb.AppendLine();
        sb.AppendLine("}");
        return new EmittedFile($"{className}.g.cs", sb.ToString());
    }

    // Plain POCO for a value object nested by an owned-type navigation. No [Table] /
    // [Key]; column names are set in the DbContext's OwnsOne config (flattened) or are
    // opaque JSON property names (jsonb), so the POCO carries no mapping attributes.
    private EmittedFile EmitValueObjectPoco(MetaObject vo, GenContext ctx)
    {
        var className = CSharpNaming.Pascal(vo.Name);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects entity-generator (owned value object). Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        XmlDocBuilder.AppendTo(sb, vo);
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        var enumDeclsVo = CollectEnumDecls(vo);

        var members = new List<string>();
        foreach (var field in vo.Fields())
        {
            string? member = null;
            if (CSharpNaming.ScalarFor(field.SubType) is not null)
                member = ScalarProperty(vo, field, [], withAttributes: false);
            else if (field.SubType == FIELD_SUBTYPE_ENUM)
                member = EnumProperty(vo, field);
            else if (field.SubType == FIELD_SUBTYPE_OBJECT && ObjectNavProperty(vo, field, ctx) is { } nav)
                member = nav;
            if (member is null) continue;
            members.Add(XmlDocBuilder.Prepend(member, field, "    "));
        }

        if (enumDeclsVo.Count > 0)
        {
            sb.Append(string.Join("\n", enumDeclsVo));
            sb.AppendLine();
        }
        sb.Append(string.Join("\n", members));
        sb.AppendLine();
        sb.AppendLine("}");
        return new EmittedFile($"{className}.g.cs", sb.ToString());
    }

    // Collects nested C# enum declarations for all enum-subtype fields on an object,
    // deduplicating by type name so two fields that extend the same abstract enum emit
    // only one declaration (prevents CS0102 "already contains a definition for '<Name>'").
    private static List<string> CollectEnumDecls(MetaObject owner)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var decls = new List<string>();
        foreach (var field in owner.Fields())
        {
            if (field.SubType != FIELD_SUBTYPE_ENUM) continue;
            var values = field.EffectiveEnumValues;
            if (values is null || values.Count == 0) continue;
            var typeName = CSharpNaming.EnumTypeName(owner, field);
            if (!seen.Add(typeName)) continue;   // skip duplicate type names
            var members = string.Join(", ", values);
            decls.Add($"    public enum {typeName} {{ {members} }}");
        }
        return decls;
    }

    // A property for an enum-subtype field. The property type is the nested enum name.
    // When the field is an array, emit List<EnumType> with an empty-list initializer;
    // the List is never nullable (the column stores a jsonb array, always present).
    private static string EnumProperty(MetaObject entity, MetaField field)
    {
        var typeName = CSharpNaming.EnumTypeName(entity, field);
        var propName = CSharpNaming.Pascal(field.Name);
        var colAttr = $"    [Column(\"{CSharpNaming.Column(field)}\")]";
        if (field.IsArray)
            return $"{colAttr}\n    public List<{typeName}> {propName} {{ get; set; }} = new();";
        var required = CSharpNaming.IsRequired(entity, field);
        var type = required ? typeName : typeName + "?";
        return $"{colAttr}\n    public {type} {propName} {{ get; set; }}";
    }

    // A scalar property. withAttributes adds the EF mapping annotations ([Key] for a
    // single-column PK, [Column], [MaxLength], [Required]); value-object POCOs omit
    // them (column mapping is fluent/JSON, not annotation-driven).
    //
    // When the field is an array (isArray: true), emit List<T> with an empty-list
    // initializer instead of a scalar T property. Arrays are always non-nullable
    // (the jsonb column holds the list; the list itself is never null in C#).
    private static string ScalarProperty(MetaObject owner, MetaField field, IReadOnlyList<string> pkFields, bool withAttributes)
    {
        var baseType = CSharpNaming.ScalarFor(field.SubType)!;
        var propName = CSharpNaming.Pascal(field.Name);

        // Array fields: emit List<T> with an empty-list initializer and only a [Column]
        // attribute — [Key]/[MaxLength]/[Required] are not meaningful for a List<T> jsonb
        // column (arrays are never PKs, and the list itself is never null in C#).
        if (field.IsArray)
        {
            var arr = new StringBuilder();
            if (withAttributes)
                arr.AppendLine($"    [Column(\"{CSharpNaming.Column(field)}\")]");
            arr.Append($"    public List<{baseType}> {propName} {{ get; set; }} = new();");
            return arr.ToString();
        }

        var required = CSharpNaming.IsRequired(owner, field);
        var isValue = CSharpNaming.IsValueType(baseType);

        var sb = new StringBuilder();
        if (withAttributes)
        {
            if (pkFields.Count == 1 && pkFields[0] == field.Name)
                sb.AppendLine("    [Key]");
            sb.AppendLine($"    [Column(\"{CSharpNaming.Column(field)}\")]");
            if (baseType == "string" && field.MaxLength is long max)
                sb.AppendLine($"    [MaxLength({max})]");
            if (required && !isValue)
                sb.AppendLine("    [Required]");
        }

        var type = required ? baseType : baseType + "?";
        var init = required && !isValue ? " = default!;" : string.Empty;
        sb.Append($"    public {type} {propName} {{ get; set; }}{init}");
        return sb.ToString();
    }

    // An owned-type navigation property for an object-typed field. Returns null (with
    // a warning) when the @objectRef can't be resolved.
    private string? ObjectNavProperty(MetaObject owner, MetaField field, GenContext ctx)
    {
        if (field.ObjectRef is not { } oref || ctx.Root.FindObject(CSharpNaming.StripPkg(oref)) is not { } target)
        {
            ctx.Warn($"{Name}: object-typed field \"{owner.Name}.{field.Name}\" has an unresolved @objectRef \"{field.ObjectRef}\" — skipped.");
            return null;
        }
        var typeName = CSharpNaming.Pascal(target.Name);
        var propName = CSharpNaming.Pascal(field.Name);
        var required = CSharpNaming.IsRequired(owner, field);
        return required
            ? $"    public {typeName} {propName} {{ get; set; }} = default!;"
            : $"    public {typeName}? {propName} {{ get; set; }}";
    }

    // Transitive closure of plain value objects reachable through entity object-fields.
    private static List<MetaObject> ReferencedValueObjects(IReadOnlyList<MetaObject> mapped, GenContext ctx)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<MetaObject>();
        var queue = new Queue<MetaObject>();

        // Seed from entity object-fields (projections handled separately).
        foreach (var e in mapped.Where(o => o.IsEntity() && !o.IsReadOnlyProjection()))
            foreach (var f in e.Fields().Where(f => f.SubType == FIELD_SUBTYPE_OBJECT))
                Enqueue(f.ObjectRef);

        while (queue.Count > 0)
        {
            var vo = queue.Dequeue();
            result.Add(vo);
            foreach (var f in vo.Fields().Where(f => f.SubType == FIELD_SUBTYPE_OBJECT))
                Enqueue(f.ObjectRef);
        }
        return result.OrderBy(o => o.Name, StringComparer.Ordinal).ToList();

        void Enqueue(string? objectRef)
        {
            if (objectRef is null) return;
            var target = ctx.Root.FindObject(CSharpNaming.StripPkg(objectRef));
            // Only plain value objects (no source) become POCOs; entities/projections
            // are already in `mapped`.
            if (target is null || !target.IsValue() || target.DbView is not null) return;
            if (seen.Add(target.Name)) queue.Enqueue(target);
        }
    }
}
