// entity-generator — emits an EF Core entity class per object.entity / projection,
// plus a plain POCO for each value object an object-typed field nests.
//
// PascalCase properties (C# convention) mapped to the metadata field name as the
// DB column via [Column]; [Table] from the dbTable source (or entity name); [Key]
// (or class-level [PrimaryKey] for composites); [MaxLength]; nullability driven by
// @required + primary-identity membership. Object-typed fields on entities become
// owned-type navigation properties (the column mapping — flattened vs. jsonb — is
// configured in the DbContext); the referenced value object is emitted as a POCO.
// Enum-typed fields emit a nested C# enum + a property typed by it; EF Core
// HasConversion<string>() is wired in the DbContext.
// Object-typed fields on read-only projections (collection origins) are not mapped
// here — that is a separate projection-materialization concern.

using System.Text;
using MetaObjects.Codegen.Docs;
using MetaObjects.Meta;
using MetaObjects.Persistence.Origin;
using static MetaObjects.Core.Field.FieldConstants;
using static MetaObjects.Core.Validator.ValidatorConstants;
using static MetaObjects.Persistence.Origin.OriginConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>
/// Generates EF Core entity/projection classes + value-object POCOs.
///
/// Open for extension (ADR-0002): the per-class emit methods are
/// <c>protected virtual</c>, and two finer-grained hooks —
/// <see cref="EmitClassHeader"/> (XML-doc + composite [PrimaryKey] + [Table] + the
/// class declaration line) and <see cref="EmitPropertyAttributes"/> (per-property
/// C# attributes appended after the framework attributes) — cover the bulk of
/// adopter customizations. The default bodies leave emitted output byte-identical.
/// </summary>
public class EntityGenerator : IGenerator
{
    public virtual string Name => "entity-generator";

    public virtual IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        // Entities + read-only projections get the full EF mapping.
        var mapped = ctx.Entities
            .Where(o => o.IsEntity() || o.DbView is not null)
            .OrderBy(o => o.Name, StringComparer.Ordinal)
            .ToList();

        // Plain value objects targeted by an entity object-field become POCOs so the
        // owned-type navigation properties compile.
        var valueObjects = ReferencedValueObjects(mapped, ctx);

        var files = new List<EmittedFile>();
        foreach (var e in mapped)
        {
            // Abstract entities never produce a table-mapped instance class. Gated
            // by EmitAbstractShapes: off → no artifact at all; on → exactly one
            // standalone `public abstract class` shape (no EF mapping attributes).
            if (InstanceArtifacts.IsAbstract(e))
            {
                if (ctx.Config.EmitAbstractShapes)
                    files.Add(EmitAbstractShapeClass(e, ctx));
                continue;
            }
            // FR-017 TPH: a concrete subtype of a @discriminator base is NOT a standalone
            // table — it is `class Sub : Base` whose only members are its own (subtype-only)
            // fields, folded into the base's single physical table by EF as nullable columns.
            if (TphPlanBuilder.IsTphSubtype(e, ctx.Root))
            {
                files.Add(EmitTphSubtypeClass(e, ctx));
                continue;
            }
            files.Add(EmitMappedClass(e, ctx));
        }
        foreach (var vo in valueObjects)
            files.Add(EmitValueObjectPoco(vo, ctx));
        return files;
    }

    // EF Core entity (table) or projection (view) class.
    protected virtual EmittedFile EmitMappedClass(MetaObject entity, GenContext ctx)
    {
        var className = CSharpNaming.Pascal(entity.Name);
        var pk = entity.PrimaryIdentity();
        var pkFields = pk?.Fields ?? [];
        // Read-only projections map to a view (configured in the DbContext via
        // .ToView); they carry no [Table]. Tables / write-through carry [Table].
        var isProjection = entity.IsReadOnlyProjection();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects entity-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        // A composite PK emits a class-level [PrimaryKey(...)] which lives in the
        // Microsoft.EntityFrameworkCore namespace (not a DataAnnotations attribute) —
        // import it so the emitted class compiles standalone, without relying on the
        // host project's ImplicitUsings.
        if (pkFields.Count > 1)
            sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();

        EmitClassHeader(sb, entity, className, isProjection, pkFields, ctx);
        sb.AppendLine("{");

        // Nested enum declarations (before the class properties, as C# enum members
        // must be declared before they are referenced by property types).
        var enumDecls = CollectEnumDecls(entity);

        // Members in declared order: scalar columns + enum-typed props + (entities only) owned-type navs.
        var members = new List<string>();
        var strategy = ctx.Config.ColumnNamingStrategy;
        foreach (var field in entity.Fields())
        {
            string? member = null;
            if (CSharpNaming.ScalarFor(field.SubType) is not null)
            {
                member = ScalarProperty(entity, field, pkFields, withAttributes: true, strategy,
                    AggregateResultScalar(field, ctx));
            }
            else if (field.SubType == FIELD_SUBTYPE_ENUM)
            {
                member = EnumProperty(entity, field, strategy);
            }
            else if (field.SubType == FIELD_SUBTYPE_OBJECT)
            {
                // Owned-type navigation only on entities; projection collection
                // origins are materialized elsewhere.
                if (isProjection)
                {
                    ctx.Warn($"{Name}: skipping object-typed field \"{entity.Name}.{field.Name}\" on projection (collection materialization not emitted here).");
                    continue;
                }
                member = ObjectNavProperty(entity, field, ctx);
            }
            if (member is null) continue;
            member = ApplyPropertyAttributes(member, entity, field, ctx);
            members.Add(XmlDocBuilder.Prepend(member, field, "    "));
        }

        // FR-018 M:N navigation collections (entities only; the EF UsingEntity
        // wiring + the REST traversal route are emitted by the DbContext + routes
        // generators). One ICollection<Target> per @cardinality:"many" + @through
        // relationship — for a self-join the member is named after the relationship.
        if (!isProjection)
            foreach (var nav in M2MNavigationBuilder.For(entity, ctx.Root))
                members.Add(M2mNavProperty(nav));

        if (enumDecls.Count > 0)
        {
            sb.Append(string.Join("\n", enumDecls));
            sb.AppendLine();
        }
        sb.Append(string.Join("\n", members));
        sb.AppendLine();
        sb.AppendLine("}");
        return new EmittedFile($"{className}.g.cs", sb.ToString());
    }

    // Extension hook — owns the per-class header for a mapped entity/projection: the
    // XML doc comment, a composite class-level [PrimaryKey(...)], the [Table(...)] (on
    // tables/write-through only, never a read-only projection view), and the
    // `public [abstract] class <name>` declaration line. The default body reproduces
    // exactly the inline emission, so the default output is byte-identical. Override to
    // emit a `partial` class, add a marker interface, attach extra class-level
    // attributes, etc. (ADR-0002, open-closed). Implementations MUST NOT emit the
    // trailing `{` — the caller does.
    protected virtual void EmitClassHeader(
        StringBuilder sb, MetaObject entity, string className, bool isProjection,
        IReadOnlyList<string> pkFields, GenContext ctx)
    {
        // XML doc + [Obsolete] FIRST — XML doc-extraction tools (docfx,
        // Sandcastle, IDE hover-doc) require the doc comment to immediately
        // precede the declaration, before any attributes.
        XmlDocBuilder.AppendTo(sb, entity);
        // Composite primary key -> class-level [PrimaryKey(...)] (EF Core 7+).
        if (pkFields.Count > 1)
        {
            var names = string.Join(", ", pkFields.Select(f => $"nameof({CSharpNaming.Pascal(f)})"));
            sb.AppendLine($"[PrimaryKey({names})]");
        }
        if (!isProjection)
            sb.AppendLine($"[Table(\"{CSharpNaming.Table(entity)}\")]");
        // FR-017 TPH: the discriminator base is emitted `abstract` — every row is a
        // concrete subtype (no plain-base rows exist), so EF Core must not require a
        // base discriminator value. A concrete base with a discriminator but no
        // HasValue<Base>(...) fails model validation ("has a discriminator property,
        // but does not have a discriminator value configured").
        var classKeyword = TphPlanBuilder.IsTphDiscriminatorBase(entity, ctx.Root) ? "abstract class" : "class";
        sb.AppendLine($"public {classKeyword} {className}");
    }

    // A M:N navigation collection property on the source entity. The collection is
    // the relationship name PascalCased; its element type is the target entity.
    //
    // Hetero (source != target) is wired as an EF skip-navigation through the
    // junction (DbContext UsingEntity<Through>). A self-join (directed or symmetric)
    // is NOT an EF many-to-many: a self-referencing M:N over an explicit junction is
    // not cleanly expressible, and a symmetric relation is union-on-read (no EF
    // relationship at all). Those navs are [NotMapped] — the REST route + runtime
    // resolver traverse the junction explicitly (the cross-port contract is the
    // route behavior, not EF eager-loading).
    private static string M2mNavProperty(M2MNavigation nav)
    {
        var target = CSharpNaming.Pascal(nav.Target.Name);
        var prop = CSharpNaming.Pascal(nav.Name);
        var notMapped = nav.IsSelfJoin ? "    [NotMapped]\n" : "";
        return $"{notMapped}    public ICollection<{target}> {prop} {{ get; set; }} = new List<{target}>();";
    }

    // FR-017 TPH subtype class: `public class <Sub> : <Base>` carrying ONLY its
    // subtype-only fields (those not already on the base). All are emitted NULLABLE
    // and WITHOUT [Key]/[Required] — they map to nullable columns in the base's single
    // physical table (a row of another subtype stores NULL there), so even an
    // @required subtype field is nullable at the column level. The subtype carries NO
    // [Table] (it shares the base's table) and no PK ([Key] lives on the base).
    protected virtual EmittedFile EmitTphSubtypeClass(MetaObject entity, GenContext ctx)
    {
        var className = CSharpNaming.Pascal(entity.Name);
        var baseClass = CSharpNaming.Pascal(TphBaseOf(entity).Name);
        var baseFieldNames = new HashSet<string>(
            TphBaseOf(entity).Fields().Select(f => f.Name), StringComparer.Ordinal);
        var strategy = ctx.Config.ColumnNamingStrategy;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects entity-generator (TPH subtype). Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();

        XmlDocBuilder.AppendTo(sb, entity);
        sb.AppendLine($"public class {className} : {baseClass}");
        sb.AppendLine("{");

        // Subtype-only enum declarations (an enum field declared on the subtype, not the base).
        var ownEnumDecls = new List<string>();
        var seenEnum = new HashSet<string>(StringComparer.Ordinal);
        foreach (var field in entity.Fields())
        {
            if (baseFieldNames.Contains(field.Name)) continue;
            if (field.SubType != FIELD_SUBTYPE_ENUM) continue;
            var values = field.EffectiveEnumValues;
            if (values is null || values.Count == 0) continue;
            var typeName = CSharpNaming.EnumTypeName(entity, field);
            if (!seenEnum.Add(typeName)) continue;
            ownEnumDecls.Add($"    public enum {typeName} {{ {string.Join(", ", values)} }}");
        }

        var members = new List<string>();
        foreach (var field in entity.Fields())
        {
            if (baseFieldNames.Contains(field.Name)) continue; // inherited from the base
            string? member = null;
            if (CSharpNaming.ScalarFor(field.SubType) is not null)
                member = TphSubtypeScalarProperty(field, strategy);
            else if (field.SubType == FIELD_SUBTYPE_ENUM)
                member = TphSubtypeEnumProperty(entity, field, strategy);
            else if (field.SubType == FIELD_SUBTYPE_OBJECT)
                member = ObjectNavProperty(entity, field, ctx);
            if (member is null) continue;
            member = ApplyPropertyAttributes(member, entity, field, ctx);
            members.Add(XmlDocBuilder.Prepend(member, field, "    "));
        }

        if (ownEnumDecls.Count > 0)
        {
            sb.Append(string.Join("\n", ownEnumDecls));
            sb.AppendLine();
        }
        sb.Append(string.Join("\n", members));
        sb.AppendLine();
        sb.AppendLine("}");
        return new EmittedFile($"{className}.g.cs", sb.ToString());
    }

    // A subtype-only scalar property: NULLABLE, [Column]-mapped, with the field's
    // validator attributes (length/numeric/regex) but NEVER [Key]/[Required] (the
    // column is nullable in the shared TPH table). Arrays keep the List<T> shape.
    private static string TphSubtypeScalarProperty(MetaField field, ColumnNamingStrategy strategy)
    {
        var baseType = CSharpNaming.ScalarFor(field.SubType)!;
        var propName = CSharpNaming.Pascal(field.Name);

        if (field.IsArray)
        {
            var arr = new StringBuilder();
            arr.AppendLine($"    [Column(\"{CSharpNaming.Column(field, strategy)}\")]");
            AppendArrayValidatorAttributes(arr, field);
            arr.Append($"    public List<{baseType}> {propName} {{ get; set; }} = new();");
            return arr.ToString();
        }

        var sb = new StringBuilder();
        sb.AppendLine($"    [Column(\"{CSharpNaming.Column(field, strategy)}\")]");
        if (baseType == "string")
            AppendStringValidatorAttributes(sb, field);
        else
            AppendNumericValidatorAttributes(sb, field);
        // Always nullable — subtype-only columns are NULL for rows of other subtypes.
        sb.Append($"    public {baseType}? {propName} {{ get; set; }}");
        return sb.ToString();
    }

    // A subtype-only enum property: NULLABLE, [Column]-mapped (no [Required]).
    private static string TphSubtypeEnumProperty(MetaObject entity, MetaField field, ColumnNamingStrategy strategy)
    {
        var typeName = CSharpNaming.EnumTypeName(entity, field);
        var propName = CSharpNaming.Pascal(field.Name);
        var colAttr = $"    [Column(\"{CSharpNaming.Column(field, strategy)}\")]\n";
        if (field.IsArray)
            return $"{colAttr}    public List<{typeName}> {propName} {{ get; set; }} = new();";
        return $"{colAttr}    public {typeName}? {propName} {{ get; set; }}";
    }

    // The nearest @discriminator-bearing ancestor of a TPH subtype (its TPH base).
    private static MetaObject TphBaseOf(MetaObject subtype)
    {
        MetaData? cursor = subtype.SuperData;
        while (cursor is not null)
        {
            if (cursor.OwnAttr(MetaObjects.Core.Object.ObjectConstants.OBJECT_ATTR_DISCRIMINATOR) is string v
                && v.Length > 0 && cursor is MetaObject mo)
                return mo;
            cursor = cursor.SuperData;
        }
        // Unreachable: IsTphSubtype guarantees a discriminator ancestor exists.
        throw new InvalidOperationException($"TPH subtype \"{subtype.Name}\" has no @discriminator base.");
    }

    // Standalone shape class for an ABSTRACT entity (emitted only when
    // GenConfig.EmitAbstractShapes is true). An abstract entity contributes shape
    // via inheritance, not as a table — so this carries NO EF mapping attributes
    // ([Table]/[Key]/[Column]/[MaxLength]/[Required]) and is emitted as
    // `public abstract class`. C# concrete entities flatten inherited fields (they
    // do not reference the base), so the shape is standalone — never a base type.
    protected virtual EmittedFile EmitAbstractShapeClass(MetaObject entity, GenContext ctx)
    {
        var className = CSharpNaming.Pascal(entity.Name);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects entity-generator (abstract shape). Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();

        XmlDocBuilder.AppendTo(sb, entity);
        sb.AppendLine($"public abstract class {className}");
        sb.AppendLine("{");

        var enumDecls = CollectEnumDecls(entity);

        // Body: scalar + enum + object-nav members, all WITHOUT EF mapping attributes
        // (a shape, not a table).
        var members = new List<string>();
        foreach (var field in entity.Fields())
        {
            string? member = null;
            if (CSharpNaming.ScalarFor(field.SubType) is not null)
                member = ScalarProperty(entity, field, [], withAttributes: false);
            else if (field.SubType == FIELD_SUBTYPE_ENUM)
                member = EnumProperty(entity, field, ColumnNamingStrategy.Literal, withAttributes: false);
            else if (field.SubType == FIELD_SUBTYPE_OBJECT && ObjectNavProperty(entity, field, ctx) is { } nav)
                member = nav;
            if (member is null) continue;
            member = ApplyPropertyAttributes(member, entity, field, ctx);
            members.Add(XmlDocBuilder.Prepend(member, field, "    "));
        }

        if (enumDecls.Count > 0)
        {
            sb.Append(string.Join("\n", enumDecls));
            sb.AppendLine();
        }
        sb.Append(string.Join("\n", members));
        sb.AppendLine();
        sb.AppendLine("}");
        return new EmittedFile($"{className}.g.cs", sb.ToString());
    }

    // Plain POCO for a value object nested by an owned-type navigation. No [Table] /
    // [Key]; column names are set in the DbContext's OwnsOne config (flattened) or are
    // opaque JSON property names (jsonb), so the POCO carries no mapping attributes.
    protected virtual EmittedFile EmitValueObjectPoco(MetaObject vo, GenContext ctx)
    {
        var className = CSharpNaming.Pascal(vo.Name);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects entity-generator (owned value object). Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        XmlDocBuilder.AppendTo(sb, vo);
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        var enumDeclsVo = CollectEnumDecls(vo);

        var members = new List<string>();
        foreach (var field in vo.Fields())
        {
            string? member = null;
            if (CSharpNaming.ScalarFor(field.SubType) is not null)
                member = ScalarProperty(vo, field, [], withAttributes: false);
            else if (field.SubType == FIELD_SUBTYPE_ENUM)
                member = EnumProperty(vo, field, ctx.Config.ColumnNamingStrategy);
            else if (field.SubType == FIELD_SUBTYPE_OBJECT && ObjectNavProperty(vo, field, ctx) is { } nav)
                member = nav;
            if (member is null) continue;
            member = ApplyPropertyAttributes(member, vo, field, ctx);
            members.Add(XmlDocBuilder.Prepend(member, field, "    "));
        }

        if (enumDeclsVo.Count > 0)
        {
            sb.Append(string.Join("\n", enumDeclsVo));
            sb.AppendLine();
        }
        sb.Append(string.Join("\n", members));
        sb.AppendLine();
        sb.AppendLine("}");
        return new EmittedFile($"{className}.g.cs", sb.ToString());
    }

    // Collects nested C# enum declarations for all enum-subtype fields on an object,
    // deduplicating by type name so two fields that extend the same abstract enum emit
    // only one declaration (prevents CS0102 "already contains a definition for '<Name>'").
    private static List<string> CollectEnumDecls(MetaObject owner)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var decls = new List<string>();
        foreach (var field in owner.Fields())
        {
            if (field.SubType != FIELD_SUBTYPE_ENUM) continue;
            var values = field.EffectiveEnumValues;
            if (values is null || values.Count == 0) continue;
            var typeName = CSharpNaming.EnumTypeName(owner, field);
            if (!seen.Add(typeName)) continue;   // skip duplicate type names
            var members = string.Join(", ", values);
            decls.Add($"    public enum {typeName} {{ {members} }}");
        }
        return decls;
    }

    // Extension hook — invoked once per emitted property, AFTER the framework
    // attributes ([Key]/[Column]/[Required]/[MaxLength]/validators) and immediately
    // BEFORE the `public <type> <Prop> { get; ... }` line. The default body is empty
    // (no-op), so default output is byte-identical. Override to append per-property C#
    // attributes (e.g. `[ContainsPhi]`, `[ReportingField(...)]`) keyed off the field's
    // metadata. Each line written should carry the 4-space property indent.
    protected virtual void EmitPropertyAttributes(
        StringBuilder sb, MetaObject owner, MetaField field, GenContext ctx)
    {
        // No-op by default.
    }

    // Splices the EmitPropertyAttributes hook output into an already-built member
    // string, immediately before its `    public ` declaration line (after the
    // framework attributes). When the hook is the default no-op the member is returned
    // unchanged, keeping default output byte-identical.
    private string ApplyPropertyAttributes(string member, MetaObject owner, MetaField field, GenContext ctx)
    {
        var hook = new StringBuilder();
        EmitPropertyAttributes(hook, owner, field, ctx);
        if (hook.Length == 0) return member;

        const string decl = "    public ";
        var idx = member.LastIndexOf(decl, StringComparison.Ordinal);
        if (idx < 0) return member; // no recognizable property line — leave untouched
        return member[..idx] + hook + member[idx..];
    }

    // A property for an enum-subtype field. The property type is the nested enum name.
    // When the field is an array, emit List<EnumType> with an empty-list initializer;
    // the List is never nullable (the column stores a jsonb array, always present).
    // withAttributes adds the EF [Column] mapping; abstract shape classes pass false
    // (shapes carry no EF mapping).
    private static string EnumProperty(
        MetaObject entity, MetaField field, ColumnNamingStrategy strategy, bool withAttributes = true)
    {
        var typeName = CSharpNaming.EnumTypeName(entity, field);
        var propName = CSharpNaming.Pascal(field.Name);
        var colAttr = withAttributes ? $"    [Column(\"{CSharpNaming.Column(field, strategy)}\")]\n" : "";
        if (field.IsArray)
            return $"{colAttr}    public List<{typeName}> {propName} {{ get; set; }} = new();";
        var required = CSharpNaming.IsRequired(entity, field);
        var type = required ? typeName : typeName + "?";
        return $"{colAttr}    public {type} {propName} {{ get; set; }}";
    }

    // A scalar property. withAttributes adds the EF mapping annotations ([Key] for a
    // single-column PK, [Column], [MaxLength], [Required]); value-object POCOs omit
    // them (column mapping is fluent/JSON, not annotation-driven).
    //
    // When the field is an array (isArray: true), emit List<T> with an empty-list
    // initializer instead of a scalar T property. Arrays are always non-nullable
    // (the jsonb column holds the list; the list itself is never null in C#).
    private static string ScalarProperty(
        MetaObject owner, MetaField field, IReadOnlyList<string> pkFields,
        bool withAttributes, ColumnNamingStrategy strategy = ColumnNamingStrategy.Literal,
        string? baseTypeOverride = null)
    {
        var baseType = baseTypeOverride ?? CSharpNaming.ScalarFor(field.SubType)!;
        var propName = CSharpNaming.Pascal(field.Name);

        // Array fields: emit List<T> with an empty-list initializer and only a [Column]
        // attribute — [Key]/[MaxLength]/[Required] are not meaningful for a List<T> jsonb
        // column (arrays are never PKs, and the list itself is never null in C#).
        if (field.IsArray)
        {
            var arr = new StringBuilder();
            if (withAttributes)
            {
                arr.AppendLine($"    [Column(\"{CSharpNaming.Column(field, strategy)}\")]");
                // validator.array @min/@max → element-count bounds on the collection.
                AppendArrayValidatorAttributes(arr, field);
            }
            arr.Append($"    public List<{baseType}> {propName} {{ get; set; }} = new();");
            return arr.ToString();
        }

        var required = CSharpNaming.IsRequired(owner, field);
        var isValue = CSharpNaming.IsValueType(baseType);

        var sb = new StringBuilder();
        if (withAttributes)
        {
            if (pkFields.Count == 1 && pkFields[0] == field.Name)
                sb.AppendLine("    [Key]");
            sb.AppendLine($"    [Column(\"{CSharpNaming.Column(field, strategy)}\")]");
            if (baseType == "string")
                AppendStringValidatorAttributes(sb, field);
            else
                AppendNumericValidatorAttributes(sb, field);
            if (required && !isValue)
                sb.AppendLine("    [Required]");
        }

        var type = required ? baseType : baseType + "?";
        var init = required && !isValue ? " = default!;" : string.Empty;
        // FR-013 — a @readOnly scalar is read-after-insert-only: EF materializes it on
        // read via a private setter; application code cannot write it, and the
        // DbContext excludes the column from INSERT / UPDATE (SetAfterSaveBehavior.Ignore).
        var setter = field.ReadOnly ? "get; private set;" : "get; set;";
        sb.Append($"    public {type} {propName} {{ {setter} }}{init}");
        return sb.ToString();
    }

    // String length + pattern DataAnnotations for a string scalar, combining the field
    // @maxLength attr with validator.length (@min/@max) and validator.regex (@pattern).
    //
    // Length: when both a minimum (validator.length @min) and a maximum (@maxLength or
    // validator.length @max) apply, emit a single [StringLength(max, MinimumLength = min)]
    // — the form TryValidateObject enforces on BOTH ends. Min-only → [MinLength]; max-only
    // → [MaxLength] (preserving the existing @maxLength semantics).
    private static void AppendStringValidatorAttributes(StringBuilder sb, MetaField field)
    {
        long? min = null;
        long? max = field.MaxLength;
        foreach (var v in field.Validators())
        {
            if (v.SubType == VALIDATOR_SUBTYPE_LENGTH)
            {
                if (v.Min is long lmin) min = lmin;
                if (v.Max is long lmax) max = lmax;
            }
            else if (v.SubType == VALIDATOR_SUBTYPE_REGEX
                     && v is MetaRegexValidator { Pattern: { } pattern })
            {
                sb.AppendLine($"    [RegularExpression(\"{EscapeAttrString(pattern)}\")]");
            }
        }

        if (min is long mn && max is long mx)
            sb.AppendLine($"    [StringLength({mx}, MinimumLength = {mn})]");
        else if (min is long mn2)
            sb.AppendLine($"    [MinLength({mn2})]");
        else if (max is long mx2)
            sb.AppendLine($"    [MaxLength({mx2})]");
    }

    // Numeric value bounds for a non-string scalar: validator.numeric (@min/@max) →
    // [Range(min, max)]. Both bounds present in the canonical corpus; when only one is
    // declared the other defaults to the type's extreme so the single bound still gates.
    private static void AppendNumericValidatorAttributes(StringBuilder sb, MetaField field)
    {
        foreach (var v in field.Validators())
        {
            if (v.SubType != VALIDATOR_SUBTYPE_NUMERIC) continue;
            if (v.Min is null && v.Max is null) continue;
            long lo = v.Min ?? long.MinValue;
            long hi = v.Max ?? long.MaxValue;
            sb.AppendLine($"    [Range({lo}, {hi})]");
            return;
        }
    }

    // Element-count bounds for an array field: validator.array (@min/@max) →
    // [MinLength(min)] + [MaxLength(max)] on the List<T> property.
    private static void AppendArrayValidatorAttributes(StringBuilder sb, MetaField field)
    {
        foreach (var v in field.Validators())
        {
            if (v.SubType != VALIDATOR_SUBTYPE_ARRAY) continue;
            if (v.Min is long amin) sb.AppendLine($"    [MinLength({amin})]");
            if (v.Max is long amax) sb.AppendLine($"    [MaxLength({amax})]");
            return;
        }
    }

    // Escapes a regex pattern for embedding in a C# string-literal attribute argument.
    private static string EscapeAttrString(string s) =>
        s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    // An owned-type navigation property for an object-typed field. Returns null (with
    // a warning) when the @objectRef can't be resolved.
    private string? ObjectNavProperty(MetaObject owner, MetaField field, GenContext ctx)
    {
        if (field.ObjectRef is not { } oref || ctx.Root.FindObject(CSharpNaming.StripPkg(oref)) is not { } target)
        {
            ctx.Warn($"{Name}: object-typed field \"{owner.Name}.{field.Name}\" has an unresolved @objectRef \"{field.ObjectRef}\" — skipped.");
            return null;
        }
        var typeName = CSharpNaming.Pascal(target.Name);
        var propName = CSharpNaming.Pascal(field.Name);
        var required = CSharpNaming.IsRequired(owner, field);
        return required
            ? $"    public {typeName} {propName} {{ get; set; }} = default!;"
            : $"    public {typeName}? {propName} {{ get; set; }}";
    }

    // The CLR scalar type for a projection field whose value is a MIN/MAX aggregate:
    // the result type of MIN(col)/MAX(col) in SQL is the aggregated column's own type,
    // NOT the (often-widened) field.* declaration. e.g. MIN over an INTEGER column is
    // INTEGER — so the projection property must materialize as `int`, which the read
    // path then surfaces as a JSON number (vs. a BIGINT → string). COUNT/SUM widen to
    // BIGINT and AVG to NUMERIC, both already matched by the declared field.* type, so
    // only MIN/MAX need the source-type narrowing. Returns null (use the declared type)
    // for non-aggregate fields, non-MIN/MAX aggregates, or an unresolvable @of target.
    private static string? AggregateResultScalar(MetaField field, GenContext ctx)
    {
        var agg = field.Children().OfType<MetaAggregateOrigin>().FirstOrDefault();
        if (agg?.Agg is not (AGGREGATE_FN_MIN or AGGREGATE_FN_MAX)) return null;
        // @of is a dotted "Entity.field" reference to the aggregated column.
        if (agg.Of is not { } of) return null;
        var dot = of.LastIndexOf('.');
        if (dot <= 0 || dot == of.Length - 1) return null;
        var sourceObj = ctx.Root.FindObject(CSharpNaming.StripPkg(of[..dot]));
        var sourceField = sourceObj?.FindField(of[(dot + 1)..]);
        return sourceField is null ? null : CSharpNaming.ScalarFor(sourceField.SubType);
    }

    // Transitive closure of plain value objects reachable through entity object-fields.
    private static List<MetaObject> ReferencedValueObjects(IReadOnlyList<MetaObject> mapped, GenContext ctx)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var result = new List<MetaObject>();
        var queue = new Queue<MetaObject>();

        // Seed from entity object-fields (projections handled separately).
        foreach (var e in mapped.Where(o => o.IsEntity() && !o.IsReadOnlyProjection()))
            foreach (var f in e.Fields().Where(f => f.SubType == FIELD_SUBTYPE_OBJECT))
                Enqueue(f.ObjectRef);

        while (queue.Count > 0)
        {
            var vo = queue.Dequeue();
            result.Add(vo);
            foreach (var f in vo.Fields().Where(f => f.SubType == FIELD_SUBTYPE_OBJECT))
                Enqueue(f.ObjectRef);
        }
        return result.OrderBy(o => o.Name, StringComparer.Ordinal).ToList();

        void Enqueue(string? objectRef)
        {
            if (objectRef is null) return;
            var target = ctx.Root.FindObject(CSharpNaming.StripPkg(objectRef));
            // Only plain value objects (no source) become POCOs; entities/projections
            // are already in `mapped`.
            if (target is null || !target.IsValue() || target.DbView is not null) return;
            if (seen.Add(target.Name)) queue.Enqueue(target);
        }
    }
}
