// Cross-port Extractor codegen (C# port) — the `extract` tier over the existing tolerant extract.
//
// For each `template.output` (json/xml, @payloadRef resolving to a value-object with a nested
// object / array-of-objects), emits `<Payload>Extractor.cs`: a static `<Payload>Extractor` class
// that turns dirty LLM text into the STRICT typed payload record (PayloadCodegen's immutable
// `sealed record` with `required init` props) in one call. It REUSES the nested-capable
// runtime-delegating extract emitted by OutputParserGenerator — `<Template>Parser.Extract(
// MetaObject, text[, opts])`, which assembles the FULL nested object graph via the Phase-A object
// model — runs it, throws ExtractException iff a @required field was lost, else maps the
// all-nullable `<Payload>Extracted` mirror onto the strict `<Payload>` via a generated recursive
// mirror->strict mapper (recurse nested objects + arrays-of-objects; one-shot object-initializer
// construct). `extract` is re-exposed unchanged. NO registry / binding / factory — codegen knows
// the whole type graph statically.
//
// Cross-port parity: mirrors the TS `renderExtractor` (templates/extractor.ts), the Python
// ExtractorGenerator, and the Java ExtractorCodeGenerator. The C# port adds the recursive
// mirror->strict mapper (ToStrict_<Type>) the JVM ports get for free from their flavored
// object-class binding.
//
// OPTIONALITY (C#-specific, no-skew). PayloadCodegen emits EVERY payload field as `required
// {NonNullableType}` (it does not honor @required). The strict record therefore has no
// nullable/optional props, so the mapper maps EVERY field as required: scalar -> m.F! ; single
// nested -> ToStrict_<Nested>(m.F!) ; array-of-objects -> m.F!.Select(ToStrict_<Item>).ToList() ;
// scalar-array -> drop-null projection. There is NO optional-null variant (there is no nullable
// strict property to assign null to) — this matches PayloadCodegen's predicate exactly. The
// lost-REQUIRED gate (ExtractException) fires only for fields the metadata marks @required:true.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Shared.BaseTypes;
using static MetaObjects.Shared.Structural;
using static MetaObjects.Core.Field.FieldConstants;
using static MetaObjects.Template.TemplateConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>
/// Emits one <c>&lt;Payload&gt;Extractor.cs</c> per nested-capable <c>template.output</c> — the
/// <c>extract</c> tier (tolerant extract into the strict typed payload record).
/// </summary>
public sealed class ExtractorGenerator : IGenerator
{
    public string Name => "extractor-generator";

    public IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        var outputs = ctx.Root.OwnChildren()
            .Where(c => c.Type == TYPE_TEMPLATE && c.SubType == TEMPLATE_SUBTYPE_OUTPUT)
            .OrderBy(t => t.Name, System.StringComparer.Ordinal)
            .ToList();

        var files = new List<EmittedFile>();
        foreach (var tmpl in outputs)
        {
            if (tmpl.OwnAttr(TEMPLATE_ATTR_PAYLOAD_REF) is not string payloadRef)
            {
                ctx.Warn($"{Name}: template.output \"{tmpl.Name}\" missing @payloadRef — skipped.");
                continue;
            }

            var format = tmpl.OwnAttr(TEMPLATE_ATTR_FORMAT) as string ?? "text";
            bool formatSupportsExtract =
                format.Equals("json", System.StringComparison.OrdinalIgnoreCase) ||
                format.Equals("xml", System.StringComparison.OrdinalIgnoreCase);
            var vo = ExtractDelegateEmitter.FindObject(ctx.Root, payloadRef);

            // The extract tier sits over the NESTED-CAPABLE delegating extract, which
            // OutputParserGenerator emits only for json/xml payloads that have a nested object /
            // array-of-objects. Skip otherwise (nothing to extract over).
            if (!formatSupportsExtract || vo is null || !ExtractDelegateEmitter.HasNested(vo, ctx.Root))
                continue;

            files.Add(EmitExtractor(tmpl, vo, payloadRef, ctx));
        }
        return files;
    }

    private static EmittedFile EmitExtractor(MetaData tmpl, MetaData vo, string payloadRef, GenContext ctx)
    {
        string templateName = tmpl.Name;
        string parserClass = $"{templateName}Parser";
        string strictType = payloadRef;                 // PayloadCodegen emits the bare VO name.
        string rootMirror = $"{payloadRef}Extracted";
        string extractorClass = $"{payloadRef}Extractor";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects extractor-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using MetaObjects.Render.Extract;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>The <c>extract</c> tier for the <c>{templateName}</c> template.output — turns dirty LLM");
        sb.AppendLine($"/// text into a fully-typed <see cref=\"{strictType}\"/> graph (nested objects + arrays-of-objects");
        sb.AppendLine($"/// populated) in one call, by delegating to the nested-capable extract and mapping the all-nullable");
        sb.AppendLine($"/// <c>{rootMirror}</c> mirror onto the strict payload. No registry / binding / factory.</summary>");
        sb.AppendLine($"public static class {extractorClass}");
        sb.AppendLine("{");

        // ---- Extract(MetaObject, text) ----
        sb.AppendLine($"    /// <summary>Extract a fully-typed <see cref=\"{strictType}\"/> from dirty <paramref name=\"text\"/> using");
        sb.AppendLine($"    /// the runtime <paramref name=\"mo\"/> (the loaded payload object). Runs the tolerant extract, then maps");
        sb.AppendLine($"    /// the extracted mirror onto the strict payload.</summary>");
        sb.AppendLine($"    /// <exception cref=\"ExtractException\">iff a <c>@required</c> field was lost (the strict opt-in gate).</exception>");
        sb.AppendLine($"    public static {strictType} Extract(global::MetaObjects.Meta.MetaObject mo, string text)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var r = {parserClass}.ExtractLenient(mo, text);");
        sb.AppendLine("        if (r.Report.HasLostRequired())");
        sb.AppendLine("            throw new ExtractException(r.Report);");
        sb.AppendLine($"        return ToStrict_{strictType}(r.Data!);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ---- Extract(MetaObject, text, opts) ----
        sb.AppendLine($"    /// <summary>Extract with explicit <see cref=\"ExtractOptions\"/>.</summary>");
        sb.AppendLine($"    /// <exception cref=\"ExtractException\">iff a <c>@required</c> field was lost.</exception>");
        sb.AppendLine($"    public static {strictType} Extract(global::MetaObjects.Meta.MetaObject mo, string text, ExtractOptions opts)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var r = {parserClass}.ExtractLenient(mo, text, opts);");
        sb.AppendLine("        if (r.Report.HasLostRequired())");
        sb.AppendLine("            throw new ExtractException(r.Report);");
        sb.AppendLine($"        return ToStrict_{strictType}(r.Data!);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ---- re-exposed Extract(MetaObject, text) (never throws; returns the mirror result) ----
        sb.AppendLine($"    /// <summary>Re-exposes the nested-capable tolerant extract; never throws. Inspect <c>Report</c> for");
        sb.AppendLine($"    /// lost/defaulted fields. Returns the all-nullable <c>{rootMirror}</c> mirror (not the strict payload).</summary>");
        sb.AppendLine($"    public static ExtractionResult<{rootMirror}> ExtractLenient(global::MetaObjects.Meta.MetaObject mo, string text) =>");
        sb.AppendLine($"        {parserClass}.ExtractLenient(mo, text);");

        // ---- recursive mirror->strict mappers (payload + nested, deduped, cycle-safe) ----
        EmitMappers(sb, vo, ctx.Root);

        sb.AppendLine("}");

        return new EmittedFile($"{extractorClass}.cs", sb.ToString());
    }

    private static void EmitMappers(StringBuilder sb, MetaData vo, MetaData root)
    {
        var seen = new HashSet<string>(System.StringComparer.Ordinal);
        EmitMapper(sb, vo, root, seen);
    }

    private static void EmitMapper(StringBuilder sb, MetaData vo, MetaData root, HashSet<string> seen)
    {
        if (!seen.Add(vo.Name)) return;
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Map the all-nullable <c>{vo.Name}Extracted</c> mirror onto the strict <c>{vo.Name}</c> payload. Generated.</summary>");
        sb.AppendLine($"    private static {vo.Name} ToStrict_{vo.Name}({vo.Name}Extracted m) => new {vo.Name}");
        sb.AppendLine("    {");
        foreach (var f in Fr010FieldMapping.Fields(vo))
            sb.AppendLine($"        {f.Name} = {StrictArg(f, root)},");
        sb.AppendLine("    };");

        // Recurse into nested-object targets (single + array) for their mappers.
        foreach (var f in Fr010FieldMapping.Fields(vo))
            if (ExtractDelegateEmitter.IsObjectField(f) && ExtractDelegateEmitter.RefVo(f, root) is { } target)
                EmitMapper(sb, target, root, seen);
    }

    /// <summary>
    /// The strict-record initializer expression for one field, reading mirror member <c>m.&lt;name&gt;</c>.
    /// Matches PayloadCodegen's predicate: every strict field is <c>required</c> + non-nullable, so every
    /// field is mapped as required (no optional-null variant).
    /// </summary>
    private static string StrictArg(MetaData field, MetaData root)
    {
        string name = field.Name;

        // Object BEFORE array (object-before-isArray): array-of-objects maps element-wise.
        if (ExtractDelegateEmitter.IsObjectField(field))
        {
            var target = ExtractDelegateEmitter.RefVo(field, root);
            if (target is null)
                // Unresolved @objectRef — PayloadCodegen types this as the bare ref name; pass through.
                return $"m.{name}!";
            string fn = $"ToStrict_{target.Name}";
            return Fr010FieldMapping.IsArray(field)
                ? $"m.{name}!.Select({fn}).ToList()"
                : $"{fn}(m.{name}!)";
        }

        // Scalar ARRAY: the mirror is kind-typed IReadOnlyList<TElem?>? (int?/long?/double?/bool?/
        // string?) and the strict payload is IReadOnlyList<TElem> — drop nulls so the element narrows
        // to non-null, unwrapping value-type elements via `.Value` (reference-type string stays bare),
        // matching the single-scalar unwrap below.
        if (Fr010FieldMapping.IsArray(field))
        {
            string elem = Fr010FieldMapping.ScalarMirrorType(field.SubType); // e.g. "int?" / "string?"
            string unwrap = field.SubType != FIELD_SUBTYPE_ENUM &&
                            Fr010FieldMapping.ScalarKind(field.SubType) is "Int" or "Long" or "Double" or "Boolean"
                ? "x!.Value" : "x!";
            return $"(m.{name} ?? global::System.Linq.Enumerable.Empty<{elem}>()).Where(x => x is not null).Select(x => {unwrap}).ToList()";
        }

        // Scalar / enum (single): the strict record is non-null. Value-type scalars (int/long/
        // double/bool) are typed T? in the mirror, so `m.F!` keeps type T? — unwrap via `.Value`.
        // Reference-type scalars (string, incl. enum which is string-backed) use the null-forgiving `!`.
        if (field.SubType == FIELD_SUBTYPE_ENUM) return $"m.{name}!";
        return Fr010FieldMapping.ScalarKind(field.SubType) switch
        {
            "Int" or "Long" or "Double" or "Boolean" => $"m.{name}!.Value",
            _ => $"m.{name}!",
        };
    }
}
