// Cross-port Extractor codegen (C# port) — the `extract` tier over the existing tolerant extract.
//
// For each responding `template.prompt` whose @responseRef value object has a nested object /
// array-of-objects, emits `<Prompt>Extractor.cs`: a static `<Prompt>Extractor` class that turns dirty LLM
// text into the value object's own POCO (ADR-0056 — the one EntityGenerator emits) in one call. It
// REUSES the nested-capable runtime-delegating extract emitted by OutputParserGenerator —
// `<Template>Parser.ExtractLenient(MetaObject, text[, opts])`, which assembles the FULL nested
// object graph via the Phase-A object model — runs it, throws ExtractException iff a @required
// field was lost, else maps the all-nullable `<Vo>Extracted` mirror onto the POCO via a generated
// recursive mirror->POCO mapper (recurse nested objects + arrays-of-objects; one object-initializer
// construct). `ExtractLenient` is re-exposed unchanged. NO registry / binding / factory — codegen
// knows the whole type graph statically.
//
// Cross-port parity: mirrors the TS `renderExtractor` (templates/extractor.ts), the Python
// ExtractorGenerator, and the Java ExtractorCodeGenerator. The C# port adds the recursive
// mirror->POCO mapper (ToStrict_<Type>) the JVM ports get for free from their flavored
// object-class binding.
//
// OPTIONALITY follows the POCO, which follows @required: a required member is non-nullable and
// the lost-REQUIRED gate guarantees its mirror value is present, so it maps with `!`; an optional
// member is nullable and maps null to null. The mirror carries temporal / uuid / uri / inet values
// as strings, so the mapper parses them into the POCO's native types (invariant culture). A member
// with @mutability readOnly has a private setter on the POCO and is left to its default here.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Shared.BaseTypes;
using static MetaObjects.Shared.Structural;
using static MetaObjects.Core.Field.FieldConstants;
using static MetaObjects.Template.TemplateConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>
/// Emits one <c>&lt;Prompt&gt;Extractor.cs</c> per responding <c>template.prompt</c> whose response
/// value object nests an object — the <c>extract</c> tier (tolerant extract into the value object's POCO).
/// </summary>
public class ExtractorGenerator : IGenerator
{
    public virtual string Name => "extractor-generator";

    public virtual IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        var files = new List<EmittedFile>();
        // ADR-0052: the direction rule lives in FindInbound, never re-derived here.
        foreach (var tmpl in FindInbound.InboundTemplates(ctx.Root))
        {
            // ADR-0052: the extract tier reads a REPLY, so it binds @responseRef. The old
            // json/xml gate against @format is gone — @responseFormat is a closed json|xml set,
            // so the only remaining skips are an unresolvable ref and a flat shape.
            if (FindInbound.ResponseShape(ctx.Root, tmpl) is not { } shape)
            {
                ctx.Warn($"{Name}: template.prompt \"{tmpl.Name}\" @responseRef does not resolve — skipped.");
                continue;
            }

            // The extract tier sits over the NESTED-CAPABLE delegating extract, which
            // OutputParserGenerator emits only for shapes that have a nested object /
            // array-of-objects. Skip otherwise (nothing to extract over).
            if (!ExtractDelegateEmitter.HasNested(shape.Vo, ctx.Root)) continue;

            files.Add(EmitExtractor(tmpl, shape.Vo, shape.Ref, ctx));
        }
        return files;
    }

    protected virtual EmittedFile EmitExtractor(MetaData tmpl, MetaData vo, string payloadRef, GenContext ctx)
    {
        string templateName = tmpl.Name;
        string parserClass = CSharpNaming.ParserClassName(templateName);
        string ns = ctx.Config.Namespace;
        // ADR-0056: the strict type IS the value object's own POCO; the mirror is its <Vo>Extracted.
        string strictType = ValueObjectNames.TypeRef(vo, ctx.Root, ctx.Config, ns);
        string rootMirror = ExtractDelegateEmitter.MirrorRef(vo, ctx.Root, ctx.Config, ns);
        string extractorClass = CSharpNaming.ExtractorClassName(templateName);
        string rootMapper = MapperName(vo, ctx.Root);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects extractor-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using MetaObjects.Render.Extract;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>The <c>extract</c> tier for the <c>{templateName}</c> template.prompt — turns dirty LLM");
        sb.AppendLine($"/// text into a fully-typed <see cref=\"{strictType}\"/> graph (nested objects + arrays-of-objects");
        sb.AppendLine($"/// populated) in one call, by delegating to the nested-capable extract and mapping the all-nullable");
        sb.AppendLine($"/// <c>{ExtractDelegateEmitter.MirrorName(vo, ctx.Root)}</c> mirror onto the value object. No registry / binding / factory.</summary>");
        sb.AppendLine($"public static class {extractorClass}");
        sb.AppendLine("{");

        sb.AppendLine($"    /// <summary>Extract a fully-typed <see cref=\"{strictType}\"/> from dirty <paramref name=\"text\"/> using");
        sb.AppendLine($"    /// the runtime <paramref name=\"mo\"/> (the loaded value object). Runs the tolerant extract, then maps");
        sb.AppendLine($"    /// the extracted mirror onto the value object.</summary>");
        sb.AppendLine($"    /// <exception cref=\"ExtractException\">iff a <c>@required</c> field was lost or malformed (the strict opt-in gate).</exception>");
        sb.AppendLine($"    public static {strictType} Extract(global::MetaObjects.Meta.MetaObject mo, string text)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var r = {parserClass}.ExtractLenient(mo, text);");
        sb.AppendLine("        if (r.Report.HasLostRequired() || r.Report.HasMalformedRequired())");
        sb.AppendLine("            throw new ExtractException(r.Report);");
        sb.AppendLine($"        return {rootMapper}(r.Data!);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Extract with explicit <see cref=\"ExtractOptions\"/>.</summary>");
        sb.AppendLine($"    /// <exception cref=\"ExtractException\">iff a <c>@required</c> field was lost or malformed.</exception>");
        sb.AppendLine($"    public static {strictType} Extract(global::MetaObjects.Meta.MetaObject mo, string text, ExtractOptions opts)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var r = {parserClass}.ExtractLenient(mo, text, opts);");
        sb.AppendLine("        if (r.Report.HasLostRequired() || r.Report.HasMalformedRequired())");
        sb.AppendLine("            throw new ExtractException(r.Report);");
        sb.AppendLine($"        return {rootMapper}(r.Data!);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Re-exposes the nested-capable tolerant extract; never throws. Inspect <c>Report</c> for");
        sb.AppendLine($"    /// lost/defaulted fields. Returns the all-nullable mirror (not the value object).</summary>");
        sb.AppendLine($"    public static ExtractionResult<{rootMirror}> ExtractLenient(global::MetaObjects.Meta.MetaObject mo, string text) =>");
        sb.AppendLine($"        {parserClass}.ExtractLenient(mo, text);");

        // One mapper per value object the mirror reaches (the root included), deduped by FQN.
        foreach (var v in ExtractDelegateEmitter.MirrorClosure(vo, ctx.Root))
            EmitMapper(sb, v, ctx);

        sb.AppendLine("}");

        return new EmittedFile($"{extractorClass}.cs", sb.ToString());
    }

    private static string MapperName(MetaData vo, MetaData root) => $"ToStrict_{ValueObjectNames.TypeName(vo, root)}";

    private static void EmitMapper(StringBuilder sb, MetaData vo, GenContext ctx)
    {
        string ns = ctx.Config.Namespace;
        string type = ValueObjectNames.TypeRef(vo, ctx.Root, ctx.Config, ns);
        string mirror = ExtractDelegateEmitter.MirrorRef(vo, ctx.Root, ctx.Config, ns);
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Map the all-nullable <c>{ExtractDelegateEmitter.MirrorName(vo, ctx.Root)}</c> mirror onto <c>{ValueObjectNames.TypeName(vo, ctx.Root)}</c>. Generated.</summary>");
        sb.AppendLine($"    private static {type} {MapperName(vo, ctx.Root)}({mirror} m) => new {type}");
        sb.AppendLine("    {");
        foreach (var f in Fr010FieldMapping.Fields(vo).OfType<MetaField>())
        {
            // A readOnly member has a private setter on the POCO: an initializer cannot set it.
            if (f.IsReadOnlyMutability) continue;
            sb.AppendLine($"        {CSharpNaming.Pascal(f.Name)} = {StrictArg((MetaObject)vo, f, ctx)},");
        }
        sb.AppendLine("    };");
    }

    /// <summary>The initializer expression mapping one mirror member onto the POCO member.</summary>
    private static string StrictArg(MetaObject owner, MetaField field, GenContext ctx)
    {
        string m = $"m.{field.Name}";
        bool required = CSharpNaming.IsRequired(owner, field);

        if (ExtractDelegateEmitter.IsObjectField(field))
        {
            if (ExtractDelegateEmitter.RefVo(field, ctx.Root) is not { } target)
                return "default!";
            string fn = MapperName(target, ctx.Root);
            if (Fr010FieldMapping.IsArray(field))
            {
                string list = $".Where(x => x is not null).Select(x => {fn}(x!)).ToList()";
                string elem = ExtractDelegateEmitter.MirrorRef(target, ctx.Root, ctx.Config, ctx.Config.Namespace);
                return required
                    ? $"({m} ?? global::System.Linq.Enumerable.Empty<{elem}?>()){list}"
                    : $"{m}?{list}";
            }
            return required ? $"{fn}({m}!)" : $"{m} is null ? null : {fn}({m})";
        }

        if (field.SubType == FIELD_SUBTYPE_ENUM)
        {
            string et = EnumTypeRef(owner, field, ctx);
            if (Fr010FieldMapping.IsArray(field))
                return $"({m} ?? global::System.Linq.Enumerable.Empty<string?>()).Where(x => x is not null)" +
                       $".Select(x => System.Enum.Parse<{et}>(x!)).ToList()";
            return required ? $"System.Enum.Parse<{et}>({m}!)" : $"{m} is null ? ({et}?)null : System.Enum.Parse<{et}>({m})";
        }

        string baseType = CSharpNaming.DbColumnTypeClrOverride(field) ?? CSharpNaming.ScalarForField(field) ?? "string";
        bool mirrorIsValue = Fr010FieldMapping.ScalarMirrorType(field.SubType) != "string?";

        if (Fr010FieldMapping.IsArray(field))
        {
            // The POCO's scalar list is never null (an absent array is empty), whatever @required says.
            string elem = Fr010FieldMapping.ScalarMirrorType(field.SubType);
            string x = Convert(mirrorIsValue ? "x!.Value" : "x!", baseType);
            return $"({m} ?? global::System.Linq.Enumerable.Empty<{elem}>()).Where(x => x is not null).Select(x => {x}).ToList()";
        }

        if (required)
            return Convert(mirrorIsValue ? $"{m}!.Value" : $"{m}!", baseType);
        // Optional: null stays null. A nullable mirror value maps straight onto a nullable POCO
        // member of the same type; anything else converts the present value.
        string converted = Convert(mirrorIsValue ? $"{m}.Value" : m, baseType);
        if (converted == m || converted == $"{m}.Value") return m;
        string nullable = CSharpNaming.IsValueType(baseType) ? $"({baseType}?)null" : "null";
        return $"{m} is null ? {nullable} : {converted}";
    }

    /// <summary>
    /// Convert a present mirror value (<paramref name="v"/>, already unwrapped for value types) to
    /// the POCO member's CLR type. The mirror carries temporal, uuid, uri and inet values as the
    /// strings the model wrote; the POCO holds the native types.
    /// </summary>
    private static string Convert(string v, string baseType) => baseType switch
    {
        "DateOnly" => $"global::System.DateOnly.Parse({v}, global::System.Globalization.CultureInfo.InvariantCulture)",
        "TimeOnly" => $"global::System.TimeOnly.Parse({v}, global::System.Globalization.CultureInfo.InvariantCulture)",
        "DateTimeOffset" => $"global::System.DateTimeOffset.Parse({v}, global::System.Globalization.CultureInfo.InvariantCulture)",
        "DateTime" => $"global::System.DateTime.Parse({v}, global::System.Globalization.CultureInfo.InvariantCulture)",
        "Guid" => $"global::System.Guid.Parse({v})",
        "Uri" => $"new global::System.Uri({v}, global::System.UriKind.RelativeOrAbsolute)",
        "IPAddress" => $"global::System.Net.IPAddress.Parse({v})",
        "JsonDocument" => $"global::System.Text.Json.JsonDocument.Parse({v})",
        "float" => $"(float){v}",
        _ => v,
    };

    /// <summary>The enum type a POCO member is typed by, as seen from the extractor's namespace:
    /// a shared enum (FR-019) by its own reference, an inline one nested in the value object's class.</summary>
    private static string EnumTypeRef(MetaObject owner, MetaField field, GenContext ctx) =>
        Fr019SharedEnum.SharedEnumForField(field) is { } shared
            ? Fr019SharedEnum.SharedEnumTypeReference(shared, ctx.Config)
            : $"{ValueObjectNames.TypeRef(owner, ctx.Root, ctx.Config, ctx.Config.Namespace)}.{CSharpNaming.EnumTypeName(owner, field)}";
}
