// filter-allowlist-generator — emits one <Entity>FilterAllowlist.cs per writable
// object.entity that lists filterable field names + the per-field operator
// allowlist (per the cross-port FR-009 spec).
//
// Authoring contract: only fields with @filterable: true appear in the
// allowlist. If no field is marked filterable the file is still emitted (with
// empty collections) so the generated routes can unconditionally delegate to
// it without conditional codegen branching.
//
// Operators-per-subtype mapping (FR-009 §5, identical across ports):
//   string / enum                              → eq, ne, in, like, isNull
//   uuid                                       → eq, ne, in, isNull  (no like — not a substring type)
//   int / long / float / double /
//   decimal / currency / date / timestamp / time → eq, ne, gt, gte, lt, lte, in, isNull
//   boolean                                    → eq, isNull
//
// Read-only projections (source.rdb @kind=view/...) are skipped — they have no
// filter routes today (G3 in the routes generator's gap list).

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Core.Field.FieldConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates one <c>&lt;Entity&gt;FilterAllowlist.cs</c> per writable entity.</summary>
public class FilterAllowlistGenerator : PerEntityGenerator
{
    public override string Name => "filter-allowlist-generator";

    /// <summary>Operator set for string-shaped subtypes.</summary>
    internal static readonly string[] OpsString =
        { "eq", "ne", "in", "like", "isNull" };

    /// <summary>Operator set for uuid — identity comparison only, no <c>like</c> (not a substring type) and no ordering.</summary>
    internal static readonly string[] OpsUuid =
        { "eq", "ne", "in", "isNull" };

    /// <summary>Operator set for numeric / date / timestamp / currency subtypes.</summary>
    internal static readonly string[] OpsNumeric =
        { "eq", "ne", "gt", "gte", "lt", "lte", "in", "isNull" };

    /// <summary>Operator set for boolean subtype.</summary>
    internal static readonly string[] OpsBoolean = { "eq", "isNull" };

    // Read-only projections (views/etc.) are not filterable in the routes
    // generator today — skip them here to match.
    protected override bool Filter(MetaObject entity) =>
        entity.IsEntity() && !entity.IsReadOnlyProjection() && InstanceArtifacts.EmitsInstanceArtifacts(entity);

    protected override EmittedFile GenerateOne(MetaObject entity, GenContext ctx)
    {
        var cls = CSharpNaming.Pascal(entity.Name);
        var opsByField = ComputeFilterableOps(entity);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects filter-allowlist-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// GENERATED — per-entity FR-009 filter allowlist for {cls}.");
        sb.AppendLine("/// <see cref=\"Fields\"/> lists the filterable field names; <see cref=\"OpsByField\"/>");
        sb.AppendLine("/// constrains the operator vocabulary for each field by its subtype.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {cls}FilterAllowlist");
        sb.AppendLine("{");

        // Fields — the field-name set. Use System.StringComparer.Ordinal for
        // case-sensitive matching (the URL grammar is case-exact).
        sb.AppendLine("    public static readonly HashSet<string> Fields = new(System.StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var f in opsByField.Keys) sb.AppendLine($"        \"{f}\",");
        sb.AppendLine("    };");
        sb.AppendLine();

        // OpsByField — Dictionary<field, HashSet<op>>.
        sb.AppendLine("    public static readonly Dictionary<string, HashSet<string>> OpsByField = new(System.StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var kvp in opsByField)
        {
            sb.Append($"        [\"{kvp.Key}\"] = new(System.StringComparer.Ordinal) {{ ");
            bool first = true;
            foreach (var op in kvp.Value)
            {
                if (!first) sb.Append(", ");
                first = false;
                sb.Append('"').Append(op).Append('"');
            }
            sb.AppendLine(" },");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return new EmittedFile($"{cls}FilterAllowlist.g.cs", sb.ToString());
    }

    /// <summary>
    /// Build the (fieldName → opSet) map for <paramref name="entity"/>. Only
    /// fields with <c>@filterable: true</c> are included; subtypes outside the
    /// FR-009 vocabulary (object/class) collapse to the empty op-set and are
    /// dropped.
    /// </summary>
    protected virtual Dictionary<string, IReadOnlyList<string>> ComputeFilterableOps(MetaObject entity)
    {
        var out_ = new Dictionary<string, IReadOnlyList<string>>(System.StringComparer.Ordinal);
        foreach (var field in entity.Fields())
        {
            if (field.SubType == FIELD_SUBTYPE_OBJECT) continue;
            if (!IsFilterable(field)) continue;
            var ops = OpsForSubtype(field.SubType);
            if (ops.Count == 0) continue;
            out_[field.Name] = ops;
        }
        return out_;
    }

    /// <summary>True iff <paramref name="field"/> carries <c>@filterable: true</c> (bool true or case-insensitive "true" — matches Java/Kotlin/Python tolerance).</summary>
    private static bool IsFilterable(MetaField field) => field.OwnAttr(FIELD_ATTR_FILTERABLE) switch
    {
        true => true,
        string s => string.Equals(s, "true", StringComparison.OrdinalIgnoreCase),
        _ => false,
    };

    /// <summary>Operator set for <paramref name="subType"/>, or empty for unsupported subtypes.</summary>
    internal static IReadOnlyList<string> OpsForSubtype(string? subType) => subType switch
    {
        FIELD_SUBTYPE_STRING or FIELD_SUBTYPE_ENUM => OpsString,
        FIELD_SUBTYPE_UUID => OpsUuid,
        FIELD_SUBTYPE_INT or FIELD_SUBTYPE_LONG
            or FIELD_SUBTYPE_FLOAT or FIELD_SUBTYPE_DOUBLE or FIELD_SUBTYPE_DECIMAL
            or FIELD_SUBTYPE_CURRENCY
            or FIELD_SUBTYPE_DATE or FIELD_SUBTYPE_TIMESTAMP or FIELD_SUBTYPE_TIME => OpsNumeric,
        FIELD_SUBTYPE_BOOLEAN => OpsBoolean,
        _ => System.Array.Empty<string>(),
    };
}
