// names-generator — emits one <Entity>Names.g.cs per object with a declared (or
// inherited) primary source (#248): GENERATED per-object physical database name
// constants (spec A1/A2/A6) a hand-written consumer references instead of a string
// literal.
//
// const, not static readonly: a [Table("...")]/[Column("...")] attribute argument
// requires a compile-time constant, and those two sites are the whole reason this
// artifact can replace a literal rather than sit beside one. ColumnsByField is
// `static readonly` because a Dictionary cannot be const — it serves iteration, not
// the attributes.

using System.Text;
using MetaObjects.Meta;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates one <c>&lt;Entity&gt;Names.g.cs</c> per object with a declared primary source.</summary>
public sealed class NamesGenerator : PerEntityGenerator
{
    public override string Name => "names";

    // #248: participation derives from a declared primary source, never from the
    // object subtype — never gate on IsEntity()/abstract/etc. A cheap existence check;
    // the strategy-sensitive full resolve happens once, in GenerateOne, against the real
    // ctx.Config.ColumnNamingStrategy. The divergence refusal is not this generator's to
    // own and never was — it lives in MetaObjects.Meta.SourceResolution, which every
    // caller that resolves a physical name goes through, codegen and runtime alike.
    protected override bool Filter(MetaObject entity) => CSharpNaming.HasPrimarySource(entity);

    protected override EmittedFile GenerateOne(MetaObject entity, GenContext ctx)
    {
        var cls = CSharpNaming.NamesClassName(entity);

        // A3: the SAME resolver the EF Core bindings are meant to call, with the same
        // arguments, in the same run — CSharpNaming.ResolveObjectNames (beside
        // NamesClassName) is the ONE place a data name is resolved. Filter() already
        // proved a primary source exists, so a null here means Filter and the resolver
        // disagree about existence — a codegen bug, not a model one.
        var names = CSharpNaming.ResolveObjectNames(entity, ctx.Config.ColumnNamingStrategy)
            ?? throw new InvalidOperationException(
                $"{entity.Name}: Filter() matched (a primary source exists) but ResolveObjectNames " +
                "returned null.");

        var fields = names.Fields.Values
            .Select(f => (Member: CSharpNaming.Pascal(f.Name), f.Name, f.Column))
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToList();

        // Two fields whose Pascal forms collide would emit duplicate const members.
        // C# would refuse to compile it, but the error would name a generated file and
        // read as a codegen bug rather than a model one. Fail here, naming the model.
        var dupe = fields.GroupBy(t => t.Member).FirstOrDefault(g => g.Count() > 1);
        if (dupe is not null)
            throw new InvalidOperationException(
                $"{entity.Name}: fields {string.Join(", ", dupe.Select(d => d.Name))} all yield the " +
                $"constant member \"{dupe.Key}\". Rename one, or give it an explicit @column.");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects names-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        // Task 4 (§A6) — the same per-package resolution EntityGenerator uses for the
        // entity itself, so a package carrying a PackageNamespaces override still lands
        // its <Entity>Names companion in the SAME namespace as the entity it describes
        // (the promise the consumption sites rely on: no new `using` is required).
        // Bare ctx.Config.Namespace would silently break that promise whenever a
        // per-package override is configured.
        sb.AppendLine($"namespace {PackageBindingResolver.Resolve(ctx.Config, PackageBindingResolver.EffectivePackage(entity), entity.Name, fallbackContext: entity.Name)};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// GENERATED — per-object physical database names for {CSharpNaming.Pascal(entity.Name)} (spec A1/A2/A6).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {cls}");
        sb.AppendLine("{");
        sb.AppendLine($"    public const string Kind = \"{names.Kind}\";");
        sb.AppendLine($"    public const string Name = \"{names.Name}\";");
        // Omitted, never emitted as null: absent means undeclared, and a `null` constant
        // would read as "declared empty".
        if (!string.IsNullOrEmpty(names.Schema))
            sb.AppendLine($"    public const string Schema = \"{names.Schema}\";");
        sb.AppendLine($"    public const bool ReadOnly = {(names.ReadOnly ? "true" : "false")};");
        sb.AppendLine();
        foreach (var (member, field, column) in fields)
        {
            sb.AppendLine($"    public const string {member}Field = \"{field}\";");
            sb.AppendLine($"    public const string {member}Column = \"{column}\";");
        }
        sb.AppendLine();
        sb.AppendLine("    public static readonly Dictionary<string, string> ColumnsByField = new(System.StringComparer.Ordinal)");
        sb.AppendLine("    {");
        foreach (var (member, field, _) in fields)
            sb.AppendLine($"        [\"{field}\"] = {member}Column,");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return new EmittedFile($"{cls}.g.cs", sb.ToString());
    }
}
