// output-prompt-generator — for each `template.output` whose @format is json or xml, emits a
// `<TemplateName>.prompt.cs` file declaring a static `<TemplateName>Prompt` class with a
// `RenderFormat()` / `RenderFormat(PromptOverrides)` pair backed by the render engine's
// OutputFormatRenderer (FR-010 artifact 1 — the "produce your answer like this" fragment).
//
// The baked OutputFormatSpec's rootName is the payload class name, so the prompt fragment and
// the extract() codegen agree on the root element/object name. Mirrors the Java
// SpringOutputPromptGenerator. Skips: template.prompt, missing/unresolved @payloadRef,
// and @format values other than json/xml.

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Shared.BaseTypes;
using static MetaObjects.Template.TemplateConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>
/// Emits one <c>&lt;Template&gt;Prompt</c> class per json/xml <c>template.output</c>, exposing
/// <c>RenderFormat()</c> + <c>RenderFormat(PromptOverrides)</c>.
/// </summary>
public class OutputPromptGenerator : IGenerator
{
    public virtual string Name => "output-prompt-generator";

    public virtual IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        var outputs = ctx.Root.OwnChildren()
            .Where(c => c.Type == TYPE_TEMPLATE && c.SubType == TEMPLATE_SUBTYPE_OUTPUT)
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToList();

        var files = new List<EmittedFile>();
        foreach (var tmpl in outputs)
        {
            if (!AppliesTo(tmpl, ctx.Root)) continue;
            var payloadRef = (string)tmpl.OwnAttr(TEMPLATE_ATTR_PAYLOAD_REF)!;
            var vo = ctx.Root.OwnChildren().First(c => c.Type == TYPE_OBJECT && c.Name == payloadRef);
            files.Add(EmitPrompt(tmpl, vo, payloadRef, ctx));
        }
        return files;
    }

    /// <summary>
    /// True iff this generator emits an output-format prompt for <paramref name="tmpl"/>:
    /// a <c>template.output</c> with a json/xml <c>@format</c> and a <c>@payloadRef</c>
    /// that resolves to a root-level <c>object</c>. Single source of truth shared by the
    /// generator loop AND the api-docs builder (so docs never claim a suppressed symbol).
    /// </summary>
    public static bool AppliesTo(MetaData tmpl, MetaRoot root)
    {
        if (tmpl.Type != TYPE_TEMPLATE || tmpl.SubType != TEMPLATE_SUBTYPE_OUTPUT) return false;
        var format = tmpl.OwnAttr(TEMPLATE_ATTR_FORMAT) as string ?? "text";
        var supported =
            format.Equals("json", StringComparison.OrdinalIgnoreCase) ||
            format.Equals("xml", StringComparison.OrdinalIgnoreCase);
        if (!supported) return false;
        if (tmpl.OwnAttr(TEMPLATE_ATTR_PAYLOAD_REF) is not string payloadRef) return false;
        return root.OwnChildren().Any(c => c.Type == TYPE_OBJECT && c.Name == payloadRef);
    }

    protected virtual EmittedFile EmitPrompt(MetaData tmpl, MetaData vo, string payloadRef, GenContext ctx)
    {
        var templateName = tmpl.Name;
        var promptClass = CSharpNaming.PromptClassName(templateName);
        // rootName == payload class name so the prompt fragment and extract() agree.
        var specLiteral = OutputFormatSpecEmitter.SpecLiteral(vo, tmpl, payloadRef);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects output-prompt-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using MetaObjects.Render.Prompt;");
        sb.AppendLine("using MetaObjects.Render.Extract;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Output-format prompt fragment for the <c>{templateName}</c> template.output.</summary>");
        sb.AppendLine($"public static class {promptClass}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly OutputFormatSpec Spec = {specLiteral};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The output-format instruction fragment (\"produce your answer like this\").</summary>");
        sb.AppendLine("    public static string RenderFormat() => OutputFormatRenderer.Render(Spec, PromptOverrides.None());");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The fragment with render-time overrides (style / per-field example / instruction).</summary>");
        sb.AppendLine("    public static string RenderFormat(PromptOverrides overrides) => OutputFormatRenderer.Render(Spec, overrides);");
        sb.AppendLine("}");
        return new EmittedFile($"{templateName}.prompt.cs", sb.ToString());
    }
}
