// output-parser-generator — for each `template.output` declaration, emits a
// `<TemplateName>.output.cs` file declaring a static `<TemplateName>Parser`
// class with the .NET BCL `Parse`/`TryParse` dual API (ADR-0010). `Parse`
// throws on bad input; `TryParse` returns a bool and an out-error.
//
// The emitted parser RETURNS the payload-VO record already emitted by
// PayloadCodegen (same metadata model). It does NOT redeclare the payload
// shape; this generator emits parser glue only.
//
// Ported from typescript/packages/codegen-ts/src/generators/output-parser-file.ts
// (renderer in typescript/packages/codegen-ts/src/templates/output-parser.ts).
// TS uses Zod; C# uses System.Text.Json + the `required` keyword for
// presence enforcement (.NET 7+). No DataAnnotations / Validator pass —
// `required`-keyword construction + STJ's strict deserialization cover
// presence + type in BCL-native form.

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Shared.BaseTypes;
using static MetaObjects.Template.TemplateConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>
/// Emits one parser file per <c>template.output</c> node, with a static class
/// exposing <c>Parse(string)</c> + <c>TryParse(string, out T?, out string?)</c>.
/// </summary>
public sealed class OutputParserGenerator : IGenerator
{
    public string Name => "output-parser-generator";

    public IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        var outputs = ctx.Root.OwnChildren()
            .Where(c => c.Type == TYPE_TEMPLATE && c.SubType == TEMPLATE_SUBTYPE_OUTPUT)
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToList();

        var files = new List<EmittedFile>();
        foreach (var tmpl in outputs)
        {
            if (tmpl.OwnAttr(TEMPLATE_ATTR_PAYLOAD_REF) is not string payloadRef)
            {
                // Loader passes treat missing @payloadRef as a load error; defensively skip.
                ctx.Warn($"{Name}: template.output \"{tmpl.Name}\" missing @payloadRef — skipped.");
                continue;
            }
            files.Add(EmitParser(tmpl.Name, payloadRef, ctx));
        }
        return files;
    }

    private static EmittedFile EmitParser(string templateName, string payloadRef, GenContext ctx)
    {
        var parserClass = $"{templateName}Parser";
        var payloadType = payloadRef;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects output-parser-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Parser for LLM responses matching the <c>{templateName}</c> template.output.</summary>");
        sb.AppendLine($"public static class {parserClass}");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly JsonSerializerOptions Options = new()");
        sb.AppendLine("    {");
        // Case-sensitive (default) — the payload-VO property names are emitted as
        // the exact metadata field names (typically camelCase), which matches the
        // JSON the LLM is expected to produce.
        sb.AppendLine("        PropertyNameCaseInsensitive = false,");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Parse an LLM response into a typed <see cref=\"{payloadType}\"/>.</summary>");
        sb.AppendLine($"    /// <param name=\"text\">The raw response text — expected to be JSON.</param>");
        sb.AppendLine("    /// <returns>The deserialized, validated payload.</returns>");
        sb.AppendLine("    /// <exception cref=\"JsonException\">JSON is malformed, missing a <c>required</c> property, or has a type mismatch.</exception>");
        sb.AppendLine($"    public static {payloadType} Parse(string text) =>");
        sb.AppendLine($"        JsonSerializer.Deserialize<{payloadType}>(text, Options)");
        sb.AppendLine($"            ?? throw new JsonException(\"deserialized to null\");");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Parse with explicit error handling — does not throw on validation failure.</summary>");
        sb.AppendLine("    /// <param name=\"text\">The raw response text — expected to be JSON.</param>");
        sb.AppendLine("    /// <param name=\"value\">On success, the deserialized payload; otherwise null.</param>");
        sb.AppendLine("    /// <param name=\"error\">On failure, a human-readable error message; otherwise null.</param>");
        sb.AppendLine("    /// <returns><c>true</c> on success; <c>false</c> on validation failure.</returns>");
        sb.AppendLine($"    public static bool TryParse(string text, [NotNullWhen(true)] out {payloadType}? value, [NotNullWhen(false)] out string? error)");
        sb.AppendLine("    {");
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            value = Parse(text);");
        sb.AppendLine("            error = null;");
        sb.AppendLine("            return true;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (JsonException ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            value = null;");
        sb.AppendLine("            error = ex.Message;");
        sb.AppendLine("            return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return new EmittedFile($"{templateName}.output.cs", sb.ToString());
    }
}
