// output-prompt-generator — for each responding `template.prompt` (one carrying `@responseRef`),
// emits a `<PromptName>.responseFormat.cs` file declaring a static `<PromptName>ResponseFormat`
// class with a `RenderFormat()` / `RenderFormat(PromptOverrides)` pair backed by the render
// engine's OutputFormatRenderer (FR-010 artifact 1 — the "produce your answer like this"
// fragment).
//
// ADR-0052: gated on `@responseRef` presence, like every other inbound generator. It previously
// keyed on `template.output` + a json/xml `@format` gate, which is how a fragment that instructs
// an LLM came to be emitted from the subtype defined as "every rendered artifact other than an
// LLM prompt".
//
// The baked OutputFormatSpec's rootName is the RESPONSE VO's class name, so the fragment and the
// extract() codegen agree on the root element/object name. Mirrors the Java
// SpringOutputPromptGenerator. Skips: template.output, and a missing/unresolved `@responseRef`.

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Shared.BaseTypes;
using static MetaObjects.Template.TemplateConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>
/// Emits one <c>&lt;Prompt&gt;ResponseFormat</c> class per responding <c>template.prompt</c>,
/// exposing <c>RenderFormat()</c> + <c>RenderFormat(PromptOverrides)</c>.
/// </summary>
public class OutputPromptGenerator : IGenerator
{
    public virtual string Name => "output-prompt-generator";

    public virtual IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        var files = new List<EmittedFile>();
        // ADR-0052: the direction rule lives in FindInbound, never re-derived here.
        foreach (var tmpl in FindInbound.InboundTemplates(ctx.Root))
        {
            // @responseRef must resolve to a value-object (same contract as the parser).
            if (FindInbound.ResponseShape(ctx.Root, tmpl) is not { } shape) continue;
            files.Add(EmitPrompt(tmpl, shape.Vo, shape.Ref, ctx));
        }
        return files;
    }

    /// <summary>
    /// True iff this generator emits a response-format fragment for <paramref name="tmpl"/>: a
    /// <c>template.prompt</c> whose <c>@responseRef</c> resolves to a root-level <c>object</c>.
    /// Single source of truth shared by the generator loop AND the api-docs builder (so docs
    /// never claim a suppressed symbol).
    /// </summary>
    public static bool AppliesTo(MetaData tmpl, MetaRoot root) => FindInbound.IsInbound(tmpl, root);

    protected virtual EmittedFile EmitPrompt(MetaData tmpl, MetaData vo, string payloadRef, GenContext ctx)
    {
        var templateName = tmpl.Name;
        var promptClass = CSharpNaming.ResponseFormatClassName(templateName);
        // rootName == response VO class name so the fragment and extract() agree.
        var specLiteral = OutputFormatSpecEmitter.SpecLiteral(vo, tmpl, payloadRef);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects output-prompt-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using MetaObjects.Render.Prompt;");
        sb.AppendLine("using MetaObjects.Render.Extract;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Response-format prompt fragment for the <c>{templateName}</c> template.prompt.</summary>");
        sb.AppendLine($"public static class {promptClass}");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly OutputFormatSpec Spec = {specLiteral};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The response-format instruction fragment (\"produce your answer like this\").</summary>");
        sb.AppendLine("    public static string RenderFormat() => OutputFormatRenderer.Render(Spec, PromptOverrides.None());");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The fragment with render-time overrides (style / per-field example / instruction).</summary>");
        sb.AppendLine("    public static string RenderFormat(PromptOverrides overrides) => OutputFormatRenderer.Render(Spec, overrides);");
        sb.AppendLine("}");
        // ADR-0052 D4: the artifact name follows the DIRECTION axis. A file named
        // `<Prompt>.prompt.cs` generated from a prompt reproduces the confusion being removed.
        return new EmittedFile($"{templateName}.responseFormat.cs", sb.ToString());
    }
}
