// payload-generator — for each `template.output` whose @payloadRef resolves to an
// object.value, emits a `<Payload>.payload.cs` file declaring the strict typed payload
// `record <PayloadRef>` (+ any nested element records) the prompt/parser/extractor bind to.
//
// This wraps the EXISTING PayloadCodegen.GeneratePayloadRecords logic (the single source
// of truth for the payload record shape) and wires it as a registered generator so the
// `record <Name>Payload` the output-parser/extractor REFERENCE is actually EMITTED by
// `dotnet meta gen`. Before this, PayloadCodegen was reachable only from VerifyCommand —
// the strict record was documented + referenced but never generated.
//
// The records are emitted under `namespace ctx.Config.Namespace` (the same namespace the
// output-parser / output-prompt / extractor generators emit under), so the references
// resolve in the consumer assembly.
//
// AppliesTo is the SINGLE SOURCE OF TRUTH the api-docs builder shares for the PAYLOAD
// symbol — a `template.output` whose `@payloadRef` resolves to a root-level
// `object.value` (the same gate RenderHelperGenerator.AppliesTo uses; the payload record
// name == the VO name).

using System.Text;
using MetaObjects.Meta;
using static MetaObjects.Shared.BaseTypes;
using static MetaObjects.Core.Object.ObjectConstants;
using static MetaObjects.Template.TemplateConstants;

namespace MetaObjects.Codegen.Generators;

/// <summary>
/// Emits one <c>&lt;Payload&gt;.payload.cs</c> per <c>template.output</c> whose
/// <c>@payloadRef</c> resolves to an <c>object.value</c>: the strict typed payload
/// <c>record &lt;PayloadRef&gt;</c> (+ nested element records) the prompt / parser /
/// extractor bind to. Wraps <see cref="PayloadCodegen"/> (the record-shape SSOT).
/// </summary>
public class PayloadGenerator : IGenerator
{
    public virtual string Name => "payload-generator";

    public virtual IEnumerable<EmittedFile> Generate(GenContext ctx)
    {
        var outputs = ctx.Root.OwnChildren()
            .Where(c => c.Type == TYPE_TEMPLATE && c.SubType == TEMPLATE_SUBTYPE_OUTPUT)
            .OrderBy(t => t.Name, StringComparer.Ordinal)
            .ToList();

        var files = new List<EmittedFile>();
        foreach (var tmpl in outputs)
        {
            if (!AppliesTo(tmpl, ctx.Root))
            {
                if (tmpl.OwnAttr(TEMPLATE_ATTR_PAYLOAD_REF) is null)
                    ctx.Warn($"{Name}: template.output \"{tmpl.Name}\" missing @payloadRef — skipped.");
                continue;
            }
            var payloadRef = (string)tmpl.OwnAttr(TEMPLATE_ATTR_PAYLOAD_REF)!;
            files.Add(EmitPayload(payloadRef, ctx));
        }
        return files;
    }

    /// <summary>
    /// True iff this generator emits a strict payload record for <paramref name="tmpl"/>: a
    /// <c>template.output</c> whose <c>@payloadRef</c> resolves to a root-level
    /// <c>object.value</c>. Single source of truth shared by the generator loop AND the
    /// api-docs builder (so docs never claim a payload record that is not emitted). Reuses
    /// the SAME resolver <see cref="RenderHelperGenerator.AppliesTo"/> uses (no mirror).
    /// </summary>
    public static bool AppliesTo(MetaData tmpl, MetaRoot root)
    {
        if (tmpl.Type != TYPE_TEMPLATE || tmpl.SubType != TEMPLATE_SUBTYPE_OUTPUT) return false;
        if (tmpl.OwnAttr(TEMPLATE_ATTR_PAYLOAD_REF) is not string payloadRef) return false;
        return RenderHelperGenerator.ResolveValueObject(root, payloadRef) is not null;
    }

    /// <summary>The root-level <c>object.value</c> a <c>@payloadRef</c> names, or null.</summary>
    internal static MetaData? ResolvePayloadVo(MetaRoot root, string payloadRef) =>
        RenderHelperGenerator.ResolveValueObject(root, payloadRef);

    protected virtual EmittedFile EmitPayload(string payloadRef, GenContext ctx)
    {
        var records = PayloadCodegen.GeneratePayloadRecords(ctx.Root, payloadRef);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects payload-generator. Do not edit by hand.");
        sb.AppendLine("// The strict typed payload record(s) the prompt / parser / extractor bind to.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.Append(records);
        return new EmittedFile($"{payloadRef}.payload.cs", sb.ToString());
    }
}
