// routes-generator — emits ASP.NET Core Minimal API CRUD endpoints per entity.
//
// One static class per entity with a Map<Entity>Routes(this IEndpointRouteBuilder,
// string prefix) extension. Single-PK entities get full CRUD (list/get/post/put/
// delete) over the generated AppDbContext; composite-/no-PK entities get the
// collection GET only (item addressing needs a single key) with a warning.

using System.Text;
using MetaObjects.Meta;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates Minimal API CRUD route registration per <c>object.entity</c>.</summary>
public sealed class RoutesGenerator : PerEntityGenerator
{
    public override string Name => "routes-generator";

    protected override bool Filter(MetaObject entity) => entity.IsEntity() || entity.DbView is not null;

    protected override EmittedFile GenerateOne(MetaObject entity, GenContext ctx)
    {
        var cls = CSharpNaming.Pascal(entity.Name);
        var dbSet = CSharpNaming.Pluralize(cls);
        var route = CSharpNaming.Pluralize(entity.Name).ToLowerInvariant();

        var pkFields = entity.PrimaryIdentity()?.Fields ?? [];
        string? pkType = null;
        if (pkFields.Count == 1)
        {
            var pkField = entity.Fields().FirstOrDefault(f => f.Name == pkFields[0]);
            if (pkField is not null) pkType = CSharpNaming.ScalarFor(pkField.SubType);
        }
        bool isProjection = entity.IsReadOnlyProjection();
        bool hasItem = pkType is not null;           // GET by id (readable by key)
        bool writable = hasItem && !isProjection;    // mutations only on writable sources
        if (!hasItem)
            ctx.Warn($"{Name}: \"{entity.Name}\" has no single-column primary key — emitting collection GET only.");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects routes-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {cls}Routes");
        sb.AppendLine("{");
        sb.AppendLine($"    public static IEndpointRouteBuilder Map{cls}Routes(this IEndpointRouteBuilder app, string prefix = \"/api\")");
        sb.AppendLine("    {");

        // List
        sb.AppendLine("        app.MapGet(prefix + \"/" + route + "\", async (AppDbContext db) =>");
        sb.AppendLine("            await db." + dbSet + ".ToListAsync());");

        if (hasItem)
        {
            sb.AppendLine();
            sb.AppendLine("        app.MapGet(prefix + \"/" + route + "/{id}\", async (" + pkType + " id, AppDbContext db) =>");
            sb.AppendLine("            await db." + dbSet + ".FindAsync(id) is { } found ? Results.Ok(found) : Results.NotFound());");
        }

        if (writable)
        {
            sb.AppendLine();
            sb.AppendLine("        app.MapPost(prefix + \"/" + route + "\", async (" + cls + " input, AppDbContext db) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            db." + dbSet + ".Add(input);");
            sb.AppendLine("            await db.SaveChangesAsync();");
            sb.AppendLine("            return Results.Created(prefix + \"/" + route + "\", input);");
            sb.AppendLine("        });");
            sb.AppendLine();
            sb.AppendLine("        app.MapPut(prefix + \"/" + route + "/{id}\", async (" + pkType + " id, " + cls + " input, AppDbContext db) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var existing = await db." + dbSet + ".FindAsync(id);");
            sb.AppendLine("            if (existing is null) return Results.NotFound();");
            sb.AppendLine("            db.Entry(existing).CurrentValues.SetValues(input);");
            sb.AppendLine("            await db.SaveChangesAsync();");
            sb.AppendLine("            return Results.NoContent();");
            sb.AppendLine("        });");
            sb.AppendLine();
            sb.AppendLine("        app.MapDelete(prefix + \"/" + route + "/{id}\", async (" + pkType + " id, AppDbContext db) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var existing = await db." + dbSet + ".FindAsync(id);");
            sb.AppendLine("            if (existing is null) return Results.NotFound();");
            sb.AppendLine("            db." + dbSet + ".Remove(existing);");
            sb.AppendLine("            await db.SaveChangesAsync();");
            sb.AppendLine("            return Results.NoContent();");
            sb.AppendLine("        });");
        }

        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return new EmittedFile($"{cls}Routes.g.cs", sb.ToString());
    }
}
