// routes-generator — emits ASP.NET Core Minimal API CRUD endpoints per entity.
//
// One static class per entity with a Map<Entity>Routes(this IEndpointRouteBuilder,
// string prefix) extension. Single-PK entities get full CRUD (list/get/post/
// patch/put/delete) over the generated AppDbContext; composite-/no-PK entities
// get the collection GET only (item addressing needs a single key) with a
// warning.
//
// Cross-port API contract conformed by the generated handlers
// (see docs/features/api-contract.md):
//   - GET list honours ?limit=N&offset=N pagination.
//   - GET list honours ?sort=<field>:asc|desc against a static SortAllowlist
//     derived from the entity's scalar fields (case-insensitive lookup).
//     Unknown field → 400 { "error": "validation", "message": ... }.
//   - GET list honours ?withCount=1 → switches the envelope from a bare row
//     array to { rows, total }. The grid hook always sends withCount=1.
//   - Update accepts BOTH PATCH and PUT (TS reference exposes both; we match).
//   - 404 responses carry a JSON envelope: { "error": "not_found" }.
//
// Filter operators (eq/ne/gt/gte/lt/lte/in/like/isNull) ship via FR-009 — the
// generated list handler calls FilterParser.Parse against the per-entity
// <Entity>FilterAllowlist (emitted by FilterAllowlistGenerator), then
// dispatches the resulting predicates onto the IQueryable<T> via
// EfCoreFilterDispatch.ApplyFilter. Both helpers live in
// MetaObjects.Codegen.Runtime — consumers reference the codegen assembly
// at runtime in their ASP.NET host.

using System.Text;
using MetaObjects.Meta;

namespace MetaObjects.Codegen.Generators;

/// <summary>Generates Minimal API CRUD route registration per <c>object.entity</c>.</summary>
public sealed class RoutesGenerator : PerEntityGenerator
{
    public override string Name => "routes-generator";

    protected override bool Filter(MetaObject entity) =>
        (entity.IsEntity() || entity.DbView is not null) && InstanceArtifacts.EmitsInstanceArtifacts(entity);

    // FR-017 TPH: a concrete subtype is served via its base's per-subtype routes — it
    // emits NO standalone routes file (the base mounts polymorphic + per-subtype CRUD).
    // The subtype skip needs the root, which Filter doesn't receive, so it is applied
    // here where the GenContext is in scope.
    public override IEnumerable<EmittedFile> Generate(GenContext ctx) =>
        ctx.Entities
            .Where(Filter)
            .Where(e => !TphPlanBuilder.IsTphSubtype(e, ctx.Root))
            .Select(e => GenerateOne(e, ctx));

    protected override EmittedFile GenerateOne(MetaObject entity, GenContext ctx)
    {
        if (TphPlanBuilder.For(entity, ctx.Root) is { } tph)
            return GenerateTphRoutes(entity, tph, ctx);
        return GenerateStandardRoutes(entity, ctx);
    }

    private EmittedFile GenerateStandardRoutes(MetaObject entity, GenContext ctx)
    {
        var cls = CSharpNaming.Pascal(entity.Name);
        var dbSet = CSharpNaming.Pluralize(cls);
        var route = CSharpNaming.Pluralize(entity.Name).ToLowerInvariant();

        var pkFields = entity.PrimaryIdentity()?.Fields ?? [];
        string? pkType = null;
        string? pkProp = null;
        if (pkFields.Count == 1)
        {
            var pkField = entity.Fields().FirstOrDefault(f => f.Name == pkFields[0]);
            if (pkField is not null)
            {
                pkType = CSharpNaming.ScalarFor(pkField.SubType);
                pkProp = CSharpNaming.Pascal(pkField.Name);
            }
        }
        bool isProjection = entity.IsReadOnlyProjection();
        bool hasItem = pkType is not null;           // GET by id (readable by key)
        bool writable = hasItem && !isProjection;    // mutations only on writable sources
        if (!hasItem)
            ctx.Warn($"{Name}: \"{entity.Name}\" has no single-column primary key — emitting collection GET only.");

        // Sort allowlist: every scalar field on the entity is sortable. The
        // generated handler does case-insensitive lookup so the wire grammar
        // (?sort=createdAt:desc) matches the C# property name (CreatedAt).
        var sortFields = entity.Fields()
            .Where(f => CSharpNaming.ScalarFor(f.SubType) is not null && !f.IsArray)
            .Select(f => CSharpNaming.Pascal(f.Name))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects routes-generator. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using MetaObjects.Codegen.Runtime;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {cls}Routes");
        sb.AppendLine("{");
        // Static sort allowlist (case-insensitive) so the qs ?sort=field:dir
        // is gated against the entity's scalar fields.
        sb.Append("    private static readonly System.Collections.Generic.HashSet<string> SortAllowlist =");
        sb.AppendLine(" new(System.StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");
        foreach (var name in sortFields) sb.AppendLine($"        \"{name}\",");
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine($"    public static IEndpointRouteBuilder Map{cls}Routes(this IEndpointRouteBuilder app, string prefix = \"/api\")");
        sb.AppendLine("    {");

        // List — honours ?limit / ?offset / ?sort / ?withCount per api-contract.md.
        sb.AppendLine("        app.MapGet(prefix + \"/" + route + "\", async (HttpContext http, AppDbContext db) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var qs = http.Request.Query;");
        sb.AppendLine($"            IQueryable<{cls}> q = db." + dbSet + ".AsNoTracking();");
        sb.AppendLine();
        sb.AppendLine("            // Filter: ?filter[<field>][<op>]=<value> against the per-entity allowlist.");
        sb.AppendLine($"            var filter = FilterParser.Parse(qs, {cls}FilterAllowlist.Fields, {cls}FilterAllowlist.OpsByField);");
        sb.AppendLine("            if (filter.ErrorEnvelope is not null)");
        sb.AppendLine("                return Results.BadRequest(new { error = filter.ErrorEnvelope });");
        sb.AppendLine($"            q = EfCoreFilterDispatch.ApplyFilter(q, filter.Predicates);");
        sb.AppendLine();
        sb.AppendLine("            // Sort: ?sort=field:asc|desc against the static allowlist.");
        sb.AppendLine("            if (qs.TryGetValue(\"sort\", out var sortRaw) && !string.IsNullOrWhiteSpace(sortRaw))");
        sb.AppendLine("            {");
        sb.AppendLine("                var parts = sortRaw.ToString().Split(':', 2);");
        sb.AppendLine("                var field = parts[0];");
        sb.AppendLine("                var desc = parts.Length > 1 && string.Equals(parts[1], \"desc\", System.StringComparison.OrdinalIgnoreCase);");
        sb.AppendLine("                if (!SortAllowlist.TryGetValue(field, out var resolved))");
        sb.AppendLine("                    return Results.BadRequest(new { error = \"invalid_sort\" });");
        sb.AppendLine($"                q = ApplySort{cls}(q, resolved, desc);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            // Pagination: ?offset=N first (skip), then ?limit=N (take).");
        sb.AppendLine("            if (qs.TryGetValue(\"offset\", out var offsetRaw) && int.TryParse(offsetRaw, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var offset) && offset > 0)");
        sb.AppendLine("                q = q.Skip(offset);");
        sb.AppendLine("            if (qs.TryGetValue(\"limit\", out var limitRaw) && int.TryParse(limitRaw, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var limit) && limit > 0)");
        sb.AppendLine("                q = q.Take(limit);");
        sb.AppendLine();
        sb.AppendLine("            var rows = await q.ToListAsync();");
        sb.AppendLine();
        sb.AppendLine("            // withCount=1 → { rows, total } envelope; otherwise bare row array.");
        sb.AppendLine("            var withCount = qs.TryGetValue(\"withCount\", out var wc) && (wc == \"1\" || string.Equals(wc, \"true\", System.StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("            if (!withCount) return Results.Ok(rows);");
        sb.AppendLine($"            var totalQ = EfCoreFilterDispatch.ApplyFilter(db.{dbSet}.AsNoTracking(), filter.Predicates);");
        sb.AppendLine("            var total = await totalQ.CountAsync();");
        sb.AppendLine("            return Results.Ok(new { rows, total });");
        sb.AppendLine("        });");

        if (hasItem)
        {
            sb.AppendLine();
            sb.AppendLine("        app.MapGet(prefix + \"/" + route + "/{id}\", async (" + pkType + " id, AppDbContext db) =>");
            sb.AppendLine("            await db." + dbSet + ".FindAsync(id) is { } found");
            sb.AppendLine("                ? Results.Ok(found)");
            sb.AppendLine("                : Results.NotFound(new { error = \"not_found\" }));");
        }

        if (writable)
        {
            sb.AppendLine();
            sb.AppendLine("        app.MapPost(prefix + \"/" + route + "\", async (" + cls + " input, AppDbContext db) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            db." + dbSet + ".Add(input);");
            sb.AppendLine("            await db.SaveChangesAsync();");
            sb.AppendLine("            return Results.Created(prefix + \"/" + route + "\", input);");
            sb.AppendLine("        });");

            // PATCH + PUT share the same handler — TS reference exposes both verbs,
            // and both return the updated row (HTTP 200), matching the cross-port
            // api-contract. The route id is authoritative for the key: stamp it onto
            // the bound input BEFORE SetValues so EF sees the primary key unchanged
            // (a default/zero key on the input would otherwise trip "the property is
            // part of a key and so cannot be modified").
            sb.AppendLine();
            sb.AppendLine("        async System.Threading.Tasks.Task<IResult> Update" + cls + "(" + pkType + " id, " + cls + " input, AppDbContext db)");
            sb.AppendLine("        {");
            sb.AppendLine("            var existing = await db." + dbSet + ".FindAsync(id);");
            sb.AppendLine("            if (existing is null) return Results.NotFound(new { error = \"not_found\" });");
            sb.AppendLine("            input." + pkProp + " = id;");
            sb.AppendLine("            db.Entry(existing).CurrentValues.SetValues(input);");
            sb.AppendLine("            await db.SaveChangesAsync();");
            sb.AppendLine("            return Results.Ok(existing);");
            sb.AppendLine("        }");
            sb.AppendLine("        app.MapPatch(prefix + \"/" + route + "/{id}\", Update" + cls + ");");
            sb.AppendLine("        app.MapPut(prefix + \"/" + route + "/{id}\", Update" + cls + ");");
            sb.AppendLine();
            sb.AppendLine("        app.MapDelete(prefix + \"/" + route + "/{id}\", async (" + pkType + " id, AppDbContext db) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            var existing = await db." + dbSet + ".FindAsync(id);");
            sb.AppendLine("            if (existing is null) return Results.NotFound(new { error = \"not_found\" });");
            sb.AppendLine("            db." + dbSet + ".Remove(existing);");
            sb.AppendLine("            await db.SaveChangesAsync();");
            sb.AppendLine("            return Results.NoContent();");
            sb.AppendLine("        });");
        }

        // FR-018 M:N traversal — GET /<source-plural>/{id}/<relationName> through the
        // junction. Only on a single-PK source (the route addresses the source by id).
        // Cross-port contract: source URL segment = pluralized ENTITY name, relation
        // segment = relationship name.
        if (hasItem)
            foreach (var nav in M2MNavigationBuilder.For(entity, ctx.Root))
                AppendM2mRoute(sb, nav, route, pkType!);

        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine();
        // Allowlisted property name → IOrderedQueryable dispatch via EF.Property.
        // Reflection-free at runtime; EF Core translates EF.Property(x, "<Name>")
        // into the column reference at SQL generation.
        sb.AppendLine($"    private static IOrderedQueryable<{cls}> ApplySort{cls}(IQueryable<{cls}> q, string field, bool desc)");
        sb.AppendLine("    {");
        sb.AppendLine("        return field switch");
        sb.AppendLine("        {");
        foreach (var name in sortFields)
        {
            sb.AppendLine($"            \"{name}\" => desc ? q.OrderByDescending(x => EF.Property<object>(x!, \"{name}\")) : q.OrderBy(x => EF.Property<object>(x!, \"{name}\")),");
        }
        sb.AppendLine("            _ => (IOrderedQueryable<" + cls + ">)q.OrderBy(x => 0),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return new EmittedFile($"{cls}Routes.g.cs", sb.ToString());
    }

    // FR-017 TPH routes for a discriminator base. Mirrors the TS routes-file TPH branch:
    //   - polymorphic list/get at the base path (GET /auths, /auths/{id}); NO base POST.
    //   - a full per-subtype CRUD set at /auths/<discriminatorValue lowercased>, scoped
    //     to that subtype via DbSet.OfType<Sub>():
    //       * create constructs `new Sub` (discriminator injected by EF via the CLR type;
    //         the POST body OMITS the discriminator),
    //       * get/update/delete are scoped — a cross-subtype id is invisible (404),
    //       * update is a partial merge that NEVER touches the discriminator or PK.
    //
    // The base path (auths) is the pluralized base ENTITY name lowercased. ASP.NET routes
    // the static /auths/<segment> ahead of the parametric /auths/{id}, so they coexist.
    private EmittedFile GenerateTphRoutes(MetaObject baseEntity, TphPlan tph, GenContext ctx)
    {
        var baseCls = CSharpNaming.Pascal(baseEntity.Name);
        var dbSet = CSharpNaming.Pluralize(baseCls);
        var baseRoute = CSharpNaming.Pluralize(baseEntity.Name).ToLowerInvariant();

        var pkFields = baseEntity.PrimaryIdentity()?.Fields ?? [];
        if (pkFields.Count != 1)
        {
            ctx.Warn($"{Name}: TPH base \"{baseEntity.Name}\" has no single-column primary key — " +
                     "emitting polymorphic collection GET only.");
        }
        var pkField = pkFields.Count == 1 ? baseEntity.Fields().FirstOrDefault(f => f.Name == pkFields[0]) : null;
        var pkType = pkField is not null ? CSharpNaming.ScalarFor(pkField.SubType) : null;
        var pkProp = pkField is not null ? CSharpNaming.Pascal(pkField.Name) : null;
        bool hasItem = pkType is not null;

        var discProp = CSharpNaming.Pascal(tph.DiscriminatorField);

        // Sortable base scalar fields (the polymorphic list sorts on base columns).
        var sortFields = baseEntity.Fields()
            .Where(f => CSharpNaming.ScalarFor(f.SubType) is not null && !f.IsArray)
            .Select(f => CSharpNaming.Pascal(f.Name))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by MetaObjects routes-generator (TPH). Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using MetaObjects.Codegen.Runtime;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ctx.Config.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public static class {baseCls}Routes");
        sb.AppendLine("{");

        // Polymorphic sort allowlist over the base scalar columns.
        sb.Append("    private static readonly System.Collections.Generic.HashSet<string> SortAllowlist =");
        sb.AppendLine(" new(System.StringComparer.OrdinalIgnoreCase)");
        sb.AppendLine("    {");
        foreach (var name in sortFields) sb.AppendLine($"        \"{name}\",");
        sb.AppendLine("    };");
        sb.AppendLine();

        // Per-subtype sort allowlists (case-insensitive) over each subtype's EFFECTIVE
        // scalar fields (inherited base + own). The per-subtype list resolves the qs
        // ?sort=<field> through this to the CLR property name before EF.Property — a raw
        // lowercase field (e.g. "id") would otherwise fail EF translation (no "id"
        // property; it's "Id") and 500.
        foreach (var st in tph.Subtypes)
        {
            var subClsName = CSharpNaming.Pascal(st.Entity.Name);
            var subSortFields = st.Entity.Fields()
                .Where(f => CSharpNaming.ScalarFor(f.SubType) is not null && !f.IsArray)
                .Select(f => CSharpNaming.Pascal(f.Name))
                .ToList();
            sb.Append($"    private static readonly System.Collections.Generic.HashSet<string> {subClsName}SortAllowlist =");
            sb.AppendLine(" new(System.StringComparer.OrdinalIgnoreCase)");
            sb.AppendLine("    {");
            foreach (var name in subSortFields) sb.AppendLine($"        \"{name}\",");
            sb.AppendLine("    };");
            sb.AppendLine();
        }

        sb.AppendLine($"    public static IEndpointRouteBuilder Map{baseCls}Routes(this IEndpointRouteBuilder app, string prefix = \"/api\")");
        sb.AppendLine("    {");

        // --- Polymorphic list: GET /<base> (union of all subtypes; each row carries its discriminator) ---
        sb.AppendLine("        app.MapGet(prefix + \"/" + baseRoute + "\", async (HttpContext http, AppDbContext db) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var qs = http.Request.Query;");
        sb.AppendLine($"            IQueryable<{baseCls}> q = db.{dbSet}.AsNoTracking();");
        sb.AppendLine($"            var filter = FilterParser.Parse(qs, {baseCls}FilterAllowlist.Fields, {baseCls}FilterAllowlist.OpsByField);");
        sb.AppendLine("            if (filter.ErrorEnvelope is not null) return Results.BadRequest(new { error = filter.ErrorEnvelope });");
        sb.AppendLine("            q = EfCoreFilterDispatch.ApplyFilter(q, filter.Predicates);");
        sb.AppendLine("            if (qs.TryGetValue(\"sort\", out var sortRaw) && !string.IsNullOrWhiteSpace(sortRaw))");
        sb.AppendLine("            {");
        sb.AppendLine("                var parts = sortRaw.ToString().Split(':', 2);");
        sb.AppendLine("                var desc = parts.Length > 1 && string.Equals(parts[1], \"desc\", System.StringComparison.OrdinalIgnoreCase);");
        sb.AppendLine("                if (!SortAllowlist.TryGetValue(parts[0], out var resolved)) return Results.BadRequest(new { error = \"invalid_sort\" });");
        sb.AppendLine("                q = ApplySort(q, resolved, desc);");
        sb.AppendLine("            }");
        sb.AppendLine("            if (qs.TryGetValue(\"offset\", out var offRaw) && int.TryParse(offRaw, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var off) && off > 0) q = q.Skip(off);");
        sb.AppendLine("            if (qs.TryGetValue(\"limit\", out var limRaw) && int.TryParse(limRaw, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var lim) && lim > 0) q = q.Take(lim);");
        sb.AppendLine("            var rows = await q.ToListAsync();");
        sb.AppendLine("            var withCount = qs.TryGetValue(\"withCount\", out var wc) && (wc == \"1\" || string.Equals(wc, \"true\", System.StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("            if (!withCount) return Results.Ok(rows);");
        sb.AppendLine($"            var total = await EfCoreFilterDispatch.ApplyFilter(db.{dbSet}.AsNoTracking(), filter.Predicates).CountAsync();");
        sb.AppendLine("            return Results.Ok(new { rows, total });");
        sb.AppendLine("        });");

        if (hasItem)
        {
            // --- Polymorphic get: GET /<base>/{id} (one row of whatever subtype) ---
            sb.AppendLine();
            sb.AppendLine("        app.MapGet(prefix + \"/" + baseRoute + "/{id}\", async (" + pkType + " id, AppDbContext db) =>");
            sb.AppendLine($"            await db.{dbSet}.AsNoTracking().FirstOrDefaultAsync(x => x.{pkProp} == id) is {{ }} found");
            sb.AppendLine("                ? Results.Ok(found)");
            sb.AppendLine("                : Results.NotFound(new { error = \"not_found\" }));");

            // --- Per-subtype CRUD sets ---
            foreach (var st in tph.Subtypes)
                AppendTphSubtypeRoutes(sb, st, baseRoute, baseCls, dbSet, pkType!, pkProp!, discProp);
        }

        sb.AppendLine();
        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Polymorphic sort dispatch over base scalar columns (reflection-free via EF.Property).
        sb.AppendLine($"    private static IOrderedQueryable<{baseCls}> ApplySort(IQueryable<{baseCls}> q, string field, bool desc)");
        sb.AppendLine("    {");
        sb.AppendLine("        return field switch");
        sb.AppendLine("        {");
        foreach (var name in sortFields)
            sb.AppendLine($"            \"{name}\" => desc ? q.OrderByDescending(x => EF.Property<object>(x!, \"{name}\")) : q.OrderBy(x => EF.Property<object>(x!, \"{name}\")),");
        sb.AppendLine("            _ => (IOrderedQueryable<" + baseCls + ">)q.OrderBy(x => 0),");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return new EmittedFile($"{baseCls}Routes.g.cs", sb.ToString());
    }

    // Emit the per-subtype CRUD route set under /<base>/<segment>. Scoped to the subtype
    // via db.<DbSet>.OfType<Sub>(); cross-subtype ids are invisible (404). Create binds the
    // subtype CLR type (discriminator injected by EF on Add); update is a partial merge
    // that never touches the PK or the discriminator.
    private static void AppendTphSubtypeRoutes(
        StringBuilder sb, TphSubtypePlan st, string baseRoute, string baseCls, string dbSet,
        string pkType, string pkProp, string discProp)
    {
        var subCls = CSharpNaming.Pascal(st.Entity.Name);
        var seg = st.RouteSegment;
        var subRoute = baseRoute + "/" + seg;

        // Per-subtype list: GET /<base>/<seg>
        sb.AppendLine();
        sb.AppendLine("        app.MapGet(prefix + \"/" + subRoute + "\", async (HttpContext http, AppDbContext db) =>");
        sb.AppendLine("        {");
        sb.AppendLine("            var qs = http.Request.Query;");
        sb.AppendLine($"            IQueryable<{subCls}> q = db.{dbSet}.OfType<{subCls}>().AsNoTracking();");
        sb.AppendLine($"            var filter = FilterParser.Parse(qs, {subCls}FilterAllowlist.Fields, {subCls}FilterAllowlist.OpsByField);");
        sb.AppendLine("            if (filter.ErrorEnvelope is not null) return Results.BadRequest(new { error = filter.ErrorEnvelope });");
        sb.AppendLine("            q = EfCoreFilterDispatch.ApplyFilter(q, filter.Predicates);");
        sb.AppendLine("            if (qs.TryGetValue(\"sort\", out var sortRaw) && !string.IsNullOrWhiteSpace(sortRaw))");
        sb.AppendLine("            {");
        sb.AppendLine("                var parts = sortRaw.ToString().Split(':', 2);");
        sb.AppendLine("                var desc = parts.Length > 1 && string.Equals(parts[1], \"desc\", System.StringComparison.OrdinalIgnoreCase);");
        sb.AppendLine($"                if (!{subCls}SortAllowlist.TryGetValue(parts[0], out var resolved)) return Results.BadRequest(new {{ error = \"invalid_sort\" }});");
        sb.AppendLine("                q = desc ? q.OrderByDescending(x => EF.Property<object>(x!, resolved)) : q.OrderBy(x => EF.Property<object>(x!, resolved));");
        sb.AppendLine("            }");
        sb.AppendLine("            if (qs.TryGetValue(\"offset\", out var offRaw) && int.TryParse(offRaw, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var off) && off > 0) q = q.Skip(off);");
        sb.AppendLine("            if (qs.TryGetValue(\"limit\", out var limRaw) && int.TryParse(limRaw, System.Globalization.NumberStyles.Integer, System.Globalization.CultureInfo.InvariantCulture, out var lim) && lim > 0) q = q.Take(lim);");
        sb.AppendLine("            var rows = await q.ToListAsync();");
        sb.AppendLine("            var withCount = qs.TryGetValue(\"withCount\", out var wc) && (wc == \"1\" || string.Equals(wc, \"true\", System.StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("            if (!withCount) return Results.Ok(rows);");
        sb.AppendLine($"            var total = await EfCoreFilterDispatch.ApplyFilter(db.{dbSet}.OfType<{subCls}>().AsNoTracking(), filter.Predicates).CountAsync();");
        sb.AppendLine("            return Results.Ok(new { rows, total });");
        sb.AppendLine("        });");

        // Per-subtype get: GET /<base>/<seg>/{id} — scoped (cross-subtype → 404).
        sb.AppendLine();
        sb.AppendLine("        app.MapGet(prefix + \"/" + subRoute + "/{id}\", async (" + pkType + " id, AppDbContext db) =>");
        sb.AppendLine($"            await db.{dbSet}.OfType<{subCls}>().AsNoTracking().FirstOrDefaultAsync(x => x.{pkProp} == id) is {{ }} found");
        sb.AppendLine("                ? Results.Ok(found)");
        sb.AppendLine("                : Results.NotFound(new { error = \"not_found\" }));");

        // Per-subtype create: POST /<base>/<seg> — discriminator injected by EF via the
        // subtype CLR type; the POST body OMITS the discriminator.
        sb.AppendLine();
        sb.AppendLine("        app.MapPost(prefix + \"/" + subRoute + "\", async (" + subCls + " input, AppDbContext db) =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            db.{dbSet}.Add(input);");
        sb.AppendLine("            await db.SaveChangesAsync();");
        sb.AppendLine("            return Results.Created(prefix + \"/" + subRoute + "/\" + input." + pkProp + ", input);");
        sb.AppendLine("        });");

        // Per-subtype update (PATCH + PUT): partial merge of the JSON body onto the scoped
        // entity, NEVER touching the PK or the discriminator. Cross-subtype id → 404.
        sb.AppendLine();
        sb.AppendLine("        async System.Threading.Tasks.Task<IResult> Update" + subCls + "(" + pkType + " id, HttpContext http, AppDbContext db)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var existing = await db.{dbSet}.OfType<{subCls}>().FirstOrDefaultAsync(x => x.{pkProp} == id);");
        sb.AppendLine("            if (existing is null) return Results.NotFound(new { error = \"not_found\" });");
        sb.AppendLine("            var body = await System.Text.Json.JsonDocument.ParseAsync(http.Request.Body);");
        sb.AppendLine("            var entry = db.Entry(existing);");
        sb.AppendLine("            foreach (var prop in body.RootElement.EnumerateObject())");
        sb.AppendLine("            {");
        sb.AppendLine("                var target = entry.Metadata.FindProperty(prop.Name)");
        sb.AppendLine("                    ?? entry.Metadata.GetProperties().FirstOrDefault(p => string.Equals(p.Name, prop.Name, System.StringComparison.OrdinalIgnoreCase));");
        sb.AppendLine("                if (target is null) continue;");
        sb.AppendLine("                if (target.IsPrimaryKey()) continue;                       // PK is route-authoritative");
        sb.AppendLine($"                if (string.Equals(target.Name, \"{discProp}\", System.StringComparison.Ordinal)) continue; // discriminator is immutable");
        sb.AppendLine("                var clr = System.Nullable.GetUnderlyingType(target.ClrType) ?? target.ClrType;");
        sb.AppendLine("                object? value = prop.Value.ValueKind == System.Text.Json.JsonValueKind.Null");
        sb.AppendLine("                    ? null");
        sb.AppendLine("                    : System.Text.Json.JsonSerializer.Deserialize(prop.Value.GetRawText(), clr);");
        sb.AppendLine("                entry.CurrentValues[target] = value;");
        sb.AppendLine("            }");
        sb.AppendLine("            await db.SaveChangesAsync();");
        sb.AppendLine("            return Results.Ok(existing);");
        sb.AppendLine("        }");
        sb.AppendLine("        app.MapPatch(prefix + \"/" + subRoute + "/{id}\", Update" + subCls + ");");
        sb.AppendLine("        app.MapPut(prefix + \"/" + subRoute + "/{id}\", Update" + subCls + ");");

        // Per-subtype delete: DELETE /<base>/<seg>/{id} — scoped (cross-subtype → 404).
        sb.AppendLine();
        sb.AppendLine("        app.MapDelete(prefix + \"/" + subRoute + "/{id}\", async (" + pkType + " id, AppDbContext db) =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var existing = await db.{dbSet}.OfType<{subCls}>().FirstOrDefaultAsync(x => x.{pkProp} == id);");
        sb.AppendLine("            if (existing is null) return Results.NotFound(new { error = \"not_found\" });");
        sb.AppendLine($"            db.{dbSet}.Remove(existing);");
        sb.AppendLine("            await db.SaveChangesAsync();");
        sb.AppendLine("            return Results.NoContent();");
        sb.AppendLine("        });");
    }

    // Emit the M:N traversal handler for one navigation. The junction + target are
    // mapped DbSets; the handler does the same two-stage join M2MResolver performs at
    // runtime, but over the generated DbSets via EF.Property (no metadata at runtime).
    //
    //   hetero / directed self-join: junction WHERE <SourceFkProp> = id → <TargetFkProp>,
    //                                then target WHERE pk IN (...).
    //   symmetric self-join: junction WHERE <SourceFkProp> = id OR <TargetFkProp> = id;
    //                        per row the related id is whichever column is NOT the source id.
    //
    // Junction FK properties / target PK property are EF.Property<T>(...) lookups, so the
    // handler stays reflection-free and EF translates the property access to the column.
    private static void AppendM2mRoute(
        System.Text.StringBuilder sb, M2MNavigation nav, string sourceRoute, string pkType)
    {
        var relSeg = nav.Name;                                    // relationship name segment
        var targetCls = CSharpNaming.Pascal(nav.Target.Name);
        var targetDbSet = CSharpNaming.Pluralize(targetCls);
        var junctionDbSet = CSharpNaming.Pluralize(CSharpNaming.Pascal(nav.Junction.Name));
        var srcFkProp = CSharpNaming.Pascal(nav.SourceField);
        var tgtFkProp = CSharpNaming.Pascal(nav.TargetField);

        // The junction FK CLR type (the related-id key type) + the target PK property.
        var fkType = JunctionFkType(nav);
        var targetPk = nav.Target.PrimaryIdentity()?.Fields is { Count: 1 } tf
            ? CSharpNaming.Pascal(tf[0]) : "Id";

        sb.AppendLine();
        sb.AppendLine("        app.MapGet(prefix + \"/" + sourceRoute + "/{id}/" + relSeg + "\", async (" + pkType + " id, AppDbContext db) =>");
        sb.AppendLine("        {");
        if (nav.Symmetric)
        {
            // Union both junction columns; the related id is the column that is NOT the source id.
            sb.AppendLine($"            var pairs = await db.{junctionDbSet}.AsNoTracking()");
            sb.AppendLine($"                .Where(j => EF.Property<{fkType}>(j, \"{srcFkProp}\").Equals(id) || EF.Property<{fkType}>(j, \"{tgtFkProp}\").Equals(id))");
            sb.AppendLine($"                .Select(j => new {{ S = EF.Property<{fkType}>(j, \"{srcFkProp}\"), T = EF.Property<{fkType}>(j, \"{tgtFkProp}\") }})");
            sb.AppendLine("                .ToListAsync();");
            sb.AppendLine($"            var relatedIds = new System.Collections.Generic.HashSet<{fkType}>();");
            sb.AppendLine("            foreach (var p in pairs)");
            sb.AppendLine("                relatedIds.Add(p.S.Equals(id) ? p.T : p.S);");
        }
        else
        {
            sb.AppendLine($"            var relatedIds = (await db.{junctionDbSet}.AsNoTracking()");
            sb.AppendLine($"                .Where(j => EF.Property<{fkType}>(j, \"{srcFkProp}\").Equals(id))");
            sb.AppendLine($"                .Select(j => EF.Property<{fkType}>(j, \"{tgtFkProp}\"))");
            sb.AppendLine("                .ToListAsync()).ToHashSet();");
        }
        sb.AppendLine($"            if (relatedIds.Count == 0) return Results.Ok(new System.Collections.Generic.List<{targetCls}>());");
        sb.AppendLine($"            var rows = await db.{targetDbSet}.AsNoTracking()");
        sb.AppendLine($"                .Where(t => relatedIds.Contains(EF.Property<{fkType}>(t, \"{targetPk}\")))");
        sb.AppendLine("                .ToListAsync();");
        sb.AppendLine("            return Results.Ok(rows);");
        sb.AppendLine("        });");
    }

    // The CLR type of the junction FK columns (and thus the related-id key). Both
    // junction references point at same-typed PKs; use the source FK field's subtype.
    private static string JunctionFkType(M2MNavigation nav)
    {
        var fkField = nav.Junction.FindField(nav.SourceField);
        return fkField is not null ? CSharpNaming.ScalarFor(fkField.SubType) ?? "long" : "long";
    }
}
