"""Build the expected SchemaSnapshot from a MetaRoot.

Port of TS migrate-ts/src/expected-schema.ts. The cross-port corpus is the
oracle — this builder must produce the same set of tables/columns/indexes/FKs
as the TS + C# + Java ports for the same fixture.
"""
from __future__ import annotations

from collections.abc import Sequence

from ..meta.meta_root import MetaRoot
from ..meta.core.object.meta_object import MetaObject
from ..meta.core.identity.meta_identity import MetaIdentity
from ..meta.core.identity import identity_constants as ic
from ..meta.core.field.meta_field import MetaField
from ..meta.core.field import field_constants as fc
from ..meta.core.relationship.meta_relationship import MetaRelationship
from ..meta.persistence.source.meta_source import MetaSource
from ..meta.persistence.source import source_constants as sc
from .expected_views import build_expected_views
from .sql_type import (
    Boolean,
    Date,
    Integer,
    Json,
    Numeric,
    Real,
    SqlType,
    Text,
    Timestamp,
)
from .types import (
    ColumnDescriptor,
    FkDescriptor,
    IndexDescriptor,
    SchemaSnapshot,
    TableDescriptor,
)


def build_expected_schema(root: MetaRoot) -> SchemaSnapshot:
    """Build the snapshot the live DB should match."""
    # Index entities by short-name for cross-entity FK + view resolution.
    # (Multi-package collisions are not handled in v1; cross-port: TS keys
    # by FQN, but the corpus today is single-package.)
    entity_by_name: dict[str, MetaObject] = {}
    for child in root.own_children():
        if isinstance(child, MetaObject):
            entity_by_name.setdefault(child.name, child)

    tables: list[TableDescriptor] = []
    for child in root.own_children():
        if not isinstance(child, MetaObject):
            continue
        primary = _primary_writable_source(child)
        if primary is None:
            continue  # value object or read-only projection — handled by view pass below
        tables.append(_build_table(child, primary, entity_by_name))

    views = build_expected_views(root, entity_by_name)
    return SchemaSnapshot(tables=tuple(tables), views=tuple(views))


# ----------------------------------------------------------------------------
# Table descriptor
# ----------------------------------------------------------------------------


def _build_table(
    entity: MetaObject, primary: MetaSource, entity_by_name: dict[str, MetaObject],
) -> TableDescriptor:
    table_name = primary.table_name() or entity.name
    schema = primary.schema()
    pk_field_names = _primary_identity_field_names(entity)

    cols = tuple(_build_column(f, pk_field_names) for f in entity.fields())
    pk = tuple(_column_for(entity, fname) for fname in pk_field_names)
    indexes = tuple(_build_indexes(entity))
    fks = tuple(_build_foreign_keys(entity, entity_by_name))
    return TableDescriptor(
        name=table_name,
        schema=schema,
        columns=cols,
        indexes=indexes,
        foreign_keys=fks,
        primary_key=pk,
    )


def _build_column(field: MetaField, pk_field_names: tuple[str, ...]) -> ColumnDescriptor:
    is_pk = field.name in pk_field_names
    required = field.attr(fc.FIELD_ATTR_REQUIRED) is True
    nullable = not is_pk and not required
    identity = None
    # PK column with @generation = increment / uuid surfaces on the descriptor
    # so the emit layer can render BIGINT GENERATED BY DEFAULT AS IDENTITY etc.
    if is_pk:
        identity = _primary_identity_generation(field)
    return ColumnDescriptor(
        name=_column_of(field),
        sql_type=_subtype_to_sql_type(field),
        nullable=nullable,
        identity=identity,
    )


def _subtype_to_sql_type(field: MetaField) -> SqlType:
    st = field.sub_type
    if st == fc.FIELD_SUBTYPE_STRING:
        max_len = field.attr(fc.FIELD_ATTR_MAX_LENGTH)
        # bool is an int subclass — defend against `@maxLength: true`.
        if isinstance(max_len, int) and not isinstance(max_len, bool):
            return Text(max_length=max_len)
        return Text()
    if st in (fc.FIELD_SUBTYPE_INT,):
        return Integer(bits=32)
    if st in (fc.FIELD_SUBTYPE_LONG, fc.FIELD_SUBTYPE_CURRENCY):
        return Integer(bits=64)
    if st in (fc.FIELD_SUBTYPE_DOUBLE, fc.FIELD_SUBTYPE_FLOAT):
        return Real()
    if st == fc.FIELD_SUBTYPE_DECIMAL:
        return Numeric()
    if st == fc.FIELD_SUBTYPE_BOOLEAN:
        return Boolean()
    if st == fc.FIELD_SUBTYPE_DATE:
        return Date()
    if st == fc.FIELD_SUBTYPE_TIME:
        # SQL TIME is rare; fall to text to match TS behavior.
        return Text()
    if st == fc.FIELD_SUBTYPE_TIMESTAMP:
        return Timestamp(with_timezone=False)
    if st == fc.FIELD_SUBTYPE_ENUM:
        # Enum members stored as text; CHECK constraint is C#-only today.
        max_len = field.attr(fc.FIELD_ATTR_MAX_LENGTH)
        if isinstance(max_len, int) and not isinstance(max_len, bool):
            return Text(max_length=max_len)
        return Text()
    if st in (fc.FIELD_SUBTYPE_OBJECT, fc.FIELD_SUBTYPE_CLASS):
        return Json()
    return Text()


def _primary_identity_field_names(entity: MetaObject) -> tuple[str, ...]:
    pi = entity.primary_identity()
    if pi is None:
        return ()
    return _identity_fields(pi)


def _primary_identity_generation(field: MetaField) -> str | None:
    """Read @generation off the primary identity if this field is part of it."""
    owner = field.parent  # type: ignore[attr-defined]
    if not isinstance(owner, MetaObject):
        return None
    pi = owner.primary_identity()
    if pi is None:
        return None
    fields = _identity_fields(pi)
    if field.name not in fields:
        return None
    gen = pi.attr(ic.IDENTITY_ATTR_GENERATION)
    return gen if gen in ("increment", "uuid") else None


# ----------------------------------------------------------------------------
# Indexes (from identity.secondary)
# ----------------------------------------------------------------------------


def _build_indexes(entity: MetaObject):
    for child in entity.children():
        if not isinstance(child, MetaIdentity):
            continue
        if child.sub_type != ic.IDENTITY_SUBTYPE_SECONDARY:
            continue
        fields = _identity_fields(child)
        if not fields:
            continue
        cols = tuple(_column_for(entity, n) for n in fields)
        unique_attr = child.attr("unique")
        unique = unique_attr is not False  # secondary is unique by default
        yield IndexDescriptor(name=child.name, columns=cols, unique=unique)


# ----------------------------------------------------------------------------
# Foreign keys (from identity.reference)
# ----------------------------------------------------------------------------


def _build_foreign_keys(entity: MetaObject, entity_by_name: dict[str, MetaObject]):
    primary = _primary_writable_source(entity)
    if primary is None or primary.table_name() is None:
        return
    owning_table = primary.table_name()

    for child in entity.children():
        if not isinstance(child, MetaIdentity):
            continue
        if child.sub_type != ic.IDENTITY_SUBTYPE_REFERENCE:
            continue
        # @enforce: false → logical-only reference; not a physical FK.
        if child.attr(ic.IDENTITY_REFERENCE_ATTR_ENFORCE) is False:
            continue
        target_ref = child.attr(ic.IDENTITY_REFERENCE_ATTR_REFERENCES)
        if not isinstance(target_ref, str) or not target_ref:
            continue
        target_name = _strip_pkg(target_ref.split(".", 1)[0])
        target = entity_by_name.get(target_name)
        if target is None:
            continue
        target_primary = _primary_writable_source(target)
        if target_primary is None or target_primary.table_name() is None:
            continue

        fk_field_names = _identity_fields(child)
        if not fk_field_names:
            continue
        cols = tuple(_column_for(entity, n) for n in fk_field_names)
        ref_cols = tuple(_target_ref_columns(target, child))

        on_delete, on_update = _matching_relationship_actions(entity, target_name)
        yield FkDescriptor(
            name=f"{owning_table}_{cols[0]}_fk",
            columns=cols,
            ref_table=target_primary.table_name(),
            ref_columns=ref_cols,
            on_delete=on_delete,
            on_update=on_update,
        )


def _target_ref_columns(target: MetaObject, ref_identity: MetaIdentity) -> Sequence[str]:
    """The FK's right-hand column list — explicit target fields else target's PK."""
    target_ref = ref_identity.attr(ic.IDENTITY_REFERENCE_ATTR_REFERENCES)
    # The `references` attr is either "Target" (no field) or "Target.field"
    # (dotted). Multi-column FKs aren't in the conformance corpus today.
    if isinstance(target_ref, str) and "." in target_ref:
        return [_column_for(target, target_ref.split(".", 1)[1])]
    pk = _primary_identity_field_names(target)
    if pk:
        return [_column_for(target, pk[0])]
    return ["id"]


def _matching_relationship_actions(entity: MetaObject, target_entity: str) -> tuple[str | None, str | None]:
    """Pair the FK to its matching relationship by @objectRef → read @onDelete/@onUpdate."""
    for child in entity.children():
        if not isinstance(child, MetaRelationship):
            continue
        ref = child.object_ref
        if ref is None:
            continue
        if _strip_pkg(ref) == _strip_pkg(target_entity):
            return child.on_delete(), child.on_update
    return None, None


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------


def _identity_fields(identity: MetaIdentity) -> tuple[str, ...]:
    """Read @fields off an identity. Accepts both string (single) and list forms."""
    raw = identity.attr(ic.IDENTITY_ATTR_FIELDS)
    if raw is None:
        return ()
    if isinstance(raw, str):
        return (raw,)
    if isinstance(raw, (list, tuple)):
        return tuple(str(x) for x in raw)
    return ()


def _column_of(field: MetaField) -> str:
    """@column override else field name (matches C# Literal default; cross-port)."""
    col = field.attr("column")
    return col if isinstance(col, str) and col else field.name


def _column_for(entity: MetaObject, field_name: str) -> str:
    f = entity.find_field(field_name)
    return _column_of(f) if f is not None else field_name


def _primary_writable_source(entity: MetaObject) -> MetaSource | None:
    for child in entity.own_children():
        if isinstance(child, MetaSource) and child.role() == sc.SOURCE_ROLE_PRIMARY and child.is_writable():
            return child
    return None


def _strip_pkg(name: str) -> str:
    idx = name.rfind("::")
    return name if idx == -1 else name[idx + 2 :]
