"""Render Change list as Postgres DDL. Port of TS emit/postgres.ts.

Mirrors the C# + Java emit shape: double-quoted identifiers throughout,
named PK constraint per table ({table}_pkey), separate CREATE INDEX +
ALTER ... ADD CONSTRAINT FK statements alongside CREATE TABLE for new
tables. Views are CREATE OR REPLACE VIEW so re-runs are idempotent.
"""
from __future__ import annotations

from .sql_type import (
    Blob,
    Boolean,
    Date,
    Integer,
    Json,
    Numeric,
    Real,
    SqlType,
    Text,
    Timestamp,
    Uuid,
)
from .types import (
    AddColumn,
    AddFk,
    AddIndex,
    Change,
    ColumnDescriptor,
    CreateTable,
    CreateView,
    DropTable,
    FkDescriptor,
    IndexDescriptor,
    TableDescriptor,
)


# Stages: low → high. drop-view runs first (so it lands before any table
# drops it depends on); create-view runs last (after FKs land).
_STAGE = {
    "create-table": 1,
    "add-column": 2, "drop-column": 2,
    "rename-column": 3, "rename-table": 3,
    "add-index": 4, "drop-index": 4,
    "add-fk": 5, "drop-fk": 5,
    "drop-table": 6,
    "create-view": 7,
}


def emit_postgres(changes: list[Change]) -> str:
    """Render the up SQL. Blocked changes are dropped — caller asserts on them separately."""
    emittable = [c for c in changes if c.status.state != "blocked"]
    emittable.sort(key=lambda c: _STAGE.get(c.kind, 99))
    parts = [_render_change(c) for c in emittable]
    return "\n\n".join(p for p in parts if p)


def _render_change(c: Change) -> str:
    if isinstance(c, CreateTable):     return _render_create_table(c.table)
    if isinstance(c, DropTable):       return f"DROP TABLE {_q_qual(c.table, c.schema)};"
    if isinstance(c, AddColumn):
        return f"ALTER TABLE {_q_qual(c.table, c.schema)} ADD COLUMN {_render_column(c.column)};"
    if isinstance(c, AddIndex):        return _render_add_index(c.table, c.schema, c.index)
    if isinstance(c, AddFk):           return _render_add_fk(c.table, c.schema, c.fk)
    if isinstance(c, CreateView):
        body = c.view.sql or ""
        return f"CREATE OR REPLACE VIEW {_q_qual(c.view.name, c.view.schema)} AS\n{body};"
    return ""


def _render_create_table(t: TableDescriptor) -> str:
    col_defs = [f"  {_render_column(c)}" for c in t.columns]
    if t.primary_key:
        pk_cols = ", ".join(_q(c) for c in t.primary_key)
        col_defs.append(f'  CONSTRAINT {_q(t.name + "_pkey")} PRIMARY KEY ({pk_cols})')
    body = ",\n".join(col_defs)
    return f"CREATE TABLE {_q_qual(t.name, t.schema)} (\n{body}\n);"


def _render_column(c: ColumnDescriptor) -> str:
    parts = [_q(c.name), _pg_type(c.sql_type)]
    if c.identity == "increment":
        parts.append("GENERATED BY DEFAULT AS IDENTITY")
    elif c.identity == "uuid":
        parts.append("DEFAULT gen_random_uuid()")
    if not c.nullable:
        parts.append("NOT NULL")
    return " ".join(parts)


def _render_add_index(table: str, schema: str | None, idx: IndexDescriptor) -> str:
    cols = ", ".join(_q(c) for c in idx.columns)
    uniq = "UNIQUE " if idx.unique else ""
    return f"CREATE {uniq}INDEX {_q(idx.name)} ON {_q_qual(table, schema)} ({cols});"


def _render_add_fk(table: str, schema: str | None, fk: FkDescriptor) -> str:
    cols = ", ".join(_q(c) for c in fk.columns)
    refs = ", ".join(_q(c) for c in fk.ref_columns)
    tail = ""
    if fk.on_delete:
        tail += " ON DELETE " + _action_sql(fk.on_delete)
    if fk.on_update:
        tail += " ON UPDATE " + _action_sql(fk.on_update)
    return (
        f"ALTER TABLE {_q_qual(table, schema)} ADD CONSTRAINT {_q(fk.name)} "
        f"FOREIGN KEY ({cols}) REFERENCES {_q(fk.ref_table)} ({refs}){tail};"
    )


def _action_sql(action: str) -> str:
    return {
        "cascade": "CASCADE",
        "set-null": "SET NULL",
        "restrict": "RESTRICT",
        "no-action": "NO ACTION",
    }.get(action, action.upper())


def _pg_type(t: SqlType) -> str:
    if isinstance(t, Text):
        return f"VARCHAR({t.max_length})" if t.max_length is not None else "TEXT"
    if isinstance(t, Integer):
        return "BIGINT" if t.bits == 64 else "INTEGER"
    if isinstance(t, Real):
        return "DOUBLE PRECISION"
    if isinstance(t, Numeric):
        if t.precision is not None and t.scale is not None:
            return f"NUMERIC({t.precision},{t.scale})"
        if t.precision is not None:
            return f"NUMERIC({t.precision})"
        return "NUMERIC"
    if isinstance(t, Boolean):  return "BOOLEAN"
    if isinstance(t, Timestamp): return "TIMESTAMP WITH TIME ZONE" if t.with_timezone else "TIMESTAMP"
    if isinstance(t, Date):     return "DATE"
    if isinstance(t, Json):     return "JSONB"
    if isinstance(t, Blob):     return "BYTEA"
    if isinstance(t, Uuid):     return "UUID"
    return "TEXT"


def _q(ident: str) -> str:
    if '"' in ident:
        raise ValueError(f"unsafe identifier: {ident}")
    return f'"{ident}"'


def _q_qual(name: str, schema: str | None) -> str:
    if not schema or schema == "public":
        return _q(name)
    return f"{_q(schema)}.{_q(name)}"
