// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: Exercise (Exercise)
// Customize via Exercise.extra.ts in this directory (e.g., auth, additional handlers).
import { db } from "~/server/db";
import {
  Exercise,
  ExerciseFilterAllowlist,
  ExerciseInsertSchema,
  exercises,
  ExerciseSortAllowlist,
  ExerciseUpdateSchema,
} from "./Exercise";
import { mountCrudRoutes } from "@metaobjects/runtime-ts/drizzle-fastify";
import type { FastifyInstance } from "fastify";

/**
 * Mount the 5 standard REST endpoints for Exercise using Drizzle directly.
 *
 * Customize: register this as-is for stock CRUD, OR import the per-verb
 * helpers (mountListRoute, mountGetRoute, ...) from
 * @metaobjects/runtime-ts/drizzle-fastify and mix with your own handlers
 * (auth, side effects, etc.).
 */
export async function exerciseRoutes(fastify: FastifyInstance) {
  mountCrudRoutes({
    fastify,
    path: Exercise.$path,
    db,
    table: exercises,
    insertSchema: ExerciseInsertSchema,
    updateSchema: ExerciseUpdateSchema,
    filterAllowlist: ExerciseFilterAllowlist,
    sortAllowlist: ExerciseSortAllowlist,
    dialect: "postgres",
  });
}
