// @generated by @metaobjectsdev/codegen-ts — hand edits are kept by a three-way merge on regeneration; meta verify --codegen checks only the generated parts.
// Source metadata: Purchase (Purchase)
// Extend in your own module (e.g. Purchase.extra.ts) — nothing imports it for you.
import {
  type InferInsertModel,
  type InferSelectModel,
  relations,
} from "drizzle-orm";
import {
  type AnyPgColumn,
  bigint,
  integer,
  pgTable,
  timestamp,
} from "drizzle-orm/pg-core";
import { z } from "zod";
import { programs } from "./Program";
import { subscribers } from "./Subscriber";

export const purchases = pgTable("purchases", {
  id: bigint("id", { mode: "number" })
    .primaryKey()
    .generatedByDefaultAsIdentity(),
  subscriberId: bigint("subscriber_id", { mode: "number" })
    .notNull()
    .references((): AnyPgColumn => subscribers.id),
  programId: bigint("program_id", { mode: "number" })
    .notNull()
    .references((): AnyPgColumn => programs.id),
  amountCents: integer("amount_cents").notNull(),
  purchasedAt: timestamp("purchased_at", { mode: "string", withTimezone: true })
    .notNull()
    .defaultNow(),
});
export const purchasesRelations = relations(purchases, ({ one }) => ({
  subscriber: one(subscribers, {
    fields: [purchases.subscriberId],
    references: [subscribers.id],
  }),
  program: one(programs, {
    fields: [purchases.programId],
    references: [programs.id],
  }),
}));
export type Purchase = InferSelectModel<typeof purchases>;
export type PurchaseInsert = InferInsertModel<typeof purchases>;
export type PurchaseUpdate = Partial<PurchaseInsert>;
/** A field.timestamp instant in UTC (`YYYY-MM-DDTHH:MM:SS[.fff]Z`): a value already spelled so is kept
 *  as sent, an offset is applied, a zoneless value is UTC and a date alone is midnight UTC.
 *  SQLite/D1 compare timestamps as text, so instants are stored in UTC. Generated. */
function utcIsoTimestamp(v: string): string {
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(v)) {
    return v;
  }
  const m =
    /^(\d{4}-\d{2}-\d{2})(?:[Tt ](\d{2}:\d{2})(?::(\d{2})(?:\.(\d+))?)?(?:([Zz])|([+-]\d{2}):?(\d{2})?)?)?$/.exec(
      v,
    );
  if (m === null) {
    return v;
  }
  const t = Date.parse(
    `${m[1]}T${m[2] ?? "00:00"}:${m[3] ?? "00"}.${(m[4] ?? "").slice(0, 3).padEnd(3, "0")}${
      m[6] === undefined ? "Z" : `${m[6]}:${m[7] ?? "00"}`
    }`,
  );
  return Number.isNaN(t)
    ? v
    : new Date(t).toISOString().replace(/\.?0+Z$/, "Z");
}

export const PurchaseInsertSchema = z.object({
  subscriberId: z.number().int(),
  programId: z.number().int(),
  amountCents: z.number().int(),
  purchasedAt: z
    .string()
    .regex(
      /^(?:\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|02-(?:0[1-9]|1\d|2[0-8]))|(?:\d{2}(?:0[48]|[2468][048]|[13579][26])|(?:[02468][048]|[13579][26])00)-02-29)(?:[Tt ](?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:[Zz]|[+-](?:[01]\d|2[0-3])(?::?[0-5]\d)?)?)?$/,
      "must be an ISO 8601 timestamp (YYYY-MM-DD[THH:MM[:SS[.fff]]][Z|±HH:MM])",
    )
    .transform(utcIsoTimestamp)
    .optional(),
});

export const PurchaseUpdateSchema = z.object({
  subscriberId: z.number().int().optional(),
  programId: z.number().int().optional(),
  amountCents: z.number().int().optional(),
  purchasedAt: z
    .string()
    .regex(
      /^(?:\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|02-(?:0[1-9]|1\d|2[0-8]))|(?:\d{2}(?:0[48]|[2468][048]|[13579][26])|(?:[02468][048]|[13579][26])00)-02-29)(?:[Tt ](?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:[Zz]|[+-](?:[01]\d|2[0-3])(?::?[0-5]\d)?)?)?$/,
      "must be an ISO 8601 timestamp (YYYY-MM-DD[THH:MM[:SS[.fff]]][Z|±HH:MM])",
    )
    .transform(utcIsoTimestamp)
    .optional(),
});

/** Typed create shape for Purchase: the insert schema's INPUT (pre-transform) type. A
 * renamed/dropped/misspelt field is a compile error at every `createPurchase` call site;
 * the schema still validates at runtime. */
export type PurchaseCreate = z.input<typeof PurchaseInsertSchema>;

/** Typed patch shape for Purchase: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updatePurchase` call site. */
export type PurchasePatch = z.input<typeof PurchaseUpdateSchema>;
/**
 * Metadata constants for Purchase.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, an htmlType where the field's view maps to one, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * placeholder and helpText are NOT emitted — no provider registers an attribute
 * for them, so nothing here could derive one. (htmlType is emitted, but derived
 * from the view subtype; the @htmlType override was removed for the same reason.)
 * useEntityForm still honours placeholder if you add it: this file is generated,
 * hand edits inside it survive regeneration through the three-way merge, and the
 * consumers read this const rather than the metadata. That is the intended way
 * to set it.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(Purchase, PurchaseInsertSchema);
 *   <input {...form.input.id} />
 */
export const Purchase = {
  $entity: "Purchase",
  $table: "purchases",
  $path: "/purchases",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  subscriberId: {
    name: "subscriberId",
    label: "Subscriber Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Subscriber Id is required" },
  },
  programId: {
    name: "programId",
    label: "Program Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Program Id is required" },
  },
  amountCents: {
    name: "amountCents",
    label: "Amount Cents",
    view: "number",
    htmlType: "number",
    rules: { required: "Amount Cents is required" },
  },
  purchasedAt: {
    name: "purchasedAt",
    label: "Purchased At",
    view: "date",
    htmlType: "datetime-local",
    rules: { required: "Purchased At is required" },
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const PurchaseFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const PurchaseSortAllowlist = {} as const satisfies SortAllowlist;
export type PurchaseFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: PurchaseFilter[];
  and?: PurchaseFilter[];
};
