// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Purchase (Purchase)
// Customize via Purchase.extra.ts in this directory (additional queries, custom logic).
import { eq, sql } from "drizzle-orm";

import { db } from "~/server/db";
import { type Purchase, PurchaseInsertSchema, purchases } from "./Purchase";
const findPurchaseByIdBase = db
  .select()
  .from(purchases)
  .where(eq(purchases.id, sql.placeholder("id")));
const findPurchaseByIdPrepared = findPurchaseByIdBase.prepare(
  "find_purchase_by_id",
);

export async function findPurchaseById(id: number): Promise<Purchase | null> {
  const [purchase] = await findPurchaseByIdPrepared.execute({ id });
  return purchase ?? null;
}
export async function listPurchases(opts?: {
  limit?: number;
  offset?: number;
}): Promise<Purchase[]> {
  let q = db.select().from(purchases).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createPurchase(data: unknown): Promise<Purchase> {
  const validated = PurchaseInsertSchema.parse(data);
  const [purchase] = await db.insert(purchases).values(validated).returning();
  return purchase!;
}
export async function updatePurchase(
  id: number,
  data: unknown,
): Promise<Purchase | null> {
  const validated = PurchaseInsertSchema.partial().parse(data);
  const [purchase] = await db
    .update(purchases)
    .set(validated)
    .where(eq(purchases.id, id))
    .returning();
  return purchase ?? null;
}
export async function deletePurchaseById(id: number): Promise<boolean> {
  const result = await db.delete(purchases).where(eq(purchases.id, id));
  // SQLite (libsql/Turso) returns { rowsAffected }; postgres returns array from .returning()
  return (
    ("rowsAffected" in result
      ? result.rowsAffected
      : (result as unknown as unknown[]).length) > 0
  );
}
