// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Tag (Tag)
// Customize via Tag.extra.ts in this directory.
import type { InferInsertModel, InferSelectModel } from "drizzle-orm";
import { bigserial, pgTable, varchar } from "drizzle-orm/pg-core";
import { z } from "zod";

export const tags = pgTable("tags", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  name: varchar("name", { length: 50 }).notNull().unique(),
  slug: varchar("slug", { length: 50 }).notNull().unique(),
});
export type Tag = InferSelectModel<typeof tags>;
export type TagInsert = InferInsertModel<typeof tags>;
export type TagUpdate = Partial<TagInsert>;
export const TagInsertSchema = z.object({
  name: z.string().min(1).max(50),
  slug: z.string().min(1).max(50),
});

export const TagUpdateSchema = z.object({
  name: z.string().min(1).max(50).optional(),
  slug: z.string().min(1).max(50).optional(),
});

/** Typed patch shape for Tag: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updateTag` call site. */
export type TagPatch = z.input<typeof TagUpdateSchema>;
/**
 * Metadata constants for Tag.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, an htmlType where the field's view maps to one, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * placeholder and helpText are NOT emitted — no provider registers an attribute
 * for them, so nothing here could derive one. (htmlType is emitted, but derived
 * from the view subtype; the @htmlType override was removed for the same reason.)
 * useEntityForm still honours placeholder if you add it: this file is generated,
 * hand edits inside it survive regeneration through the three-way merge, and the
 * consumers read this const rather than the metadata. That is the intended way
 * to set it.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(Tag, TagInsertSchema);
 *   <input {...form.input.id} />
 */
export const Tag = {
  $entity: "Tag",
  $table: "tags",
  $path: "/tags",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  name: {
    name: "name",
    label: "Name",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Name is required",
      maxLength: { value: 50, message: "Must be 50 characters or fewer" },
    },
  },
  slug: {
    name: "slug",
    label: "Slug",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Slug is required",
      maxLength: { value: 50, message: "Must be 50 characters or fewer" },
    },
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const TagFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const TagSortAllowlist = {} as const satisfies SortAllowlist;
export type TagFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: TagFilter[];
  and?: TagFilter[];
};
