// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Video (Video)
// Customize via Video.extra.ts in this directory.
import {
  type InferInsertModel,
  type InferSelectModel,
  relations,
} from "drizzle-orm";
import {
  type AnyPgColumn,
  bigint,
  bigserial,
  integer,
  pgTable,
  varchar,
} from "drizzle-orm/pg-core";
import { z } from "zod";
import { exercises } from "./Exercise";

export const videos = pgTable("videos", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  exerciseId: bigint("exercise_id", { mode: "number" })
    .notNull()
    .references((): AnyPgColumn => exercises.id),
  url: varchar("url", { length: 500 }).notNull(),
  title: varchar("title", { length: 200 }),
  durationSeconds: integer("duration_seconds"),
});
export const videosRelations = relations(videos, ({ one }) => ({
  exercise: one(exercises, {
    fields: [videos.exerciseId],
    references: [exercises.id],
  }),
}));
export type Video = InferSelectModel<typeof videos>;
export type VideoInsert = InferInsertModel<typeof videos>;
export type VideoUpdate = Partial<VideoInsert>;
export const VideoInsertSchema = z.object({
  exerciseId: z.number().int(),
  url: z.string().min(1).max(500),
  title: z.string().max(200).optional(),
  durationSeconds: z.number().int().optional(),
});

export const VideoUpdateSchema = z.object({
  exerciseId: z.number().int().optional(),
  url: z.string().min(1).max(500).optional(),
  title: z.string().max(200).optional(),
  durationSeconds: z.number().int().optional(),
});
/**
 * Metadata constants for Video.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, optional htmlType/placeholder/helpText, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(Video, VideoInsertSchema);
 *   <input {...form.input.id} />
 */
export const Video = {
  $entity: "Video",
  $table: "videos",
  $path: "/videos",
  $apiPrefix: "",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  exerciseId: {
    name: "exerciseId",
    label: "Exercise Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Exercise Id is required" },
  },
  url: {
    name: "url",
    label: "Url",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Url is required",
      maxLength: { value: 500, message: "Must be 500 characters or fewer" },
    },
  },
  title: {
    name: "title",
    label: "Title",
    view: "text",
    htmlType: "text",
    rules: {
      maxLength: { value: 200, message: "Must be 200 characters or fewer" },
    },
  },
  durationSeconds: {
    name: "durationSeconds",
    label: "Duration Seconds",
    view: "number",
    htmlType: "number",
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const VideoFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const VideoSortAllowlist = {} as const satisfies SortAllowlist;
export type VideoFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: VideoFilter[];
  and?: VideoFilter[];
};
