// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: Week (Week)
// Customize via Week.extra.ts in this directory.
import { InferInsertModel, InferSelectModel, relations } from "drizzle-orm";
import {
  bigint,
  bigserial,
  integer,
  pgTable,
  varchar,
} from "drizzle-orm/pg-core";
import { z } from "zod";
import { programs } from "./Program";
import { workouts } from "./Workout";

export const weeks = pgTable("weeks", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  programId: bigint("program_id", { mode: "number" })
    .notNull()
    .references(() => programs.id),
  weekNumber: integer("week_number").notNull(),
  title: varchar("title", { length: 200 }).notNull(),
});
export const weeksRelations = relations(weeks, ({ one, many }) => ({
  program: one(programs, {
    fields: [weeks.programId],
    references: [programs.id],
  }),
  workouts: many(workouts),
}));
export type Week = InferSelectModel<typeof weeks>;
export type WeekInsert = InferInsertModel<typeof weeks>;
export type WeekUpdate = Partial<WeekInsert>;
export const WeekInsertSchema = z.object({
  programId: z.number().int(),
  weekNumber: z.number().int(),
  title: z.string().min(1).max(200),
});

export const WeekUpdateSchema = z.object({
  programId: z.number().int().optional(),
  weekNumber: z.number().int().optional(),
  title: z.string().min(1).max(200).optional(),
});
/**
 * Metadata constants for Week.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, optional htmlType/placeholder/helpText, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjects/runtime-ts-client/react';
 *   const form = useEntityForm(Week, WeekInsertSchema);
 *   <input {...form.input.id} />
 */
export const Week = {
  $entity: "Week",
  $table: "weeks",
  $path: "/weeks",
  $apiPrefix: "",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  programId: {
    name: "programId",
    label: "Program Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Program Id is required" },
  },
  weekNumber: {
    name: "weekNumber",
    label: "Week Number",
    view: "number",
    htmlType: "number",
    rules: { required: "Week Number is required" },
  },
  title: {
    name: "title",
    label: "Title",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Title is required",
      maxLength: { value: 200, message: "Must be 200 characters or fewer" },
    },
  },
} as const;
import type { FilterAllowlist } from "@metaobjects/runtime-ts/drizzle-fastify";

export const WeekFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjects/runtime-ts/drizzle-fastify";

export const WeekSortAllowlist = {} as const satisfies SortAllowlist;
export type WeekFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: WeekFilter[];
  and?: WeekFilter[];
};
