// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Week (Week)
// Customize via Week.extra.tsx (custom layouts, per-field components, etc.).
import { Week, WeekInsertSchema } from "./Week";
import type { Week as WeekRow } from "./Week";
import { useEntityForm } from "@metaobjectsdev/react";
import type { ReactElement } from "react";
import type { SubmitHandler } from "react-hook-form";

export interface WeekFormProps {
  onSubmit: SubmitHandler<Partial<WeekRow>>;
  defaultValues?: Partial<WeekRow>;
  submitLabel?: string;
  className?: string;
}

/**
 * Generated React form for Week. All field metadata (name, label,
 * placeholder, html input type, RHF validation rules) comes from the
 * Week constants emitted alongside this file. Validation uses the
 * generated Zod schema, shared with the server-side Fastify route.
 *
 * Customize: this file is regenerated on every `forge gen`. If you need a
 * custom layout, write your own component using useEntityForm + the
 * Week constants directly.
 */
export function WeekForm(props: WeekFormProps): ReactElement {
  const form = useEntityForm(
    Week,
    WeekInsertSchema,
    props.defaultValues !== undefined ? { defaultValues: props.defaultValues } : {},
  );
  return (
    <form
      className={props.className ?? "metaobjects-form"}
      data-entity={Week.$entity}
      onSubmit={form.handleSubmit(props.onSubmit as never)}
    >
      <div className="metaobjects-field" key="programId">
        <label className="metaobjects-field-label" htmlFor={Week.programId.name}>{Week.programId.label}</label>
        <input className="metaobjects-field-input" {...form.input.programId} />
        {form.formState.errors.programId !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.programId?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="weekNumber">
        <label className="metaobjects-field-label" htmlFor={Week.weekNumber.name}>{Week.weekNumber.label}</label>
        <input className="metaobjects-field-input" {...form.input.weekNumber} />
        {form.formState.errors.weekNumber !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.weekNumber?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="title">
        <label className="metaobjects-field-label" htmlFor={Week.title.name}>{Week.title.label}</label>
        <input className="metaobjects-field-input" {...form.input.title} />
        {form.formState.errors.title !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.title?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-form-actions">
        <button className="metaobjects-form-submit" type="submit" disabled={form.formState.isSubmitting}>
          {props.submitLabel ?? "Submit"}
        </button>
      </div>
    </form>
  );
}
