// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: WorkoutEvent (WorkoutEvent)
// Customize via WorkoutEvent.extra.ts in this directory (additional queries, custom logic).
import { eq, inArray } from "drizzle-orm";

import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
type Db = PgDatabase<PgQueryResultHKT, Record<string, never>>;

import {
  type WorkoutEvent,
  WorkoutEventInsertSchema,
  workoutEvents,
} from "./WorkoutEvent";
export async function findWorkoutEventById(
  db: Db,
  id: number,
): Promise<WorkoutEvent | null> {
  const [workoutEvent] = await db
    .select()
    .from(workoutEvents)
    .where(eq(workoutEvents.id, id))
    .limit(1);
  return workoutEvent ?? null;
}
export async function listWorkoutEvents(
  db: Db,
  opts?: { limit?: number; offset?: number },
): Promise<WorkoutEvent[]> {
  let q = db.select().from(workoutEvents).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createWorkoutEvent(
  db: Db,
  data: unknown,
): Promise<WorkoutEvent> {
  const validated = WorkoutEventInsertSchema.parse(data);
  const [workoutEvent] = await db
    .insert(workoutEvents)
    .values(validated)
    .returning();
  return workoutEvent!;
}
export async function updateWorkoutEvent(
  db: Db,
  id: number,
  data: unknown,
): Promise<WorkoutEvent | null> {
  const validated = WorkoutEventInsertSchema.partial().parse(data);
  const [workoutEvent] = await db
    .update(workoutEvents)
    .set(validated)
    .where(eq(workoutEvents.id, id))
    .returning();
  return workoutEvent ?? null;
}
export async function deleteWorkoutEventById(
  db: Db,
  id: number,
): Promise<boolean> {
  // Use .returning() unconditionally — supported on SQLite ≥3.35 (covers D1, libsql/Turso)
  // and Postgres. Result is an array of deleted rows; presence implies success.
  const deleted = await db
    .delete(workoutEvents)
    .where(eq(workoutEvents.id, id))
    .returning();
  return deleted.length > 0;
}
export async function findWorkoutEventsBySubscriber(
  db: Db,
  subscriberId: number,
): Promise<WorkoutEvent[]> {
  return db
    .select()
    .from(workoutEvents)
    .where(eq(workoutEvents.subscriberId, subscriberId));
}

export async function findWorkoutEventsBySubscriberIn(
  db: Db,
  subscriberIds: number[],
): Promise<WorkoutEvent[]> {
  if (subscriberIds.length === 0) {
    return [];
  }
  return db
    .select()
    .from(workoutEvents)
    .where(inArray(workoutEvents.subscriberId, subscriberIds));
}
export async function findWorkoutEventsByWorkout(
  db: Db,
  workoutId: number,
): Promise<WorkoutEvent[]> {
  return db
    .select()
    .from(workoutEvents)
    .where(eq(workoutEvents.workoutId, workoutId));
}

export async function findWorkoutEventsByWorkoutIn(
  db: Db,
  workoutIds: number[],
): Promise<WorkoutEvent[]> {
  if (workoutIds.length === 0) {
    return [];
  }
  return db
    .select()
    .from(workoutEvents)
    .where(inArray(workoutEvents.workoutId, workoutIds));
}
