// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: WorkoutEvent (WorkoutEvent)
// Customize via WorkoutEvent.extra.ts in this directory.
import {
  type InferInsertModel,
  type InferSelectModel,
  relations,
} from "drizzle-orm";
import {
  type AnyPgColumn,
  bigint,
  bigserial,
  integer,
  pgTable,
  timestamp,
} from "drizzle-orm/pg-core";
import { z } from "zod";
import { subscribers } from "./Subscriber";
import { workouts } from "./Workout";

export const workoutEvents = pgTable("workout_events", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  subscriberId: bigint("subscriber_id", { mode: "number" })
    .notNull()
    .references((): AnyPgColumn => subscribers.id),
  workoutId: bigint("workout_id", { mode: "number" })
    .notNull()
    .references((): AnyPgColumn => workouts.id),
  completedAt: timestamp("completed_at", { mode: "string", withTimezone: true })
    .notNull()
    .defaultNow(),
  durationMinutes: integer("duration_minutes"),
});
export const workoutEventsRelations = relations(workoutEvents, ({ one }) => ({
  subscriber: one(subscribers, {
    fields: [workoutEvents.subscriberId],
    references: [subscribers.id],
  }),
  workout: one(workouts, {
    fields: [workoutEvents.workoutId],
    references: [workouts.id],
  }),
}));
export type WorkoutEvent = InferSelectModel<typeof workoutEvents>;
export type WorkoutEventInsert = InferInsertModel<typeof workoutEvents>;
export type WorkoutEventUpdate = Partial<WorkoutEventInsert>;
export const WorkoutEventInsertSchema = z.object({
  subscriberId: z.number().int(),
  workoutId: z.number().int(),
  completedAt: z.string().optional(),
  durationMinutes: z.number().int().optional(),
});

export const WorkoutEventUpdateSchema = z.object({
  subscriberId: z.number().int().optional(),
  workoutId: z.number().int().optional(),
  completedAt: z.string().optional(),
  durationMinutes: z.number().int().optional().nullable(),
});

/** Typed patch shape for WorkoutEvent: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updateWorkoutEvent` call site. */
export type WorkoutEventPatch = z.input<typeof WorkoutEventUpdateSchema>;
/**
 * Metadata constants for WorkoutEvent.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, and the RHF-shaped validation rules derived from the
 * field's validator children.
 *
 * htmlType, placeholder and helpText are NOT emitted — no provider registers
 * an attribute for them, so nothing here could derive one. useEntityForm
 * still honours all three if you add them: this file is generated, hand edits
 * inside it survive regeneration through the three-way merge, and the
 * consumers read this const rather than the metadata. That is the intended
 * way to set them.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(WorkoutEvent, WorkoutEventInsertSchema);
 *   <input {...form.input.id} />
 */
export const WorkoutEvent = {
  $entity: "WorkoutEvent",
  $table: "workout_events",
  $path: "/workout_events",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  subscriberId: {
    name: "subscriberId",
    label: "Subscriber Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Subscriber Id is required" },
  },
  workoutId: {
    name: "workoutId",
    label: "Workout Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Workout Id is required" },
  },
  completedAt: {
    name: "completedAt",
    label: "Completed At",
    view: "date",
    htmlType: "date",
    rules: { required: "Completed At is required" },
  },
  durationMinutes: {
    name: "durationMinutes",
    label: "Duration Minutes",
    view: "number",
    htmlType: "number",
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const WorkoutEventFilterAllowlist =
  {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const WorkoutEventSortAllowlist = {} as const satisfies SortAllowlist;
export type WorkoutEventFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: WorkoutEventFilter[];
  and?: WorkoutEventFilter[];
};
