// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: WorkoutEvent (WorkoutEvent)
// Customize via WorkoutEvent.extra.ts in this directory (e.g., auth, additional handlers).
import { db } from "~/server/db";
import {
  WorkoutEvent,
  WorkoutEventFilterAllowlist,
  WorkoutEventInsertSchema,
  workoutEvents,
  WorkoutEventSortAllowlist,
  WorkoutEventUpdateSchema,
} from "./WorkoutEvent";
import { mountCrudRoutes } from "@metaobjects/runtime-ts/drizzle-fastify";
import type { FastifyInstance } from "fastify";

/**
 * Mount the 5 standard REST endpoints for WorkoutEvent using Drizzle directly.
 *
 * Customize: register this as-is for stock CRUD, OR import the per-verb
 * helpers (mountListRoute, mountGetRoute, ...) from
 * @metaobjects/runtime-ts/drizzle-fastify and mix with your own handlers
 * (auth, side effects, etc.).
 */
export async function workoutEventRoutes(fastify: FastifyInstance) {
  mountCrudRoutes({
    fastify,
    path: WorkoutEvent.$path,
    db,
    table: workoutEvents,
    insertSchema: WorkoutEventInsertSchema,
    updateSchema: WorkoutEventUpdateSchema,
    filterAllowlist: WorkoutEventFilterAllowlist,
    sortAllowlist: WorkoutEventSortAllowlist,
    dialect: "postgres",
  });
}
