// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Workout (Workout)
// Customize via Workout.extra.ts in this directory (additional queries, custom logic).
import { eq, sql } from "drizzle-orm";

import type { NodePgDatabase } from "drizzle-orm/node-postgres";
type Db = NodePgDatabase<Record<string, never>>;

import { type Workout, WorkoutInsertSchema, workouts } from "./Workout";
export async function findWorkoutById(
  db: Db,
  id: number,
): Promise<Workout | null> {
  const findWorkoutByIdBase = db
    .select()
    .from(workouts)
    .where(eq(workouts.id, sql.placeholder("id")));
  const findWorkoutByIdPrepared =
    findWorkoutByIdBase.prepare("find_workout_by_id");
  const [workout] = await findWorkoutByIdPrepared.execute({ id });
  return workout ?? null;
}
export async function listWorkouts(
  db: Db,
  opts?: { limit?: number; offset?: number },
): Promise<Workout[]> {
  let q = db.select().from(workouts).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createWorkout(db: Db, data: unknown): Promise<Workout> {
  const validated = WorkoutInsertSchema.parse(data);
  const [workout] = await db.insert(workouts).values(validated).returning();
  return workout!;
}
export async function updateWorkout(
  db: Db,
  id: number,
  data: unknown,
): Promise<Workout | null> {
  const validated = WorkoutInsertSchema.partial().parse(data);
  const [workout] = await db
    .update(workouts)
    .set(validated)
    .where(eq(workouts.id, id))
    .returning();
  return workout ?? null;
}
export async function deleteWorkoutById(db: Db, id: number): Promise<boolean> {
  // Use .returning() unconditionally — supported on SQLite ≥3.35 (covers D1, libsql/Turso)
  // and Postgres. Result is an array of deleted rows; presence implies success.
  const deleted = await db
    .delete(workouts)
    .where(eq(workouts.id, id))
    .returning();
  return deleted.length > 0;
}
