import { readFileSync, readdirSync, existsSync, statSync } from "node:fs";
import { join } from "node:path";
import {
  SKILL_NAMES, SERVER_LANGS, CLIENT_FRAMEWORKS, CONCERN_TOKENS, type AssembledFile, type Stack,
} from "./types.js";

// Language/framework/concern reference fragments are stack-scoped; any other
// fragment (e.g. capability-checklist) is universal and always installs. Adding a
// future concern token to CONCERN_TOKENS (types.ts) is all that's needed to gate
// its matching references/<token>.md fragment here.
const SCOPED_FRAGMENT_TOKENS = new Set<string>([...SERVER_LANGS, ...CLIENT_FRAMEWORKS, ...CONCERN_TOKENS]);

interface ServerMeta {
  displayName: string;
  install: string;
  codegenCommand: string;
  /** The command that writes THIS port's api docs — `mvn metaobjects:docs`, `metaobjects
   *  docs`, `dotnet meta docs`, `meta docs`. Named per server because the always-on
   *  pointer tells a reader to run it, and a pointer naming a command the stack does not
   *  have is worse than no pointer. */
  docsCommand: string;
}

function readServerMeta(contentRoot: string, server: string): ServerMeta | undefined {
  const p = join(contentRoot, "servers", `${server}.meta.json`);
  if (!existsSync(p)) return undefined;
  return JSON.parse(readFileSync(p, "utf8")) as ServerMeta;
}

function stackLine(
  contentRoot: string,
  stack: Stack,
): { line: string; codegenCommand: string; docsCommand: string } {
  const primary = stack.servers[0];
  const meta = primary ? readServerMeta(contentRoot, primary) : undefined;
  const serverPart = stack.servers.length ? stack.servers.join(", ") + " server" : "no server";
  const clientPart = stack.clients.length ? stack.clients.join(", ") + " client" : "no client";
  return {
    // Describe only what the stack actually declares — never assert a migration
    // binding (the tool states invariants; the project states bindings). The
    // "schema + migrations are metadata-derived" invariant lives in the template
    // principle, and the always-installed metaobjects-verify/migration reference
    // fragment carries the project-agnostic how. See issue #1.
    line: `Stack: ${serverPart}, ${clientPart}.`,
    codegenCommand: meta ? meta.codegenCommand : "meta gen",
    docsCommand: meta ? meta.docsCommand : "meta docs",
  };
}

/**
 * True when this stack runs the Node `meta` toolchain over a `metaobjects.config.ts`.
 *
 * This is the condition for the `agent/` docs surface EXISTING AT ALL: `meta docs` gates
 * those three pages on a loadable gen config, because the physical names, the dialect and
 * the view dispatch all come from it. A TypeScript server has one; so does any stack
 * declaring a web CLIENT, because the React/TanStack tiers are generated by `meta gen`
 * whatever the backend is. A port-only stack (java alone, python alone) has none, and for
 * it the pointer must name only the one file its own docs command writes.
 *
 * The pointer landed verbatim in every stack before this existed, so a Python project was
 * told to read four files that cannot exist and to run a command that cannot make them —
 * on the one page an agent is told to trust.
 */
function hasNodeDocsSurface(stack: Stack): boolean {
  return stack.servers.includes("typescript") || stack.clients.length > 0;
}

/**
 * Substitute `{{var}}` and the two section forms `{{#name}}…{{/name}}` (render when the
 * flag is true) and `{{^name}}…{{/name}}` (render when it is false).
 *
 * Sections do NOT nest — one pass, non-greedy to the matching close tag — which is all the
 * always-on template needs and keeps the failure mode of a mis-typed tag loud. An unknown
 * variable or section name THROWS, deliberately: a silently empty substitution in a file
 * an agent is told to trust is the failure this whole surface exists to prevent.
 */
function applyTemplate(
  tpl: string,
  vars: Record<string, string>,
  sections: Record<string, boolean>,
): string {
  const resolved = tpl.replace(
    /\{\{([#^])(\w+)\}\}\n?([\s\S]*?)\{\{\/\2\}\}\n?/g,
    (_m, sigil: string, name: string, body: string) => {
      if (!(name in sections)) {
        throw new Error(`agent-context: unknown template section {{${sigil}${name}}}`);
      }
      // `#` shows its body when the flag is true, `^` when it is false.
      const shownWhen = sigil === "#";
      return sections[name] === shownWhen ? body : "";
    },
  );
  return resolved.replace(/\{\{(\w+)\}\}/g, (_m, k: string) => {
    if (!(k in vars)) throw new Error(`agent-context: unknown template variable {{${k}}}`);
    return vars[k]!;
  });
}

/** Assemble the consumer files for a resolved stack. Pure given the content tree. */
export function assemble(opts: { contentRoot: string; stack: Stack }): AssembledFile[] {
  const { contentRoot, stack } = opts;
  const out: AssembledFile[] = [];

  // 1. Always-on (AGENTS.md + CLAUDE.md, identical contents).
  const tpl = readFileSync(join(contentRoot, "templates", "always-on.md.mustache"), "utf8");
  const { line, codegenCommand, docsCommand } = stackLine(contentRoot, stack);
  const alwaysOn = applyTemplate(
    tpl,
    { stackLine: line, codegenCommand, docsCommand },
    { nodeDocsSurface: hasNodeDocsSurface(stack) },
  );
  out.push({ path: ".metaobjects/AGENTS.md", contents: alwaysOn });
  out.push({ path: ".metaobjects/CLAUDE.md", contents: alwaysOn });

  // 2. Skills: body + only the references whose token is in the stack.
  for (const skill of SKILL_NAMES) {
    const skillDir = join(contentRoot, "skills", skill);
    const body = readFileSync(join(skillDir, "SKILL.md"), "utf8");
    out.push({ path: `.claude/skills/${skill}/SKILL.md`, contents: body });

    const refDir = join(skillDir, "references");
    if (existsSync(refDir) && statSync(refDir).isDirectory()) {
      // Stack-scoped: a language/framework/concern fragment installs only when its
      // token is in the resolved stack (Stack.tokens = servers ∪ clients ∪ concerns
      // ∪ {migration}). Non-scoped fragments (e.g. capability-checklist) are
      // universal and always install. Keeps each skill's references/ to what the
      // project actually uses, so the SKILL.md "read every references/*.md" footer
      // stays accurate.
      const refs = readdirSync(refDir)
        .filter((f) => f.endsWith(".md"))
        .map((f) => f.replace(/\.md$/, ""))
        .sort();
      for (const token of refs) {
        if (SCOPED_FRAGMENT_TOKENS.has(token) && !stack.tokens.has(token)) continue;
        out.push({
          path: `.claude/skills/${skill}/references/${token}.md`,
          contents: readFileSync(join(refDir, `${token}.md`), "utf8"),
        });
      }
    }
  }

  // Stable order: by path.
  out.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return out;
}
