import { createHash } from "node:crypto";
import type { AssembledFile, Stack } from "./types.js";

/** Consumer-relative path of the sidecar manifest that tracks scaffolded files. */
export const AGENT_CONTEXT_MANIFEST_PATH = ".metaobjects/.agent-context.json";

export interface Manifest {
  version: 1;
  /**
   * The MetaObjects version that last scaffolded this agent context. Used to nudge
   * a re-scaffold when the installed version moves ahead (the skills/docs ship with
   * the package, so an upgrade can leave the copied-in context stale). Optional for
   * back-compat with manifests written before version tracking existed.
   */
  generatedBy?: string;
  servers: string[];
  clients: string[];
  /** consumer-relative path → sha256 of the contents as last scaffolded. */
  files: Record<string, string>;
}

export function hashContents(s: string): string {
  return createHash("sha256").update(s, "utf8").digest("hex");
}

export interface ScaffoldDecision {
  /** files to (over)write at their own path: new, or unmodified-since-last-scaffold. */
  writes: { path: string; contents: string }[];
  /** hand-edited files: write the fresh contents to `<path>.new`, leave the original. */
  conflicts: { path: string; newPath: string; contents: string }[];
  /** the manifest to persist after writing. */
  manifest: Manifest;
  /** paths the prior manifest tracked that are no longer assembled (e.g. stack shrank) — reported, never auto-deleted. */
  removed: string[];
}

/**
 * Decide what to write for a (re-)scaffold. Pure: filesystem access is via the
 * `readCurrent` callback (returns the on-disk contents, or undefined if absent).
 * A file is safe to overwrite iff it is absent, or its on-disk hash still equals
 * the hash the prior manifest recorded (i.e. the user hasn't hand-edited it).
 */
export function planScaffold(opts: {
  stack: Stack;
  assembled: AssembledFile[];
  prior: Manifest | undefined;
  readCurrent: (path: string) => string | undefined;
  /** The MetaObjects version doing the scaffold — stamped into the manifest. */
  generatedBy: string;
}): ScaffoldDecision {
  const { stack, assembled, prior, readCurrent, generatedBy } = opts;
  const writes: ScaffoldDecision["writes"] = [];
  const conflicts: ScaffoldDecision["conflicts"] = [];
  const files: Record<string, string> = {};

  for (const f of assembled) {
    files[f.path] = hashContents(f.contents);
    const current = readCurrent(f.path);
    if (current === undefined) {
      writes.push({ path: f.path, contents: f.contents });
      continue;
    }
    const priorHash = prior?.files[f.path];
    if (priorHash !== undefined && hashContents(current) === priorHash) {
      writes.push({ path: f.path, contents: f.contents }); // unmodified → refresh to latest
    } else {
      conflicts.push({ path: f.path, newPath: `${f.path}.new`, contents: f.contents });
    }
  }

  const assembledPaths = new Set(assembled.map((f) => f.path));
  const removed = prior ? Object.keys(prior.files).filter((p) => !assembledPaths.has(p)) : [];

  return {
    writes,
    conflicts,
    manifest: { version: 1, generatedBy, servers: stack.servers, clients: stack.clients, files },
    removed,
  };
}

/**
 * A one-line nudge if the scaffolded agent context predates the installed MetaObjects
 * (so `gen`/`verify` can remind the user to refresh the skills after an upgrade), or
 * `null` when there is nothing to say — no agent context scaffolded, or it is in sync.
 * Advisory only: never throws, never blocks, never writes.
 */
export function agentContextStaleness(opts: {
  manifest: Manifest | undefined;
  currentVersion: string;
}): string | null {
  const { manifest, currentVersion } = opts;
  if (manifest === undefined) return null; // no agent context here → nothing to nudge
  // Exact-equality on purpose: ANY drift nudges (a re-scaffold is cheap + idempotent).
  // Don't "fix" this into a semver compare — a prerelease/build-metadata difference is
  // still a reason to refresh, and the nudge is advisory, never a gate.
  if (manifest.generatedBy === currentVersion) return null; // in sync
  const from = manifest.generatedBy ?? "an older MetaObjects";
  return (
    `MetaObjects agent context was generated by ${from}; you're on ${currentVersion}. ` +
    `Re-run 'meta init --docs-only --refresh-docs' to refresh the .claude/skills docs.`
  );
}
