package com.metaobjects.agentcontext;

import java.io.InputStream;
import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * Sidecar manifest and staleness advisor for the agent-context writer.
 *
 * <p>Scaffold planning has moved to the {@code meta} CLI
 * ({@code npx meta agent-docs --server java}). This class retains the READ-ONLY
 * staleness advisory ({@link #staleness}/{@link #installedVersion}) called by
 * {@code AbstractMetaDataMojo.warnIfAgentContextStale()}.
 */
public final class AgentContextScaffold {

    /** Consumer-relative path of the sidecar manifest that tracks scaffolded files. */
    public static final String MANIFEST_PATH = ".metaobjects/.agent-context.json";

    /**
     * Safe fallback when the installed version can't be resolved from the classpath
     * (mirrors the TS reference's {@code "0.0.0"} fallback). Compares unequal to any
     * real stamped version, so a real {@code generatedBy} always wins the equality
     * check — the nudge stays advisory, never spuriously asserting "in sync".
     */
    public static final String UNKNOWN_VERSION = "0.0.0";

    /** Maven group of the artifact carrying this class — used to find {@code pom.properties}. */
    private static final String MAVEN_GROUP_ID = "com.metaobjects";
    /** Maven artifact carrying this class — used to find {@code pom.properties}. */
    private static final String MAVEN_ARTIFACT_ID = "metaobjects-metadata";

    private AgentContextScaffold() {
    }

    /**
     * Tracks what the assembler last wrote, so re-runs can detect hand-edits.
     *
     * <p>{@code generatedBy} is the MetaObjects version that last scaffolded this agent
     * context. It is stamped so {@code gen}/{@code verify} can nudge a re-scaffold when
     * the installed version moves ahead (the skills/docs ship with the artifact, so an
     * upgrade can leave the copied-in context stale). It may be {@code null} for
     * back-compat with manifests written before version tracking existed (and for
     * cross-read manifests written by another port). Serialized as {@code "generatedBy"}
     * — the SAME key as the TS reference — so a polyglot repo can cross-read it.
     */
    public record Manifest(int version, String generatedBy, List<String> servers,
                           List<String> clients, Map<String, String> files) {
    }

    /**
     * A one-line nudge if the scaffolded agent context predates the installed MetaObjects
     * (so {@code gen}/{@code verify} can remind the user to refresh the skills after an
     * upgrade), or {@code null} when there is nothing to say — no agent context
     * scaffolded, or it is in sync.
     *
     * <p>Pure + advisory: never throws, never blocks, never writes. Direct port of the TS
     * {@code agentContextStaleness}. The equality check is EXACT on purpose — any drift
     * (including a prerelease/build-metadata difference) nudges, because a re-scaffold is
     * cheap + idempotent. Don't "fix" this into a semver compare.
     *
     * @param manifest       the parsed prior manifest, or {@code null} if none on disk.
     * @param currentVersion the installed MetaObjects version (see {@link #installedVersion()}).
     * @return the nudge message, or {@code null} when nothing needs saying.
     */
    public static String staleness(Manifest manifest, String currentVersion) {
        if (manifest == null) {
            return null; // no agent context here → nothing to nudge
        }
        if (currentVersion.equals(manifest.generatedBy())) {
            return null; // in sync
        }
        String from = manifest.generatedBy() != null ? manifest.generatedBy() : "an older MetaObjects";
        return "MetaObjects agent context was generated by " + from + "; you're on "
                + currentVersion + ". Run 'npx meta agent-docs --server java' to refresh "
                + "the .claude/skills docs.";
    }

    /**
     * The installed MetaObjects version, resolved the idiomatic Maven way: read
     * {@code /META-INF/maven/com.metaobjects/metaobjects-metadata/pom.properties} from the
     * classpath (Maven stamps this into the built jar). Falls back to
     * {@link #UNKNOWN_VERSION} when it can't be resolved (e.g. running from an exploded
     * classes dir in a test/IDE) — mirroring the TS reference's {@code "0.0.0"} fallback.
     * Never throws.
     *
     * @return the installed version, or {@link #UNKNOWN_VERSION}.
     */
    public static String installedVersion() {
        String resource = "/META-INF/maven/" + MAVEN_GROUP_ID + "/" + MAVEN_ARTIFACT_ID
                + "/pom.properties";
        try (InputStream in = AgentContextScaffold.class.getResourceAsStream(resource)) {
            if (in == null) {
                return UNKNOWN_VERSION;
            }
            Properties props = new Properties();
            props.load(in);
            String v = props.getProperty("version");
            return (v == null || v.isBlank()) ? UNKNOWN_VERSION : v.trim();
        } catch (Exception e) {
            return UNKNOWN_VERSION;
        }
    }
}
