-- @generated by @metaobjectsdev/integration-tests — DO NOT EDIT.
-- Canonical persistence-conformance schema (Postgres).
-- Produced by TypeScript from canonical/meta.fitness.json; every port's
-- query-scenario runner executes this file verbatim to provision its test DB.
-- Regenerate: `bun run gen:schema` in this package. Drift-checked by
-- schema-artifact.test.ts (CI fails if this file diverges from metadata).

CREATE TABLE "programs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  "priceCents" BIGINT NOT NULL,
  "status" TEXT NOT NULL,
  "createdAt" TIMESTAMP NOT NULL,
  CONSTRAINT "programs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "programs_status_chk" CHECK ("status" IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE "weeks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "programId" BIGINT NOT NULL,
  "label" VARCHAR(80),
  "durationMinutes" INTEGER NOT NULL,
  CONSTRAINT "weeks_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "measurements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tempC" REAL NOT NULL,
  "massKg" DOUBLE PRECISION NOT NULL,
  "preciseKg" NUMERIC(9,4) NOT NULL,
  CONSTRAINT "measurements_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "assets" (
  "id" UUID DEFAULT gen_random_uuid() NOT NULL,
  "ownerId" UUID NOT NULL,
  "externalId" UUID,
  "payload" JSONB,
  "recordedAt" TIMESTAMPTZ NOT NULL,
  "observedAt" TIMESTAMP NOT NULL,
  "asOfDate" DATE NOT NULL,
  "atTime" TIME NOT NULL,
  CONSTRAINT "assets_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "tags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(80) NOT NULL,
  CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "post_tags" (
  "postId" BIGINT NOT NULL,
  "tagId" BIGINT NOT NULL,
  CONSTRAINT "post_tags_pkey" PRIMARY KEY ("postId", "tagId")
);

CREATE TABLE "people" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(80) NOT NULL,
  CONSTRAINT "people_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "follows" (
  "followerId" BIGINT NOT NULL,
  "followeeId" BIGINT NOT NULL,
  CONSTRAINT "follows_pkey" PRIMARY KEY ("followerId", "followeeId")
);

CREATE TABLE "friendships" (
  "personAId" BIGINT NOT NULL,
  "personBId" BIGINT NOT NULL,
  CONSTRAINT "friendships_pkey" PRIMARY KEY ("personAId", "personBId")
);

CREATE TABLE "auths" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" TEXT,
  "reference" VARCHAR(80) NOT NULL,
  "quantity" INTEGER,
  "copayAmount" NUMERIC(10,2),
  "approver" VARCHAR(80),
  CONSTRAINT "auths_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "auths_type_chk" CHECK ("type" IN ('Bridge', 'Copay', 'PriorAuth'))
);

CREATE TABLE "all_types" (
  "id" UUID DEFAULT gen_random_uuid() NOT NULL,
  "sVal" VARCHAR(200) NOT NULL,
  "iVal" INTEGER NOT NULL,
  "lVal" BIGINT NOT NULL,
  "dVal" DOUBLE PRECISION NOT NULL,
  "fVal" REAL NOT NULL,
  "decVal" NUMERIC(18,6) NOT NULL,
  "bVal" BOOLEAN NOT NULL,
  "dateVal" DATE NOT NULL,
  "timeVal" TIME NOT NULL,
  "tsVal" TIMESTAMP NOT NULL,
  "tsTzVal" TIMESTAMPTZ NOT NULL,
  "moneyVal" BIGINT NOT NULL,
  "enumVal" TEXT NOT NULL,
  "uuidVal" UUID NOT NULL,
  "settings" JSONB,
  CONSTRAINT "all_types_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "all_types_enumVal_chk" CHECK ("enumVal" IN ('LOW', 'MEDIUM', 'HIGH'))
);

CREATE UNIQUE INDEX "byTitle" ON "programs" ("title");

ALTER TABLE "weeks" ADD CONSTRAINT "weeks_programId_fk" FOREIGN KEY ("programId") REFERENCES "programs" ("id");

ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_postId_fk" FOREIGN KEY ("postId") REFERENCES "posts" ("id");

ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tagId_fk" FOREIGN KEY ("tagId") REFERENCES "tags" ("id");

ALTER TABLE "follows" ADD CONSTRAINT "follows_followerId_fk" FOREIGN KEY ("followerId") REFERENCES "people" ("id");

ALTER TABLE "follows" ADD CONSTRAINT "follows_followeeId_fk" FOREIGN KEY ("followeeId") REFERENCES "people" ("id");

ALTER TABLE "friendships" ADD CONSTRAINT "friendships_personAId_fk" FOREIGN KEY ("personAId") REFERENCES "people" ("id");

ALTER TABLE "friendships" ADD CONSTRAINT "friendships_personBId_fk" FOREIGN KEY ("personBId") REFERENCES "people" ("id");

CREATE VIEW "v_program" AS
SELECT
  "id" AS "id",
  "title" AS "title",
  "status" AS "status"
FROM "programs";

CREATE VIEW "v_program_stat" AS
SELECT
  "id" AS "programId",
  (SELECT count(t."id") FROM "weeks" t WHERE t."programId" = "programs"."id") AS "weekCount",
  (SELECT sum(t."durationMinutes") FROM "weeks" t WHERE t."programId" = "programs"."id") AS "totalMinutes",
  (SELECT avg(t."durationMinutes") FROM "weeks" t WHERE t."programId" = "programs"."id") AS "avgMinutes",
  (SELECT min(t."durationMinutes") FROM "weeks" t WHERE t."programId" = "programs"."id") AS "minMinutes",
  (SELECT max(t."durationMinutes") FROM "weeks" t WHERE t."programId" = "programs"."id") AS "maxMinutes"
FROM "programs";
