-- @generated by @metaobjectsdev/integration-tests — DO NOT EDIT.
-- Canonical persistence-conformance schema (Postgres).
-- Produced by TypeScript from canonical/meta.fitness.json; every port's
-- query-scenario runner executes this file verbatim to provision its test DB.
-- Regenerate: `bun run gen:schema` in this package. Drift-checked by
-- schema-artifact.test.ts (CI fails if this file diverges from metadata).

CREATE TABLE "programs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  "priceCents" BIGINT NOT NULL,
  "status" TEXT NOT NULL,
  "created_ts" TIMESTAMP NOT NULL,
  CONSTRAINT "programs_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "programs_status_chk" CHECK ("status" IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE "weeks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "programId" BIGINT NOT NULL,
  "label" VARCHAR(80),
  "durationMinutes" INTEGER NOT NULL,
  CONSTRAINT "weeks_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "nodes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "label" VARCHAR(80) NOT NULL,
  "parentId" BIGINT,
  CONSTRAINT "nodes_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "measurements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tempC" REAL NOT NULL,
  "massKg" DOUBLE PRECISION NOT NULL,
  "preciseKg" NUMERIC(9,4) NOT NULL,
  CONSTRAINT "measurements_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "assets" (
  "id" UUID DEFAULT gen_random_uuid() NOT NULL,
  "ownerId" UUID NOT NULL,
  "externalId" UUID,
  "payload" JSONB,
  "recordedAt" TIMESTAMPTZ NOT NULL,
  "observedAt" TIMESTAMP NOT NULL,
  "asOfDate" DATE NOT NULL,
  "atTime" TIME NOT NULL,
  CONSTRAINT "assets_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  CONSTRAINT "posts_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "tags" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(80) NOT NULL,
  CONSTRAINT "tags_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "post_tags" (
  "postId" BIGINT NOT NULL,
  "tagId" BIGINT NOT NULL,
  CONSTRAINT "post_tags_pkey" PRIMARY KEY ("postId", "tagId")
);

CREATE TABLE "people" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" VARCHAR(80) NOT NULL,
  CONSTRAINT "people_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "follows" (
  "followerId" BIGINT NOT NULL,
  "followeeId" BIGINT NOT NULL,
  CONSTRAINT "follows_pkey" PRIMARY KEY ("followerId", "followeeId")
);

CREATE TABLE "friendships" (
  "personAId" BIGINT NOT NULL,
  "personBId" BIGINT NOT NULL,
  CONSTRAINT "friendships_pkey" PRIMARY KEY ("personAId", "personBId")
);

CREATE TABLE "auths" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" TEXT,
  "reference" VARCHAR(80) NOT NULL,
  "quantity" INTEGER,
  "copayAmount" NUMERIC(10,2),
  "approver" VARCHAR(80),
  "urgency" VARCHAR(16),
  CONSTRAINT "auths_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "auths_type_chk" CHECK ("type" IN ('Bridge', 'Copay', 'PriorAuth', 'Referral'))
);

CREATE TABLE "post_referrals" (
  "postId" BIGINT NOT NULL,
  "referralId" BIGINT NOT NULL,
  CONSTRAINT "post_referrals_pkey" PRIMARY KEY ("postId", "referralId")
);

CREATE TABLE "all_types" (
  "id" UUID DEFAULT gen_random_uuid() NOT NULL,
  "sVal" VARCHAR(200) NOT NULL,
  "iVal" INTEGER NOT NULL,
  "lVal" BIGINT NOT NULL,
  "dVal" DOUBLE PRECISION NOT NULL,
  "fVal" REAL NOT NULL,
  "decVal" NUMERIC(18,6) NOT NULL,
  "bVal" BOOLEAN NOT NULL,
  "dateVal" DATE NOT NULL,
  "timeVal" TIME NOT NULL,
  "tsVal" TIMESTAMP NOT NULL,
  "tsTzVal" TIMESTAMPTZ NOT NULL,
  "moneyVal" BIGINT NOT NULL,
  "enumVal" TEXT NOT NULL,
  "intEnumVal" INTEGER,
  "uuidVal" UUID NOT NULL,
  "uriVal" TEXT NOT NULL,
  "inetVal" INET NOT NULL,
  "inet6Val" INET NOT NULL,
  "settings" JSONB,
  "labels" JSONB,
  CONSTRAINT "all_types_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "all_types_enumVal_chk" CHECK ("enumVal" IN ('LOW', 'MEDIUM', 'HIGH')),
  CONSTRAINT "all_types_intEnumVal_chk" CHECK ("intEnumVal" IN (0, 5, 9))
);

CREATE UNIQUE INDEX "byTitle" ON "programs" ("title");

CREATE INDEX "idx_programs_title_status" ON "programs" ("title", "status");

ALTER TABLE "weeks" ADD CONSTRAINT "weeks_programId_fk" FOREIGN KEY ("programId") REFERENCES "programs" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "nodes" ADD CONSTRAINT "nodes_parentId_fk" FOREIGN KEY ("parentId") REFERENCES "nodes" ("id");

ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_postId_fk" FOREIGN KEY ("postId") REFERENCES "posts" ("id");

ALTER TABLE "post_tags" ADD CONSTRAINT "post_tags_tagId_fk" FOREIGN KEY ("tagId") REFERENCES "tags" ("id");

ALTER TABLE "follows" ADD CONSTRAINT "follows_followerId_fk" FOREIGN KEY ("followerId") REFERENCES "people" ("id");

ALTER TABLE "follows" ADD CONSTRAINT "follows_followeeId_fk" FOREIGN KEY ("followeeId") REFERENCES "people" ("id");

ALTER TABLE "friendships" ADD CONSTRAINT "friendships_personAId_fk" FOREIGN KEY ("personAId") REFERENCES "people" ("id");

ALTER TABLE "friendships" ADD CONSTRAINT "friendships_personBId_fk" FOREIGN KEY ("personBId") REFERENCES "people" ("id");

ALTER TABLE "post_referrals" ADD CONSTRAINT "post_referrals_postId_fk" FOREIGN KEY ("postId") REFERENCES "posts" ("id");

ALTER TABLE "post_referrals" ADD CONSTRAINT "post_referrals_referralId_fk" FOREIGN KEY ("referralId") REFERENCES "auths" ("id");

CREATE VIEW "v_program" AS
  SELECT
    p.id AS id,
    p.title AS title,
    p.status AS status
  FROM programs p;
COMMENT ON VIEW "v_program" IS 'metaobjects:v1:sha256:0338b5e7329eb5d951e6d2311bde8d4c95d71204cac6aa895a903d7b7b5cbab4';

CREATE VIEW "v_program_stat" AS
  SELECT
    p.id AS "programId",
    COUNT(DISTINCT w.id) AS "weekCount",
    SUM(w."durationMinutes") AS "totalMinutes",
    AVG(w."durationMinutes") AS "avgMinutes",
    MIN(w."durationMinutes") AS "minMinutes",
    MAX(w."durationMinutes") AS "maxMinutes"
  FROM programs p
  LEFT OUTER JOIN weeks w ON w."programId" = p.id
  GROUP BY p.id;
COMMENT ON VIEW "v_program_stat" IS 'metaobjects:v1:sha256:9120c9f8899e257b52a087c4841b8e55f679d7f9c7a6e58d8823912855f2ab57';

CREATE VIEW "v_program_minutes" AS
  SELECT
    w."programId" AS "program",
    p."title" AS "programTitle",
    COUNT(w."id") AS "weeks",
    COUNT(w."id") FILTER (WHERE w."durationMinutes" >= 60) AS "longWeeks",
    COUNT(DISTINCT w."label") AS "labels",
    COUNT(DISTINCT (w."programId", w."durationMinutes")) FILTER (WHERE w."programId" IS NOT NULL AND w."durationMinutes" IS NOT NULL) AS "slots",
    CAST(SUM(w."durationMinutes") AS BIGINT) AS "totalMinutes",
    AVG(w."durationMinutes") AS "avgMinutes",
    MIN(w."durationMinutes") AS "minMinutes",
    MAX(w."durationMinutes") AS "maxMinutes",
    CAST(COUNT(w."id") FILTER (WHERE w."durationMinutes" >= 60) AS NUMERIC) / NULLIF(COUNT(w."id"), 0) AS "longShare"
  FROM "weeks" w
  INNER JOIN "programs" p ON p."id" = w."programId"
  GROUP BY w."programId", p."title";
COMMENT ON VIEW "v_program_minutes" IS 'metaobjects:v1:sha256:06b54e731e0221acab4b6e0a7cb7f5914662eff39af6ca57031a7df69cbbec93';

CREATE VIEW "v_fitness_totals" AS
  SELECT
    COUNT(w."id") AS "weeks",
    CAST(SUM(w."durationMinutes") AS BIGINT) AS "totalMinutes",
    CAST(COUNT(w."id") FILTER (WHERE w."durationMinutes" >= 60) AS NUMERIC) / NULLIF(COUNT(w."id"), 0) AS "longShare"
  FROM "weeks" w;
COMMENT ON VIEW "v_fitness_totals" IS 'metaobjects:v1:sha256:92ac554bcb44ee0bc7f3ddab40cf64c52fd964865dfe155104621babdd766e80';

CREATE VIEW "v_programs_by_month" AS
  SELECT
    CAST(date_trunc('month', p."created_ts") AS DATE) AS "createdAtMonth",
    p."status" AS "status",
    COUNT(p."id") AS "programs",
    CAST(SUM(p."priceCents") FILTER (WHERE p."status" = 'PUBLISHED') AS BIGINT) AS "listValue"
  FROM "programs" p
  GROUP BY CAST(date_trunc('month', p."created_ts") AS DATE), p."status";
COMMENT ON VIEW "v_programs_by_month" IS 'metaobjects:v1:sha256:8310fbae2f38c07296f2c22297c5e83ef2fbd12faaed5f90bd4211dbc8b45935';

CREATE VIEW "v_programs_by_week" AS
  SELECT
    CAST(date_trunc('week', p."created_ts") AS DATE) AS "createdAtWeek",
    COUNT(p."id") AS "programs"
  FROM "programs" p
  WHERE p."status" = 'PUBLISHED'
  GROUP BY CAST(date_trunc('week', p."created_ts") AS DATE);
COMMENT ON VIEW "v_programs_by_week" IS 'metaobjects:v1:sha256:656478aaf3e58443a6123f4f016bd61fbebfe2b0122175260155fb92d754e5ae';

CREATE VIEW "v_recent_programs" AS
  SELECT
    COUNT(p."id") AS "programs"
  FROM "programs" p
  WHERE p."created_ts" >= ((now() AT TIME ZONE 'UTC') - INTERVAL 'P30D');
COMMENT ON VIEW "v_recent_programs" IS 'metaobjects:v1:sha256:9e675bb71fe4a3c74f06f5db65d7908e246a59c2a8fc062fc2c899948841eccc';

CREATE VIEW "v_asset_activity" AS
  SELECT
    date_trunc('hour', a."recordedAt", 'UTC') AS "recordedAtHour",
    CAST(date_trunc('week', CAST(a."asOfDate" AS TIMESTAMP)) AS DATE) AS "asOfDateWeek",
    COUNT(a."id") AS "assets"
  FROM "assets" a
  GROUP BY date_trunc('hour', a."recordedAt", 'UTC'), CAST(date_trunc('week', CAST(a."asOfDate" AS TIMESTAMP)) AS DATE);
COMMENT ON VIEW "v_asset_activity" IS 'metaobjects:v1:sha256:02b68a9ec0c67e11c6e505a47591c24e8dece737a46161549167c2cafece0a26';
