-- @generated by @metaobjectsdev/integration-tests — DO NOT EDIT.
-- Canonical persistence-conformance schema (SQLite).
-- Produced by TypeScript from canonical/meta.fitness.json; every port's
-- query-scenario runner executes this file verbatim to provision its test DB.
-- Regenerate: `bun run gen:schema` in this package. Drift-checked by
-- schema-artifact.test.ts (CI fails if this file diverges from metadata).

CREATE TABLE "programs" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "title" VARCHAR(200) NOT NULL,
  "priceCents" INTEGER NOT NULL,
  "status" TEXT NOT NULL,
  "created_ts" TEXT NOT NULL,
  CONSTRAINT "programs_status_chk" CHECK ("status" IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE TABLE "weeks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "programId" INTEGER NOT NULL,
  "label" VARCHAR(80),
  "durationMinutes" INTEGER NOT NULL,
  FOREIGN KEY ("programId") REFERENCES "programs" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE "nodes" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "label" VARCHAR(80) NOT NULL,
  "parentId" INTEGER,
  FOREIGN KEY ("parentId") REFERENCES "nodes" ("id")
);

CREATE TABLE "measurements" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "tempC" REAL NOT NULL,
  "massKg" REAL NOT NULL,
  "preciseKg" NUMERIC(9,4) NOT NULL
);

CREATE TABLE "assets" (
  "id" TEXT PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(16)))),
  "ownerId" TEXT NOT NULL,
  "externalId" TEXT,
  "payload" TEXT,
  "recordedAt" TEXT NOT NULL,
  "observedAt" TEXT NOT NULL,
  "asOfDate" TEXT NOT NULL,
  "atTime" TEXT NOT NULL
);

CREATE TABLE "posts" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "title" VARCHAR(200) NOT NULL
);

CREATE TABLE "tags" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" VARCHAR(80) NOT NULL
);

CREATE TABLE "post_tags" (
  "postId" INTEGER NOT NULL,
  "tagId" INTEGER NOT NULL,
  PRIMARY KEY ("postId", "tagId"),
  FOREIGN KEY ("postId") REFERENCES "posts" ("id"),
  FOREIGN KEY ("tagId") REFERENCES "tags" ("id")
);

CREATE TABLE "people" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "name" VARCHAR(80) NOT NULL
);

CREATE TABLE "follows" (
  "followerId" INTEGER NOT NULL,
  "followeeId" INTEGER NOT NULL,
  PRIMARY KEY ("followerId", "followeeId"),
  FOREIGN KEY ("followerId") REFERENCES "people" ("id"),
  FOREIGN KEY ("followeeId") REFERENCES "people" ("id")
);

CREATE TABLE "friendships" (
  "personAId" INTEGER NOT NULL,
  "personBId" INTEGER NOT NULL,
  PRIMARY KEY ("personAId", "personBId"),
  FOREIGN KEY ("personAId") REFERENCES "people" ("id"),
  FOREIGN KEY ("personBId") REFERENCES "people" ("id")
);

CREATE TABLE "auths" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  "type" TEXT,
  "reference" VARCHAR(80) NOT NULL,
  "quantity" INTEGER,
  "copayAmount" NUMERIC(10,2),
  "approver" VARCHAR(80),
  "urgency" VARCHAR(16),
  CONSTRAINT "auths_type_chk" CHECK ("type" IN ('Bridge', 'Copay', 'PriorAuth', 'Referral'))
);

CREATE TABLE "post_referrals" (
  "postId" INTEGER NOT NULL,
  "referralId" INTEGER NOT NULL,
  PRIMARY KEY ("postId", "referralId"),
  FOREIGN KEY ("postId") REFERENCES "posts" ("id"),
  FOREIGN KEY ("referralId") REFERENCES "auths" ("id")
);

CREATE TABLE "all_types" (
  "id" TEXT PRIMARY KEY NOT NULL DEFAULT (lower(hex(randomblob(16)))),
  "sVal" VARCHAR(200) NOT NULL,
  "iVal" INTEGER NOT NULL,
  "lVal" INTEGER NOT NULL,
  "dVal" REAL NOT NULL,
  "fVal" REAL NOT NULL,
  "decVal" NUMERIC(18,6) NOT NULL,
  "bVal" INTEGER NOT NULL,
  "dateVal" TEXT NOT NULL,
  "timeVal" TEXT NOT NULL,
  "tsVal" TEXT NOT NULL,
  "tsTzVal" TEXT NOT NULL,
  "moneyVal" INTEGER NOT NULL,
  "enumVal" TEXT NOT NULL,
  "intEnumVal" INTEGER,
  "uuidVal" TEXT NOT NULL,
  "uriVal" TEXT NOT NULL,
  "inetVal" TEXT NOT NULL,
  "inet6Val" TEXT NOT NULL,
  "settings" TEXT,
  "labels" TEXT,
  CONSTRAINT "all_types_enumVal_chk" CHECK ("enumVal" IN ('LOW', 'MEDIUM', 'HIGH')),
  CONSTRAINT "all_types_intEnumVal_chk" CHECK ("intEnumVal" IN (0, 5, 9))
);

CREATE UNIQUE INDEX "byTitle" ON "programs" ("title");

CREATE INDEX "idx_programs_title_status" ON "programs" ("title", "status");

CREATE VIEW "v_program" AS
  SELECT
    p.id AS id,
    p.title AS title,
    p.status AS status
  FROM programs p;

CREATE VIEW "v_program_stat" AS
  SELECT
    p.id AS "programId",
    COUNT(DISTINCT w.id) AS "weekCount",
    SUM(w."durationMinutes") AS "totalMinutes",
    AVG(w."durationMinutes") AS "avgMinutes",
    MIN(w."durationMinutes") AS "minMinutes",
    MAX(w."durationMinutes") AS "maxMinutes"
  FROM programs p
  LEFT OUTER JOIN weeks w ON w."programId" = p.id
  GROUP BY p.id;

CREATE VIEW "v_program_minutes" AS
  SELECT
    w."programId" AS "program",
    p."title" AS "programTitle",
    COUNT(w."id") AS "weeks",
    COUNT(CASE WHEN w."durationMinutes" >= 60 THEN w."id" END) AS "longWeeks",
    COUNT(DISTINCT w."label") AS "labels",
    COUNT(DISTINCT CASE WHEN w."programId" IS NOT NULL AND w."durationMinutes" IS NOT NULL THEN json_array(w."programId", w."durationMinutes") END) AS "slots",
    SUM(w."durationMinutes") AS "totalMinutes",
    AVG(w."durationMinutes") AS "avgMinutes",
    MIN(w."durationMinutes") AS "minMinutes",
    MAX(w."durationMinutes") AS "maxMinutes",
    CAST(COUNT(CASE WHEN w."durationMinutes" >= 60 THEN w."id" END) AS REAL) / NULLIF(COUNT(w."id"), 0) AS "longShare"
  FROM "weeks" w
  INNER JOIN "programs" p ON p."id" = w."programId"
  GROUP BY w."programId", p."title";

CREATE VIEW "v_fitness_totals" AS
  SELECT
    COUNT(w."id") AS "weeks",
    SUM(w."durationMinutes") AS "totalMinutes",
    CAST(COUNT(CASE WHEN w."durationMinutes" >= 60 THEN w."id" END) AS REAL) / NULLIF(COUNT(w."id"), 0) AS "longShare"
  FROM "weeks" w;

CREATE VIEW "v_programs_by_month" AS
  SELECT
    date(p."created_ts", 'start of month') AS "createdAtMonth",
    p."status" AS "status",
    COUNT(p."id") AS "programs",
    SUM(CASE WHEN p."status" = 'PUBLISHED' THEN p."priceCents" END) AS "listValue"
  FROM "programs" p
  GROUP BY date(p."created_ts", 'start of month'), p."status";

CREATE VIEW "v_programs_by_week" AS
  SELECT
    date(p."created_ts", 'weekday 0', '-6 days') AS "createdAtWeek",
    COUNT(p."id") AS "programs"
  FROM "programs" p
  WHERE p."status" = 'PUBLISHED'
  GROUP BY date(p."created_ts", 'weekday 0', '-6 days');

CREATE VIEW "v_recent_programs" AS
  SELECT
    COUNT(p."id") AS "programs"
  FROM "programs" p
  WHERE p."created_ts" >= strftime('%Y-%m-%dT%H:%M:%f', 'now', '-30 days');

CREATE VIEW "v_asset_activity" AS
  SELECT
    strftime('%Y-%m-%dT%H:00:00.000Z', a."recordedAt") AS "recordedAtHour",
    date(a."asOfDate", 'weekday 0', '-6 days') AS "asOfDateWeek",
    COUNT(a."id") AS "assets"
  FROM "assets" a
  GROUP BY strftime('%Y-%m-%dT%H:00:00.000Z', a."recordedAt"), date(a."asOfDate", 'weekday 0', '-6 days');

CREATE VIEW "v_program_roster" AS
  SELECT
    p."id" AS "programKey",
    p."title" AS "programTitle",
    COUNT(w."id") AS "weeks",
    SUM(w."durationMinutes") AS "totalMinutes",
    COALESCE(SUM(w."durationMinutes"), 0) AS "totalMinutesOrZero",
    CAST(COUNT(CASE WHEN w."durationMinutes" >= 60 THEN w."id" END) AS REAL) / NULLIF(COUNT(w."id"), 0) AS "longShare",
    COALESCE(CAST(COUNT(CASE WHEN w."durationMinutes" >= 60 THEN w."id" END) AS REAL) / NULLIF(COUNT(w."id"), 0), 0.0) AS "longShareOrZero"
  FROM "programs" p
  LEFT OUTER JOIN "weeks" w ON p."id" = w."programId"
  GROUP BY p."id", p."title";

CREATE VIEW "v_program_long_weeks" AS
  SELECT
    p."id" AS "programKey",
    COUNT(w."id") AS "weeks",
    COALESCE(SUM(w."durationMinutes"), 0) AS "totalMinutesOrZero"
  FROM "programs" p
  LEFT OUTER JOIN "weeks" w ON p."id" = w."programId" AND w."durationMinutes" >= 60
  GROUP BY p."id";

CREATE VIEW "v_fitness_totals_filled" AS
  SELECT
    COUNT(w."id") AS "weeks",
    COALESCE(SUM(w."durationMinutes"), 0) AS "totalMinutesOrZero",
    COALESCE(CAST(COUNT(CASE WHEN w."durationMinutes" >= 60 THEN w."id" END) AS REAL) / NULLIF(COUNT(w."id"), 0), 0.0) AS "longShareOrZero"
  FROM "weeks" w;
