#!/usr/bin/env bash
# One-time setup for the OPTIONAL self-contained registry in docker-compose.yml.
#
# Creates the registry owner account, mints a package-scoped token, and writes
# tools/prerelease/registry.env (gitignored). Skip this entirely if you already have a
# registry — just copy registry.env.example to registry.env and fill it in.
#
#   docker compose -f tools/prerelease/docker-compose.yml up -d
#   tools/prerelease/bootstrap.sh
#
# Re-running is safe: it reuses the account and mints a fresh token.
set -euo pipefail

HOST="${MO_REGISTRY_BASE:-http://localhost:3939}"
OWNER="${MO_REGISTRY_OWNER:-prerelease}"
PASS="${MO_REGISTRY_PASS:-PrereleaseDev1!}"
CONTAINER="${MO_REGISTRY_CONTAINER:-mo-prerelease-registry}"
HERE="$(cd "$(dirname "$0")" && pwd)"

# This script drives the compose container directly, so it only makes sense against the
# instance that compose file starts.
case "$HOST" in
  http://localhost:*|http://127.0.0.1:*) ;;
  *) echo "bootstrap.sh only manages the local compose instance; for an existing registry"  >&2
     echo "copy registry.env.example to registry.env and fill in your own values."          >&2
     exit 1 ;;
esac

echo "waiting for $HOST ..."
for _ in $(seq 1 60); do
  curl -fsS -o /dev/null "$HOST/" && break || sleep 1
done

if ! curl -fsS -o /dev/null -u "$OWNER:$PASS" "$HOST/api/v1/user" 2>/dev/null; then
  docker exec -u git "$CONTAINER" gitea admin user create \
    --username "$OWNER" --password "$PASS" --email "$OWNER@registry.invalid" \
    --admin --must-change-password=false >/dev/null
  echo "created registry owner '$OWNER'"
fi

TOKEN="$(curl -fsS -X POST -H 'Content-Type: application/json' -u "$OWNER:$PASS" \
  -d '{"name":"prerelease-'"$(date +%s)"'","scopes":["write:package","read:package"]}' \
  "$HOST/api/v1/users/$OWNER/tokens" | sed -n 's/.*"sha1":"\([^"]*\)".*/\1/p')"

[ -n "$TOKEN" ] || { echo "failed to mint a token" >&2; exit 1; }

cat > "$HERE/registry.env" <<EOF
# Generated by tools/prerelease/bootstrap.sh — gitignored, local only.
MO_REGISTRY_BASE=$HOST
MO_REGISTRY_OWNER=$OWNER
MO_REGISTRY_TOKEN=$TOKEN
EOF
chmod 600 "$HERE/registry.env"

echo "wrote $HERE/registry.env"
echo "  npm    $HOST/api/packages/$OWNER/npm/"
echo "  PyPI   $HOST/api/packages/$OWNER/pypi"
echo "  NuGet  $HOST/api/packages/$OWNER/nuget/index.json"
echo "  Maven  $HOST/api/packages/$OWNER/maven"
