#!/usr/bin/env bash
# One-time setup for the OPTIONAL self-contained registry in docker-compose.yml.
#
# Creates the registry owner account, mints a package-scoped token, and writes
# tools/prerelease/registry.env (gitignored). Skip this entirely if you already have a
# registry — just copy registry.env.example to registry.env and fill it in.
#
#   docker compose -f tools/prerelease/docker-compose.yml up -d
#   tools/prerelease/bootstrap.sh
#
# Re-running is safe: it reuses the account and mints a fresh token.
set -euo pipefail

HOST="${MO_REGISTRY_BASE:-http://localhost:3939}"
OWNER="${MO_REGISTRY_OWNER:-prerelease}"
CONTAINER="${MO_REGISTRY_CONTAINER:-mo-prerelease-registry}"
HERE="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$HERE/registry.env"

# This script drives the compose container directly, so it only makes sense against the
# instance that compose file starts.
case "$HOST" in
  http://localhost:*|http://127.0.0.1:*) ;;
  *) echo "bootstrap.sh only manages the local compose instance; for an existing registry"  >&2
     echo "copy registry.env.example to registry.env and fill in your own values."          >&2
     exit 1 ;;
esac

# No committed default for an --admin credential — this repository is public, so a
# publicly-known password would exist behind nothing but the loopback bind. MO_REGISTRY_PASS
# wins; else a previous bootstrap's registry.env is reused (same registry only) so
# re-running stays idempotent; else a fresh random password is minted and persisted below.
PASS="${MO_REGISTRY_PASS:-}"
if [ -z "$PASS" ] && [ -f "$ENV_FILE" ]; then
  prev_base="$(sed -n 's/^MO_REGISTRY_BASE=//p' "$ENV_FILE" | tail -n1)"
  if [ "$prev_base" = "$HOST" ]; then
    PASS="$(sed -n 's/^MO_REGISTRY_PASS=//p' "$ENV_FILE" | tail -n1)"
  fi
fi
if [ -z "$PASS" ]; then
  PASS="$(openssl rand -base64 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  [ -n "$PASS" ] || { echo "could not generate a password — set MO_REGISTRY_PASS" >&2; exit 1; }
fi

echo "waiting for $HOST ..."
for _ in $(seq 1 60); do
  if curl -fsS -o /dev/null "$HOST/"; then
    break
  fi
  sleep 1
done

if ! curl -fsS -o /dev/null -u "$OWNER:$PASS" "$HOST/api/v1/user" 2>/dev/null; then
  docker exec -u git "$CONTAINER" gitea admin user create \
    --username "$OWNER" --password "$PASS" --email "$OWNER@registry.invalid" \
    --admin --must-change-password=false >/dev/null
  echo "created registry owner '$OWNER'"
fi

TOKEN="$(curl -fsS -X POST -H 'Content-Type: application/json' -u "$OWNER:$PASS" \
  -d '{"name":"prerelease-'"$(date +%s)"'","scopes":["write:package","read:package"]}' \
  "$HOST/api/v1/users/$OWNER/tokens" | sed -n 's/.*"sha1":"\([^"]*\)".*/\1/p')"

[ -n "$TOKEN" ] || { echo "failed to mint a token" >&2; exit 1; }

cat > "$ENV_FILE" <<EOF
# Generated by tools/prerelease/bootstrap.sh — gitignored, local only.
MO_REGISTRY_BASE=$HOST
MO_REGISTRY_OWNER=$OWNER
MO_REGISTRY_TOKEN=$TOKEN
MO_REGISTRY_PASS=$PASS
EOF
chmod 600 "$ENV_FILE"

echo "wrote $ENV_FILE (the account password is stored in it, never printed)"
echo "  npm    $HOST/api/packages/$OWNER/npm/"
echo "  PyPI   $HOST/api/packages/$OWNER/pypi"
echo "  NuGet  $HOST/api/packages/$OWNER/nuget/index.json"
echo "  Maven  $HOST/api/packages/$OWNER/maven"
