// Integration test: trainer-website-shape (9 entities)
// End-to-end gate that proves Tasks 1-16 produce production-quality output.

import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, readFileSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { FileMetaDataLoader } from "@metaobjects/metadata/core";
import { runGen, defineConfig } from "../src/index.js";
import { entityFile, queriesFile, routesFile, barrel } from "../src/generators/index.js";

let tmp: string;
beforeEach(() => { tmp = mkdtempSync(join(tmpdir(), "codegen-integration-")); });
afterEach(() => { rmSync(tmp, { recursive: true, force: true }); });

const FIXTURE = resolve(import.meta.dir, "fixtures/trainer-website-shape.json");

describe("trainer-website-shape integration — 9 entities, SQLite", () => {
  test("loads 9 entities with no errors", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([FIXTURE]);

    expect(result.errors).toEqual([]);

    const entities = result.root.ownChildren().filter((c) => c.type === "object");
    expect(entities).toHaveLength(9);

    const names = entities.map((e) => e.name).sort();
    expect(names).toEqual([
      "Exercise",
      "Program",
      "Purchase",
      "Subscriber",
      "Tag",
      "Video",
      "Week",
      "Workout",
      "WorkoutEvent",
    ]);
  });

  test("emits 28 files (9 entity + 9 queries + 9 routes + 1 barrel) with no warnings (forms opt-in)", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([FIXTURE]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    expect(out.warnings).toEqual([]);

    const files = readdirSync(tmp).sort();
    expect(files).toHaveLength(28);

    // Barrel
    expect(files).toContain("index.ts");

    // One .ts + one .queries.ts per entity
    const entityNames = [
      "Subscriber",
      "Program",
      "Week",
      "Workout",
      "Exercise",
      "Video",
      "WorkoutEvent",
      "Purchase",
      "Tag",
    ];
    for (const name of entityNames) {
      expect(files).toContain(`${name}.ts`);
      expect(files).toContain(`${name}.queries.ts`);
      expect(files).toContain(`${name}.routes.ts`);
      // Forms are opt-in (off by default), so .form.tsx should NOT appear here.
      expect(files).not.toContain(`${name}.form.tsx`);
    }
  });

  test("generated files satisfy structural contracts", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([FIXTURE]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    expect(out.warnings).toEqual([]);

    const files = readdirSync(tmp);

    for (const file of files) {
      const content = readFileSync(join(tmp, file), "utf-8");

      if (
        file.endsWith(".ts") &&
        !file.endsWith(".queries.ts") &&
        !file.endsWith(".routes.ts") &&
        file !== "index.ts"
      ) {
        // Entity files: @generated header, sqlite table fn, Zod schemas, Drizzle types,
        // plus the metadata-constants block.
        expect(content).toContain("@generated by @metaobjects/codegen-ts");
        expect(content).toContain("sqliteTable");
        expect(content).toContain("InsertSchema");
        expect(content).toContain("InferSelectModel");
        expect(content).toContain("$entity:");
        expect(content).toContain("$path:");
      }

      if (file.endsWith(".queries.ts")) {
        // Queries files: @generated header, db import, findById + create per entity
        expect(content).toContain("@generated by @metaobjects/codegen-ts");
        expect(content).toContain("~/server/db");
        // Pattern matches find<Entity>ById for any entity name
        expect(content).toMatch(/find\w+ById/);
      }

      if (file.endsWith(".routes.ts")) {
        // Routes files: @generated header, fastify import, db + table import,
        // delegates to mountCrudRoutes from @metaobjects/runtime-ts/drizzle-fastify.
        expect(content).toContain("@generated by @metaobjects/codegen-ts");
        expect(content).toContain("FastifyInstance");
        expect(content).toContain("mountCrudRoutes");
        expect(content).toContain("@metaobjects/runtime-ts/drizzle-fastify");
        expect(content).toContain("db,");
        expect(content).toContain("table:");
        expect(content).toMatch(/insertSchema:\s*\w+InsertSchema/);
        expect(content).toMatch(/updateSchema:\s*\w+UpdateSchema/);
      }

      // The @generated header must be at line 1 of every generated file
      // (not pushed below imports by ts-poet's hoisting). Tooling and
      // overwrite-policy both rely on this convention.
      expect(content.split("\n")[0]).toContain("@generated by @metaobjects/codegen-ts");
    }

    // Barrel re-exports every entity but no .queries references
    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Subscriber"');
    expect(barrelContent).toContain('export * from "./Program"');
    expect(barrelContent).toContain('export * from "./Tag"');
    expect(barrelContent).not.toContain("queries");

    // Cross-entity FK + relations: Workout belongs to Week
    const workout = readFileSync(join(tmp, "Workout.ts"), "utf-8");
    expect(workout).toContain('import { weeks } from "./Week"');
    expect(workout).toContain(".references(");
    expect(workout).toContain("workoutsRelations");

    // WorkoutEvent has two FKs (subscriberId + workoutId)
    const workoutEvent = readFileSync(join(tmp, "WorkoutEvent.ts"), "utf-8");
    expect(workoutEvent).toContain('import { subscribers } from "./Subscriber"');
    expect(workoutEvent).toContain('import { workouts } from "./Workout"');
    expect(workoutEvent).toContain("workoutEventsRelations");

    // Purchase has two FKs (subscriberId + programId)
    const purchase = readFileSync(join(tmp, "Purchase.ts"), "utf-8");
    expect(purchase).toContain('import { subscribers } from "./Subscriber"');
    expect(purchase).toContain('import { programs } from "./Program"');
    expect(purchase).toContain("purchasesRelations");

    // Tag has no relationships — no .references() call
    const tag = readFileSync(join(tmp, "Tag.ts"), "utf-8");
    expect(tag).not.toContain(".references(");
  });

  test("emits FilterAllowlist + SortAllowlist + Filter TS type in every entity file", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([FIXTURE]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });
    expect(out.warnings).toEqual([]);

    // Spot-check that <Entity>.ts contains the new exports for all entities.
    // The fixture entities may not have @filterable set; the consts must still
    // emit (as empty allowlists / minimal Filter types).
    const files = readdirSync(tmp);
    const entityFiles = files.filter(
      (f) =>
        f.endsWith(".ts") &&
        !f.endsWith(".queries.ts") &&
        !f.endsWith(".routes.ts") &&
        f !== "index.ts"
    );
    expect(entityFiles.length).toBeGreaterThan(0);

    for (const file of entityFiles) {
      const content = readFileSync(join(tmp, file), "utf-8");
      const entityName = file.replace(/\.ts$/, "");
      expect(content).toContain(`export const ${entityName}FilterAllowlist`);
      expect(content).toContain(`export const ${entityName}SortAllowlist`);
      expect(content).toContain(`export type ${entityName}Filter`);
    }
  });

  test("routes file passes filterAllowlist + sortAllowlist + dialect to mountCrudRoutes", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([FIXTURE]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });
    expect(out.warnings).toEqual([]);

    // Pick any routes file and verify it imports + passes the new fields
    const files = readdirSync(tmp);
    const routesFiles = files.filter((f) => f.endsWith(".routes.ts"));
    expect(routesFiles.length).toBeGreaterThan(0);

    const sampleFile = routesFiles[0]!;
    const content = readFileSync(join(tmp, sampleFile), "utf-8");
    const entityName = sampleFile.replace(/\.routes\.ts$/, "");

    // Verify the imports include the new allowlist consts
    expect(content).toContain(`${entityName}FilterAllowlist`);
    expect(content).toContain(`${entityName}SortAllowlist`);

    // Verify the mountCrudRoutes call includes all three new fields
    expect(content).toContain(`filterAllowlist: ${entityName}FilterAllowlist`);
    expect(content).toContain(`sortAllowlist: ${entityName}SortAllowlist`);
    expect(content).toMatch(/dialect:\s*"sqlite"/);
  });
});

describe("trainer-website-shape integration — 9 entities, Postgres", () => {
  test("emits 28 files with no warnings (forms opt-in)", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([FIXTURE]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    expect(out.warnings).toEqual([]);

    const files = readdirSync(tmp).sort();
    expect(files).toHaveLength(28);
    expect(files).toContain("index.ts");

    const entityNames = [
      "Subscriber",
      "Program",
      "Week",
      "Workout",
      "Exercise",
      "Video",
      "WorkoutEvent",
      "Purchase",
      "Tag",
    ];
    for (const name of entityNames) {
      expect(files).toContain(`${name}.ts`);
      expect(files).toContain(`${name}.queries.ts`);
      expect(files).toContain(`${name}.routes.ts`);
      // Forms are opt-in (off by default), so .form.tsx should NOT appear here.
      expect(files).not.toContain(`${name}.form.tsx`);
    }
  });

  test("generated files satisfy Postgres structural contracts", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([FIXTURE]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    expect(out.warnings).toEqual([]);

    const files = readdirSync(tmp);

    // @generated header must be at line 1 of every file
    for (const file of files) {
      const content = readFileSync(join(tmp, file), "utf-8");
      expect(content.split("\n")[0]).toContain("@generated by @metaobjects/codegen-ts");
    }

    // Subscriber: Postgres-specific — bigserial PK, pgTable, .defaultNow() for createdAt
    const subscriber = readFileSync(join(tmp, "Subscriber.ts"), "utf-8");
    expect(subscriber).toContain("pgTable");
    expect(subscriber).not.toContain("sqliteTable");
    expect(subscriber).toContain("bigserial");   // long PK with increment → bigserial
    expect(subscriber).toContain(".defaultNow()"); // timestamp @default:"now" → .defaultNow()

    // WorkoutEvent has two FKs — cross-entity imports + .references()
    const workoutEvent = readFileSync(join(tmp, "WorkoutEvent.ts"), "utf-8");
    expect(workoutEvent).toContain('import { subscribers } from "./Subscriber"');
    expect(workoutEvent).toContain('import { workouts } from "./Workout"');
    expect(workoutEvent).toContain(".references(");

    // Barrel re-exports all entities but no .queries references
    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Subscriber"');
    expect(barrelContent).toContain('export * from "./Tag"');
    expect(barrelContent).not.toContain("queries");
  });
});
