// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Tag (Tag)
// Customize via Tag.extra.ts in this directory.
import {
  type InferInsertModel,
  type InferSelectModel,
  relations,
} from "drizzle-orm";
import {
  type AnySQLiteColumn,
  integer,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";
import { z } from "zod";
import { TagNames } from "./Tag.names";
import { customers } from "./shop/users/Customer";

export const tags = sqliteTable(TagNames.sources.primary.table, {
  id: integer(TagNames.fields.id.column).primaryKey({ autoIncrement: true }),
  label: text(TagNames.fields.label.column).notNull(),
  customerId: integer(TagNames.fields.customerId.column)
    .notNull()
    .references((): AnySQLiteColumn => customers.id),
});
export const tagsRelations = relations(tags, ({ one }) => ({
  customer: one(customers, {
    fields: [tags.customerId],
    references: [customers.id],
  }),
}));
export type Tag = InferSelectModel<typeof tags>;
export type TagInsert = InferInsertModel<typeof tags>;
export type TagUpdate = Partial<TagInsert>;
export const TagInsertSchema = z.object({
  label: z.string().min(1).max(100),
  customerId: z.number().int(),
});

export const TagUpdateSchema = z.object({
  label: z.string().min(1).max(100).optional(),
  customerId: z.number().int().optional(),
});

/** Typed patch shape for Tag: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updateTag` call site. */
export type TagPatch = z.input<typeof TagUpdateSchema>;
/**
 * Metadata constants for Tag.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, optional htmlType/placeholder/helpText, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(Tag, TagInsertSchema);
 *   <input {...form.input.id} />
 */
export const Tag = {
  $entity: "Tag",
  $table: TagNames.sources.primary.table,
  $path: "/tags",
  $apiPrefix: "",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  label: {
    name: "label",
    label: "Label",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Label is required",
      maxLength: { value: 100, message: "Must be 100 characters or fewer" },
    },
  },
  customerId: {
    name: "customerId",
    label: "Customer Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Customer Id is required" },
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const TagFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const TagSortAllowlist = {} as const satisfies SortAllowlist;
export type TagFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: TagFilter[];
  and?: TagFilter[];
};
