"""One pytest file per metamodel package: one test per declared requirement (ADR-0057).

A requirement ledger claims what the software DOES. This generator emits a test for each
requirement the filter selects; the test calls a project-owned WITNESS, a function named by
the test's witness key in the module ``requirement_tests(witness_module=...)`` names. No such
function and the test fails, naming the requirement and the counterexample, so an empty
generated test can never pass: a ``live`` entry claims the capability works, and a green test
that checks nothing asserts the opposite. A ``planned`` or ``retired`` requirement is skipped,
and never looks a witness up.

The generated file is machine-owned and rewritten whole on every run: there is no hand-edited
body to merge. Project code lives in the witnesses. Which tests exist, what each is called and
what it fingerprints are decided in :mod:`metaobjects.codegen.requirement_walk`, which the
shared identity corpus pins in every language port.

This module is a REFERENCE HELPER (ADR-0034 Amendment 3), ejectable with
``metaobjects eject requirement-tests``. ``eject`` copies this file whole, so it holds the
generator and its default renderer and nothing unrelated, and it imports only absolute
``metaobjects.*`` module paths so the copy still resolves from an adopter's tree. An owned copy
keeps reading the ``requirementTests`` config block, because the factory it is wired by takes
the build context.

The generated file imports ``importlib`` and ``pytest`` and nothing from MetaObjects, and parses
under the Python 3.9 grammar (the generator itself runs on the package's own floor).
"""
from __future__ import annotations

import json
import re
import unicodedata
from typing import TYPE_CHECKING

from metaobjects.codegen.generator import EmittedFile, GenContext, Generator
from metaobjects.codegen.project_config import (
    DEFAULT_REQUIREMENT_WITNESS_MODULE,
    DOTTED_MODULE_PATTERN,
)
from metaobjects.codegen.requirement_hooks import (
    RenderedTest,
    RequirementTestArgs,
    RequirementTestRenderer,
)
from metaobjects.codegen.requirement_walk import (
    RequirementFilter,
    RequirementTestIdentity,
    ResolvedClaim,
    WalkedRequirement,
    assert_requirement_test_grain,
    default_requirement_test_filter,
    mangle,
    requirement_test_identity,
    requirement_test_units,
    walk_requirements,
    witness_key_collisions,
)
from metaobjects.meta.core.requirement.requirement_constants import (
    REQUIREMENT_ATTR_COUNTEREXAMPLE,
    REQUIREMENT_ATTR_STATEMENT,
    REQUIREMENT_STATUS_PLANNED,
    REQUIREMENT_STATUS_RETIRED,
)

if TYPE_CHECKING:  # the registry imports this module; the type is only an annotation here
    from metaobjects.codegen.generator_registry import GeneratorBuildContext

#: The refusal code when two tests map to one witness key (identical in every port).
ERR_REQUIREMENT_WITNESS_KEY_COLLISION = "ERR_REQUIREMENT_WITNESS_KEY_COLLISION"

GENERATOR_NAME = "requirement-tests"

#: The module the witnesses are looked up in when the project names none.
DEFAULT_WITNESS_MODULE = DEFAULT_REQUIREMENT_WITNESS_MODULE

#: Where the generated files land, relative to the generator's output directory.
OUTPUT_DIR = "requirements"

#: How many uncovered requirements to name before "and N more".
MAX_NAMED_UNCOVERED = 5

SKIP_REASON_PLANNED = "planned - not built yet"
SKIP_REASON_RETIRED = "retired - the capability was deliberately removed; assert it stays removed"

_DOTTED_NAME = re.compile(DOTTED_MODULE_PATTERN)

_HEADER = (
    "# @generated by metaobjects (requirement-tests). DO NOT EDIT: this file is rewritten whole.\n"
    "# Witnesses are project-owned functions in the module named below.\n"
)

#: The imports every generated file carries. A renderer hook's imports are merged after them.
_BASE_IMPORTS = ("import importlib", "import pytest")

#: The file's prelude. A missing witness module is "no witness"; a witness module that exists
#: and fails to import raises its OWN error, never "unimplemented requirement" on every test.
_PRELUDE = '''
def _witness(key):
    try:
        module = importlib.import_module(_WITNESS_MODULE)
    except ModuleNotFoundError as exc:
        missing = exc.name or ""
        if _WITNESS_MODULE != missing and not _WITNESS_MODULE.startswith(missing + "."):
            raise
        return None
    return getattr(module, key, None)


def _run(key, test_id, counterexample):
    witness = _witness(key)
    if witness is None:
        pytest.fail(
            "unimplemented requirement: " + test_id + " - write " + _WITNESS_MODULE + "." + key
            + "() so that it fails when: " + counterexample
        )
    witness()
'''


# ---------------------------------------------------------------------------
# Escaping: author prose lands in a string literal and in comments, and must not break either.
# ---------------------------------------------------------------------------


def _string_literal(value: str) -> str:
    """A double-quoted Python string literal holding *value* exactly.

    JSON's string syntax is a subset of Python's: it escapes the backslash, the quote, the
    newline, the carriage return and every other control character, so no value can end the
    literal (a triple quote becomes three escaped quotes).
    """
    return json.dumps(value, ensure_ascii=False)


def _comment_text(line: str) -> str:
    """One line of prose as comment text. ``*/`` is broken as ``* /``: the rule every port's
    generator shares (contract Table H), harmless here and what keeps the five ports' comments
    reading alike. A control character that would break the file (a NUL makes Python refuse the
    whole source) is written visibly as ``\\xNN``; a tab stays."""
    line = line.replace("*/", "* /")
    return "".join(
        f"\\x{ord(c):02x}" if unicodedata.category(c) == "Cc" and c != "\t" else c for c in line
    )


def _comment_lines(text: str) -> str:
    """One ``#`` marker per line. A carriage return ends a Python line as a line feed does, so
    both split."""
    return "\n".join(("# " + _comment_text(line)).rstrip() for line in re.split(r"\r\n|\r|\n", text))


def _skip_reason(skip: str) -> str:
    if skip == REQUIREMENT_STATUS_PLANNED:
        return SKIP_REASON_PLANNED
    if skip == REQUIREMENT_STATUS_RETIRED:
        return SKIP_REASON_RETIRED
    return f"{skip} - skipped"


# ---------------------------------------------------------------------------
# The default renderer.
# ---------------------------------------------------------------------------


def render_requirement_test(args: RequirementTestArgs) -> RenderedTest:
    """The default rendering of one test: its comments, then a test that calls the witness
    (or, when the requirement is skipped, a skipped test that does not look one up).

    A renderer hook has this signature and may return ``None`` to keep this default.
    """
    identity = args.identity
    claims = ", ".join(f"{ref}  ({concern})" for ref, concern in args.targets) or "(none)"
    comments = "\n".join(
        (
            _comment_lines(identity.id),
            _comment_lines(args.statement),
            _comment_lines("Counterexample: " + args.counterexample),
            _comment_lines("Status: " + (identity.status if identity.status is not None else "(none)")),
            _comment_lines("Claims: " + claims),
            _comment_lines("Digest: " + identity.digest),
        )
    )
    name = f"test_{identity.witness_key}"
    if identity.skip is not None:
        body = (
            f"@pytest.mark.skip(reason={_string_literal(_skip_reason(identity.skip))})\n"
            f"def {name}():\n"
            f"    pass"
        )
    else:
        body = (
            f"def {name}():\n"
            f"    _run(\n"
            f"        {_string_literal(identity.witness_key)},\n"
            f"        {_string_literal(identity.id)},\n"
            f"        {_string_literal(args.counterexample)},\n"
            f"    )"
        )
    return RenderedTest(imports=(), source=f"{comments}\n{body}")


# ---------------------------------------------------------------------------
# The generator.
# ---------------------------------------------------------------------------


def _package_key(package: str) -> str:
    """The file key of a package: each run of non-ASCII-alphanumerics as one ``_``, or ``root``
    for the empty package. Two packages that mangle alike share a file; their tests keep
    distinct witness keys, which the collision check has proven."""
    return mangle(package) if package else "root"


class _RequirementTestsGenerator:
    # The runner treats a `filter` attribute on a generator as its ENTITY matcher, and this
    # generator's filter selects requirements, so the predicate is kept under another name.
    name = GENERATOR_NAME

    def __init__(
        self,
        witness_module: str,
        grain: str,
        renderer: RequirementTestRenderer | None,
        include: RequirementFilter | None,
        warn_uncovered: bool,
    ) -> None:
        self._witness_module = witness_module
        self._grain = grain
        self._renderer = renderer
        self._include = include if include is not None else default_requirement_test_filter
        self._warn_uncovered = warn_uncovered

    def generate(self, ctx: GenContext) -> list[EmittedFile]:
        if ctx.loaded_root is None:
            return []
        planned: list[tuple[RequirementTestIdentity, RequirementTestArgs]] = []
        uncovered: list[str] = []
        for walked in walk_requirements(ctx.loaded_root):
            if not self._include(walked.view):
                # Named by PATH: diagnostics use the path (contract Table A).
                uncovered.append(walked.view.path)
                continue
            for unit, targets in requirement_test_units(walked, self._grain).items():
                identity = requirement_test_identity(walked, unit)
                planned.append((identity, _args_for(walked, identity, targets)))
        planned.sort(key=lambda p: p[0].id)
        _refuse_collisions([identity for identity, _ in planned])
        if self._warn_uncovered and uncovered:
            shown = ", ".join(uncovered[:MAX_NAMED_UNCOVERED])
            more = (
                f", and {len(uncovered) - MAX_NAMED_UNCOVERED} more"
                if len(uncovered) > MAX_NAMED_UNCOVERED
                else ""
            )
            ctx.warn(
                f"{len(uncovered)} requirement(s) matched no filter and get no test. "
                f"If that is deliberate, set warnUncovered: false to silence this. "
                f"Uncovered: {shown}{more}."
            )

        by_package: dict[str, list[tuple[RequirementTestIdentity, RequirementTestArgs]]] = {}
        for item in planned:
            by_package.setdefault(_package_key(item[0].package), []).append(item)
        return [
            EmittedFile(
                path=f"{OUTPUT_DIR}/test_{key}_requirements.py",
                content=self._file_text(items),
            )
            for key, items in sorted(by_package.items())
        ]

    def _file_text(self, items: list[tuple[RequirementTestIdentity, RequirementTestArgs]]) -> str:
        rendered: list[RenderedTest] = []
        for identity, args in items:
            result = self._renderer(args) if self._renderer is not None else None
            if result is not None and not (
                isinstance(result, RenderedTest) and isinstance(result.source, str)
            ):
                raise ValueError(
                    f"requirement-tests renderer {_describe(self._renderer)} returned "
                    f"{_returned(result)} for {identity.id!r}: expected a RenderedTest "
                    f"(from metaobjects.codegen.requirement_hooks) whose source is a string, or None."
                )
            rendered.append(result if result is not None else render_requirement_test(args))

        extra = sorted({i for r in rendered for i in r.imports} - set(_BASE_IMPORTS))
        imports = "\n".join(_BASE_IMPORTS[:1]) + "\n\n" + _BASE_IMPORTS[1]
        if extra:
            imports += "\n\n" + "\n".join(extra)
        head = f"{_HEADER}{imports}\n\n_WITNESS_MODULE = {_string_literal(self._witness_module)}\n\n{_PRELUDE}"
        return head + "".join("\n\n" + r.source.rstrip() + "\n" for r in rendered)


def _describe(renderer: object) -> str:
    module = getattr(renderer, "__module__", None)
    name = getattr(renderer, "__qualname__", None) or repr(renderer)
    return f"{module}.{name}" if module else name


def _returned(result: object) -> str:
    if isinstance(result, RenderedTest):
        return f"a RenderedTest whose source is {type(result.source).__name__}"
    return type(result).__name__


def _args_for(
    walked: WalkedRequirement, identity: RequirementTestIdentity, targets: list[ResolvedClaim]
) -> RequirementTestArgs:
    node = walked.node
    statement = node.get_meta_attr(REQUIREMENT_ATTR_STATEMENT)
    counterexample = node.get_meta_attr(REQUIREMENT_ATTR_COUNTEREXAMPLE)
    return RequirementTestArgs(
        identity=identity,
        statement=statement if isinstance(statement, str) else "",
        counterexample=counterexample if isinstance(counterexample, str) else "",
        targets=tuple((t.ref, t.concern) for t in targets),
        disposition=node.disposition(),
        tracked_by=tuple(node.tracked_by()),
    )


def _refuse_collisions(identities: list[RequirementTestIdentity]) -> None:
    collisions = witness_key_collisions(identities)
    if not collisions:
        return
    key_by_id = {identity.id: identity.witness_key for identity in identities}
    pairs = "".join(
        f"\n  '{first}' and '{second}' (witness key {key_by_id[first]})" for first, second in collisions
    )
    raise ValueError(
        f"{ERR_REQUIREMENT_WITNESS_KEY_COLLISION}: two requirement tests map to one witness key, so "
        f"one witness could not serve both. Rename one so the names differ in more than punctuation:{pairs}"
    )


def requirement_tests(
    *,
    witness_module: str = DEFAULT_WITNESS_MODULE,
    grain: str = "concern",
    renderer: RequirementTestRenderer | None = None,
    filter: RequirementFilter | None = None,  # noqa: A002 — the seam's published name
    warn_uncovered: bool = True,
) -> Generator:
    """The ``requirement-tests`` generator.

    ``witness_module`` is the dotted module the project's witness functions live in;
    ``grain`` is ``concern`` (one test per distinct ``<type>.<subType>`` a requirement claims)
    or ``member`` (one per distinct reference that resolves); ``renderer`` replaces the text
    of one test and returns ``None`` to keep the default; ``filter`` chooses which requirements
    get a test, replacing the default (functional, level 4 or above); ``warn_uncovered`` names
    the requirements the filter excluded, once, capped.
    """
    # Refused here, when the generator is built, rather than on the first requirement: an
    # unknown grain or a malformed module is a mistake in the config whatever the model holds.
    assert_requirement_test_grain(grain)
    if not isinstance(witness_module, str) or not _DOTTED_NAME.fullmatch(witness_module):
        raise ValueError(
            f"requirement-tests witness module {witness_module!r} is not a dotted module name "
            f"such as {DEFAULT_WITNESS_MODULE!r}."
        )
    return _RequirementTestsGenerator(witness_module, grain, renderer, filter, warn_uncovered)


def requirement_tests_generator(ctx: "GeneratorBuildContext") -> Generator:
    """The registry's ``source=``, and so the symbol an ejected copy is wired by.

    It takes the build context (one required positional parameter, which is what
    ``eject.build_owned`` passes the context to) and builds :func:`requirement_tests` from the
    ``requirementTests`` config block the context carries. With no block the defaults apply.
    """
    options = getattr(ctx, "requirement_tests", None)
    if options is None:
        return requirement_tests()
    return requirement_tests(
        witness_module=options.witness_module,
        grain=options.grain,
        renderer=options.renderer,
        filter=options.filter,
        warn_uncovered=options.warn_uncovered,
    )
