"""Tests for the FastAPI router generator (FR-008 §2.3).

Mirrors the Java SpringControllerGenerator / Kotlin KotlinSpringControllerGenerator
contracts: one router per writable entity (source.rdb @kind="table"); 5 CRUD endpoints
(GET list / GET by id / POST / PATCH+PUT / DELETE); ?sort, ?limit/?offset, ?withCount=1
envelope, 404 + 400 envelopes per the cross-port API contract.
"""
import json
import shutil
import tempfile
from pathlib import Path

import metaobjects.core_types  # noqa: F401  — side-effect: registers attr classes
from metaobjects import MetaDataLoader
from metaobjects.codegen.generators.m2m_codegen import build_object_index
from metaobjects.codegen.generators.router_generator import render_router
from metaobjects.meta.core.field.meta_field import MetaField
from metaobjects.meta.core.field import field_constants as fc
from metaobjects.meta.core.object.meta_object import MetaObject
from metaobjects.meta.persistence.source.meta_source import MetaSource
from metaobjects.meta.persistence.source.source_constants import (
    SOURCE_ATTR_KIND,
    SOURCE_KIND_VIEW,
    SOURCE_SUBTYPE_RDB,
)
from metaobjects.shared.base_types import TYPE_FIELD, TYPE_OBJECT, TYPE_SOURCE


def _entity(
    name: str,
    fields: list[MetaField],
    *,
    source_kind: str | None = "table",
    package: str | None = None,
) -> MetaObject:
    o = MetaObject(TYPE_OBJECT, "entity", name)
    o.package = package
    if source_kind is not None:
        src = MetaSource(TYPE_SOURCE, SOURCE_SUBTYPE_RDB, "")
        if source_kind != "table":
            src.set_attr(SOURCE_ATTR_KIND, source_kind, sub_type="string")
        o.add_child(src)
    for f in fields:
        o.add_child(f)
    return o


def _f(name: str, sub: str, *, required: bool = False) -> MetaField:
    f = MetaField(TYPE_FIELD, sub, name)
    if required:
        f.set_attr(fc.FIELD_ATTR_REQUIRED, True)
    return f


def _author() -> MetaObject:
    return _entity(
        "Author",
        [
            _f("id", fc.FIELD_SUBTYPE_INT, required=True),
            _f("name", fc.FIELD_SUBTYPE_STRING, required=True),
            _f("createdAt", fc.FIELD_SUBTYPE_TIMESTAMP),
        ],
        package="acme::blog",
    )


def _require(entity: MetaObject) -> str:
    """Narrow ``render_router`` to ``str`` for type checkers (writable
    entities always render)."""
    out = render_router(entity)
    assert out is not None
    return out


def test_router_has_apirouter_with_pluralized_lowercase_prefix() -> None:
    out = _require(_author())
    assert 'APIRouter(prefix="/api/authors", tags=["authors"])' in out
    assert "@generated by metaobjects" in out


def test_all_five_verbs_present() -> None:
    out = _require(_author())
    # Two GETs (list + by-id), POST, PATCH+PUT on the same handler, DELETE.
    assert out.count("@router.get") == 2
    assert out.count("@router.post") == 1
    assert out.count("@router.patch") == 1
    assert out.count("@router.put") == 1
    assert out.count("@router.delete") == 1
    # PATCH + PUT stack on a single update handler.
    assert '@router.patch("/{author_id}")\n@router.put("/{author_id}")' in out


def test_per_entity_sort_allowlist_constant_emitted() -> None:
    out = _require(_author())
    assert "_SORT_ALLOWLIST" in out
    # Author has 3 scalar fields → all sortable.
    assert '"id"' in out
    assert '"name"' in out
    assert '"createdAt"' in out
    # Per-entity parse helper closes over the allowlist.
    assert "def _parse_sort" in out


def test_with_count_returns_envelope_bare_list_otherwise() -> None:
    out = _require(_author())
    # withCount=1 → {"rows": ..., "total": N}
    assert 'return {"rows": rows, "total": total}' in out
    # default → bare list
    assert "return rows" in out
    # The 404 envelope and 400 invalid_sort envelope are part of the contract.
    assert '"error": "not_found"' in out
    assert '"error": "invalid_sort"' in out


def test_view_kind_skipped() -> None:
    # Only @kind="table" gets a router. Views are read-only — skipped (returns None).
    view = _entity(
        "AuthorView",
        [_f("id", fc.FIELD_SUBTYPE_INT, required=True)],
        source_kind=SOURCE_KIND_VIEW,
        package="acme::blog",
    )
    assert render_router(view) is None


def test_router_imports_filter_allowlist_module_and_parser() -> None:
    """FR-009: the router must import the per-entity allowlist constants from
    the sibling `<entity_snake>_filter_allowlist.py` module + the shared
    `parse_filter` helper from `metaobjects.codegen.runtime.filter_parser`."""
    out = _require(_author())
    # Shared runtime helper import — used by the list handler.
    assert "from metaobjects.codegen.runtime.filter_parser import" in out
    assert "FilterPredicate" in out
    assert "parse_filter" in out
    # Sibling allowlist module import — emitted as a relative import so the
    # router + allowlist live in the same generated package.
    assert "from .author_filter_allowlist import" in out
    assert "AUTHOR_FILTER_FIELDS" in out
    assert "AUTHOR_FILTER_OPS_BY_FIELD" in out


def test_router_list_handler_calls_parse_filter() -> None:
    """FR-009: the generated `list_authors` handler must accept the FastAPI
    Request, call `parse_filter(request.query_params, FIELDS, OPS)`, raise
    400 on `error_envelope`, and thread `predicates` into `repo.list` /
    `repo.count`."""
    out = _require(_author())
    # Handler takes the Request (so it can read raw bracketed-qs params).
    assert "request: Request" in out
    # FastAPI's Request import must be present in the import line.
    assert "from fastapi import" in out and "Request" in out
    # Calls the shared parser against the allowlist constants.
    assert (
        "parse_filter(request.query_params, AUTHOR_FILTER_FIELDS, AUTHOR_FILTER_OPS_BY_FIELD)"
        in out
    )
    # On error_envelope -> 400 with the envelope as the response body. Uses
    # JSONResponse (not HTTPException, which FastAPI would wrap as {"detail": ...}
    # and break the cross-port {"error": ...} envelope contract — see SP-F Unit 4).
    assert "filter_result.error_envelope" in out
    assert "return JSONResponse(status_code=400, content=filter_result.error_envelope)" in out
    # Predicates thread through to the repository's list + count.
    assert "predicates = filter_result.predicates" in out
    assert "repo.list(actual_limit, actual_offset, sort_clause, predicates)" in out
    assert "repo.count(predicates)" in out
    # Repository protocol gains the filters parameter on list + count.
    assert "filters: list[FilterPredicate]" in out


# ---------------------------------------------------------------------------
# PK path-param typing — the route path param + the repository ``Protocol`` id
# must carry the entity's DECLARED primary-key type (metadata-derived via
# ``type_map.py_type_for``), never a hardcoded ``int``. Mirrors the C#
# RoutesGenerator (``CSharpNaming.ScalarFor(pkField.SubType)`` threaded through
# get/update/delete/M:N/TPH) and the TS ``getPkInfo`` (composite PK → fields[0];
# no primary identity → the field.long default, i.e. ``int``).
# ---------------------------------------------------------------------------


def _load_entities(meta: dict) -> dict[str, MetaObject]:
    """Author *meta* as a temp ``meta.json`` and load it through the real loader
    (identity/relationship resolution included)."""
    tmp = Path(tempfile.mkdtemp(prefix="router-pk-"))
    try:
        (tmp / "meta.json").write_text(json.dumps(meta))
        result = MetaDataLoader.from_directory(str(tmp))
        assert not result.errors, "; ".join(
            f"{e.code}: {e.message}" for e in result.errors
        )
        return {
            c.name: c
            for c in result.root.children()
            if c.type == TYPE_OBJECT and isinstance(c, MetaObject)
        }
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


_PK_TYPES_META = {
    "metadata.root": {
        "package": "acme::pk",
        "children": [
            # uuid PK + an M:N navigation (traversal route + find_related finder).
            {"object.entity": {
                "name": "Gadget",
                "children": [
                    {"source.rdb": {"@table": "gadgets"}},
                    {"field.uuid": {"name": "id", "@filterable": True, "@sortable": True}},
                    {"field.string": {"name": "label", "@required": True, "@maxLength": 80}},
                    {"relationship.association": {
                        "name": "tags", "@cardinality": "many",
                        "@objectRef": "Tag", "@through": "GadgetTag",
                    }},
                    {"identity.primary": {"name": "id", "@fields": "id", "@generation": "uuid"}},
                ],
            }},
            {"object.entity": {
                "name": "Tag",
                "children": [
                    {"source.rdb": {"@table": "tags"}},
                    {"field.long": {"name": "id"}},
                    {"field.string": {"name": "name", "@required": True, "@maxLength": 80}},
                    {"identity.primary": {"name": "id", "@fields": "id", "@generation": "increment"}},
                ],
            }},
            {"object.entity": {
                "name": "GadgetTag",
                "children": [
                    {"source.rdb": {"@table": "gadget_tags"}},
                    {"field.uuid": {"name": "gadgetId", "@required": True}},
                    {"field.long": {"name": "tagId", "@required": True}},
                    {"identity.primary": {"name": "id", "@fields": ["gadgetId", "tagId"]}},
                    {"identity.reference": {"name": "fkGadget", "@fields": "gadgetId", "@references": "Gadget"}},
                    {"identity.reference": {"name": "fkTag", "@fields": "tagId", "@references": "Tag"}},
                ],
            }},
            # string PK whose field is NOT named "id" — the URL param name stays
            # <entity>_id (cross-port grammar) but the TYPE follows the field.
            {"object.entity": {
                "name": "Coupon",
                "children": [
                    {"source.rdb": {"@table": "coupons"}},
                    {"field.string": {"name": "code", "@required": True, "@maxLength": 40}},
                    {"field.int": {"name": "percentOff"}},
                    {"identity.primary": {"name": "code", "@fields": "code", "@generation": "assigned"}},
                ],
            }},
            # long increment PK — the regression guard: must still be ``int``.
            {"object.entity": {
                "name": "Widget",
                "children": [
                    {"source.rdb": {"@table": "widgets"}},
                    {"field.long": {"name": "id"}},
                    {"field.string": {"name": "name", "@maxLength": 80}},
                    {"identity.primary": {"name": "id", "@fields": "id", "@generation": "increment"}},
                ],
            }},
        ],
    }
}


def test_uuid_pk_types_every_path_param_and_protocol_site_as_uuid() -> None:
    entities = _load_entities(_PK_TYPES_META)
    index = build_object_index(list(entities.values()))
    out = render_router(entities["Gadget"], index)
    assert out is not None
    # The module imports the stdlib uuid the annotation needs.
    assert "import uuid" in out
    # get / update / delete handlers + the M:N traversal route: 4 sites.
    assert out.count("    gadget_id: uuid.UUID,") == 4
    # Repository Protocol: find_by_id / update / delete / find_related_tags.
    assert "def find_by_id(self, id: uuid.UUID) -> Any | None: ..." in out
    assert "def update(self, id: uuid.UUID, dto: Any) -> Any | None: ..." in out
    assert "def delete(self, id: uuid.UUID) -> bool: ..." in out
    assert "def find_related_tags(self, id: uuid.UUID) -> list[Any]: ..." in out
    # No int-typed pk leaks anywhere.
    assert "gadget_id: int" not in out
    assert "id: int)" not in out


def test_string_pk_types_path_param_as_str() -> None:
    entities = _load_entities(_PK_TYPES_META)
    out = render_router(entities["Coupon"])
    assert out is not None
    # get / update / delete handlers: 3 sites (no M:N on Coupon).
    assert out.count("    coupon_id: str,") == 3
    assert "def find_by_id(self, id: str) -> Any | None: ..." in out
    assert "coupon_id: int" not in out


def test_long_increment_pk_still_types_int() -> None:
    entities = _load_entities(_PK_TYPES_META)
    out = render_router(entities["Widget"])
    assert out is not None
    assert out.count("    widget_id: int,") == 3
    assert "def find_by_id(self, id: int) -> Any | None: ..." in out
    assert "import uuid" not in out


def test_no_primary_identity_defaults_to_int() -> None:
    # The in-test Author has no identity.primary child — the PK type falls back
    # to int (the field.long default), matching the TS getPkInfo default.
    out = _require(_author())
    assert out.count("    author_id: int,") == 3
    assert "def find_by_id(self, id: int) -> Any | None: ..." in out


_TPH_UUID_META = {
    "metadata.root": {
        "package": "acme::auth",
        "children": [
            {"object.entity": {
                "name": "Auth",
                "@discriminator": "type",
                "children": [
                    {"source.rdb": {"@table": "auths"}},
                    {"field.uuid": {"name": "id", "@filterable": True, "@sortable": True}},
                    {"field.enum": {"name": "type", "@values": ["Bridge", "Copay"], "@filterable": True}},
                    {"field.string": {"name": "reference", "@required": True, "@maxLength": 80}},
                    {"identity.primary": {"name": "id", "@fields": "id", "@generation": "uuid"}},
                ],
            }},
            {"object.entity": {
                "name": "BridgeAuth",
                "extends": "Auth",
                "@discriminatorValue": "Bridge",
                "children": [
                    {"field.int": {"name": "quantity", "@required": True}},
                ],
            }},
            {"object.entity": {
                "name": "CopayAuth",
                "extends": "Auth",
                "@discriminatorValue": "Copay",
                "children": [
                    {"field.string": {"name": "payer", "@maxLength": 80}},
                ],
            }},
        ],
    }
}


def test_tph_uuid_pk_types_base_and_subtype_routes_as_uuid() -> None:
    entities = _load_entities(_TPH_UUID_META)
    index = build_object_index(list(entities.values()))
    out = render_router(entities["Auth"], index)
    assert out is not None
    assert "import uuid" in out
    # Per-subtype get/update/delete (3 sites × 2 subtypes) + polymorphic base get.
    assert out.count("    auth_id: uuid.UUID,") == 7
    # Subtype-keyed repository Protocol.
    assert "def find_by_id(self, subtype: str | None, id: uuid.UUID) -> Any | None: ..." in out
    assert "def update(self, subtype: str, id: uuid.UUID, dto: Any) -> Any | None: ..." in out
    assert "def delete(self, subtype: str, id: uuid.UUID) -> bool: ..." in out
    assert "auth_id: int" not in out
