"""Tests for the template.output parser generator (FR-006).

Mirrors the TS ``output-parser-file.test.ts`` / C# ``OutputParserGeneratorTests``
contracts adapted to Python's single-API throw-only convention: emit a
``parse_<name>(text)`` function returning a typed Pydantic model, raising
``pydantic.ValidationError`` on bad input. No ``safeParseX`` / ``TryParse``
companion — Pydantic is the throw-only ecosystem norm.
"""
from __future__ import annotations

import json

import metaobjects.core_types  # noqa: F401  — side-effect: registers attr classes
from metaobjects.codegen.config import GenConfig
from metaobjects.codegen.generator import GenContext
from metaobjects.codegen.generators.output_parser_generator import (
    OutputParserGenerator,
    _snake_case,
    output_parser_generator,
    render_output_parser,
)
from metaobjects.meta.core.field import field_constants as fc
from metaobjects.meta.core.field.meta_field import MetaField
from metaobjects.meta.core.object.meta_object import MetaObject
from metaobjects.meta.meta_root import MetaRoot
from metaobjects.meta.template import template_constants as tc
from metaobjects.meta.template.meta_template import MetaTemplate
from metaobjects.shared.base_types import (
    SUBTYPE_ROOT,
    TYPE_FIELD,
    TYPE_METADATA,
    TYPE_OBJECT,
    TYPE_TEMPLATE,
)


# ---------------------------------------------------------------------------
# Builders — minimal MetaRoot trees for the canonical fixture-style shape.
# ---------------------------------------------------------------------------


def _field(name: str, sub: str, *, required: bool = False) -> MetaField:
    f = MetaField(TYPE_FIELD, sub, name)
    if required:
        f.set_attr(fc.FIELD_ATTR_REQUIRED, True)
    return f


def _payload_vo(name: str, fields: list[MetaField], *, package: str | None = None) -> MetaObject:
    obj = MetaObject(TYPE_OBJECT, "value", name)
    obj.package = package
    for f in fields:
        obj.add_child(f)
    return obj


def _output_template(
    name: str,
    payload_ref: str,
    *,
    text_ref: str = "tpl/output",
    fmt: str = "json",
) -> MetaTemplate:
    tmpl = MetaTemplate(TYPE_TEMPLATE, tc.TEMPLATE_SUBTYPE_OUTPUT, name)
    tmpl.set_attr(tc.TEMPLATE_ATTR_PAYLOAD_REF, payload_ref)
    tmpl.set_attr(tc.TEMPLATE_ATTR_TEXT_REF, text_ref)
    tmpl.set_attr(tc.TEMPLATE_ATTR_FORMAT, fmt)
    return tmpl


def _root(children: list[MetaObject | MetaTemplate], *, package: str = "acme::ai") -> MetaRoot:
    root = MetaRoot(TYPE_METADATA, SUBTYPE_ROOT, "test")
    root.package = package
    for c in children:
        root.add_child(c)
    return root


def _ctx(root: MetaRoot, *, out_dir: str = "/tmp/out") -> GenContext:
    cfg = GenConfig(out_dir=out_dir)
    return GenContext(
        entities=[],
        loaded_root=root,
        matches=lambda _e: True,
        config=cfg,
        warn=lambda _m: None,
    )


def _npc_root() -> MetaRoot:
    """Mirrors fixtures/conformance/template-output-simple/input/*.json."""
    payload = _payload_vo(
        "NpcResponsePayload",
        [
            # @required so the strict Pydantic payload keeps them non-optional —
            # the missing-field round-trip below asserts parse raises when absent.
            _field("name", fc.FIELD_SUBTYPE_STRING, required=True),
            _field("age", fc.FIELD_SUBTYPE_INT, required=True),
        ],
    )
    tmpl = _output_template("NpcResponseOutput", "NpcResponsePayload")
    return _root([payload, tmpl])


# ---------------------------------------------------------------------------
# render_output_parser — text-level assertions on the emitted module.
# ---------------------------------------------------------------------------


def test_render_imports_payload_and_emits_parse_function() -> None:
    """Parser module imports ``<Name>Payload`` from the sibling payload module
    and exposes a throw-only ``parse_<name>(text)`` entry point."""
    out = render_output_parser(_npc_root().own_children()[1], _npc_root())
    assert out is not None
    # The strict PAYLOAD comes from the sibling payload module — no inline Pydantic
    # model. (FR-010 adds a separate nullable mirror dataclass for extract() — see
    # the extract tests below — but the strict payload class is never inlined.)
    assert "class NpcResponseOutputPayload(" not in out
    assert "from .npc_response_output_payload import NpcResponseOutputPayload" in out
    assert "def parse_npc_response_output(text: str) -> NpcResponseOutputPayload:" in out
    assert "return NpcResponseOutputPayload.model_validate_json(text)" in out


def test_render_includes_generated_header_no_pydantic_import() -> None:
    """Parser module carries the @generated header; pydantic is imported by the
    payload module, not the parser module."""
    out = render_output_parser(_npc_root().own_children()[1], _npc_root())
    assert out is not None
    assert "@generated by metaobjects" in out
    # Pydantic lives in the payload module now.
    assert "from pydantic import BaseModel" not in out


def test_render_returns_none_when_payload_ref_unresolved() -> None:
    tmpl = _output_template("StrayOutput", "DoesNotExist")
    root = _root([tmpl])
    assert render_output_parser(tmpl, root) is None


def test_render_returns_none_when_payload_ref_attr_missing() -> None:
    tmpl = MetaTemplate(TYPE_TEMPLATE, tc.TEMPLATE_SUBTYPE_OUTPUT, "Naked")
    root = _root([tmpl])
    assert render_output_parser(tmpl, root) is None


def test_render_returns_none_when_payload_ref_targets_entity_not_value() -> None:
    """Mirrors Kotlin's contract — ``@payloadRef`` MUST resolve to ``object.value``."""
    entity = MetaObject(TYPE_OBJECT, "entity", "Imposter")
    tmpl = _output_template("FailingOutput", "Imposter")
    root = _root([entity, tmpl])
    assert render_output_parser(tmpl, root) is None


# ---------------------------------------------------------------------------
# Generator — wraps render + iterates root for all template.output children.
# ---------------------------------------------------------------------------


def test_generator_emits_one_file_per_template_output() -> None:
    payload_a = _payload_vo("PayloadA", [_field("name", fc.FIELD_SUBTYPE_STRING)])
    payload_b = _payload_vo("PayloadB", [_field("count", fc.FIELD_SUBTYPE_INT)])
    tmpl_a = _output_template("AlphaOutput", "PayloadA")
    tmpl_b = _output_template("BetaOutput", "PayloadB")
    root = _root([payload_a, payload_b, tmpl_a, tmpl_b])

    files = OutputParserGenerator().generate(_ctx(root))
    paths = [f.path for f in files]
    assert paths == ["alpha_output_output_parser.py", "beta_output_output_parser.py"]


def test_generator_skips_unresolved_and_warns() -> None:
    tmpl = _output_template("StrayOutput", "DoesNotExist")
    root = _root([tmpl])
    warnings: list[str] = []
    ctx = GenContext(
        entities=[],
        loaded_root=root,
        matches=lambda _e: True,
        config=GenConfig(out_dir="/tmp/out"),
        warn=warnings.append,
    )
    files = OutputParserGenerator().generate(ctx)
    assert files == []
    assert any("StrayOutput" in w for w in warnings)


def test_generator_ignores_prompt_subtype() -> None:
    payload = _payload_vo("Payload", [_field("name", fc.FIELD_SUBTYPE_STRING)])
    prompt = MetaTemplate(TYPE_TEMPLATE, tc.TEMPLATE_SUBTYPE_PROMPT, "Greet")
    prompt.set_attr(tc.TEMPLATE_ATTR_PAYLOAD_REF, "Payload")
    prompt.set_attr(tc.TEMPLATE_ATTR_TEXT_REF, "greet")
    root = _root([payload, prompt])
    files = OutputParserGenerator().generate(_ctx(root))
    assert files == []


def test_factory_returns_generator_with_expected_name() -> None:
    gen = output_parser_generator()
    assert gen.name == "output-parser-generator"


# ---------------------------------------------------------------------------
# Round-trip — execute the emitted parser+payload pair as a package and verify
# Pydantic-shape behavior end-to-end. The parser module does ``from .<payload>
# import …``, so we need a real package on the filesystem (not a string exec).
# ---------------------------------------------------------------------------


def _materialize_package(files: list, payload_files: list, tmp_path) -> tuple[str, list[str]]:
    """Write *files* + *payload_files* into a real Python package under *tmp_path*
    and return ``(package_dir, modules_relative_to_package)``."""
    import os

    pkg_dir = str(tmp_path / "_gen_pkg")
    os.makedirs(pkg_dir, exist_ok=True)
    open(os.path.join(pkg_dir, "__init__.py"), "w").close()
    module_names: list[str] = []
    for f in [*payload_files, *files]:
        with open(os.path.join(pkg_dir, f.path), "w") as fh:
            fh.write(f.content)
        module_names.append(f.path[:-3])  # strip .py
    return pkg_dir, module_names


def _import_package(pkg_dir: str, monkeypatch) -> object:
    """Import the materialized package and return it."""
    import importlib
    import sys

    parent = pkg_dir.rsplit("/", 1)[0]
    monkeypatch.syspath_prepend(parent)
    # Drop any prior import cache for this throwaway package name.
    for k in list(sys.modules):
        if k == "_gen_pkg" or k.startswith("_gen_pkg."):
            del sys.modules[k]
    return importlib.import_module("_gen_pkg")


def test_emitted_module_parses_valid_payload(tmp_path, monkeypatch) -> None:
    from metaobjects.codegen.generators.payload_vo_generator import PayloadVoGenerator

    root = _npc_root()
    parser_files = OutputParserGenerator().generate(_ctx(root))
    payload_files = PayloadVoGenerator().generate(_ctx(root))
    assert len(parser_files) == 1
    pkg_dir, _ = _materialize_package(parser_files, payload_files, tmp_path)
    _import_package(pkg_dir, monkeypatch)
    from importlib import import_module
    parser_mod = import_module("_gen_pkg.npc_response_output_output_parser")
    result = parser_mod.parse_npc_response_output(json.dumps({"name": "Igor", "age": 42}))
    assert result.name == "Igor"
    assert result.age == 42


def test_emitted_module_raises_validation_error_on_bad_payload(tmp_path, monkeypatch) -> None:
    from importlib import import_module

    from pydantic import ValidationError

    from metaobjects.codegen.generators.payload_vo_generator import PayloadVoGenerator

    root = _npc_root()
    parser_files = OutputParserGenerator().generate(_ctx(root))
    payload_files = PayloadVoGenerator().generate(_ctx(root))
    pkg_dir, _ = _materialize_package(parser_files, payload_files, tmp_path)
    _import_package(pkg_dir, monkeypatch)
    parser_mod = import_module("_gen_pkg.npc_response_output_output_parser")
    try:
        parser_mod.parse_npc_response_output(json.dumps({"name": "Igor", "age": "forty-two"}))
    except ValidationError:
        return
    raise AssertionError("Expected ValidationError for non-int age")


def test_emitted_module_raises_on_missing_field(tmp_path, monkeypatch) -> None:
    from importlib import import_module

    from pydantic import ValidationError

    from metaobjects.codegen.generators.payload_vo_generator import PayloadVoGenerator

    root = _npc_root()
    parser_files = OutputParserGenerator().generate(_ctx(root))
    payload_files = PayloadVoGenerator().generate(_ctx(root))
    pkg_dir, _ = _materialize_package(parser_files, payload_files, tmp_path)
    _import_package(pkg_dir, monkeypatch)
    parser_mod = import_module("_gen_pkg.npc_response_output_output_parser")
    try:
        parser_mod.parse_npc_response_output(json.dumps({"name": "Igor"}))
    except ValidationError:
        return
    raise AssertionError("Expected ValidationError for missing 'age'")


# ---------------------------------------------------------------------------
# Snake-case helper — same shape as the router_generator's local helper.
# ---------------------------------------------------------------------------


def test_snake_case_pascal_to_snake() -> None:
    assert _snake_case("NpcResponseOutput") == "npc_response_output"
    assert _snake_case("Alpha") == "alpha"
    assert _snake_case("ABC") == "a_b_c"
