import metaobjects.core_types  # noqa: F401  — side-effect: registers attr classes (set_attr needs them)
from metaobjects.codegen.generators.entity_model import render_entity_model
from metaobjects.meta.core.object.meta_object import MetaObject
from metaobjects.meta.core.field.meta_field import MetaField
from metaobjects.meta.core.field import field_constants as fc
from metaobjects.shared.base_types import TYPE_OBJECT, TYPE_FIELD


def _entity(name, fields, *, super_data=None, package=None):
    o = MetaObject(TYPE_OBJECT, "entity", name)
    o.package = package
    o.super_data = super_data
    for f in fields:
        o.add_child(f)
    return o


def _f(name, sub, *, required=False, max_length=None, is_array=False, object_ref=None):
    f = MetaField(TYPE_FIELD, sub, name)
    f.is_array = is_array
    if required:
        f.set_attr(fc.FIELD_ATTR_REQUIRED, True)
    if max_length is not None:
        f.set_attr(fc.FIELD_ATTR_MAX_LENGTH, max_length)
    if object_ref is not None:
        f.set_attr(fc.FIELD_ATTR_OBJECT_REF, object_ref)
    return f


def test_vanilla_entity_model():
    e = _entity("Subscriber", [
        _f("email", fc.FIELD_SUBTYPE_STRING, required=True, max_length=200),
        _f("subscribed", fc.FIELD_SUBTYPE_BOOLEAN),
    ], package="myapp::users")
    out = render_entity_model(e)
    assert "@generated by metaobjects" in out
    assert "from pydantic import BaseModel, Field" in out
    assert "class Subscriber(BaseModel):" in out
    assert "email: str = Field(max_length=200)" in out
    assert "subscribed: bool | None = None" in out


def test_extends_subclasses_base_and_imports_it():
    base = _entity("BaseEntity", [_f("id", fc.FIELD_SUBTYPE_INT, required=True)])
    child = _entity("Program", [_f("name", fc.FIELD_SUBTYPE_STRING, required=True)], super_data=base)
    out = render_entity_model(child)
    assert "from .BaseEntity import BaseEntity" in out
    assert "class Program(BaseEntity):" in out
    assert "name: str" in out
    assert "id" not in out  # inherited; not re-emitted (own_fields only)


def test_nested_object_array_imports_ref():
    e = _entity("AuthorBrief", [
        _f("displayName", fc.FIELD_SUBTYPE_STRING, required=True),
        _f("posts", fc.FIELD_SUBTYPE_OBJECT, object_ref="PostBrief", is_array=True),
    ])
    out = render_entity_model(e)
    assert "from .PostBrief import PostBrief" in out
    assert "posts: list[PostBrief] | None = None" in out
