import importlib.util
import sys
import tempfile
import uuid as _uuid
from pathlib import Path

import pytest
from pydantic import ValidationError

import metaobjects.core_types  # noqa: F401  — side-effect: registers attr classes (set_attr needs them)
from metaobjects.codegen.generators.entity_model import render_entity_model
from metaobjects.meta.core.object.meta_object import MetaObject
from metaobjects.meta.core.field.meta_field import MetaField
from metaobjects.meta.core.field import field_constants as fc
from metaobjects.meta.core.identity import identity_constants as ic
from metaobjects.meta.core.identity.meta_identity import MetaIdentity
from metaobjects.shared.base_types import TYPE_IDENTITY, TYPE_OBJECT, TYPE_FIELD


def _entity(
    name: str,
    fields: list[MetaField],
    *,
    super_data: MetaObject | None = None,
    package: str | None = None,
) -> MetaObject:
    o = MetaObject(TYPE_OBJECT, "entity", name)
    o.package = package
    o.super_data = super_data
    for f in fields:
        o.add_child(f)
    return o


def _f(
    name: str,
    sub: str,
    *,
    required: bool = False,
    max_length: int | None = None,
    is_array: bool = False,
    object_ref: str | None = None,
) -> MetaField:
    f = MetaField(TYPE_FIELD, sub, name)
    f.is_array = is_array
    if required:
        f.set_attr(fc.FIELD_ATTR_REQUIRED, True)
    if max_length is not None:
        f.set_attr(fc.FIELD_ATTR_MAX_LENGTH, max_length)
    if object_ref is not None:
        f.set_attr(fc.FIELD_ATTR_OBJECT_REF, object_ref)
    return f


def _primary_identity(fields: list[str], generation: str) -> MetaIdentity:
    ident = MetaIdentity(TYPE_IDENTITY, ic.IDENTITY_SUBTYPE_PRIMARY, "primary")
    ident.set_attr(ic.IDENTITY_ATTR_FIELDS, fields)
    ident.set_attr(ic.IDENTITY_ATTR_GENERATION, generation)
    return ident


def _load_models(entity: MetaObject):
    """Render *entity*'s model and import it as a REAL module (registered in
    ``sys.modules``) so pydantic can resolve forward-ref annotations (datetime / uuid),
    then return the module. Mirrors how the generated api-contract lanes import the
    emitted model before constructing it."""
    src = render_entity_model(entity)
    mod_name = f"genmodel_{_uuid.uuid4().hex[:8]}"
    path = Path(tempfile.mkdtemp()) / f"{mod_name}.py"
    path.write_text(src)
    spec = importlib.util.spec_from_file_location(mod_name, path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    sys.modules[mod_name] = mod
    spec.loader.exec_module(mod)
    return mod


def test_vanilla_entity_model() -> None:
    e = _entity("Subscriber", [
        _f("email", fc.FIELD_SUBTYPE_STRING, required=True, max_length=200),
        _f("subscribed", fc.FIELD_SUBTYPE_BOOLEAN),
    ], package="myapp::users")
    out = render_entity_model(e)
    assert "@generated by metaobjects" in out
    assert "from pydantic import BaseModel, Field" in out
    assert "class Subscriber(BaseModel):" in out
    # FR-036 Pin 1: a @required string carries an implicit min_length=1 (non-empty).
    assert "email: str = Field(min_length=1, max_length=200)" in out
    assert "subscribed: bool | None = None" in out


def test_extends_subclasses_base_and_imports_it() -> None:
    base = _entity("BaseEntity", [_f("id", fc.FIELD_SUBTYPE_INT, required=True)])
    child = _entity("Program", [_f("name", fc.FIELD_SUBTYPE_STRING, required=True)], super_data=base)
    out = render_entity_model(child)
    assert "from .BaseEntity import BaseEntity" in out
    assert "class Program(BaseEntity):" in out
    assert "name: str" in out
    # The MAIN model emits OWN fields only — the inherited id is not re-emitted in the
    # Program class body (ADR-0039 subclass-emit). The flat FR-036 ProgramCreate /
    # ProgramPatch models DO restate id (all effective fields), so scope to the read
    # model by splitting on the first generated validation model.
    main_body = out.split("class ProgramCreate")[0]
    assert "id" not in main_body


def test_nested_object_array_imports_ref() -> None:
    e = _entity("AuthorBrief", [
        _f("displayName", fc.FIELD_SUBTYPE_STRING, required=True),
        _f("posts", fc.FIELD_SUBTYPE_OBJECT, object_ref="PostBrief", is_array=True),
    ])
    out = render_entity_model(e)
    assert "from .PostBrief import PostBrief" in out
    assert "posts: list[PostBrief] | None = None" in out


def test_column_attr_overrides_python_field_name() -> None:
    """A field's ``@column`` (the physical DB column) is the READ-model Pydantic field
    name when present, falling back to ``field.name``. This lets one entity carry the
    camelCase ``field.name`` the TS port emits as a property AND the snake_case
    ``@column`` the Python read model emits as the model field (= DB column), so a single
    cross-port entity feeds both languages idiomatically. The FR-036 create/patch
    VALIDATION models, by contrast, key by the WIRE name (field.name) — the router
    validates the raw wire body (see test_create_model_validates_against_wire_name)."""
    f = _f("callPurpose", fc.FIELD_SUBTYPE_STRING, required=True)
    f.set_attr(fc.FIELD_ATTR_COLUMN, "call_purpose")
    e = _entity("LlmCall", [f], package="app::telemetry")
    out = render_entity_model(e)
    # Scope to the read model (before the first validation model): it binds @column.
    read_model = out.split("class LlmCallCreate")[0]
    assert "call_purpose: str" in read_model
    assert "callPurpose" not in read_model


def test_field_name_used_when_no_column_attr() -> None:
    """Backward-compat: with no ``@column``, the Pydantic field name is ``field.name``
    verbatim (so snake-authored models regenerate byte-identically)."""
    e = _entity("Subscriber", [_f("email_address", fc.FIELD_SUBTYPE_STRING, required=True)])
    out = render_entity_model(e)
    assert "email_address: str" in out


def test_server_default_expression_is_not_a_python_default() -> None:
    """A server-side default EXPRESSION (gen_random_uuid(), now(), CURRENT_TIMESTAMP)
    is filled by the database, not the Python model — so it must NOT become a Pydantic
    field default (``id: uuid.UUID = "gen_random_uuid()"`` is invalid). The field keeps
    its required/optional shape with no Python default. Mirrors the TS column-mapper's
    SQL_EXPR_PATTERNS so both ports agree on what's an expression."""
    fid = _f("id", fc.FIELD_SUBTYPE_UUID, required=True)
    fid.set_attr(fc.FIELD_ATTR_DEFAULT, "gen_random_uuid()")
    fts = _f("started_at", fc.FIELD_SUBTYPE_TIMESTAMP, required=True)
    fts.set_attr(fc.FIELD_ATTR_DEFAULT, "now()")
    fcur = _f("logged_at", fc.FIELD_SUBTYPE_TIMESTAMP)
    fcur.set_attr(fc.FIELD_ATTR_DEFAULT, "CURRENT_TIMESTAMP")
    out = render_entity_model(_entity("Row", [fid, fts, fcur]))
    assert "id: uuid.UUID" in out
    assert "gen_random_uuid" not in out
    assert "started_at: datetime.datetime" in out
    assert "now()" not in out
    assert "logged_at: datetime.datetime | None = None" in out
    assert "CURRENT_TIMESTAMP" not in out


def test_literal_default_is_still_emitted() -> None:
    """A non-expression default (a string literal, bool, number) stays a Python default."""
    fstatus = _f("status", fc.FIELD_SUBTYPE_STRING)
    fstatus.set_attr(fc.FIELD_ATTR_DEFAULT, "active")
    fflag = _f("enabled", fc.FIELD_SUBTYPE_BOOLEAN)
    fflag.set_attr(fc.FIELD_ATTR_DEFAULT, True)
    out = render_entity_model(_entity("Row", [fstatus, fflag]))
    assert "status: str = 'active'" in out
    assert "enabled: bool = True" in out


def test_header_fqn_folds_file_default_package_after_merge() -> None:
    """After a multi-file merge an object hangs under one package-less merged
    root, so the naive nearest-ancestor walk would fold every object onto the
    alphabetically-first file's package. The header FQN must instead use the
    canonical ``resolution_key`` (own → file-default → ancestor), so an object
    keeps its true source-file package regardless of merge order."""
    from metaobjects.codegen.generators.entity_model import _effective_fqn

    obj = _entity("ClaimComplexity", [_f("confidence", fc.FIELD_SUBTYPE_DOUBLE)])
    # Post-merge shape: no own package, captured file-default from its real file,
    # parent is the merged super-root carrying a DIFFERENT (first-file) package.
    obj.file_default_package = "app::reasoning"
    merged_root = _entity("_merged", [], package="app::orchestration")
    merged_root.add_child(obj)

    assert _effective_fqn(obj) == "app::reasoning::ClaimComplexity"


def test_object_ref_fqn_is_shortened_to_class_name() -> None:
    """@objectRef is FQN-expanded at load time (``app::pkg::Thing``); the type
    annotation and the relative import must use the bare class name, not the
    raw FQN (which is not valid Python). Regression: object.value VOs emitted
    ``list[app::pkg::Thing]`` and ``from .app::pkg::Thing import ...``."""
    e = _entity("Catalog", [
        _f("tools", fc.FIELD_SUBTYPE_OBJECT, object_ref="myapp::orch::ToolDescriptor", is_array=True),
    ])
    out = render_entity_model(e)
    assert "from .ToolDescriptor import ToolDescriptor" in out
    assert "tools: list[ToolDescriptor] | None = None" in out
    assert "::" not in out


def test_field_default_is_emitted_as_literal() -> None:
    """@default renders a Python-literal default and makes the field non-Optional."""
    flag = MetaField(TYPE_FIELD, fc.FIELD_SUBTYPE_BOOLEAN, "flag")
    flag.set_attr(fc.FIELD_ATTR_DEFAULT, False)
    n = MetaField(TYPE_FIELD, fc.FIELD_SUBTYPE_INT, "n")
    n.set_attr(fc.FIELD_ATTR_DEFAULT, 1)
    c = MetaField(TYPE_FIELD, fc.FIELD_SUBTYPE_DOUBLE, "c")
    c.set_attr(fc.FIELD_ATTR_DEFAULT, 0.5)
    s = MetaField(TYPE_FIELD, fc.FIELD_SUBTYPE_STRING, "s")
    s.set_attr(fc.FIELD_ATTR_DEFAULT, "approx")
    out = render_entity_model(_entity("M", [flag, n, c, s]))
    assert "flag: bool = False" in out
    assert "n: int = 1" in out
    assert "c: float = 0.5" in out
    assert "s: str = 'approx'" in out


def test_dbcolumntype_jsonb_field_is_any_with_import() -> None:
    """Issue #98 — a field.string @dbColumnType:jsonb stores genuinely-open JSON,
    which pg8000 decodes to a native Python object at read time. The generated
    Pydantic field is typed ``Any`` (not the lying ``str``) and the module threads
    ``from typing import Any`` into its import block."""
    from metaobjects.meta.persistence.db import db_constants as dbc

    payload = MetaField(TYPE_FIELD, fc.FIELD_SUBTYPE_STRING, "payload")
    payload.set_attr(dbc.FIELD_ATTR_DB_COLUMN_TYPE, dbc.DB_COLUMN_TYPE_JSONB)
    out = render_entity_model(_entity("Event", [payload], package="myapp::events"))
    assert "from typing import Any" in out
    assert "payload: Any | None = None" in out


# --------------------------------------------------------------------------- #
# FR-036 — the CREATE/PATCH validation models the router binds (findings #1–#4).
# The router validates the raw WIRE body against these (POST → <Entity>Create,
# PATCH → <Entity>Patch), so they must reflect the create/patch SHAPE, not the
# read/entity shape.
# --------------------------------------------------------------------------- #


def test_create_model_makes_server_filled_required_fields_optional() -> None:
    """FR-036 #1 (REGRESSION) — a @required field with a server-side @default (a SQL
    expression like ``now()``) or an @autoSet is DB/trigger-filled, so the
    CREATE-validation model makes it OPTIONAL: a POST that omits it must not 400. A
    genuinely-@required field (no default / autoSet) stays required."""
    expr_default = _f("createdAt", fc.FIELD_SUBTYPE_TIMESTAMP, required=True)
    expr_default.set_attr(fc.FIELD_ATTR_DEFAULT, "now()")
    auto_set = _f("updatedAt", fc.FIELD_SUBTYPE_TIMESTAMP, required=True)
    auto_set.set_attr(fc.FIELD_ATTR_AUTO_SET, fc.AUTO_SET_ON_UPDATE)
    name = _f("name", fc.FIELD_SUBTYPE_STRING, required=True, max_length=50)
    mod = _load_models(_entity("Widget", [expr_default, auto_set, name], package="app::w"))

    # createdAt (SQL-expr default) + updatedAt (@autoSet) omitted → constructs cleanly.
    inst = mod.WidgetCreate(name="ok")
    assert inst.createdAt is None and inst.updatedAt is None
    # The genuinely-@required name is still enforced.
    with pytest.raises(ValidationError):
        mod.WidgetCreate()


def test_create_model_excludes_auto_generated_pk() -> None:
    """FR-036 #2 (REGRESSION) — an auto-generated PK (identity.primary @generation) is
    server-assigned, so it is EXCLUDED from the CREATE-validation model even when the PK
    field is @required: a POST omitting the id must not 400."""
    pk = _f("id", fc.FIELD_SUBTYPE_LONG, required=True)
    label = _f("label", fc.FIELD_SUBTYPE_STRING, required=True, max_length=80)
    e = _entity("Gadget", [pk, label], package="app::g")
    e.add_child(_primary_identity(["id"], ic.GENERATION_INCREMENT))
    mod = _load_models(e)

    assert "id" not in mod.GadgetCreate.model_fields
    # Omitting the server-assigned id constructs cleanly (label supplied).
    assert mod.GadgetCreate(label="anvil").label == "anvil"


def test_create_model_validates_against_wire_name_not_column() -> None:
    """FR-036 #3 (constraint bypass) — the router validates the raw WIRE body (field.name
    keys), so the CREATE-validation model must key by the wire name, NOT @column;
    otherwise pydantic's ``extra='ignore'`` DROPS the wire key and never enforces its
    @maxLength. The read/entity model keeps its @column naming (unchanged)."""
    f = _f("fullName", fc.FIELD_SUBTYPE_STRING, required=True, max_length=5)
    f.set_attr(fc.FIELD_ATTR_COLUMN, "full_name")
    mod = _load_models(_entity("Person", [f], package="app::p"))

    # Read model keeps the @column name; the create model keys by the wire name.
    assert "full_name" in mod.Person.model_fields
    assert "fullName" in mod.PersonCreate.model_fields
    # An over-length WIRE value is now actually rejected (was silently dropped before).
    with pytest.raises(ValidationError):
        mod.PersonCreate(fullName="toolong")
    assert mod.PersonCreate(fullName="ok").fullName == "ok"


def test_patch_model_excludes_primary_key() -> None:
    """FR-036 #4 — the PK is route-authoritative (taken from the URL), so it is EXCLUDED
    from the all-optional <Entity>Patch model (TS/C#/Java exclude it too)."""
    pk = _f("id", fc.FIELD_SUBTYPE_LONG, required=True)
    name = _f("name", fc.FIELD_SUBTYPE_STRING, max_length=80)
    e = _entity("Article", [pk, name], package="app::a")
    e.add_child(_primary_identity(["id"], ic.GENERATION_INCREMENT))
    mod = _load_models(e)

    assert "id" not in mod.ArticlePatch.model_fields
    assert "name" in mod.ArticlePatch.model_fields
