"""Tests for the template.output parser generator (FR-006).

Mirrors the TS ``output-parser-file.test.ts`` / C# ``OutputParserGeneratorTests``
contracts adapted to Python's single-API throw-only convention: emit a
``parse_<name>(text)`` function returning a typed Pydantic model, raising
``pydantic.ValidationError`` on bad input. No ``safeParseX`` / ``TryParse``
companion — Pydantic is the throw-only ecosystem norm.
"""
from __future__ import annotations

import json

import metaobjects.core_types  # noqa: F401  — side-effect: registers attr classes
from metaobjects.codegen.config import GenConfig
from metaobjects.codegen.generator import GenContext
from metaobjects.codegen.generators.output_parser_generator import (
    OutputParserGenerator,
    _snake_case,
    output_parser_generator,
    render_output_parser,
)
from metaobjects.meta.core.field import field_constants as fc
from metaobjects.meta.core.field.meta_field import MetaField
from metaobjects.meta.core.object.meta_object import MetaObject
from metaobjects.meta.meta_root import MetaRoot
from metaobjects.meta.template import template_constants as tc
from metaobjects.meta.template.meta_template import MetaTemplate
from metaobjects.shared.base_types import (
    SUBTYPE_ROOT,
    TYPE_FIELD,
    TYPE_METADATA,
    TYPE_OBJECT,
    TYPE_TEMPLATE,
)


# ---------------------------------------------------------------------------
# Builders — minimal MetaRoot trees for the canonical fixture-style shape.
# ---------------------------------------------------------------------------


def _field(name: str, sub: str) -> MetaField:
    return MetaField(TYPE_FIELD, sub, name)


def _payload_vo(name: str, fields: list[MetaField], *, package: str | None = None) -> MetaObject:
    obj = MetaObject(TYPE_OBJECT, "value", name)
    obj.package = package
    for f in fields:
        obj.add_child(f)
    return obj


def _output_template(
    name: str,
    payload_ref: str,
    *,
    text_ref: str = "tpl/output",
    fmt: str = "json",
) -> MetaTemplate:
    tmpl = MetaTemplate(TYPE_TEMPLATE, tc.TEMPLATE_SUBTYPE_OUTPUT, name)
    tmpl.set_attr(tc.TEMPLATE_ATTR_PAYLOAD_REF, payload_ref)
    tmpl.set_attr(tc.TEMPLATE_ATTR_TEXT_REF, text_ref)
    tmpl.set_attr(tc.TEMPLATE_ATTR_FORMAT, fmt)
    return tmpl


def _root(children: list[MetaObject | MetaTemplate], *, package: str = "acme::ai") -> MetaRoot:
    root = MetaRoot(TYPE_METADATA, SUBTYPE_ROOT, "test")
    root.package = package
    for c in children:
        root.add_child(c)
    return root


def _ctx(root: MetaRoot, *, out_dir: str = "/tmp/out") -> GenContext:
    cfg = GenConfig(out_dir=out_dir)
    return GenContext(
        entities=[],
        loaded_root=root,
        matches=lambda _e: True,
        config=cfg,
        warn=lambda _m: None,
    )


def _npc_root() -> MetaRoot:
    """Mirrors fixtures/conformance/template-output-simple/input/*.json."""
    payload = _payload_vo(
        "NpcResponsePayload",
        [_field("name", fc.FIELD_SUBTYPE_STRING), _field("age", fc.FIELD_SUBTYPE_INT)],
    )
    tmpl = _output_template("NpcResponseOutput", "NpcResponsePayload")
    return _root([payload, tmpl])


# ---------------------------------------------------------------------------
# render_output_parser — text-level assertions on the emitted module.
# ---------------------------------------------------------------------------


def test_render_emits_class_and_parse_function() -> None:
    out = render_output_parser(_npc_root().own_children()[1], _npc_root())
    assert out is not None
    assert "class NpcResponseOutputData(BaseModel):" in out
    assert "name: str" in out
    assert "age: int" in out
    assert "def parse_npc_response_output(text: str) -> NpcResponseOutputData:" in out
    assert "model_validate_json(text)" in out


def test_render_includes_generated_header_and_pydantic_import() -> None:
    out = render_output_parser(_npc_root().own_children()[1], _npc_root())
    assert out is not None
    assert "@generated by metaobjects" in out
    assert "from pydantic import BaseModel" in out


def test_render_returns_none_when_payload_ref_unresolved() -> None:
    tmpl = _output_template("StrayOutput", "DoesNotExist")
    root = _root([tmpl])
    assert render_output_parser(tmpl, root) is None


def test_render_returns_none_when_payload_ref_attr_missing() -> None:
    tmpl = MetaTemplate(TYPE_TEMPLATE, tc.TEMPLATE_SUBTYPE_OUTPUT, "Naked")
    root = _root([tmpl])
    assert render_output_parser(tmpl, root) is None


def test_render_field_type_mapping_covers_core_subtypes() -> None:
    payload = _payload_vo(
        "FullShape",
        [
            _field("s", fc.FIELD_SUBTYPE_STRING),
            _field("i", fc.FIELD_SUBTYPE_INT),
            _field("l", fc.FIELD_SUBTYPE_LONG),
            _field("d", fc.FIELD_SUBTYPE_DOUBLE),
            _field("b", fc.FIELD_SUBTYPE_BOOLEAN),
            _field("c", fc.FIELD_SUBTYPE_CURRENCY),
            _field("t", fc.FIELD_SUBTYPE_TIMESTAMP),
        ],
    )
    tmpl = _output_template("FullShapeOutput", "FullShape")
    root = _root([payload, tmpl])
    out = render_output_parser(tmpl, root)
    assert out is not None
    assert "s: str" in out
    assert "i: int" in out
    assert "l: int" in out
    assert "d: float" in out
    assert "b: bool" in out
    assert "c: int" in out
    assert "t: datetime" in out
    assert "from datetime import datetime" in out


def test_render_emits_pass_for_payload_with_no_fields() -> None:
    payload = _payload_vo("Empty", [])
    tmpl = _output_template("EmptyOutput", "Empty")
    root = _root([payload, tmpl])
    out = render_output_parser(tmpl, root)
    assert out is not None
    assert "class EmptyOutputData(BaseModel):" in out
    assert "    pass" in out


# ---------------------------------------------------------------------------
# Generator — wraps render + iterates root for all template.output children.
# ---------------------------------------------------------------------------


def test_generator_emits_one_file_per_template_output() -> None:
    payload_a = _payload_vo("PayloadA", [_field("name", fc.FIELD_SUBTYPE_STRING)])
    payload_b = _payload_vo("PayloadB", [_field("count", fc.FIELD_SUBTYPE_INT)])
    tmpl_a = _output_template("AlphaOutput", "PayloadA")
    tmpl_b = _output_template("BetaOutput", "PayloadB")
    root = _root([payload_a, payload_b, tmpl_a, tmpl_b])

    files = OutputParserGenerator().generate(_ctx(root))
    paths = [f.path for f in files]
    assert paths == ["alpha_output_output_parser.py", "beta_output_output_parser.py"]


def test_generator_skips_unresolved_and_warns() -> None:
    tmpl = _output_template("StrayOutput", "DoesNotExist")
    root = _root([tmpl])
    warnings: list[str] = []
    ctx = GenContext(
        entities=[],
        loaded_root=root,
        matches=lambda _e: True,
        config=GenConfig(out_dir="/tmp/out"),
        warn=warnings.append,
    )
    files = OutputParserGenerator().generate(ctx)
    assert files == []
    assert any("StrayOutput" in w for w in warnings)


def test_generator_ignores_prompt_subtype() -> None:
    payload = _payload_vo("Payload", [_field("name", fc.FIELD_SUBTYPE_STRING)])
    prompt = MetaTemplate(TYPE_TEMPLATE, tc.TEMPLATE_SUBTYPE_PROMPT, "Greet")
    prompt.set_attr(tc.TEMPLATE_ATTR_PAYLOAD_REF, "Payload")
    prompt.set_attr(tc.TEMPLATE_ATTR_TEXT_REF, "greet")
    root = _root([payload, prompt])
    files = OutputParserGenerator().generate(_ctx(root))
    assert files == []


def test_factory_returns_generator_with_expected_name() -> None:
    gen = output_parser_generator()
    assert gen.name == "output-parser-generator"


# ---------------------------------------------------------------------------
# Round-trip — execute the emitted source and verify Pydantic-shape behavior.
# ---------------------------------------------------------------------------


def _exec_module(source: str) -> dict:
    ns: dict = {}
    exec(compile(source, "<output_parser_test>", "exec"), ns)
    return ns


def test_emitted_module_parses_valid_payload() -> None:
    files = OutputParserGenerator().generate(_ctx(_npc_root()))
    assert len(files) == 1
    ns = _exec_module(files[0].content)
    result = ns["parse_npc_response_output"](json.dumps({"name": "Igor", "age": 42}))
    assert result.name == "Igor"
    assert result.age == 42


def test_emitted_module_raises_validation_error_on_bad_payload() -> None:
    from pydantic import ValidationError

    files = OutputParserGenerator().generate(_ctx(_npc_root()))
    ns = _exec_module(files[0].content)
    parse_fn = ns["parse_npc_response_output"]
    try:
        parse_fn(json.dumps({"name": "Igor", "age": "forty-two"}))
    except ValidationError:
        return
    raise AssertionError("Expected ValidationError for non-int age")


def test_emitted_module_raises_on_missing_field() -> None:
    from pydantic import ValidationError

    files = OutputParserGenerator().generate(_ctx(_npc_root()))
    ns = _exec_module(files[0].content)
    parse_fn = ns["parse_npc_response_output"]
    try:
        parse_fn(json.dumps({"name": "Igor"}))
    except ValidationError:
        return
    raise AssertionError("Expected ValidationError for missing 'age'")


# ---------------------------------------------------------------------------
# Snake-case helper — same shape as the router_generator's local helper.
# ---------------------------------------------------------------------------


def test_snake_case_pascal_to_snake() -> None:
    assert _snake_case("NpcResponseOutput") == "npc_response_output"
    assert _snake_case("Alpha") == "alpha"
    assert _snake_case("ABC") == "a_b_c"
