"""Identity subtype + attr vocabulary (colocated)."""
IDENTITY_SUBTYPE_PRIMARY = "primary"
IDENTITY_SUBTYPE_SECONDARY = "secondary"
IDENTITY_SUBTYPE_REFERENCE = "reference"
IDENTITY_SUBTYPES = (IDENTITY_SUBTYPE_PRIMARY, IDENTITY_SUBTYPE_SECONDARY, IDENTITY_SUBTYPE_REFERENCE)

IDENTITY_ATTR_FIELDS = "fields"
IDENTITY_ATTR_GENERATION = "generation"
IDENTITY_ATTR_UNIQUE = "unique"

# Allowed values for @generation on identity.primary
GENERATION_INCREMENT = "increment"
GENERATION_UUID = "uuid"
GENERATION_ASSIGNED = "assigned"
GENERATION_VALUES = (GENERATION_INCREMENT, GENERATION_UUID, GENERATION_ASSIGNED)

# identity.reference attrs: target entity and enforcement flag
IDENTITY_REFERENCE_ATTR_REFERENCES = "references"
IDENTITY_REFERENCE_ATTR_ENFORCE = "enforce"
