"""Identity subtype + attr vocabulary (colocated)."""
IDENTITY_SUBTYPE_PRIMARY = "primary"
IDENTITY_SUBTYPE_SECONDARY = "secondary"
IDENTITY_SUBTYPES = (IDENTITY_SUBTYPE_PRIMARY, IDENTITY_SUBTYPE_SECONDARY)

IDENTITY_ATTR_FIELDS = "fields"
IDENTITY_ATTR_GENERATION = "generation"

# Allowed values for @generation on identity.primary
GENERATION_INCREMENT = "increment"
GENERATION_UUID = "uuid"
GENERATION_ASSIGNED = "assigned"
GENERATION_VALUES = (GENERATION_INCREMENT, GENERATION_UUID, GENERATION_ASSIGNED)
