"""Sidecar manifest + staleness nudge for the agent-context scaffolder.

The assembly path (assemble / plan_scaffold / ScaffoldDecision) has been removed —
that work is now owned by the Node ``meta agent-docs`` CLI. This module retains
only the staleness-nudge machinery (``agent_context_staleness``, ``Manifest``,
``AGENT_CONTEXT_MANIFEST_PATH``, ``installed_metaobjects_version``) which is used
by ``gen``/``verify`` to detect when the scaffolded agent context predates the
installed MetaObjects version.
"""

from __future__ import annotations

from dataclasses import dataclass
from importlib.metadata import PackageNotFoundError, version as _pkg_version

#: Consumer-relative path of the sidecar manifest that tracks scaffolded files.
AGENT_CONTEXT_MANIFEST_PATH = ".metaobjects/.agent-context.json"


def installed_metaobjects_version() -> str:
    """The installed ``metaobjects`` distribution version, or ``"0.0.0"`` if absent.

    Resolved idiomatically via :func:`importlib.metadata.version`; a
    ``PackageNotFoundError`` (e.g. running straight from a source checkout that
    was never installed) falls back to ``"0.0.0"`` — mirroring the TS reference's
    fallback so the stamp/nudge never crashes.
    """
    try:
        return _pkg_version("metaobjects")
    except PackageNotFoundError:
        return "0.0.0"


@dataclass
class Manifest:
    """Tracks what the assembler last wrote, so re-runs can detect hand-edits."""

    version: int
    servers: list[str]
    clients: list[str]
    #: consumer-relative path → sha256 of the contents as last scaffolded.
    files: dict[str, str]
    #: The MetaObjects version that last scaffolded this context. Drives the
    #: staleness nudge (an upgrade can leave the copied-in skills/docs stale).
    #: Optional for back-compat with manifests written before version tracking.
    #: Serialized as ``generatedBy`` — the SAME key as the TS reference, so a
    #: polyglot repo can cross-read the manifest regardless of which port wrote it.
    generated_by: str | None = None

    def to_json(self) -> dict[str, object]:
        out: dict[str, object] = {"version": self.version}
        if self.generated_by is not None:
            out["generatedBy"] = self.generated_by
        out["servers"] = list(self.servers)
        out["clients"] = list(self.clients)
        out["files"] = dict(self.files)
        return out

    @staticmethod
    def from_json(data: dict[str, object]) -> "Manifest":
        files_raw = data.get("files", {})
        files = (
            {str(k): str(v) for k, v in files_raw.items()}
            if isinstance(files_raw, dict)
            else {}
        )
        servers = data.get("servers", [])
        clients = data.get("clients", [])
        generated_by = data.get("generatedBy")
        return Manifest(
            version=int(data.get("version", 1)),  # type: ignore[arg-type]
            servers=[str(x) for x in servers] if isinstance(servers, list) else [],
            clients=[str(x) for x in clients] if isinstance(clients, list) else [],
            files=files,
            generated_by=str(generated_by) if generated_by is not None else None,
        )


def agent_context_staleness(
    manifest: dict[str, object] | None, current_version: str
) -> str | None:
    """One-line nudge if the scaffolded agent context predates the install.

    Returns ``None`` when there is nothing to say — no agent context here, or it
    is in sync — and a one-line advisory message otherwise. Pure + advisory:
    never raises, never blocks, never writes.

    The comparison is **exact equality** on purpose: ANY drift nudges (a
    re-scaffold is cheap + idempotent). Do NOT "fix" this into a semver compare —
    a prerelease/build-metadata difference is still a reason to refresh.
    """
    if manifest is None:
        return None  # no agent context here → nothing to nudge
    generated_by = manifest.get("generatedBy")
    if generated_by == current_version:
        return None  # in sync
    frm = generated_by if generated_by else "an older MetaObjects"
    return (
        f"MetaObjects agent context was generated by {frm}; "
        f"you're on {current_version}. Run 'npx meta agent-docs --server python' to "
        f"refresh the .claude/skills docs."
    )
