"""Render-tier engine: the build-time template drift-check ``verify`` (FR-004), the
FR-010 tolerant ``recover`` parser, and the FR-010 output-format prompt renderer."""

from metaobjects.render.prompt import (
    PROMPT_OVERRIDES_NONE,
    OutputFormatSpec,
    PromptField,
    PromptOverrides,
    PromptStyle,
    no_overrides,
    prompt_style_from,
    render_output_format,
)
from metaobjects.render.recover import (
    FieldKind,
    FieldRecovery,
    FieldSpec,
    Format,
    RecoverOptions,
    RecoverOutcome,
    RecoverSchema,
    RecoveryReport,
    RecoveryResult,
    Tolerance,
    recover,
    recover_map,
)
from metaobjects.render.verify import (
    ERR_OUTPUT_TAG_MISSING,
    ERR_PARTIAL_UNRESOLVED,
    ERR_REQUIRED_SLOT_UNUSED,
    ERR_VAR_NOT_ON_PAYLOAD,
    InMemoryProvider,
    PayloadField,
    Provider,
    VerifyError,
    verify,
)

__all__ = [
    "ERR_OUTPUT_TAG_MISSING",
    "ERR_PARTIAL_UNRESOLVED",
    "ERR_REQUIRED_SLOT_UNUSED",
    "ERR_VAR_NOT_ON_PAYLOAD",
    "PROMPT_OVERRIDES_NONE",
    "FieldKind",
    "FieldRecovery",
    "FieldSpec",
    "Format",
    "InMemoryProvider",
    "OutputFormatSpec",
    "PayloadField",
    "PromptField",
    "PromptOverrides",
    "PromptStyle",
    "Provider",
    "RecoverOptions",
    "RecoverOutcome",
    "RecoverSchema",
    "RecoveryReport",
    "RecoveryResult",
    "Tolerance",
    "VerifyError",
    "no_overrides",
    "prompt_style_from",
    "recover",
    "recover_map",
    "render_output_format",
    "verify",
]
