"""Render-tier engine: the build-time template drift-check ``verify`` (FR-004), the
FR-010 tolerant ``extract`` parser, and the FR-010 output-format prompt renderer."""

from metaobjects.render.prompt import (
    PROMPT_OVERRIDES_NONE,
    OutputFormatSpec,
    PromptField,
    PromptOverrides,
    PromptStyle,
    no_overrides,
    prompt_style_from,
    render_output_format,
)
from metaobjects.render.extract import (
    FieldKind,
    FieldExtraction,
    FieldSpec,
    Format,
    ExtractOptions,
    ExtractionOutcome,
    ExtractSchema,
    ExtractionReport,
    ExtractionResult,
    Tolerance,
    extract,
    extract_map,
)
from metaobjects.render.verify import (
    ERR_OUTPUT_TAG_MISSING,
    ERR_PARTIAL_UNRESOLVED,
    ERR_REQUIRED_SLOT_UNUSED,
    ERR_VAR_NOT_ON_PAYLOAD,
    InMemoryProvider,
    PayloadField,
    Provider,
    VerifyError,
    verify,
)

__all__ = [
    "ERR_OUTPUT_TAG_MISSING",
    "ERR_PARTIAL_UNRESOLVED",
    "ERR_REQUIRED_SLOT_UNUSED",
    "ERR_VAR_NOT_ON_PAYLOAD",
    "PROMPT_OVERRIDES_NONE",
    "FieldKind",
    "FieldExtraction",
    "FieldSpec",
    "Format",
    "InMemoryProvider",
    "OutputFormatSpec",
    "PayloadField",
    "PromptField",
    "PromptOverrides",
    "PromptStyle",
    "Provider",
    "ExtractOptions",
    "ExtractionOutcome",
    "ExtractSchema",
    "ExtractionReport",
    "ExtractionResult",
    "Tolerance",
    "VerifyError",
    "no_overrides",
    "prompt_style_from",
    "extract",
    "extract_map",
    "render_output_format",
    "verify",
]
