using MetaObjects.Codegen;
using MetaObjects.Loader;
using Xunit;

namespace MetaObjects.Codegen.Tests;

/// <summary>
/// `dotnet meta verify --codegen` drift logic (ADR-0021 D2, C# port of the TS
/// codegen-drift reference). Regenerates the default suite into a TEMP tree and
/// diffs it against the committed output under the real out dir. A fresh regen
/// that matches is clean; a mutated / missing / extra committed file is drift.
/// Crucially: the real out dir is never touched (we only write to temp).
/// </summary>
public sealed class CodegenDriftTests : IDisposable
{
    private readonly string _tmp = Path.Combine(Path.GetTempPath(), "meta-codegen-drift-" + Guid.NewGuid().ToString("N"));
    private string MetaDir => Path.Combine(_tmp, "metaobjects");
    private string OutDir => Path.Combine(_tmp, "generated");

    private const string Metadata = """
    { "metadata.root": { "package": "acme", "children": [
      { "object.entity": { "name": "Subscriber", "children": [
        { "source.rdb": { "@table": "subscribers" } },
        { "field.long":   { "name": "id" } },
        { "field.string": { "name": "email", "@required": true } },
        { "identity.primary": { "@fields": "id" } }
      ]}}
    ]}}
    """;

    public CodegenDriftTests()
    {
        Directory.CreateDirectory(MetaDir);
        File.WriteAllText(Path.Combine(MetaDir, "meta.acme.json"), Metadata);
    }

    public void Dispose() { try { Directory.Delete(_tmp, recursive: true); } catch { } }

    // The default suite, resolved straight from the registry (the same names GenCommand
    // uses) — keeps Codegen.Tests independent of the Cli project. Kept in sync with
    // GenCommand.DefaultGeneratorNames (Python-parity eight; render-helper is opt-in).
    private static readonly IReadOnlyList<string> DefaultNames =
        ["entity", "db-context", "routes", "filter-allowlist", "payload", "output-parser", "output-prompt", "extractor"];

    private static IReadOnlyList<IGenerator> DefaultGenerators() => GeneratorRegistry.Resolve(DefaultNames);

    /// <summary>Generate the committed output exactly as `gen` would.</summary>
    private void Gen()
    {
        var load = MetaDataLoader.FromDirectory(MetaDir);
        Assert.Empty(load.Errors);
        var config = new GenConfig { OutDir = OutDir, Namespace = "Acme.Generated" };
        CodegenRunner.Run(config, load.Root, DefaultGenerators());
    }

    private CodegenDrift.Result RunDrift()
    {
        var load = MetaDataLoader.FromDirectory(MetaDir);
        Assert.Empty(load.Errors);
        var config = new GenConfig { OutDir = OutDir, Namespace = "Acme.Generated" };
        return CodegenDrift.Compute(config, load.Root, DefaultGenerators());
    }

    [Fact]
    public void Committed_output_matching_fresh_regen_is_clean()
    {
        Gen();

        var drift = RunDrift();
        Assert.True(drift.Clean, string.Join("; ", drift.Lines));
        Assert.Empty(drift.DriftedFiles);
        Assert.Null(drift.Error);
    }

    [Fact]
    public void Mutated_committed_file_is_drift_and_named()
    {
        Gen();

        // Hand-edit a committed generated file — must surface as content drift.
        var entity = Path.Combine(OutDir, "Subscriber.g.cs");
        File.AppendAllText(entity, "\n// hand edit\n");

        var drift = RunDrift();
        Assert.False(drift.Clean);
        Assert.Contains(drift.DriftedFiles, f => f.EndsWith("Subscriber.g.cs"));
        Assert.Contains(drift.Lines, l => l.Contains("Subscriber.g.cs"));
    }

    [Fact]
    public void Missing_committed_file_is_drift()
    {
        Gen();
        File.Delete(Path.Combine(OutDir, "Subscriber.g.cs"));

        var drift = RunDrift();
        Assert.False(drift.Clean);
        Assert.Contains(drift.DriftedFiles, f => f.EndsWith("Subscriber.g.cs"));
    }

    [Fact]
    public void Extra_committed_file_is_drift()
    {
        Gen();
        // A stray generated-looking file the regen would not emit.
        File.WriteAllText(Path.Combine(OutDir, "Stray.g.cs"), "// <auto-generated/>\n");

        var drift = RunDrift();
        Assert.False(drift.Clean);
        Assert.Contains(drift.DriftedFiles, f => f.EndsWith("Stray.g.cs"));
    }

    [Fact]
    public void No_committed_output_dir_is_an_error_not_clean()
    {
        // Never ran gen; OutDir does not exist. Nothing to diff against → error.
        var drift = RunDrift();
        Assert.False(drift.Clean);
        Assert.NotNull(drift.Error);
    }

    [Fact]
    public void Drift_run_never_writes_to_the_real_out_dir()
    {
        Gen();

        // Snapshot the committed out dir (relative path + content hash).
        var before = SnapshotDir(OutDir);

        // A drift run (with a mutation present) must touch ONLY temp, never OutDir.
        File.AppendAllText(Path.Combine(OutDir, "Subscriber.g.cs"), "\n// edit\n");
        var afterMutation = SnapshotDir(OutDir);
        RunDrift();
        var afterDrift = SnapshotDir(OutDir);

        // The drift computation itself changed nothing on disk under OutDir.
        Assert.Equal(afterMutation, afterDrift);
        // (sanity: our own mutation is the only delta vs the pristine snapshot)
        Assert.NotEqual(before, afterMutation);
    }

    // -------------------- namespace inference from committed output ----------

    [Fact]
    public void InferNamespace_reads_file_scoped_namespace()
    {
        Gen(); // writes files with `namespace Acme.Generated;`
        Assert.Equal("Acme.Generated", CodegenDrift.InferNamespace(OutDir));
    }

    [Fact]
    public void InferNamespace_reads_block_scoped_namespace()
    {
        Directory.CreateDirectory(OutDir);
        File.WriteAllText(Path.Combine(OutDir, "Block.g.cs"),
            "// <auto-generated/>\nnamespace Acme.Block\n{\n    public class Foo { }\n}\n");
        Assert.Equal("Acme.Block", CodegenDrift.InferNamespace(OutDir));
    }

    [Fact]
    public void InferNamespace_picks_the_first_sorted_file()
    {
        Directory.CreateDirectory(OutDir);
        File.WriteAllText(Path.Combine(OutDir, "Zeta.g.cs"), "namespace Zeta.Ns;\n");
        File.WriteAllText(Path.Combine(OutDir, "Alpha.g.cs"), "namespace Alpha.Ns;\n");
        Assert.Equal("Alpha.Ns", CodegenDrift.InferNamespace(OutDir));
    }

    [Fact]
    public void InferNamespace_returns_null_for_missing_dir()
    {
        Assert.Null(CodegenDrift.InferNamespace(Path.Combine(_tmp, "does-not-exist")));
    }

    [Fact]
    public void InferNamespace_returns_null_when_no_cs_has_a_namespace()
    {
        Directory.CreateDirectory(OutDir);
        File.WriteAllText(Path.Combine(OutDir, "NoNs.g.cs"), "// top-level statements only\nvar x = 1;\n");
        File.WriteAllText(Path.Combine(OutDir, "notes.txt"), "namespace NotCSharp;\n");
        Assert.Null(CodegenDrift.InferNamespace(OutDir));
    }

    private static Dictionary<string, string> SnapshotDir(string dir)
    {
        var snap = new Dictionary<string, string>(StringComparer.Ordinal);
        if (!Directory.Exists(dir)) return snap;
        foreach (var f in Directory.EnumerateFiles(dir, "*", SearchOption.AllDirectories))
            snap[Path.GetRelativePath(dir, f)] = File.ReadAllText(f);
        return snap;
    }
}
