// GeneratorExtensibilityTests — verifies the open-closed (ADR-0002) extension
// seams on the remaining C# code generators (mirroring the EntityGenerator work):
// each generator is subclassable, its per-artifact emit methods are overridable,
// and a subclass override changes output WITHOUT altering the base default output.
//
// The base (unsubclassed) generators stay byte-stable — the IntegrationFixture drift
// gate is the strong enforcer of that; these tests assert the override seams work and
// that, for the same input, the base output is unchanged.

using System.Collections.Generic;
using System.Linq;
using System.Text;
using MetaObjects.Codegen;
using MetaObjects.Codegen.Generators;
using MetaObjects.Loader;
using MetaObjects.Meta;
using Xunit;

namespace MetaObjects.Codegen.Tests;

public class GeneratorExtensibilityTests
{
    private static MetaRoot Load(string model)
    {
        var r = new MetaDataLoader().Load([new InMemoryStringSource(model, id: "ext.json")]);
        Assert.Empty(r.Errors);
        return r.Root;
    }

    private static GenContext Ctx(MetaRoot root) => new()
    {
        Entities = root.Objects(),
        Root = root,
        Config = new GenConfig { OutDir = "/tmp", Namespace = "Acme.Generated" },
    };

    // A single filterable entity — enough to exercise the DbContext + filter-allowlist seams.
    private const string EntityModel = """
    { "metadata.root": { "package": "acme", "children": [
      { "object.entity": { "name": "Subscriber", "children": [
        { "source.rdb": { "@table": "subscribers" } },
        { "field.long":    { "name": "id" } },
        { "field.string":  { "name": "email", "@required": true, "@maxLength": 255, "@filterable": true } },
        { "field.boolean": { "name": "subscribed", "@filterable": true } },
        { "identity.primary": { "@fields": "id" } }
      ]}}
    ]}}
    """;

    // A template.output + value-object payload — exercises the output-parser seam.
    private const string OutputModel = """
    { "metadata.root": { "package": "acme::ai", "children": [
      { "object.value": { "name": "AlphaPayload", "children": [ { "field.string": { "name": "name" } } ] } },
      { "template.prompt": { "name": "Alpha", "@payloadRef": "AlphaPayload", "@responseRef": "AlphaPayload", "@textRef": "a/x", "@format": "text", "@responseFormat": "json" } }
    ]}}
    """;

    // ---- DbContextGenerator: override the OnModelCreating-body seam ---------------

    private sealed class TaggedDbContextGenerator : DbContextGenerator
    {
        protected override void EmitOnModelCreatingBody(
            StringBuilder sb, IReadOnlyList<string> modelLines, GenContext ctx)
        {
            sb.AppendLine();
            sb.AppendLine("    // ADOPTER MODEL CONFIG");
            base.EmitOnModelCreatingBody(sb, modelLines, ctx);
        }
    }

    [Fact]
    public void DbContext_subclass_can_override_on_model_creating_body_seam()
    {
        var ctx = Ctx(Load(EntityModel));
        var src = Assert.Single(new TaggedDbContextGenerator().Generate(ctx)).Content;
        Assert.Contains("// ADOPTER MODEL CONFIG", src);
    }

    [Fact]
    public void DbContext_base_output_is_unchanged_by_the_extension_seams()
    {
        var ctx = Ctx(Load(EntityModel));
        var src = Assert.Single(new DbContextGenerator().Generate(ctx)).Content;
        Assert.DoesNotContain("ADOPTER MODEL CONFIG", src);
        Assert.Contains("public class AppDbContext : DbContext", src);
        Assert.Contains("public DbSet<Subscriber> Subscribers", src);
    }

    // ---- OutputParserGenerator: override the EmitParser seam ----------------------

    private sealed class BannerOutputParserGenerator : OutputParserGenerator
    {
        protected override EmittedFile EmitParser(MetaData tmpl, string payloadRef, GenContext ctx)
        {
            var f = base.EmitParser(tmpl, payloadRef, ctx);
            return f with { Content = "// ADOPTER PARSER BANNER\n" + f.Content };
        }
    }

    [Fact]
    public void OutputParser_subclass_can_override_emit_parser_seam()
    {
        var ctx = Ctx(Load(OutputModel));
        var src = Assert.Single(new BannerOutputParserGenerator().Generate(ctx)).Content;
        Assert.StartsWith("// ADOPTER PARSER BANNER\n", src);
        // The base parser body is preserved underneath the banner.
        Assert.Contains("public static class AlphaParser", src);
    }

    [Fact]
    public void OutputParser_base_output_is_unchanged_by_the_extension_seams()
    {
        var ctx = Ctx(Load(OutputModel));
        var src = Assert.Single(new OutputParserGenerator().Generate(ctx)).Content;
        Assert.DoesNotContain("ADOPTER PARSER BANNER", src);
        Assert.StartsWith("// <auto-generated/>", src);
    }

    // ---- FilterAllowlistGenerator: override the ComputeFilterableOps seam ----------

    private sealed class NoOpsFilterAllowlistGenerator : FilterAllowlistGenerator
    {
        // Drop every field's op-set → an empty allowlist regardless of @filterable.
        protected override Dictionary<string, IReadOnlyList<string>> ComputeFilterableOps(MetaObject entity) =>
            new(System.StringComparer.Ordinal);
    }

    [Fact]
    public void FilterAllowlist_subclass_can_override_compute_ops_seam()
    {
        var ctx = Ctx(Load(EntityModel));
        var src = Assert.Single(new NoOpsFilterAllowlistGenerator().Generate(ctx)).Content;
        // Overridden to empty → no field entries emitted.
        Assert.DoesNotContain("\"email\"", src);
        Assert.DoesNotContain("\"subscribed\"", src);
    }

    [Fact]
    public void FilterAllowlist_base_output_is_unchanged_by_the_extension_seams()
    {
        var ctx = Ctx(Load(EntityModel));
        var src = Assert.Single(new FilterAllowlistGenerator().Generate(ctx)).Content;
        // Default still computes the filterable fields from @filterable.
        Assert.Contains("\"email\"", src);
        Assert.Contains("\"subscribed\"", src);
    }
}
