// A MongoDB repository per SOURCELESS entity: an object.entity with an identity.primary and
// no source.* — a record MetaObjects models but does not store. The entity generator emits
// its wire contract (<E>InsertSchema, <E>UpdateSchema, <E>FilterAllowlist); this emits the
// data access over it. The collection name comes from an author-supplied `@mongo` property
// bag on the entity: `"@mongo": { "collection": "orders" }`.
import { isSourcelessEntity, perEntity, type Generator } from "@metaobjectsdev/codegen-ts";
import type { MetaObject } from "@metaobjectsdev/metadata";

function collectionOf(obj: MetaObject): string {
  const bag = obj.attr("mongo");
  if (bag !== null && typeof bag === "object" && "collection" in bag && typeof bag.collection === "string") {
    return bag.collection;
  }
  return `${obj.name.charAt(0).toLowerCase()}${obj.name.slice(1)}s`;
}

function render(obj: MetaObject): string {
  const E = obj.name;
  const e = `${E.charAt(0).toLowerCase()}${E.slice(1)}`;
  const pk = obj.primaryIdentity()?.fields[0] ?? "id";
  const generated = obj.primaryIdentity()?.attr("generation") === "uuid";
  const newId = generated ? `crypto.randomUUID()` : `(input as { ${pk}: string }).${pk}`;
  return `// GENERATED by codegen/generators/mongo-repository.ts — edit the generator, not this file.
import type { Collection, Db, Filter } from "mongodb";
import {
  ${E}InsertSchema, ${E}UpdateSchema, ${E}FilterAllowlist,
  type ${E}, type ${E}Create, type ${E}Patch,
} from "./${E}.js";

type ${E}Doc = Omit<${E}, "${pk}"> & { _id: string };

const OPS = { eq: "$eq", ne: "$ne", gt: "$gt", gte: "$gte", lt: "$lt", lte: "$lte", in: "$in" } as const;

function toEntity({ _id, ...rest }: ${E}Doc): ${E} {
  return { ${pk}: _id, ...rest } as ${E};
}

/** A query \`{ field: value }\` or \`{ field: { op: value } }\`, checked against ${E}FilterAllowlist. */
export type ${E}Query = Record<string, unknown>;

function toMongoFilter(query: ${E}Query): Filter<${E}Doc> {
  const out: Record<string, unknown> = {};
  for (const [field, raw] of Object.entries(query)) {
    const rule = (${E}FilterAllowlist as Record<string, { ops: readonly string[] }>)[field];
    if (rule === undefined) throw new Error(\`${E}: "\${field}" is not filterable\`);
    const clauses = raw !== null && typeof raw === "object" && !Array.isArray(raw) ? raw : { eq: raw };
    const mongo: Record<string, unknown> = {};
    for (const [op, value] of Object.entries(clauses)) {
      if (!rule.ops.includes(op) || !(op in OPS)) throw new Error(\`${E}: "\${op}" is not allowed on "\${field}"\`);
      mongo[OPS[op as keyof typeof OPS]] = value;
    }
    out[field === "${pk}" ? "_id" : field] = mongo;
  }
  return out as Filter<${E}Doc>;
}

export function ${e}Repository(db: Db) {
  const docs: Collection<${E}Doc> = db.collection<${E}Doc>(${JSON.stringify(collectionOf(obj))});
  return {
    async create(input: ${E}Create): Promise<${E}> {
      const row = ${E}InsertSchema.parse(input);
      const _id = ${newId};
      await docs.insertOne({ ...row, _id } as ${E}Doc);
      return toEntity({ ...row, _id } as ${E}Doc);
    },

    async findById(id: string): Promise<${E} | null> {
      const doc = await docs.findOne({ _id: id } as Filter<${E}Doc>);
      return doc === null ? null : toEntity(doc);
    },

    async list(query: ${E}Query = {}): Promise<${E}[]> {
      return (await docs.find(toMongoFilter(query)).toArray()).map(toEntity);
    },

    /** PATCH: an absent key is untouched, an explicit null clears the field. */
    async patch(id: string, patch: ${E}Patch): Promise<${E} | null> {
      const changes = ${E}UpdateSchema.parse(patch) as Record<string, unknown>;
      const $set: Record<string, unknown> = {};
      const $unset: Record<string, ""> = {};
      for (const [k, v] of Object.entries(changes)) {
        if (v === undefined) continue;
        if (v === null) $unset[k] = "";
        else $set[k] = v;
      }
      const doc = await docs.findOneAndUpdate(
        { _id: id } as Filter<${E}Doc>,
        { $set, $unset },
        { returnDocument: "after" },
      );
      return doc === null ? null : toEntity(doc);
    },

    async delete(id: string): Promise<boolean> {
      return (await docs.deleteOne({ _id: id } as Filter<${E}Doc>)).deletedCount === 1;
    },
  };
}
`;
}

export function mongoRepositoryGenerator(): Generator {
  return {
    name: "mongo-repository",
    filter: isSourcelessEntity,
    generate: perEntity((obj) => ({ path: `${obj.name}.repository.ts`, content: render(obj) })),
  };
}
