// AUTO-GENERATED by scripts/generate-embedded-metamodel.ts — DO NOT EDIT.
// Canonical source: repo-root spec/metamodel/identity.json
// Regenerate: bun run scripts/generate-embedded-metamodel.ts
//
// Embeds the canonical FR-033 ProviderDefinition so the provider can register
// itself wherever the on-disk spec/ tree is unavailable (bundled builds).
import type { ProviderDefinition } from "../../provider-data.js";

export const IDENTITY_DEFINITION: ProviderDefinition = {
  "provider": "metaobjects-core-types",
  "types": [
    {
      "type": "identity",
      "subType": "primary",
      "description": "The primary key — one per entity; @fields names its column(s), @generation the value strategy.",
      "whenToUse": "Every entity needs exactly one — names the primary-key field(s) and how the value is generated. Always declare it.",
      "maxOccurs": 1,
      "defaultName": "primary",
      "children": [
        {
          "type": "attr",
          "subType": "string",
          "name": "fields",
          "isArray": true,
          "min": 1,
          "max": 1,
          "description": "The field name(s) composing this identity. Single-element for a simple PK/index, multiple for a composite."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "generation",
          "min": 0,
          "max": 1,
          "allowedValues": [
            "increment",
            "uuid",
            "assigned"
          ],
          "description": "Primary-key value generation strategy: 'increment' (auto-increment), 'uuid', or 'assigned' (caller-supplied)."
        }
      ]
    },
    {
      "type": "identity",
      "subType": "secondary",
      "description": "A secondary unique index on one or more fields. Always enforces uniqueness — use index.lookup for non-unique query-performance indexes.",
      "whenToUse": "A column or set of columns must be unique (e.g. email, slug, composite business key). For a plain non-unique index, use index.lookup instead.",
      "children": [
        {
          "type": "attr",
          "subType": "string",
          "name": "fields",
          "isArray": true,
          "min": 0,
          "max": 1,
          "description": "The field name(s) composing this identity. Single-element for a simple unique index, multiple for a composite unique constraint. Required UNLESS @expr is present — a unique index keys off plain columns (@fields) or a key expression (@expr), never both; declaring both is ERR_INVALID_INDEX."
        }
      ]
    },
    {
      "type": "identity",
      "subType": "reference",
      "description": "A foreign-key reference to another entity (@references target; @enforce toggles a physical FK).",
      "whenToUse": "This entity holds a foreign key to another. Declare it to generate the FK constraint + typed navigation, instead of a loose id field you join on by hand.",
      "children": [
        {
          "type": "attr",
          "subType": "string",
          "name": "fields",
          "isArray": true,
          "min": 1,
          "max": 1,
          "description": "The field name(s) composing this identity. Single-element for a simple PK/index, multiple for a composite."
        },
        {
          "type": "attr",
          "subType": "string",
          "name": "references",
          "min": 1,
          "max": 1,
          "description": "Target of the reference. Bare entity name (e.g. 'Program') resolves to that entity's primary identity. Dotted forms ('Program.id' or 'Program.fieldA,fieldB') target an explicit field set on the entity."
        },
        {
          "type": "attr",
          "subType": "boolean",
          "name": "enforce",
          "min": 0,
          "max": 1,
          "description": "When true (default), the backend physically enforces the reference (SQL FK constraint, document validation rule, graph edge guarantee). Set false to declare a logical reference for navigation/typing/codegen only — the value may dangle at the backend level."
        }
      ]
    }
  ]
};
