// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: Program (Program)
// Customize via Program.extra.ts in this directory.
import {
  InferInsertModel,
  InferSelectModel,
  relations,
  sql,
} from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { z } from "zod";
import { purchases } from "./Purchase";
import { weeks } from "./Week";

export const programs = sqliteTable("programs", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  slug: text("slug").notNull().unique(),
  title: text("title").notNull(),
  description: text("description"),
  priceCents: integer("price_cents").notNull(),
  isPublished: integer("is_published", { mode: "boolean" })
    .notNull()
    .default(false),
  createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
});
export const programsRelations = relations(programs, ({ many }) => ({
  weeks: many(weeks),
  purchases: many(purchases),
}));
export type Program = InferSelectModel<typeof programs>;
export type NewProgram = InferInsertModel<typeof programs>;
export const ProgramInsertSchema = z.object({
  slug: z.string().min(1).max(100),
  title: z.string().min(1).max(200),
  description: z.string().optional(),
  priceCents: z.number().int(),
  isPublished: z.boolean().optional(),
  createdAt: z.string().optional(),
});

export const ProgramUpdateSchema = z.object({
  slug: z.string().min(1).max(100).optional(),
  title: z.string().min(1).max(200).optional(),
  description: z.string().optional(),
  priceCents: z.number().int().optional(),
  isPublished: z.boolean().optional(),
  createdAt: z.string().optional(),
});
/**
 * Metadata constants for Program.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, optional htmlType/placeholder/helpText, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjects/runtime-ts-client/react';
 *   const form = useEntityForm(Program, ProgramInsertSchema);
 *   <input {...form.input.id} />
 */
export const Program = {
  $entity: "Program",
  $table: "programs",
  $path: "/programs",
  $apiPrefix: "",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  slug: {
    name: "slug",
    label: "Slug",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Slug is required",
      maxLength: { value: 100, message: "Must be 100 characters or fewer" },
    },
  },
  title: {
    name: "title",
    label: "Title",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Title is required",
      maxLength: { value: 200, message: "Must be 200 characters or fewer" },
    },
  },
  description: {
    name: "description",
    label: "Description",
    view: "text",
    htmlType: "text",
  },
  priceCents: {
    name: "priceCents",
    label: "Price Cents",
    view: "number",
    htmlType: "number",
    rules: { required: "Price Cents is required" },
  },
  isPublished: {
    name: "isPublished",
    label: "Is Published",
    view: "checkbox",
    htmlType: "checkbox",
    rules: { required: "Is Published is required" },
  },
  createdAt: {
    name: "createdAt",
    label: "Created At",
    view: "date",
    htmlType: "date",
    rules: { required: "Created At is required" },
  },
} as const;
import type { FilterAllowlist } from "@metaobjects/runtime-ts/drizzle-fastify";

export const ProgramFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjects/runtime-ts/drizzle-fastify";

export const ProgramSortAllowlist = {} as const satisfies SortAllowlist;
export type ProgramFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: ProgramFilter[];
  and?: ProgramFilter[];
};
