#!/usr/bin/env bun
//
// generate-embedded-metamodel.ts
//
// Reads the canonical declarative metamodel definitions spec/metamodel/*.json
// (FR-033 ProviderDefinition data) and emits, per file, a typed TS module that
// embeds the parsed definition as a `ProviderDefinition` object literal so the
// provider can register itself wherever the on-disk spec/ tree is unavailable
// (bundled / published builds). The byte-stable embed is the JSON re-serialized
// with 2-space indent; the embed module exports it as a typed const.
//
// One module per spec/metamodel/<name>.json →
//   server/typescript/packages/metadata/src/core/<name>/<name>-definition.embedded.ts
// exporting `<NAME>_DEFINITION` (e.g. field.json → FIELD_DEFINITION in
// core/field/field-definition.embedded.ts).
//
// Mirrors scripts/generate-embedded-library.ts. Run:
//   bun run scripts/generate-embedded-metamodel.ts
//
// A deep-equal drift test gates each output (e.g.
//   server/typescript/packages/metadata/test/field-definition-embed.test.ts).

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

// Resolve the repo root relative to THIS script (walk up to the dir containing
// both spec/ and server/). No hardcoded absolute paths.
function findRepoRoot(start: string): string {
  let dir = start;
  while (true) {
    if (existsSync(join(dir, "spec")) && existsSync(join(dir, "server"))) {
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error("Could not locate repo root (dir containing spec/ and server/)");
    }
    dir = parent;
  }
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = findRepoRoot(scriptDir);

const specDir = join(repoRoot, "spec", "metamodel");
const metadataSrc = join(repoRoot, "server", "typescript", "packages", "metadata", "src");

if (!existsSync(specDir)) {
  console.error(`error: spec/metamodel not found at ${specDir}`);
  process.exit(1);
}

const jsonFiles = readdirSync(specDir)
  .filter((n) => n.endsWith(".json"))
  .sort();

if (jsonFiles.length === 0) {
  console.error(`error: no *.json files found under ${specDir}`);
  process.exit(1);
}

/** field → core/field/field-definition.embedded.ts, exporting FIELD_DEFINITION. */
function targetFor(name: string): { outFile: string; constName: string } {
  const constName = `${name.toUpperCase()}_DEFINITION`;
  const outFile = join(metadataSrc, "core", name, `${name}-definition.embedded.ts`);
  return { outFile, constName };
}

for (const file of jsonFiles) {
  const name = file.replace(/\.json$/, "");
  const { outFile, constName } = targetFor(name);
  if (!existsSync(dirname(outFile))) {
    console.error(`error: target dir for "${name}" does not exist: ${dirname(outFile)}`);
    process.exit(1);
  }

  const raw = readFileSync(join(specDir, file), "utf-8");
  // Round-trip through parse so the embedded literal is canonical 2-space JSON
  // (matches the gate test, which parses the same on-disk file).
  const parsed = JSON.parse(raw);
  const literal = JSON.stringify(parsed, null, 2);

  const source = `// AUTO-GENERATED by scripts/generate-embedded-metamodel.ts — DO NOT EDIT.
// Canonical source: repo-root spec/metamodel/${file}
// Regenerate: bun run scripts/generate-embedded-metamodel.ts
//
// Embeds the canonical FR-033 ProviderDefinition so the provider can register
// itself wherever the on-disk spec/ tree is unavailable (bundled builds).
import type { ProviderDefinition } from "../../provider-data.js";

export const ${constName}: ProviderDefinition = ${literal};
`;

  writeFileSync(outFile, source, "utf-8");
  console.log(`wrote ${constName} to ${relative(repoRoot, outFile)}`);
}
