#!/usr/bin/env bun
//
// generate-embedded-library.ts
//
// Reads canonical library/**/*.yaml and emits a plain-string TS module
//   server/typescript/packages/metadata/src/library/embedded-library.generated.ts
// mapping each file's ref (path under library/ WITHOUT the .yaml suffix,
// e.g. "ai/llm-call") to the EXACT file contents.
//
// Mirrors scripts/generate-embedded-templates.ts. Run:
//   bun run scripts/generate-embedded-library.ts
//
// A byte-identity drift test gates this output:
//   server/typescript/packages/metadata/test/embedded-library.test.ts

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

// Resolve the repo root relative to THIS script (walk up to the dir containing
// both library/ and server/). No hardcoded absolute paths.
function findRepoRoot(start: string): string {
  let dir = start;
  while (true) {
    if (existsSync(join(dir, "library")) && existsSync(join(dir, "server"))) {
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error("Could not locate repo root (dir containing library/ and server/)");
    }
    dir = parent;
  }
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = findRepoRoot(scriptDir);

const libDir = join(repoRoot, "library");
const outFile = join(
  repoRoot,
  "server",
  "typescript",
  "packages",
  "metadata",
  "src",
  "library",
  "embedded-library.generated.ts",
);

function collect(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...collect(p));
    else if (e.name.endsWith(".yaml")) out.push(p);
  }
  return out;
}

const files = collect(libDir);

if (files.length === 0) {
  console.error(`error: no *.yaml files found under ${libDir}`);
  process.exit(1);
}

// ref = path under library/ WITHOUT the .yaml suffix.
// e.g. library/ai/llm-call.yaml -> "ai/llm-call"
// Sorted by ref for deterministic, byte-stable output.
const entries = files
  .map((abs) => {
    const ref = relative(libDir, abs).replace(/\.yaml$/, "").split("\\").join("/");
    const content = readFileSync(abs, "utf-8");
    return { ref, content };
  })
  .sort((a, b) => (a.ref < b.ref ? -1 : a.ref > b.ref ? 1 : 0));

const body = entries
  // JSON.stringify emits a safe string literal — preserves newlines/quotes/
  // unicode byte-for-byte.
  .map((e) => `  ${JSON.stringify(e.ref)}: ${JSON.stringify(e.content)},`)
  .join("\n");

const source = `// AUTO-GENERATED by scripts/generate-embedded-library.ts — DO NOT EDIT.
// Canonical source: repo-root library/**/*.yaml
// Regenerate: bun run scripts/generate-embedded-library.ts
//
// Embeds the canonical library files as string literals so they resolve
// wherever the on-disk library/ directory is unavailable.
// Keys are refs: path under library/ minus the .yaml extension.
export const EMBEDDED_LIBRARY: Record<string, string> = {
${body}
};
`;

writeFileSync(outFile, source, "utf-8");
console.log(
  `wrote ${entries.length} embedded library file(s) to ${relative(repoRoot, outFile)}`,
);
