#!/usr/bin/env bun
//
// generate-embedded-library.ts
//
// Reads canonical library/**/*.yaml and emits a plain-string TS module
//   server/typescript/packages/metadata/src/library/embedded-library.generated.ts
// mapping each file's ref (path under library/ WITHOUT the .yaml suffix,
// e.g. "ai/llm-call") to the EXACT file contents.
//
// Mirrors scripts/generate-embedded-templates.ts. Run:
//   bun run scripts/generate-embedded-library.ts
//
// A byte-identity drift test gates this output:
//   server/typescript/packages/metadata/test/embedded-library.test.ts

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

// Resolve the repo root relative to THIS script (walk up to the dir containing
// both library/ and server/). No hardcoded absolute paths.
function findRepoRoot(start: string): string {
  let dir = start;
  while (true) {
    if (existsSync(join(dir, "library")) && existsSync(join(dir, "server"))) {
      return dir;
    }
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error("Could not locate repo root (dir containing library/ and server/)");
    }
    dir = parent;
  }
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = findRepoRoot(scriptDir);

const libDir = join(repoRoot, "library");
const outFile = join(
  repoRoot,
  "server",
  "typescript",
  "packages",
  "metadata",
  "src",
  "library",
  "embedded-library.generated.ts",
);
// The JVM embed is emitted from THIS script rather than a second one, deliberately: two
// scripts walking the same tree are two things that can drift, and an embed's whole job is
// to be byte-identical to the canonical source. Python keeps its own
// (`server/python/scripts/generate_embedded_library.py`) because it shipped first, gated
// by its own byte-identity test.
const javaOutFile = join(
  repoRoot,
  "server",
  "java",
  "metadata",
  "src",
  "main",
  "java",
  "com",
  "metaobjects",
  "library",
  "EmbeddedLibrary.java",
);
const csharpOutFile = join(
  repoRoot,
  "server",
  "csharp",
  "MetaObjects",
  "Library",
  "EmbeddedLibrary.cs",
);

function collect(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...collect(p));
    else if (e.name.endsWith(".yaml")) out.push(p);
  }
  return out;
}

const files = collect(libDir);

if (files.length === 0) {
  console.error(`error: no *.yaml files found under ${libDir}`);
  process.exit(1);
}

// ref = path under library/ WITHOUT the .yaml suffix.
// e.g. library/ai/llm-call.yaml -> "ai/llm-call"
// Sorted by ref for deterministic, byte-stable output.
const entries = files
  .map((abs) => {
    const ref = relative(libDir, abs).replace(/\.yaml$/, "").split("\\").join("/");
    const content = readFileSync(abs, "utf-8");
    return { ref, content };
  })
  .sort((a, b) => (a.ref < b.ref ? -1 : a.ref > b.ref ? 1 : 0));

const body = entries
  // JSON.stringify emits a safe string literal — preserves newlines/quotes/
  // unicode byte-for-byte.
  .map((e) => `  ${JSON.stringify(e.ref)}: ${JSON.stringify(e.content)},`)
  .join("\n");

const source = `// AUTO-GENERATED by scripts/generate-embedded-library.ts — DO NOT EDIT.
// Canonical source: repo-root library/**/*.yaml
// Regenerate: bun run scripts/generate-embedded-library.ts
//
// Embeds the canonical library files as string literals so they resolve
// wherever the on-disk library/ directory is unavailable.
// Keys are refs: path under library/ minus the .yaml extension.
export const EMBEDDED_LIBRARY: Record<string, string> = {
${body}
};
`;

writeFileSync(outFile, source, "utf-8");

// Java: a generated CLASS holding string constants, not a src/main/resources copy. A
// resource can be dropped or mangled by build configuration — resource filtering, shading,
// a repackaging plugin — and the failure would surface much later as ERR_UNRESOLVED_SUPER
// against the adopter's own metadata, which is the wrong place to send someone looking. A
// class constant cannot go missing without the class going missing. Same rationale Python
// records for embedding as a source module.
//
// `JSON.stringify` output IS a valid Java string literal: every escape it emits (\" \\ \b
// \f \n \r \t \uXXXX) means the same thing in both languages. That keeps this emitter free
// of a Java-version dependency — no text blocks, so the language level can stay wherever
// the build puts it.
const javaEntries = entries
  .map((e) => `        m.put(${JSON.stringify(e.ref)}, ${JSON.stringify(e.content)});`)
  .join("\n");

const javaSource = `package com.metaobjects.library;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * AUTO-GENERATED by scripts/generate-embedded-library.ts — DO NOT EDIT.
 *
 * <p>Canonical source: the repo-root {@code library/} tree.
 * Regenerate with {@code bun run scripts/generate-embedded-library.ts}.</p>
 *
 * <p>Embeds the canonical library files as string constants so they resolve wherever the
 * on-disk {@code library/} directory is unavailable — which is every consumer of the
 * published jar. Keys are refs: the path under {@code library/} minus the {@code .yaml}
 * extension (e.g. {@code "ai/llm-call"}).</p>
 *
 * <p>{@code EmbeddedLibraryFreshnessTest} gates this file byte-for-byte against the
 * canonical tree, so a stale embed cannot ship.</p>
 */
public final class EmbeddedLibrary {

    private EmbeddedLibrary() {}

    /** Ref to exact file contents, insertion-ordered by ref. */
    public static final Map<String, String> CONTENT;

    static {
        Map<String, String> m = new LinkedHashMap<>();
${javaEntries}
        CONTENT = Collections.unmodifiableMap(m);
    }
}
`;

writeFileSync(javaOutFile, javaSource, "utf-8");

// C#: same reasoning as Java — a generated class, not an embedded resource, so no build
// configuration can drop it. C# verbatim strings would need `""` doubling and would still
// re-wrap; a regular literal from `JSON.stringify` needs neither, because every escape it
// emits (\" \\ \b \f \n \r \t \uXXXX) means the same thing in C# as in JSON.
const csharpEntries = entries
  .map((e) => `        [${JSON.stringify(e.ref)}] = ${JSON.stringify(e.content)},`)
  .join("\n");

const csharpSource = `namespace MetaObjects.Library;

/// <summary>
/// AUTO-GENERATED by scripts/generate-embedded-library.ts — DO NOT EDIT.
///
/// <para>Canonical source: the repo-root <c>library/</c> tree.
/// Regenerate with <c>bun run scripts/generate-embedded-library.ts</c>.</para>
///
/// <para>Embeds the canonical library files as string constants so they resolve wherever the
/// on-disk <c>library/</c> directory is unavailable — which is every consumer of the published
/// NuGet package. Keys are refs: the path under <c>library/</c> minus the <c>.yaml</c>
/// extension (e.g. <c>"ai/llm-call"</c>).</para>
///
/// <para><c>EmbeddedLibraryTests</c> gates this file byte-for-byte against the canonical tree,
/// so a stale embed cannot ship.</para>
/// </summary>
public static class EmbeddedLibrary
{
    /// <summary>Ref to exact file contents, insertion-ordered by ref.</summary>
    public static readonly IReadOnlyDictionary<string, string> Content =
        new Dictionary<string, string>
    {
${csharpEntries}
    };
}
`;

writeFileSync(csharpOutFile, csharpSource, "utf-8");

console.log(
  `wrote ${entries.length} embedded library file(s) to ${relative(repoRoot, outFile)}, ` +
    `${relative(repoRoot, javaOutFile)} and ${relative(repoRoot, csharpOutFile)}`,
);
