#!/usr/bin/env bun
/**
 * Phase 5 — the harness. One test slot per authored promise, in every port.
 *
 * ── What this is for ───────────────────────────────────────────────────────────
 *
 * `expected-registry.json` proves the five ports SPELL the vocabulary identically.
 * It is blind to what they DO with it, and the blindness is measured rather than
 * feared: one attribute naming a column was found meaning three different things
 * across the ports at once while every port byte-matched the manifest throughout.
 *
 * The ledger states what each piece of vocabulary must DO. This turns each of those
 * statements into a NAMED SLOT in every port, so a promise that nobody checks is
 * visible as a slot nobody filled, instead of being invisible as a sentence nobody
 * wrote.
 *
 * ── Why every stub is skipped, and why that is not the usual cop-out ────────────
 *
 * The shipped `requirementTests()` renderer FAILS a live stub deliberately: for an
 * adopter, an empty green test asserts the opposite of the claim. That rule is right
 * there and wrong here, and the difference is worth stating rather than quietly
 * departing from.
 *
 * An adopter generates a handful of stubs for capabilities nothing else checks. This
 * generates 109 across five ports for a library whose conformance corpora ALREADY
 * check a great many of them. Emitting 545 red tests would claim nothing is verified,
 * which is false, and a suite red for a false reason is silenced wholesale — taking
 * with it the slots that were telling the truth. So the stub is skipped and the DRIFT
 * GATE is what has teeth: the generated set must match the ledger exactly, so a new
 * promise appears as a new unfilled slot in all five ports and cannot be forgotten.
 *
 * A filled-in slot is an ordinary test in that port's idiom. Nothing here rewrites a
 * body: the generator emits the file whole, so adopting a slot means moving it into
 * the port's own suite. That is the honest boundary — this repository has not yet
 * wired four of the five, and says so rather than implying a harness that runs.
 */
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { MetaDataLoader } from "../server/typescript/packages/metadata/src/index.js";
import { collectAddressedRequirements } from "../server/typescript/packages/cli/src/lib/requirement-check.js";

const REPO_ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const OUT_DIR = join(REPO_ROOT, "fixtures/requirement-harness");
const LEVEL_SUBTYPE = 4;
const LEVEL_ATTR = 5;

interface Promise_ {
  /** The requirement's dotted address — stable, unique, and the link. */
  path: string;
  /** A valid identifier in every port's test naming. */
  ident: string;
  title: string;
  status: string;
  statement: string;
  counterexample: string;
}

/** Why this slot is unfilled, in words a reader can act on. */
function reason(p: Promise_): string {
  if (p.status === "retired") return "retired — the capability was deliberately removed; assert it stays removed";
  if (p.status === "planned") return "planned — not built yet";
  return `unfilled slot — write an assertion that fails when: ${p.counterexample}`;
}

const esc = (s: string): string => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ");

function collect(root: unknown): Promise_[] {
  const out: Promise_[] = [];
  for (const { node, path } of collectAddressedRequirements(root as never)) {
    const level = node.level();
    if (level !== LEVEL_SUBTYPE && level !== LEVEL_ATTR) continue;
    // `attr()` RESOLVES — it reads through `extends`. The own-only accessors would
    // silently drop anything a node inherited (ADR-0039), which for a scaffold means
    // emitting a slot with no promise in it and reporting success.
    const str = (name: string): string => {
      const v = node.attr(name);
      return typeof v === "string" ? v : "";
    };
    out.push({
      path,
      // Drop the solution root; the rest is already unique and identifier-safe.
      ident: path.split(".").slice(1).join("_"),
      title: str("title") || node.name,
      status: String(node.status() ?? "live"),
      statement: str("statement"),
      counterexample: str("counterexample"),
    });
  }
  return out.sort((a, b) => a.path.localeCompare(b.path));
}

const BANNER = (port: string, n: number, comment: string): string =>
  [
    `${comment} @generated by scripts/generate-requirement-harness.ts — DO NOT EDIT IN PLACE.`,
    `${comment}`,
    `${comment} One slot per authored promise in metaobjects/meta.requirements.yaml (${n} of them).`,
    `${comment} Every slot is SKIPPED: this is a to-do list with a drift gate behind it, not a`,
    `${comment} claim that nothing is verified — the conformance corpora already check many of`,
    `${comment} these. To FILL one, move it into ${port}'s own suite and write the assertion the`,
    `${comment} skip reason describes. Adding a promise to the ledger adds a slot here.`,
    "",
  ].join("\n");

const renderers: Record<string, { file: string; render: (ps: Promise_[]) => string }> = {
  typescript: {
    file: "typescript/requirement-harness.test.ts",
    render: (ps) =>
      `${BANNER("TypeScript", ps.length, "//")}import { test } from "bun:test";\n\n` +
      ps.map((p) =>
        `// ${p.title} — ${p.statement}\n` +
        `test.skip("${esc(p.path)}", () => {\n  // ${esc(reason(p))}\n});\n`,
      ).join("\n"),
  },
  python: {
    file: "python/test_requirement_harness.py",
    render: (ps) =>
      `${BANNER("Python", ps.length, "#")}import pytest\n\n` +
      ps.map((p) =>
        `# ${p.title} — ${p.statement}\n` +
        `@pytest.mark.skip(reason="${esc(reason(p))}")\n` +
        `def test_${p.ident}():\n    """${esc(p.path)}"""\n\n`,
      ).join(""),
  },
  java: {
    file: "java/RequirementHarnessTest.java",
    render: (ps) =>
      `${BANNER("Java", ps.length, "//")}package com.metaobjects.requirements;\n\n` +
      `import org.junit.jupiter.api.Disabled;\nimport org.junit.jupiter.api.Test;\n\n` +
      `class RequirementHarnessTest {\n\n` +
      ps.map((p) =>
        `    // ${p.title} — ${p.statement}\n` +
        `    @Test\n    @Disabled("${esc(reason(p))}")\n` +
        `    void ${p.ident}() { /* ${esc(p.path)} */ }\n\n`,
      ).join("") + `}\n`,
  },
  kotlin: {
    file: "kotlin/RequirementHarnessTest.kt",
    render: (ps) =>
      `${BANNER("Kotlin", ps.length, "//")}package com.metaobjects.requirements\n\n` +
      `import org.junit.jupiter.api.Disabled\nimport org.junit.jupiter.api.Test\n\n` +
      `class RequirementHarnessTest {\n\n` +
      ps.map((p) =>
        `    // ${p.title} — ${p.statement}\n` +
        `    @Test\n    @Disabled("${esc(reason(p))}")\n` +
        `    fun ${p.ident}() { /* ${esc(p.path)} */ }\n\n`,
      ).join("") + `}\n`,
  },
  csharp: {
    file: "csharp/RequirementHarnessTests.cs",
    render: (ps) =>
      `${BANNER("C#", ps.length, "//")}using Xunit;\n\nnamespace MetaObjects.Requirements;\n\n` +
      `public class RequirementHarnessTests\n{\n\n` +
      ps.map((p) =>
        `    // ${p.title} — ${p.statement}\n` +
        `    [Fact(Skip = "${esc(reason(p))}")]\n` +
        `    public void ${p.ident}() { /* ${esc(p.path)} */ }\n\n`,
      ).join("") + `}\n`,
  },
};

async function main(): Promise<number> {
  const check = process.argv.includes("--check");
  const { root, errors } = await MetaDataLoader.fromDirectory(join(REPO_ROOT, "metaobjects"), { strict: true });
  if (errors.length > 0 || root === undefined) {
    console.error("requirement-harness: the ledger does not load.\n");
    for (const e of errors) console.error(`  ${e.code ?? ""} ${e.message}`);
    return 1;
  }
  const promises = collect(root);
  if (promises.length === 0) {
    console.error("requirement-harness: the ledger declares no L4 or L5 promise — nothing to scaffold.\n");
    return 1;
  }

  // FAIL CLOSED ON A HOLLOW SLOT. The first version of this generator read the two
  // prose fields through accessors that do not exist, so every slot came out empty —
  // and it printed "109 promise(s) scaffolded across 5 ports" and passed its own
  // drift check, because a consistently empty harness is perfectly self-consistent. A
  // scaffold whose entire value is the sentence it carries must refuse to emit one
  // without it.
  const hollow = promises.filter((p) => p.statement === "" || p.counterexample === "");
  if (hollow.length > 0) {
    console.error(
      `requirement-harness: ${hollow.length} promise(s) carry no statement or no counterexample.\n` +
      `Both are required by the loader, so an empty one here means this generator is reading\n` +
      `them wrongly — fix the read, do not emit a harness that carries nothing.\n`,
    );
    for (const p of hollow.slice(0, 5)) console.error(`  ${p.path}`);
    return 1;
  }

  // Identifier collisions would silently drop a slot in the three ports whose test
  // names must be unique methods, so they are refused rather than deduplicated.
  const seen = new Map<string, string>();
  for (const p of promises) {
    const prior = seen.get(p.ident);
    if (prior !== undefined) {
      console.error(`requirement-harness: '${p.path}' and '${prior}' produce the same test identifier.\n`);
      return 1;
    }
    seen.set(p.ident, p.path);
  }

  let stale = 0;
  for (const [port, { file, render }] of Object.entries(renderers)) {
    const target = join(OUT_DIR, file);
    const content = render(promises);
    const current = existsSync(target) ? readFileSync(target, "utf8") : undefined;
    if (current === content) continue;
    if (check) {
      console.error(
        `requirement-harness: ${file} is ${current === undefined ? "missing" : "stale"}.\n` +
        `The ledger and the harness have diverged — regenerate with:\n` +
        `  bun scripts/generate-requirement-harness.ts\n`,
      );
      stale++;
      continue;
    }
    mkdirSync(join(OUT_DIR, port), { recursive: true });
    writeFileSync(target, content);
    console.log(`  wrote  ${file}`);
  }

  if (check) {
    if (stale > 0) return 1;
    console.log(`requirement-harness: OK — ${promises.length} promise(s), 5 port(s) in sync with the ledger.`);
    return 0;
  }
  console.log(`requirement-harness: ${promises.length} promise(s) scaffolded across 5 ports.`);
  return 0;
}

process.exit(await main());
