using MetaObjects.Codegen.Migrate;
using Xunit;

namespace MetaObjects.Codegen.Tests.Migrate;

public class PostgresEmitTests
{
    private static string Up(params Change[] changes) => PostgresEmit.Render(changes).Up;
    private static string Down(params Change[] changes) => PostgresEmit.Render(changes).Down;

    [Fact]
    public void Create_table_quotes_columns_pk_identity_and_types()
    {
        var t = new TableDescriptor("posts",
            [
                new ColumnDescriptor("id", new SqlType.Integer(64), Nullable: false, Identity: IdentityKind.Increment),
                new ColumnDescriptor("title", new SqlType.Text(200), Nullable: false),
                new ColumnDescriptor("score", new SqlType.Numeric(10, 2), Nullable: true,
                    Default: new ColumnDefault(DefaultKind.Literal, "0")),
            ],
            Indexes: [], ForeignKeys: [], PrimaryKey: ["id"]);

        var sql = Up(new Change.CreateTable(t));

        Assert.Contains("CREATE TABLE \"posts\" (", sql);
        Assert.Contains("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
        Assert.Contains("\"title\" VARCHAR(200) NOT NULL", sql);
        Assert.Contains("\"score\" NUMERIC(10,2) DEFAULT '0'", sql);
        Assert.Contains("CONSTRAINT \"posts_pkey\" PRIMARY KEY (\"id\")", sql);
    }

    [Fact]
    public void Uuid_identity_uses_gen_random_uuid_and_no_duplicate_default()
    {
        var t = new TableDescriptor("u",
            [new ColumnDescriptor("id", new SqlType.Uuid(), Nullable: false, Identity: IdentityKind.Uuid,
                Default: new ColumnDefault(DefaultKind.Expr, "gen_random_uuid()"))],
            [], [], ["id"]);
        var sql = Up(new Change.CreateTable(t));
        Assert.Contains("\"id\" UUID DEFAULT gen_random_uuid() NOT NULL", sql);
        // Only one DEFAULT clause (the identity one); not duplicated from the default attr.
        Assert.Equal(1, sql.Split("DEFAULT").Length - 1);
    }

    [Fact]
    public void Add_and_drop_column_up_and_down()
    {
        var add = new Change.AddColumn("t", new ColumnDescriptor("email", new SqlType.Text(255), Nullable: false));
        Assert.Equal("ALTER TABLE \"t\" ADD COLUMN \"email\" VARCHAR(255) NOT NULL;", Up(add));
        Assert.Equal("ALTER TABLE \"t\" DROP COLUMN \"email\";", Down(add));

        var drop = new Change.DropColumn("t", "stale");
        Assert.Equal("ALTER TABLE \"t\" DROP COLUMN \"stale\";", Up(drop));
        Assert.Contains("WARNING: down migration cannot restore data", Down(drop));
    }

    [Fact]
    public void Change_type_nullable_and_default()
    {
        Assert.Equal("ALTER TABLE \"t\" ALTER COLUMN \"n\" TYPE BIGINT;",
            Up(new Change.ChangeColumnType("t", "n", new SqlType.Integer(32), new SqlType.Integer(64))));

        Assert.Equal("ALTER TABLE \"t\" ALTER COLUMN \"c\" SET NOT NULL;",
            Up(new Change.ChangeColumnNullable("t", "c", From: true, To: false)));
        Assert.Equal("ALTER TABLE \"t\" ALTER COLUMN \"c\" DROP NOT NULL;",
            Up(new Change.ChangeColumnNullable("t", "c", From: false, To: true)));

        Assert.Equal("ALTER TABLE \"t\" ALTER COLUMN \"c\" SET DEFAULT 'x';",
            Up(new Change.ChangeColumnDefault("t", "c", From: null, To: new ColumnDefault(DefaultKind.Literal, "x"))));
        Assert.Equal("ALTER TABLE \"t\" ALTER COLUMN \"c\" DROP DEFAULT;",
            Up(new Change.ChangeColumnDefault("t", "c", From: new ColumnDefault(DefaultKind.Literal, "x"), To: null)));
    }

    [Fact]
    public void Index_and_fk_statements()
    {
        Assert.Equal("CREATE UNIQUE INDEX \"ix\" ON \"t\" (\"a\", \"b\");",
            Up(new Change.AddIndex("t", new IndexDescriptor("ix", ["a", "b"], true))));
        Assert.Equal("DROP INDEX \"ix\";", Up(new Change.DropIndex("t", "ix")));

        var fk = new Change.AddFk("t", new FkDescriptor("t_x_fk", ["x"], "other", ["id"], OnDelete: FkAction.Cascade));
        Assert.Equal(
            "ALTER TABLE \"t\" ADD CONSTRAINT \"t_x_fk\" FOREIGN KEY (\"x\") REFERENCES \"other\" (\"id\") ON DELETE CASCADE;",
            Up(fk));
        Assert.Equal("ALTER TABLE \"t\" DROP CONSTRAINT \"t_x_fk\";", Up(new Change.DropFk("t", "t_x_fk")));
    }

    [Fact]
    public void Non_default_schema_is_qualified()
    {
        var sql = Up(new Change.AddColumn("t", new ColumnDescriptor("c", new SqlType.Text(), Nullable: true), Schema: "billing"));
        Assert.Contains("ALTER TABLE \"billing\".\"t\" ADD COLUMN", sql);
        // public / null are never qualified.
        Assert.DoesNotContain("\"public\".", Up(new Change.DropColumn("t", "c", Schema: "public")));
    }

    [Fact]
    public void Changes_are_staged_and_down_is_reversed()
    {
        // Deliberately out of stage order on input.
        var dropTable = new Change.DropTable("old");
        var createTable = new Change.CreateTable(new TableDescriptor("new",
            [new ColumnDescriptor("id", new SqlType.Integer(64), Nullable: false)], [], [], ["id"]));
        var addFk = new Change.AddFk("new", new FkDescriptor("fk", ["id"], "old", ["id"]));

        var up = Up(dropTable, addFk, createTable);
        var idxCreate = up.IndexOf("CREATE TABLE", System.StringComparison.Ordinal);
        var idxFk = up.IndexOf("ADD CONSTRAINT", System.StringComparison.Ordinal);
        var idxDrop = up.IndexOf("DROP TABLE", System.StringComparison.Ordinal);
        Assert.True(idxCreate < idxFk && idxFk < idxDrop, "stages: create < add-fk < drop-table");

        // Down reverses: the create-table's down (DROP TABLE "new") comes last.
        var down = Down(createTable, addFk);
        Assert.True(
            down.IndexOf("DROP CONSTRAINT", System.StringComparison.Ordinal) <
            down.IndexOf("DROP TABLE \"new\"", System.StringComparison.Ordinal),
            "down reversed: drop-constraint before drop-table");
    }

    [Fact]
    public void PgType_renders_each_kind()
    {
        string T(SqlType t) => Up(new Change.AddColumn("t", new ColumnDescriptor("c", t, Nullable: true)));
        Assert.Contains("TEXT;", T(new SqlType.Text()));
        Assert.Contains("VARCHAR(50)", T(new SqlType.Text(50)));
        Assert.Contains("INTEGER;", T(new SqlType.Integer(32)));
        Assert.Contains("DOUBLE PRECISION", T(new SqlType.Real()));
        Assert.Contains("NUMERIC(10,2)", T(new SqlType.Numeric(10, 2)));
        Assert.Contains("NUMERIC(8)", T(new SqlType.Numeric(8)));
        Assert.Contains("NUMERIC;", T(new SqlType.Numeric()));
        Assert.Contains("BOOLEAN", T(new SqlType.Boolean()));
        Assert.Contains("TIMESTAMPTZ", T(new SqlType.Timestamp(true)));
        Assert.Contains("TIMESTAMP;", T(new SqlType.Timestamp(false)));
        Assert.Contains("DATE", T(new SqlType.Date()));
        Assert.Contains("JSONB", T(new SqlType.Json()));
        Assert.Contains("BYTEA", T(new SqlType.Blob()));
        Assert.Contains("UUID", T(new SqlType.Uuid()));
    }

    [Fact]
    public void Literal_default_escapes_single_quotes()
    {
        var sql = Up(new Change.ChangeColumnDefault("t", "c", From: null,
            To: new ColumnDefault(DefaultKind.Literal, "O'Brien")));
        Assert.Contains("SET DEFAULT 'O''Brien';", sql);
    }
}
