// AgentContextScaffold — sidecar manifest descriptor + staleness decision.
//
// The scaffold-WRITE path (Plan/assemble/write) has moved to the Node meta CLI
// (ADR-0015). This file retains only the manifest shape and the pure staleness
// decision so the live `gen`/`verify` commands can nudge a re-scaffold when the
// installed agent context predates the current MetaObjects build.

namespace MetaObjects.AgentContext;

/// <summary>Sidecar manifest descriptor and staleness decision for the agent-context nudge.</summary>
public static class AgentContextScaffold
{
    /// <summary>Consumer-relative path of the sidecar manifest that tracks scaffolded files.</summary>
    public const string ManifestPath = ".metaobjects/.agent-context.json";

    /// <summary>Tracks what the assembler last wrote, so re-runs can detect hand-edits.</summary>
    /// <param name="GeneratedBy">
    /// The MetaObjects version that last scaffolded this agent context. Used to nudge a
    /// re-scaffold when the installed version moves ahead (the skills/docs ship with the
    /// package, so an upgrade can leave the copied-in context stale). Nullable for
    /// back-compat with manifests written before version tracking existed.
    /// </param>
    public sealed record Manifest(
        int Version,
        string? GeneratedBy,
        IReadOnlyList<string> Servers,
        IReadOnlyList<string> Clients,
        IReadOnlyDictionary<string, string> Files);

    /// <summary>
    /// A one-line nudge if the scaffolded agent context predates the installed MetaObjects
    /// (so <c>gen</c>/<c>verify</c> can remind the user to refresh the skills after an
    /// upgrade), or <c>null</c> when there is nothing to say — no agent context scaffolded,
    /// or it is in sync. Advisory only: never throws, never blocks, never writes. Pure.
    /// </summary>
    public static string? AgentContextStaleness(Manifest? manifest, string currentVersion)
    {
        if (manifest is null) return null; // no agent context here → nothing to nudge
        // Exact-equality FIRST: ANY drift nudges (a re-scaffold is cheap + idempotent). A
        // prerelease/build-metadata difference is still a reason to refresh, so this is not a
        // semver compare — see ContextIsAheadOfInstall for the ONE case that is exempt.
        if (manifest.GeneratedBy == currentVersion) return null; // in sync
        if (ContextIsAheadOfInstall(manifest.GeneratedBy, currentVersion)) return null;
        var from = manifest.GeneratedBy ?? "an older MetaObjects";
        return
            $"MetaObjects agent context was generated by {from}; you're on {currentVersion}. " +
            "Re-run 'npx meta agent-docs --server csharp' to refresh the .claude/skills docs.";
    }

    /// <summary>The sentinel a port stamps when it cannot resolve its own installed version.</summary>
    private const string UnresolvedVersion = "0.0.0";

    /// <summary>
    /// Ordered release coordinate <c>(minor, patch)</c>, or <c>null</c> when not orderable.
    /// <para>The MAJOR is deliberately dropped. It is a per-registry constant, not information:
    /// npm/PyPI/NuGet ship <c>0.&lt;m&gt;.&lt;p&gt;</c> and Maven Central the same
    /// <c>&lt;m&gt;.&lt;p&gt;</c> on its historical major <c>7</c>, so minor.patch IS the shared
    /// release coordinate across all four ports.</para>
    /// <para><c>null</c> means "not orderable, so nudge", and deliberately covers prereleases
    /// (<c>0.24.5-rc.1</c>), build metadata (<c>0.24.5+abc</c>) and the <c>0.0.0</c> sentinel.
    /// Each must keep nudging: an RC-scaffolded context against a final release is still worth
    /// refreshing, and an unknown install must never assert "in sync".</para>
    /// </summary>
    private static (int Minor, int Patch)? ReleaseSeries(string? version)
    {
        if (version is null) return null;
        var v = version.Trim();
        if (v == UnresolvedVersion) return null;
        var parts = v.Split('.');
        if (parts.Length != 3) return null;
        foreach (var p in parts)
        {
            if (p.Length == 0) return null;
            foreach (var c in p) if (c < '0' || c > '9') return null;
        }
        return (int.Parse(parts[1]), int.Parse(parts[2]));
    }

    /// <summary>
    /// True when the manifest was stamped by a release STRICTLY NEWER than the install.
    /// <para>The one exemption from "any drift nudges", and it exists because of the
    /// publish-what-changed rule (docs/RELEASING.md): a registry publishes only when it has a
    /// changed product file, so a port legitimately sits behind npm — while
    /// <c>meta agent-docs</c>, the canonical scaffolder for EVERY port, stamps the npm version
    /// it was run from. A C# install at <c>0.24.4</c> whose context was scaffolded by npm
    /// <c>0.24.7</c> is correct, and nudging it is issue #347 exactly: the remedy re-runs the
    /// scaffolder, which re-stamps <c>0.24.7</c>, so the advisory can never be satisfied and
    /// fires on every build forever.</para>
    /// <para>KNOWN BOUND, stated rather than hidden: ordering on minor.patch assumes both
    /// versions sit in the same release SERIES. That holds for every release to date and after
    /// the 1.0/8.0 cut, but not ACROSS it — there a <c>0.24.x</c> context against a
    /// <c>1.0.0</c> install reads as "ahead" and the nudge is suppressed once. A missed
    /// advisory, never a wrong action.</para>
    /// </summary>
    private static bool ContextIsAheadOfInstall(string? generatedBy, string currentVersion)
    {
        var stamped = ReleaseSeries(generatedBy);
        var installed = ReleaseSeries(currentVersion);
        if (stamped is null || installed is null) return false; // not orderable → nudge
        return stamped.Value.Minor > installed.Value.Minor
            || (stamped.Value.Minor == installed.Value.Minor && stamped.Value.Patch > installed.Value.Patch);
    }
}
