// AgentContextScaffold — sidecar manifest descriptor + staleness decision.
//
// The scaffold-WRITE path (Plan/assemble/write) has moved to the Node meta CLI
// (ADR-0015). This file retains only the manifest shape and the pure staleness
// decision so the live `gen`/`verify` commands can nudge a re-scaffold when the
// installed agent context predates the current MetaObjects build.

namespace MetaObjects.AgentContext;

/// <summary>Sidecar manifest descriptor and staleness decision for the agent-context nudge.</summary>
public static class AgentContextScaffold
{
    /// <summary>Consumer-relative path of the sidecar manifest that tracks scaffolded files.</summary>
    public const string ManifestPath = ".metaobjects/.agent-context.json";

    /// <summary>Tracks what the assembler last wrote, so re-runs can detect hand-edits.</summary>
    /// <param name="GeneratedBy">
    /// The MetaObjects version that last scaffolded this agent context. Used to nudge a
    /// re-scaffold when the installed version moves ahead (the skills/docs ship with the
    /// package, so an upgrade can leave the copied-in context stale). Nullable for
    /// back-compat with manifests written before version tracking existed.
    /// </param>
    public sealed record Manifest(
        int Version,
        string? GeneratedBy,
        IReadOnlyList<string> Servers,
        IReadOnlyList<string> Clients,
        IReadOnlyDictionary<string, string> Files);

    /// <summary>
    /// A one-line nudge if the scaffolded agent context predates the installed MetaObjects
    /// (so <c>gen</c>/<c>verify</c> can remind the user to refresh the skills after an
    /// upgrade), or <c>null</c> when there is nothing to say — no agent context scaffolded,
    /// or it is in sync. Advisory only: never throws, never blocks, never writes. Pure.
    /// </summary>
    public static string? AgentContextStaleness(Manifest? manifest, string currentVersion)
    {
        if (manifest is null) return null; // no agent context here → nothing to nudge
        // Exact-equality on purpose: ANY drift nudges (a re-scaffold is cheap + idempotent).
        // Don't "fix" this into a semver compare — a prerelease/build-metadata difference is
        // still a reason to refresh, and the nudge is advisory, never a gate.
        if (manifest.GeneratedBy == currentVersion) return null; // in sync
        var from = manifest.GeneratedBy ?? "an older MetaObjects";
        return
            $"MetaObjects agent context was generated by {from}; you're on {currentVersion}. " +
            "Re-run 'npx meta agent-docs --server csharp' to refresh the .claude/skills docs.";
    }
}
