# @generated by metaobjects — DO NOT EDIT.
# Source metadata: BaseEntity (acme::common::BaseEntity)
# Customize via BaseEntity_extra.py in this directory.

from __future__ import annotations

from pydantic import BaseModel


class BaseEntity(BaseModel):
    id: int


class BaseEntityPatch(BaseModel):
    """GENERATED — PATCH input: all fields optional; present values validated (FR-036)."""

    id: int | None = None
