import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, readFileSync, readdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { runGen, defineConfig } from "../src/index.js";
import { entityFile, queriesFile, barrel } from "../src/generators/index.js";
import { MetaDataLoader } from "@metaobjectsdev/metadata";

let tmp: string;
beforeEach(() => { tmp = mkdtempSync(join(tmpdir(), "ai-codegen-")); });
afterEach(() => { rmSync(tmp, { recursive: true, force: true }); });

// ---------------------------------------------------------------------------
// Inline model: abstract LlmCallBase with representative field types
// (uuid, string, int, currency, and string+jsonb override) + a concrete ApiCall
// that extends it and adds source.rdb + identity.primary.
// ---------------------------------------------------------------------------
const MODEL_YAML = [
  "metadata:",
  "  package: app::ops",
  "  children:",
  "    - object.entity:",
  "        name: LlmCallBase",
  "        abstract: true",
  "        children:",
  "          - field.uuid:     { name: traceId }",
  "          - field.string:   { name: callType }",
  "          - field.int:      { name: inputTokens }",
  "          - field.currency: { name: costMinor, currency: USD }",
  "          - field.string:   { name: llmRequest, dbColumnType: jsonb }",
  "    - object.entity:",
  "        name: ApiCall",
  "        extends: LlmCallBase",
  "        children:",
  "          - source.rdb:      { table: api_call, role: primary }",
  '          - identity.primary: { name: id, fields: ["traceId"] }',
].join("\n");

describe("ai LlmCall codegen — abstract base + concrete entity", () => {
  test("concrete entity extending an abstract base emits a table with inherited jsonb column", async () => {
    // --- Load ---
    const loaded = await MetaDataLoader.fromString(MODEL_YAML, "yaml");
    expect(loaded.errors).toEqual([]);

    // --- Generate ---
    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: loaded.root,
    });
    expect(out.warnings).toEqual([]);

    const files = readdirSync(tmp);

    // Concrete entity MUST be emitted as a full table file.
    expect(files).toContain("ApiCall.ts");

    // Abstract base is emitted as a pure TS shape (interface + Zod, no pgTable)
    // via the default emitAbstractShapes:true knob.  This is expected behavior.
    expect(files).toContain("LlmCallBase.ts");

    // --- Inspect the generated ApiCall entity file ---
    const apiCall = readFileSync(join(tmp, "ApiCall.ts"), "utf-8");

    // Standard generated-file header must be present
    expect(apiCall).toContain("@generated by @metaobjectsdev/codegen-ts");

    // ApiCall uses pgTable (Postgres dialect) keyed to the source.rdb table name
    expect(apiCall).toContain("pgTable");
    expect(apiCall).toContain("api_call");

    // Inherited field.string + dbColumnType:jsonb → jsonb("llm_request") in Postgres
    expect(apiCall).toContain("jsonb");
    expect(apiCall).toContain("llmRequest");

    // Inherited field.uuid → uuid("trace_id").primaryKey()
    expect(apiCall).toContain("uuid");
    expect(apiCall).toContain("traceId");

    // Inherited field.int → integer("input_tokens")
    expect(apiCall).toContain("integer");

    // Inherited field.currency → bigint("cost_minor", { mode: "number" })
    expect(apiCall).toContain("bigint");

    // --- Abstract shape file has NO pgTable (no DB table for abstract base) ---
    const base = readFileSync(join(tmp, "LlmCallBase.ts"), "utf-8");
    expect(base).not.toContain("pgTable");
    expect(base).toContain("LlmCallBase");   // interface/type present
    expect(base).toContain("LlmCallBaseInsertSchema"); // Zod shape present
  });
});
