import { describe, test, expect } from "bun:test";
import {
  runGen, defineConfig, perEntity, oncePerRun,
  mapColumnType, buildPkMap, makeRenderContext,
  GENERATED_HEADER,
} from "../src/index.js";
import type { Dialect, Generator, MetaobjectsGenConfig } from "../src/index.js";

describe("public API", () => {
  test("exports the new runGen + defineConfig + Generator + helpers", () => {
    expect(runGen).toBeDefined();
    expect(defineConfig).toBeDefined();
    expect(perEntity).toBeDefined();
    expect(oncePerRun).toBeDefined();
    expect(mapColumnType).toBeDefined();
    expect(buildPkMap).toBeDefined();
    expect(makeRenderContext).toBeDefined();
  });

  test("GENERATED_HEADER is the byte the overwrite-policy looks for", () => {
    expect(GENERATED_HEADER).toBe("@generated by @metaobjects/codegen-ts");
  });

  test("Dialect / Generator / MetaobjectsGenConfig type-only imports compile", () => {
    const dialect: Dialect = "sqlite";
    expect(dialect).toBe("sqlite");
    const stub: Generator = { name: "stub", generate: async () => [] };
    const cfg: MetaobjectsGenConfig = { outDir: "out", extStyle: "none", dbImport: "../db", dialect, generators: [stub] };
    expect(cfg.generators.length).toBe(1);
  });
});
