// FR-038 §4 — red-stub semantics.
//
// The load-bearing rule: an empty generated stub must NOT pass. A `live` entry
// claims the capability works, so an empty green test asserts the opposite of the
// claim and recreates the original defect in a new place.

import { describe, test, expect } from "bun:test";
import { renderRequirementTest } from "../src/templates/requirement-test.js";
import type { RequirementTestArgs } from "../src/templates/requirement-test.js";

const base: RequirementTestArgs = {
  view: {
    subType: "functional",
    level: 4,
    status: "live",
    path: "links.slugField",
    package: "acme::probe",
    implementedByTypes: [],
  },
  concern: "object.entity",
  statement: "A council has a human-readable slug.",
  counterexample: "a council with no slug",
  targets: [],
  package: "acme::probe",
  unit: "object.entity",
  id: "acme::probe::links.slugField [object.entity]",
  witnessKey: "req_acme_probe_links_slugField__object_entity",
  skip: null,
  digest: "0".repeat(64),
};

describe("renderRequirementTest", () => {
  test("a LIVE stub emits a failing assertion, never an empty body", () => {
    const src = renderRequirementTest(base);
    expect(src).toContain("expect.unreachable");
    expect(src).not.toContain("test.skip");
  });

  test("a PLANNED stub is skipped — a red build for something deliberately unbuilt is noise", () => {
    const src = renderRequirementTest({
      ...base,
      view: { ...base.view, status: "planned" },
    });
    expect(src).toContain("test.skip");
    expect(src).not.toContain("expect.unreachable");
  });

  test("a RETIRED stub is skipped — the capability was deliberately removed", () => {
    // 0.24.0 retired `abandoned` and `superseded`; 0.24.2 restored `retired` in
    // their place. The skip set was never moved across, so it skipped two statuses
    // the loader now REFUSES and failed on the one that replaced them — emitting a
    // permanently red stub for a capability nobody intends to rebuild, which is the
    // exact noise the set exists to prevent. Found by authoring the first real
    // retired entries outside a conformance fixture.
    const src = renderRequirementTest({
      ...base,
      view: { ...base.view, status: "retired" },
    });
    expect(src).toContain("test.skip");
    expect(src).not.toContain("expect.unreachable");
    // And it must not read as an instruction to REVIVE the capability. `planned` and
    // `retired` are both skipped and mean opposite things, so sharing a body told a
    // reader of a retired stub to write the assertion "when this becomes live".
    expect(src).toContain("must not be rebuilt");
    expect(src).not.toContain("becomes live");
  });

  test("a PARTIAL stub fails like live, and carries its disposition and tracking", () => {
    const src = renderRequirementTest({
      ...base,
      view: { ...base.view, status: "partial" },
      disposition: "deferred",
      trackedBy: ["#123"],
    });
    expect(src).toContain("expect.unreachable");
    expect(src).toContain("deferred");
    expect(src).toContain("#123");
  });

  test("the statement and the violation are both in the doc comment", () => {
    const src = renderRequirementTest(base);
    expect(src).toContain("A council has a human-readable slug.");
    expect(src).toContain("a council with no slug");
  });

  test("claimed refs are listed with their concerns", () => {
    const src = renderRequirementTest({
      ...base,
      targets: [
        { ref: "Council", concern: "object.entity", node: {} as never },
        { ref: "Council.slug", concern: "field.string", node: {} as never },
      ],
    });
    expect(src).toContain("Council.slug");
    expect(src).toContain("field.string");
  });

  test("says the body is hand-written — this file is NOT 'do not edit'", () => {
    // The identity is generated; the assertions are the author's and survive
    // regeneration through the three-way merge. A DO-NOT-EDIT header would tell
    // the one person who must edit it not to.
    const src = renderRequirementTest(base);
    expect(src).toContain("@generated");
    expect(src).not.toContain("DO NOT EDIT");
  });

  test("the test name carries both the requirement path and the concern", () => {
    const src = renderRequirementTest(base);
    expect(src).toContain("links.slugField");
    expect(src).toContain("object.entity");
  });
});

describe("renderRequirementTest — the default stub keeps its bytes", () => {
  // The whole stub, pinned. An application's hand-written test bodies live in these
  // files and are merged against them, so a changed byte in the default output is a
  // three-way merge on every stub an adopter has already filled in.
  const EXPECTED =
    `// @generated by @metaobjectsdev/codegen-ts.\n` +
    `// The test IDENTITY is generated from the requirement; the BODY below is yours.\n` +
    `// Do not rename the test — the name is the link.\n` +
    `// Your body is never overwritten: MERGED where .metaobjects/.gen-state/ holds this\n` +
    `// file's snapshot body, REFUSED (run exits 1, body kept) where it does not. Those\n` +
    `// bodies are gitignored, so a fresh clone or CI is always the second case — see\n` +
    `// docs/features/own-your-codegen.md for the recovery.\n` +
    `import { test, expect } from "bun:test";\n` +
    `\n` +
    `/**\n` +
    ` * A council has a human-readable slug.\n` +
    ` *\n` +
    ` * Counterexample: a council with no slug\n` +
    ` *\n` +
    ` * Claims:\n` +
    ` *   (none — this requirement names no model nodes)\n` +
    ` */\n` +
    `test("links.slugField [object.entity]", () => {\n` +
    `  expect.unreachable(\n` +
    `    "unimplemented requirement stub: links.slugField [object.entity] — " +\n` +
    `    "replace this with an assertion that fails when: a council with no slug",\n` +
    `  );\n` +
    `});\n`;

  test("the default output is byte-identical with the new args present", () => {
    expect(renderRequirementTest(base)).toBe(EXPECTED);
    // …and the identity fields are DATA for an application's renderer, not input to
    // this one: whatever they hold, the default stub does not move.
    expect(
      renderRequirementTest({
        ...base,
        view: { ...base.view, package: "other::pkg" },
        package: "other::pkg",
        unit: "Other.member",
        id: "other::pkg::Somewhere.Else [Other.member]",
        witnessKey: "req_other_pkg_Somewhere_Else__Other_member",
        skip: "planned",
        digest: "f".repeat(64),
      }),
    ).toBe(EXPECTED);
  });
});
