import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, readFileSync, existsSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import type { MetaRoot, MetaObject } from "@metaobjects/metadata";
import {
  TypeId,
  TYPE_IDENTITY,
  OBJECT_SUBTYPE_ENTITY,
  FIELD_SUBTYPE_STRING,
  FIELD_SUBTYPE_LONG,
  IDENTITY_SUBTYPE_PRIMARY,
  IDENTITY_ATTR_FIELDS,
  IDENTITY_ATTR_GENERATION,
  GENERATION_INCREMENT,
} from "@metaobjects/metadata";
import { FileMetaDataLoader } from "@metaobjects/metadata/core";
import { meta, metaRoot, metaObject, metaField } from "./_meta-build.js";
import { runGen, defineConfig } from "../src/index.js";
import { entityFile, queriesFile, routesFile, barrel } from "../src/generators/index.js";

let tmp: string;
beforeEach(() => { tmp = mkdtempSync(join(tmpdir(), "codegen-run-gen-")); });
afterEach(() => { rmSync(tmp, { recursive: true, force: true }); });

const FIXTURE_DIR = resolve(import.meta.dir, "fixtures");

describe("runGen — single entity, SQLite", () => {
  test("emits Post.ts, Post.queries.ts, and index.ts in outDir", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([join(FIXTURE_DIR, "single-entity.json")]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    // dbImport is set; no warning expected
    expect(out.warnings).toEqual([]);
    const files = readdirSync(tmp);
    expect(files).toContain("Post.ts");
    expect(files).toContain("Post.queries.ts");
    expect(files).toContain("index.ts");

    const postContent = readFileSync(join(tmp, "Post.ts"), "utf-8");
    expect(postContent).toContain("@generated by @metaobjects/codegen-ts");
    expect(postContent).toContain("sqliteTable");
    expect(postContent).toContain("PostInsertSchema");
    expect(postContent).toContain("InferSelectModel");

    const queriesContent = readFileSync(join(tmp, "Post.queries.ts"), "utf-8");
    expect(queriesContent).toContain("@generated by @metaobjects/codegen-ts");
    expect(queriesContent).toContain("~/server/db");
    expect(queriesContent).toContain("findPostById");
    expect(queriesContent).toContain("createPost");

    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Post"');
    // barrel does NOT re-export from Post.queries.js
    expect(barrelContent).not.toContain("queries");
  });
});

describe("runGen — two entities with FK, Postgres", () => {
  test("emits entity + queries files; FK .references() auto-emitted; column type matches User.id", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([join(FIXTURE_DIR, "two-entities-fk.json")]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    expect(out.warnings).toEqual([]);
    expect(existsSync(join(tmp, "User.ts"))).toBe(true);
    expect(existsSync(join(tmp, "User.queries.ts"))).toBe(true);
    expect(existsSync(join(tmp, "Post.ts"))).toBe(true);
    expect(existsSync(join(tmp, "Post.queries.ts"))).toBe(true);
    expect(existsSync(join(tmp, "index.ts"))).toBe(true);

    const postContent = readFileSync(join(tmp, "Post.ts"), "utf-8");
    expect(postContent).toContain("pgTable");
    expect(postContent).toContain("authorId");
    expect(postContent).toContain("bigint");        // long PK → bigint FK in postgres
    expect(postContent).toContain(".references(");  // FK .references() auto-emitted
    expect(postContent).toContain("postsRelations"); // relations() block auto-emitted
  });
});

describe("runGen — refuses to clobber hand-written files", () => {
  test("file without @generated header is left alone, status 'refused'", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([join(FIXTURE_DIR, "single-entity.json")]);

    // Pre-place a hand-written Post.ts in outDir
    const handPath = join(tmp, "Post.ts");
    writeFileSync(handPath, "// I am a user wrote this\nexport const sacred = true;");

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    const postFile = out.files.find((f) => f.path.endsWith("Post.ts"));
    expect(postFile?.status).toBe("refused");
    expect(readFileSync(handPath, "utf-8")).toContain("sacred = true");
    expect(out.warnings.length).toBeGreaterThan(0);

    // Post.queries.ts should still be generated (its refusal is independent)
    expect(existsSync(join(tmp, "Post.queries.ts"))).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Helper: build a minimal in-memory MetaData root with one entity + long PK.
// Used for tests that need custom/untrusted names without going through the
// JSON parser (which might itself reject invalid names).
// ---------------------------------------------------------------------------
function makeRoot(pkg: string): MetaRoot {
  return metaRoot("root", pkg);
}

function makeEntity(name: string): MetaObject {
  const entity = metaObject(OBJECT_SUBTYPE_ENTITY, name);
  // id field (long)
  const id = metaField(FIELD_SUBTYPE_LONG, "id");
  entity.addChild(id);
  // title field (string)
  const title = metaField(FIELD_SUBTYPE_STRING, "title");
  entity.addChild(title);
  // primary identity
  const pk = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
  pk.setAttr(IDENTITY_ATTR_FIELDS, ["id"]);
  pk.setAttr(IDENTITY_ATTR_GENERATION, GENERATION_INCREMENT);
  entity.addChild(pk);
  return entity;
}

// ---------------------------------------------------------------------------
// Item 2 regression: path-traversal guard
// ---------------------------------------------------------------------------
describe("runGen — path-traversal guard (security)", () => {
  test("entity named '../evil' is skipped with a warning; normal entity still generates", async () => {
    const root = makeRoot("security-test");
    root.addChild(makeEntity("../evil"));
    root.addChild(makeEntity("Post"));

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), barrel()],
      }),
      metadata: root,
    });

    // The warning must mention the unsafe name
    expect(out.warnings.some((w) => w.includes("unsafe name") && w.includes("../evil"))).toBe(true);

    // No file should be written for "../evil" — nothing outside tmp
    expect(existsSync(join(tmp, "../evil.ts"))).toBe(false);
    expect(existsSync(join(tmp, "..evil.ts"))).toBe(false);

    // Post should still be generated normally
    expect(existsSync(join(tmp, "Post.ts"))).toBe(true);

    // Barrel should only reference Post
    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Post"');
    expect(barrelContent).not.toContain("evil");
  });
});

// ---------------------------------------------------------------------------
// Item 4: skip-existing strategy E2E test
// ---------------------------------------------------------------------------
describe("runGen — mergeStrategy: 'skip-existing'", () => {
  test("existing generated files are skipped; new entities still written", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([join(FIXTURE_DIR, "single-entity.json")]);
    expect(result.errors).toEqual([]);

    const baseConfig = defineConfig({
      outDir: tmp,
      extStyle: "none",
      dbImport: "~/server/db",
      dialect: "sqlite",
      generators: [entityFile(), queriesFile(), barrel()],
    });

    // First run: overwrite strategy produces new files
    const run1 = await runGen({
      config: baseConfig,
      metadata: result.root,
      mergeStrategy: "overwrite",
    });
    expect(run1.files.every((f) => f.status === "new")).toBe(true);

    // Modify Post.ts slightly (append a comment) — still has @generated header
    const postPath = join(tmp, "Post.ts");
    const original = readFileSync(postPath, "utf-8");
    writeFileSync(postPath, original + "\n// user tweak");

    // Second run: skip-existing — Post.ts should be skipped, content unchanged
    const run2 = await runGen({
      config: baseConfig,
      metadata: result.root,
      mergeStrategy: "skip-existing",
    });

    const postResult = run2.files.find((f) => f.path.endsWith("Post.ts"));
    expect(postResult?.status).toBe("skipped");

    // Content must be unchanged (our tweak comment is still there)
    const afterRun2 = readFileSync(postPath, "utf-8");
    expect(afterRun2).toContain("// user tweak");

    // All other files also skipped (they all have @generated headers)
    for (const f of run2.files) {
      expect(f.status).toBe("skipped");
    }

    // Now add a NEW entity to the root — it should still be written
    const root2 = makeRoot("test");
    // Copy the Post entity from result
    const postEntity = result.root.ownChildren().find((c) => c.name === "Post")!;
    root2.addChild(postEntity);
    root2.addChild(makeEntity("Comment"));

    const run3 = await runGen({
      config: baseConfig,
      metadata: root2,
      mergeStrategy: "skip-existing",
    });

    const commentResult = run3.files.find((f) => f.path.endsWith("Comment.ts"));
    expect(commentResult?.status).toBe("new");

    const postResult3 = run3.files.find((f) => f.path.endsWith("Post.ts"));
    expect(postResult3?.status).toBe("skipped");
  });
});

// ---------------------------------------------------------------------------
// Item 5: entityFilter test
// ---------------------------------------------------------------------------
describe("runGen — entityFilter", () => {
  test("entityFilter: ['Post'] produces only Post files; barrel reflects filter", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([join(FIXTURE_DIR, "two-entities-fk.json")]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: result.root,
      entityFilter: ["Post"],
    });

    expect(out.warnings).toEqual([]);

    // Only Post files should exist — no User files
    expect(existsSync(join(tmp, "Post.ts"))).toBe(true);
    expect(existsSync(join(tmp, "Post.queries.ts"))).toBe(true);
    expect(existsSync(join(tmp, "index.ts"))).toBe(true);
    expect(existsSync(join(tmp, "User.ts"))).toBe(false);
    expect(existsSync(join(tmp, "User.queries.ts"))).toBe(false);

    // Barrel only re-exports Post
    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Post"');
    expect(barrelContent).not.toContain("User");
  });

  test("entityFilter: ['NonExistent'] produces 0 entity files and a warning", async () => {
    const loader = new FileMetaDataLoader();
    const result = await loader.loadFiles([join(FIXTURE_DIR, "two-entities-fk.json")]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: result.root,
      entityFilter: ["NonExistent"],
    });

    expect(out.warnings.some((w) => w.includes("No entities to generate"))).toBe(true);
    expect(out.files).toHaveLength(0);
    expect(existsSync(join(tmp, "index.ts"))).toBe(false);
  });
});
