import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, readFileSync, existsSync, readdirSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import type { MetaRoot, MetaObject } from "@metaobjectsdev/metadata";
import {
  TypeId,
  TYPE_IDENTITY,
  OBJECT_SUBTYPE_ENTITY,
  FIELD_SUBTYPE_STRING,
  FIELD_SUBTYPE_LONG,
  IDENTITY_SUBTYPE_PRIMARY,
  IDENTITY_ATTR_FIELDS,
  IDENTITY_ATTR_GENERATION,
  GENERATION_INCREMENT,
} from "@metaobjectsdev/metadata";
import { meta, metaRoot, metaObject, metaField } from "./_meta-build.js";
import { runGen, defineConfig } from "../src/index.js";
import { entityFile, queriesFile, routesFile, barrel } from "../src/generators/index.js";
import { MetaDataLoader } from "@metaobjectsdev/metadata";
import { FileSource } from "@metaobjectsdev/metadata/core";

let tmp: string;
beforeEach(() => { tmp = mkdtempSync(join(tmpdir(), "codegen-run-gen-")); });
afterEach(() => { rmSync(tmp, { recursive: true, force: true }); });

const FIXTURE_DIR = resolve(import.meta.dir, "fixtures");

describe("runGen — single entity, SQLite", () => {
  test("emits Post.ts, Post.queries.ts, and index.ts in outDir", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "single-entity.json"))]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    // dbImport is set; no warning expected
    expect(out.warnings).toEqual([]);
    const files = readdirSync(tmp);
    expect(files).toContain("Post.ts");
    expect(files).toContain("Post.queries.ts");
    expect(files).toContain("index.ts");

    const postContent = readFileSync(join(tmp, "Post.ts"), "utf-8");
    expect(postContent).toContain("@generated by @metaobjectsdev/codegen-ts");
    expect(postContent).toContain("sqliteTable");
    expect(postContent).toContain("PostInsertSchema");
    expect(postContent).toContain("InferSelectModel");

    const queriesContent = readFileSync(join(tmp, "Post.queries.ts"), "utf-8");
    expect(queriesContent).toContain("@generated by @metaobjectsdev/codegen-ts");
    // FR2 / ADR-0008: queries-file no longer imports a runtime `db` from
    // <dbImport>; it emits a dialect-correct `type Db = ...` alias instead and
    // every CRUD helper takes `db: Db` as its first parameter.
    expect(queriesContent).not.toContain("~/server/db");
    expect(queriesContent).toContain("type Db = BaseSQLiteDatabase");
    expect(queriesContent).toContain("findPostById");
    expect(queriesContent).toContain("createPost");

    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Post"');
    // barrel does NOT re-export from Post.queries.js
    expect(barrelContent).not.toContain("queries");
  });
});

describe("runGen — two entities with FK, Postgres", () => {
  test("emits entity + queries files; FK .references() auto-emitted; column type matches User.id", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "two-entities-fk.json"))]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
    });

    expect(out.warnings).toEqual([]);
    expect(existsSync(join(tmp, "User.ts"))).toBe(true);
    expect(existsSync(join(tmp, "User.queries.ts"))).toBe(true);
    expect(existsSync(join(tmp, "Post.ts"))).toBe(true);
    expect(existsSync(join(tmp, "Post.queries.ts"))).toBe(true);
    expect(existsSync(join(tmp, "index.ts"))).toBe(true);

    const postContent = readFileSync(join(tmp, "Post.ts"), "utf-8");
    expect(postContent).toContain("pgTable");
    expect(postContent).toContain("authorId");
    expect(postContent).toContain("bigint");        // long PK → bigint FK in postgres
    expect(postContent).toContain(".references(");  // FK .references() auto-emitted
    expect(postContent).toContain("postsRelations"); // relations() block auto-emitted
  });
});

describe("runGen — first-time regen on a pre-existing file", () => {
  // A file at a codegen output path that we have NO record of writing is refused,
  // not overwritten. This assertion was the reverse until the hash manifest made
  // "did we write this?" answerable without the gitignored snapshot body.
  //
  // The `<Entity>.extra.ts` sibling convention is still the right way to keep
  // hand-written code near a generated module — but it is advice, and advice is
  // not a reason to destroy the file of someone who did not follow it.
  test("pre-existing file with different content → REFUSED, content preserved", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "single-entity.json"))]);

    // Pre-place a hand-written Post.ts in outDir
    const handPath = join(tmp, "Post.ts");
    writeFileSync(handPath, "// I am a user wrote this\nexport const sacred = true;");

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), queriesFile(), routesFile(), barrel()],
      }),
      metadata: result.root,
      projectRoot: tmp,
    });

    const postFile = out.files.find((f) => f.path.endsWith("Post.ts"));
    expect(postFile?.status).toBe("refused");
    // The sentinel survives — and the run says why rather than staying silent.
    expect(readFileSync(handPath, "utf-8")).toContain("sacred = true");
    expect(out.warnings.some((w) => w.includes("Post.ts"))).toBe(true);

    // Post.queries.ts likewise generated normally.
    expect(existsSync(join(tmp, "Post.queries.ts"))).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Helper: build a minimal in-memory MetaData root with one entity + long PK.
// Used for tests that need custom/untrusted names without going through the
// JSON parser (which might itself reject invalid names).
// ---------------------------------------------------------------------------
function makeRoot(pkg: string): MetaRoot {
  return metaRoot("root", pkg);
}

function makeEntity(name: string): MetaObject {
  const entity = metaObject(OBJECT_SUBTYPE_ENTITY, name);
  // id field (long)
  const id = metaField(FIELD_SUBTYPE_LONG, "id");
  entity.addChild(id);
  // title field (string)
  const title = metaField(FIELD_SUBTYPE_STRING, "title");
  entity.addChild(title);
  // primary identity
  const pk = meta(new TypeId(TYPE_IDENTITY, IDENTITY_SUBTYPE_PRIMARY), "primary");
  pk.setAttr(IDENTITY_ATTR_FIELDS, ["id"]);
  pk.setAttr(IDENTITY_ATTR_GENERATION, GENERATION_INCREMENT);
  entity.addChild(pk);
  return entity;
}

// ---------------------------------------------------------------------------
// Item 2 regression: path-traversal guard
// ---------------------------------------------------------------------------
describe("runGen — path-traversal guard (security)", () => {
  test("entity named '../evil' is skipped with a warning; normal entity still generates", async () => {
    const root = makeRoot("security-test");
    root.addChild(makeEntity("../evil"));
    root.addChild(makeEntity("Post"));

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "sqlite",
        generators: [entityFile(), barrel()],
      }),
      metadata: root,
    });

    // The warning must mention the unsafe name
    expect(out.warnings.some((w) => w.includes("unsafe name") && w.includes("../evil"))).toBe(true);

    // No file should be written for "../evil" — nothing outside tmp
    expect(existsSync(join(tmp, "../evil.ts"))).toBe(false);
    expect(existsSync(join(tmp, "..evil.ts"))).toBe(false);

    // Post should still be generated normally
    expect(existsSync(join(tmp, "Post.ts"))).toBe(true);

    // Barrel should only reference Post
    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Post"');
    expect(barrelContent).not.toContain("evil");
  });
});

// ---------------------------------------------------------------------------
// Item 4: skip-existing strategy E2E test
// ---------------------------------------------------------------------------
describe("runGen — mergeStrategy: 'skip-existing'", () => {
  test("existing generated files are skipped; new entities still written", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "single-entity.json"))]);
    expect(result.errors).toEqual([]);

    const baseConfig = defineConfig({
      outDir: tmp,
      extStyle: "none",
      dbImport: "~/server/db",
      dialect: "sqlite",
      generators: [entityFile(), queriesFile(), barrel()],
    });

    // First run: overwrite strategy produces new files
    const run1 = await runGen({
      config: baseConfig,
      metadata: result.root,
      mergeStrategy: "overwrite",
    });
    expect(run1.files.every((f) => f.status === "new")).toBe(true);

    // Modify Post.ts slightly (append a comment) — still has @generated header
    const postPath = join(tmp, "Post.ts");
    const original = readFileSync(postPath, "utf-8");
    writeFileSync(postPath, original + "\n// user tweak");

    // Second run: skip-existing — Post.ts should be skipped, content unchanged
    const run2 = await runGen({
      config: baseConfig,
      metadata: result.root,
      mergeStrategy: "skip-existing",
    });

    const postResult = run2.files.find((f) => f.path.endsWith("Post.ts"));
    expect(postResult?.status).toBe("skipped");

    // Content must be unchanged (our tweak comment is still there)
    const afterRun2 = readFileSync(postPath, "utf-8");
    expect(afterRun2).toContain("// user tweak");

    // All other files also skipped (they all have @generated headers)
    for (const f of run2.files) {
      expect(f.status).toBe("skipped");
    }

    // Now add a NEW entity to the root — it should still be written
    const root2 = makeRoot("test");
    // Copy the Post entity from result
    const postEntity = result.root.ownChildren().find((c) => c.name === "Post")!;
    root2.addChild(postEntity);
    root2.addChild(makeEntity("Comment"));

    const run3 = await runGen({
      config: baseConfig,
      metadata: root2,
      mergeStrategy: "skip-existing",
    });

    const commentResult = run3.files.find((f) => f.path.endsWith("Comment.ts"));
    expect(commentResult?.status).toBe("new");

    const postResult3 = run3.files.find((f) => f.path.endsWith("Post.ts"));
    expect(postResult3?.status).toBe("skipped");
  });
});

// ---------------------------------------------------------------------------
// Item 5: entityFilter test
// ---------------------------------------------------------------------------
describe("runGen — entityFilter", () => {
  test("entityFilter: ['Post'] produces only Post files; barrel reflects filter", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "two-entities-fk.json"))]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: result.root,
      entityFilter: ["Post"],
    });

    expect(out.warnings).toEqual([]);

    // Only Post files should exist — no User files
    expect(existsSync(join(tmp, "Post.ts"))).toBe(true);
    expect(existsSync(join(tmp, "Post.queries.ts"))).toBe(true);
    expect(existsSync(join(tmp, "index.ts"))).toBe(true);
    expect(existsSync(join(tmp, "User.ts"))).toBe(false);
    expect(existsSync(join(tmp, "User.queries.ts"))).toBe(false);

    // Barrel only re-exports Post
    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Post"');
    expect(barrelContent).not.toContain("User");
  });

  test("entityFilter: ['NonExistent'] produces 0 entity files and a warning", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "two-entities-fk.json"))]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: result.root,
      entityFilter: ["NonExistent"],
    });

    expect(out.warnings.some((w) => w.includes("No entities to generate"))).toBe(true);
    expect(out.files).toHaveLength(0);
    expect(existsSync(join(tmp, "index.ts"))).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Task 12b: collection-level `scope` filters generated output.
// ---------------------------------------------------------------------------
describe("runGen — scope", () => {
  test("a scope predicate emits artifacts for in-scope entities only (file list + contents)", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "two-entities-fk.json"))]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: result.root,
      // "demo::Post" only — User is in the same package but declares an
      // `identity.reference`/`relationship.association` TO Post's declared
      // scope, so this fixture doubles as evidence the predicate is matched
      // against the FQN (`demo::Post`), never the bare "Post".
      scope: (fqn) => fqn === "demo::Post",
    });

    expect(out.warnings).toEqual([]);
    expect(existsSync(join(tmp, "Post.ts"))).toBe(true);
    expect(existsSync(join(tmp, "Post.queries.ts"))).toBe(true);
    expect(existsSync(join(tmp, "User.ts"))).toBe(false);
    expect(existsSync(join(tmp, "User.queries.ts"))).toBe(false);

    const postContent = readFileSync(join(tmp, "Post.ts"), "utf-8");
    expect(postContent).toContain("pgTable");
    expect(postContent).toContain("authorId");

    // Barrel content, not just the file's existence — only Post is re-exported.
    const barrelContent = readFileSync(join(tmp, "index.ts"), "utf-8");
    expect(barrelContent).toContain('export * from "./Post"');
    expect(barrelContent).not.toContain("User");
  });

  test("no scope option produces byte-identical output to an always-matching scope predicate", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "two-entities-fk.json"))]);
    expect(result.errors).toEqual([]);

    const noScopeDir = join(tmp, "no-scope");
    const alwaysTrueDir = join(tmp, "always-true");

    const baseConfig = {
      extStyle: "none" as const,
      dbImport: "~/server/db",
      dialect: "postgres" as const,
      generators: [entityFile(), queriesFile(), routesFile(), barrel()],
    };

    // The real-world "no scope declared" path (`meta gen`) still ALWAYS passes a
    // predicate — `collection.inScope`, which an unconfigured project compiles
    // from an empty include/exclude, so it admits everything. The byte-identical
    // guarantee that matters is exactly this: omitting `scope` entirely vs. a
    // predicate that matches every entity must produce identical output, not
    // merely "close".
    const outA = await runGen({
      config: defineConfig({ ...baseConfig, outDir: noScopeDir }),
      metadata: result.root,
    });
    const outB = await runGen({
      config: defineConfig({ ...baseConfig, outDir: alwaysTrueDir }),
      metadata: result.root,
      scope: () => true,
    });

    expect(outB.warnings).toEqual(outA.warnings);

    const filesA = readdirSync(noScopeDir).sort();
    const filesB = readdirSync(alwaysTrueDir).sort();
    expect(filesB).toEqual(filesA);
    for (const f of filesA) {
      expect(readFileSync(join(alwaysTrueDir, f), "utf-8")).toEqual(
        readFileSync(join(noScopeDir, f), "utf-8"),
      );
    }
  });

  test("scope intersects entityFilter — an entity passing only one of the two is not emitted", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "two-entities-fk.json"))]);
    expect(result.errors).toEqual([]);

    // User passes entityFilter but is excluded by scope (which admits only
    // Post); Post passes scope but is excluded by entityFilter. Neither alone
    // is enough — intersection means NEITHER is emitted.
    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: result.root,
      entityFilter: ["User"],
      scope: (fqn) => fqn === "demo::Post",
    });

    expect(out.files).toHaveLength(0);
    expect(existsSync(join(tmp, "User.ts"))).toBe(false);
    expect(existsSync(join(tmp, "Post.ts"))).toBe(false);
    // Attributed to the real cause (scope), not entityFilter — User genuinely
    // matched entityFilter and was then excluded by scope.
    expect(out.warnings.some((w) => w.includes("scope"))).toBe(true);
  });

  test("a scope matching nothing warns with a reason that names scope", async () => {
    const loader = new MetaDataLoader();
    const result = await loader.load([new FileSource(join(FIXTURE_DIR, "two-entities-fk.json"))]);
    expect(result.errors).toEqual([]);

    const out = await runGen({
      config: defineConfig({
        outDir: tmp,
        extStyle: "none",
        dbImport: "~/server/db",
        dialect: "postgres",
        generators: [entityFile(), queriesFile(), barrel()],
      }),
      metadata: result.root,
      scope: () => false,
    });

    expect(out.files).toHaveLength(0);
    // The reason must name scope specifically — "root has no object children"
    // would be a false statement (the root has two) that sends the reader to
    // the wrong file.
    const scopeWarning = out.warnings.find((w) => w.includes("No entities to generate"));
    expect(scopeWarning).toBeDefined();
    expect(scopeWarning).toContain("scope");
    expect(scopeWarning).not.toContain("entityFilter");
    expect(scopeWarning).not.toContain("root has no object children");
  });
});
