using Xunit;

namespace MetaObjects.Cli.Tests;

/// <summary>
/// A refusal is a FAILED gate — <c>dotnet meta gen</c> exits 1, matching TypeScript's
/// <c>meta gen</c>.
/// <para>
/// This port and Python used to print the warning and exit 0, so an adopter who wired
/// <c>gen</c> into CI as a drift gate was green while codegen was refusing to write: the
/// gate did not gate. The exit code is the only part of this a CI step reads, which is
/// why the assertion has to come from the real process rather than from a
/// <c>RunResult</c> a helper returns.
/// </para>
/// </summary>
public sealed class GenRefusalExitCodeTests : IDisposable
{
    private readonly string _tmp = Path.Combine(
        Path.GetTempPath(), "meta-refusal-" + Guid.NewGuid().ToString("N"));

    private string MetaDir => Path.Combine(_tmp, "metaobjects");
    private string OutDir => Path.Combine(_tmp, "generated");

    private const string Metadata = """
    { "metadata.root": { "package": "acme", "children": [
      { "object.entity": { "name": "Subscriber", "children": [
        { "source.rdb": { "@table": "subscribers" } },
        { "field.long":   { "name": "id" } },
        { "field.string": { "name": "email", "@required": true } },
        { "identity.primary": { "@fields": "id" } }
      ]}}
    ]}}
    """;

    public GenRefusalExitCodeTests()
    {
        Directory.CreateDirectory(MetaDir);
        File.WriteAllText(Path.Combine(MetaDir, "meta.acme.json"), Metadata);
    }

    public void Dispose() { try { Directory.Delete(_tmp, recursive: true); } catch { } }

    [Fact]
    public void A_refused_file_fails_the_run_and_baseline_adopt_clears_it()
    {
        // A project that predates the committed manifest: output on disk that no longer
        // matches fresh output, and no `.gen-state` recording it.
        Assert.Equal(0, CliProcess.Run(_tmp, "gen", MetaDir, "--out", OutDir, "--namespace", "Acme").ExitCode);
        var stale = Path.Combine(OutDir, "Subscriber.g.cs");
        var onDisk = "// <auto-generated/>\n// from an older engine\n";
        File.WriteAllText(stale, onDisk);
        Directory.Delete(Path.Combine(_tmp, ".metaobjects"), recursive: true);

        var refusedRun = CliProcess.Run(_tmp, "gen", MetaDir, "--out", OutDir, "--namespace", "Acme");

        Assert.Equal(1, refusedRun.ExitCode);
        Assert.Contains("--baseline=adopt", refusedRun.Stderr);
        Assert.Equal(onDisk, File.ReadAllText(stale));   // refusing means NOT writing

        // The remedy the failure names has to work, or the exit code is just a wall.
        var adoptRun = CliProcess.Run(
            _tmp, "gen", MetaDir, "--out", OutDir, "--namespace", "Acme", "--baseline=adopt");

        Assert.Equal(0, adoptRun.ExitCode);
        Assert.Equal(onDisk, File.ReadAllText(stale));   // adopting writes nothing either
        Assert.True(File.Exists(Path.Combine(_tmp, ".metaobjects", ".gen-state", ".hashes.json")));
    }

    [Fact]
    public void An_unknown_baseline_is_a_usage_error()
    {
        var run = CliProcess.Run(
            _tmp, "gen", MetaDir, "--out", OutDir, "--namespace", "Acme", "--baseline=nonsense");

        Assert.Equal(2, run.ExitCode);
        Assert.Contains("unknown --baseline", run.Stderr);
    }
}
