package com.metaobjects.generator.spring;

import com.metaobjects.loader.MetaDataLoader;
import com.metaobjects.registry.SharedRegistryTestBase;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

/**
 * The generated by-id surface must derive its key type from the entity's
 * {@code identity.primary} field — NOT hard-code {@code Long}. For a
 * {@code field.uuid} PK ({@code @generation: uuid}) the DTO already carries
 * {@code java.util.UUID}, so a {@code Long} path variable makes Spring reject
 * every by-id request with 400, and a {@code findById(Long)} repository
 * interface is un-implementable against the UUID-keyed table.
 *
 * <p>Covers EVERY by-id site: vanilla get/update/delete, the FR-018 M:N
 * traversal endpoint + finder, and the FR-017 TPH polymorphic + per-subtype
 * routes/repository. Mirrors the C# {@code RoutesGenerator}, which derives the
 * PK scalar via {@code CSharpNaming.ScalarFor} and threads it through the same
 * sites.</p>
 */
public class SpringUuidPrimaryKeyCodegenTest extends SharedRegistryTestBase {

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    /** uuid-PK Note —tags→ uuid-PK Tag via NoteTag (M:N), all keyed by field.uuid. */
    private static final String UUID_M2M_FIXTURE = """
        {
          "metadata.root": { "package": "acme::notes", "children": [
            { "object.entity": { "name": "Note", "children": [
                { "source.rdb":   { "@table": "notes" } },
                { "field.uuid":   { "name": "id" } },
                { "field.string": { "name": "title", "@required": true, "@maxLength": 200 } },
                { "relationship.association": { "name": "tags", "@cardinality": "many",
                    "@objectRef": "Tag", "@through": "NoteTag" } },
                { "identity.primary": { "@fields": "id", "@generation": "uuid" } }
            ] } },
            { "object.entity": { "name": "Tag", "children": [
                { "source.rdb":   { "@table": "tags" } },
                { "field.uuid":   { "name": "id" } },
                { "field.string": { "name": "name", "@required": true, "@maxLength": 80 } },
                { "identity.primary": { "@fields": "id", "@generation": "uuid" } }
            ] } },
            { "object.entity": { "name": "NoteTag", "children": [
                { "source.rdb":         { "@table": "note_tags" } },
                { "field.uuid":         { "name": "noteId", "@required": true } },
                { "field.uuid":         { "name": "tagId",  "@required": true } },
                { "identity.primary":   { "@fields": ["noteId", "tagId"] } },
                { "identity.reference": { "name": "fkNote", "@fields": "noteId", "@references": "Note" } },
                { "identity.reference": { "name": "fkTag",  "@fields": "tagId",  "@references": "Tag" } }
            ] } }
          ] }
        }
        """;

    /** FR-017 TPH hierarchy whose single-table base is keyed by a field.uuid PK. */
    private static final String UUID_TPH_FIXTURE = """
        {
          "metadata.root": { "package": "acme::auth", "children": [
            { "object.entity": { "name": "Auth", "@discriminator": "type", "children": [
                { "source.rdb":   { "@table": "auths" } },
                { "field.uuid":   { "name": "id" } },
                { "field.enum":   { "name": "type", "@values": ["Bridge", "Copay"] } },
                { "field.string": { "name": "reference", "@required": true, "@maxLength": 80 } },
                { "identity.primary": { "@fields": "id", "@generation": "uuid" } }
            ] } },
            { "object.entity": { "name": "BridgeAuth", "extends": "Auth",
                "@discriminatorValue": "Bridge", "children": [
                { "field.int": { "name": "quantity" } }
            ] } },
            { "object.entity": { "name": "CopayAuth", "extends": "Auth",
                "@discriminatorValue": "Copay", "children": [
                { "field.string": { "name": "copayCode", "@maxLength": 40 } }
            ] } }
          ] }
        }
        """;

    /** Long-PK regression guard — the increment default must keep emitting Long. */
    private static final String LONG_PK_FIXTURE = """
        {
          "metadata.root": { "package": "acme::blog", "children": [
            { "object.entity": { "name": "Author", "children": [
                { "source.rdb":   { "@table": "authors" } },
                { "field.long":   { "name": "id" } },
                { "field.string": { "name": "name", "@required": true, "@maxLength": 100 } },
                { "identity.primary": { "@fields": "id", "@generation": "increment" } }
            ] } }
          ] }
        }
        """;

    private String generate(Object generator, String fixture, String fixtureName, String relPath)
            throws Exception {
        Path workspace = tempFolder.newFolder().toPath();
        MetaDataLoader loader = SpringTestFixtures.loadFixture(workspace, fixtureName, fixture);
        Path outDir = tempFolder.newFolder().toPath();
        Map<String, String> args = new HashMap<>();
        args.put("outputDir", outDir.toString());
        ((com.metaobjects.generator.direct.MultiFileDirectGeneratorBase<?>) generator).setArgs(args);
        ((com.metaobjects.generator.direct.MultiFileDirectGeneratorBase<?>) generator).execute(loader);
        Path f = outDir.resolve(relPath);
        assertTrue("expected generated file " + f, Files.exists(f));
        return Files.readString(f);
    }

    @Test
    public void uuidPkControllerUsesUuidPathVariables() throws Exception {
        String src = generate(new SpringControllerGenerator(), UUID_M2M_FIXTURE,
            "uuid-ctrl", "acme/notes/NoteController.java");

        // get / update / delete all bind the PK as java.util.UUID.
        assertTrue("expected get(@PathVariable java.util.UUID id); saw:\n" + src,
            src.contains("public ResponseEntity<?> get(@PathVariable java.util.UUID id)"));
        assertTrue("expected update(@PathVariable java.util.UUID id, ...); saw:\n" + src,
            src.contains("public ResponseEntity<?> update(@PathVariable java.util.UUID id,"));
        assertTrue("expected delete(@PathVariable java.util.UUID id); saw:\n" + src,
            src.contains("public ResponseEntity<?> delete(@PathVariable java.util.UUID id)"));
        // FR-018 M:N traversal endpoint binds the SOURCE id as its PK type too.
        assertTrue("expected findTags(@PathVariable java.util.UUID id); saw:\n" + src,
            src.contains("findTags(@PathVariable java.util.UUID id)"));
        // No residual hard-coded Long path variable anywhere in the file.
        assertFalse("uuid-PK controller must not bind @PathVariable Long; saw:\n" + src,
            src.contains("@PathVariable Long id"));
    }

    @Test
    public void uuidPkRepositoryUsesUuidKeyType() throws Exception {
        String src = generate(new SpringRepositoryGenerator(), UUID_M2M_FIXTURE,
            "uuid-repo", "acme/notes/NoteRepository.java");

        assertTrue("expected findById(java.util.UUID id); saw:\n" + src,
            src.contains("findById(java.util.UUID id)"));
        assertTrue("expected update(java.util.UUID id, NoteDto dto); saw:\n" + src,
            src.contains("update(java.util.UUID id, NoteDto dto)"));
        assertTrue("expected delete(java.util.UUID id); saw:\n" + src,
            src.contains("boolean delete(java.util.UUID id)"));
        // FR-018 M:N finder takes the SOURCE id as its PK type.
        assertTrue("expected findTags(java.util.UUID sourceId); saw:\n" + src,
            src.contains("findTags(java.util.UUID sourceId)"));
        assertFalse("uuid-PK repository must not trade Long ids; saw:\n" + src,
            src.contains("(Long id") || src.contains("(Long sourceId"));
    }

    @Test
    public void uuidPkTphControllerUsesUuidPathVariables() throws Exception {
        String src = generate(new SpringControllerGenerator(), UUID_TPH_FIXTURE,
            "uuid-tph-ctrl", "acme/auth/AuthController.java");

        // Polymorphic get + per-subtype get/update/delete all bind java.util.UUID.
        assertTrue("expected polymorphic get(@PathVariable java.util.UUID id); saw:\n" + src,
            src.contains("public ResponseEntity<?> get(@PathVariable java.util.UUID id)"));
        assertTrue("expected per-subtype getBridge(@PathVariable java.util.UUID id); saw:\n" + src,
            src.contains("getBridge(@PathVariable java.util.UUID id)"));
        assertTrue("expected per-subtype updateBridge(@PathVariable java.util.UUID id, ...); saw:\n" + src,
            src.contains("updateBridge(@PathVariable java.util.UUID id,"));
        assertTrue("expected per-subtype deleteCopay(@PathVariable java.util.UUID id); saw:\n" + src,
            src.contains("deleteCopay(@PathVariable java.util.UUID id)"));
        assertFalse("uuid-PK TPH controller must not bind @PathVariable Long; saw:\n" + src,
            src.contains("@PathVariable Long id"));
    }

    @Test
    public void uuidPkTphRepositoryUsesUuidKeyType() throws Exception {
        String src = generate(new SpringRepositoryGenerator(), UUID_TPH_FIXTURE,
            "uuid-tph-repo", "acme/auth/AuthRepository.java");

        assertTrue("expected findById(java.util.UUID id); saw:\n" + src,
            src.contains("findById(java.util.UUID id)"));
        assertTrue("expected findByIdAndType(java.util.UUID id, String discriminator); saw:\n" + src,
            src.contains("findByIdAndType(java.util.UUID id, String discriminator)"));
        assertTrue("expected updateByIdAndType(java.util.UUID id, ...); saw:\n" + src,
            src.contains("updateByIdAndType(java.util.UUID id, String discriminator,"));
        assertTrue("expected deleteByIdAndType(java.util.UUID id, String discriminator); saw:\n" + src,
            src.contains("deleteByIdAndType(java.util.UUID id, String discriminator)"));
        assertFalse("uuid-PK TPH repository must not trade Long ids; saw:\n" + src,
            src.contains("(Long id"));
    }

    @Test
    public void longPkStillEmitsLongEverywhere() throws Exception {
        // Regression guard: the dominant field.long @generation:increment convention
        // must keep producing Long-keyed signatures byte-for-byte.
        String ctrl = generate(new SpringControllerGenerator(), LONG_PK_FIXTURE,
            "long-ctrl", "acme/blog/AuthorController.java");
        assertTrue("expected get(@PathVariable Long id) for a field.long PK; saw:\n" + ctrl,
            ctrl.contains("public ResponseEntity<?> get(@PathVariable Long id)"));

        String repo = generate(new SpringRepositoryGenerator(), LONG_PK_FIXTURE,
            "long-repo", "acme/blog/AuthorRepository.java");
        assertTrue("expected findById(Long id) for a field.long PK; saw:\n" + repo,
            repo.contains("findById(Long id)"));
    }
}
