import { test, expect, describe } from "bun:test";
import { emit } from "../../src/emit/index.js";
import type { Change, ColumnDescriptor, TableDescriptor } from "../../src/types.js";

const ALLOWED = { state: "allowed" as const };

function table(name: string, cols: ColumnDescriptor[], pk: string[] = []): TableDescriptor {
  return { name, columns: cols, indexes: [], foreignKeys: [], primaryKey: pk, checks: [] };
}

function norm(s: string): string {
  return s.trim().split("\n").map((l) => l.trim()).filter((l) => l.length > 0).join("\n");
}

describe("renderPostgres — create-table", () => {
  test("simple table with PK", () => {
    const cols: ColumnDescriptor[] = [
      { name: "id", sqlType: { kind: "integer", bits: 64 }, nullable: false, identity: "increment" },
      { name: "email", sqlType: { kind: "text", maxLength: 255 }, nullable: false },
      { name: "created_at", sqlType: { kind: "timestamp", withTimezone: false }, nullable: false,
        default: { kind: "expr", value: "CURRENT_TIMESTAMP" } },
    ];
    const changes: Change[] = [
      { kind: "create-table", table: table("users", cols, ["id"]), status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(norm(`
      CREATE TABLE "users" (
        "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "email" VARCHAR(255) NOT NULL,
        "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "users_pkey" PRIMARY KEY ("id")
      );
    `));
  });

  test("uuid identity uses GENERATED ALWAYS pattern stub", () => {
    // For v0.1 we use gen_random_uuid() default; documented as such.
    const cols: ColumnDescriptor[] = [
      { name: "id", sqlType: { kind: "uuid" }, nullable: false, identity: "uuid" },
    ];
    const changes: Change[] = [{ kind: "create-table", table: table("u", cols, ["id"]), status: ALLOWED }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(up).toContain("UUID");
    expect(up).toContain("DEFAULT gen_random_uuid()");
  });
});

describe("renderPostgres — column changes", () => {
  test("add-column", () => {
    const changes: Change[] = [{
      kind: "add-column", table: "users",
      column: { name: "phone", sqlType: { kind: "text" }, nullable: true },
      status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" ADD COLUMN "phone" TEXT;`);
  });

  test("drop-column", () => {
    const changes: Change[] = [{
      kind: "drop-column", table: "users", column: "legacy",
      status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" DROP COLUMN "legacy";`);
  });

  test("rename-column", () => {
    const changes: Change[] = [{
      kind: "rename-column", table: "users", from: "firstname", to: "first_name",
      status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" RENAME COLUMN "firstname" TO "first_name";`);
  });

  test("change-column-type", () => {
    const changes: Change[] = [{
      kind: "change-column-type", table: "users", column: "age",
      from: { kind: "integer", bits: 32 },
      to: { kind: "integer", bits: 64 },
      status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" ALTER COLUMN "age" TYPE BIGINT;`);
  });

  test("change-column-nullable: notnull → nullable", () => {
    const changes: Change[] = [{
      kind: "change-column-nullable", table: "users", column: "note",
      from: false, to: true, status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" ALTER COLUMN "note" DROP NOT NULL;`);
  });

  test("change-column-nullable: nullable → notnull", () => {
    const changes: Change[] = [{
      kind: "change-column-nullable", table: "users", column: "email",
      from: true, to: false, status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" ALTER COLUMN "email" SET NOT NULL;`);
  });

  test("change-column-default: set", () => {
    const changes: Change[] = [{
      kind: "change-column-default", table: "users", column: "active",
      to: { kind: "literal", value: "true" }, status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" ALTER COLUMN "active" SET DEFAULT 'true';`);
  });

  test("change-column-default: drop", () => {
    const changes: Change[] = [{
      kind: "change-column-default", table: "users", column: "active",
      from: { kind: "literal", value: "true" }, status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "users" ALTER COLUMN "active" DROP DEFAULT;`);
  });
});

describe("renderPostgres — table-level", () => {
  test("rename-table", () => {
    const changes: Change[] = [{ kind: "rename-table", from: "posts", to: "articles", status: ALLOWED }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE "posts" RENAME TO "articles";`);
  });

  test("drop-table", () => {
    const changes: Change[] = [{ kind: "drop-table", table: "legacy", status: ALLOWED }];
    const { up } = emit(changes, { dialect: "postgres" });
    // #313 — forward drops carry IF EXISTS so a committed chain replays from empty.
    expect(norm(up)).toBe(`DROP TABLE IF EXISTS "legacy";`);
  });
});

describe("renderPostgres — indexes + FKs", () => {
  test("add-index unique", () => {
    const changes: Change[] = [{
      kind: "add-index", table: "users",
      index: { name: "users_email_uniq", columns: ["email"], unique: true },
      status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`CREATE UNIQUE INDEX "users_email_uniq" ON "users" ("email");`);
  });

  test("add-index non-unique", () => {
    const changes: Change[] = [{
      kind: "add-index", table: "weeks",
      index: { name: "weeks_pid_idx", columns: ["program_id"], unique: false },
      status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`CREATE INDEX "weeks_pid_idx" ON "weeks" ("program_id");`);
  });

  test("drop-index", () => {
    const changes: Change[] = [{ kind: "drop-index", table: "users", index: "old_idx", status: ALLOWED }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`DROP INDEX IF EXISTS "old_idx";`);
  });

  // F10 — the constraint-backed arm ALSO guards the enclosing ALTER TABLE, not
  // just the constraint name (see the `drop-fk` test below for the failure mode).
  test("drop-index (constraint-backed)", () => {
    const changes: Change[] = [{
      kind: "drop-index", table: "work_items", index: "work_items_message_id_uniq", status: ALLOWED,
      restore: { name: "work_items_message_id_uniq", columns: ["message_id"], unique: true, constraint: "unique" },
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(
      `ALTER TABLE IF EXISTS "work_items" DROP CONSTRAINT IF EXISTS "work_items_message_id_uniq";`,
    );
  });

  test("add-fk with ON DELETE CASCADE", () => {
    const changes: Change[] = [{
      kind: "add-fk", table: "weeks",
      fk: {
        name: "weeks_program_id_fk",
        columns: ["program_id"], refTable: "programs", refColumns: ["id"],
        onDelete: "cascade",
      },
      status: ALLOWED,
    }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(
      `ALTER TABLE "weeks" ADD CONSTRAINT "weeks_program_id_fk" ` +
      `FOREIGN KEY ("program_id") REFERENCES "programs" ("id") ON DELETE CASCADE;`,
    );
  });

  // F10 — `DROP CONSTRAINT IF EXISTS` alone only guards the constraint NAME;
  // Postgres still requires the TABLE to exist to parse `ALTER TABLE` at all, so
  // this failed to replay against a virgin database for a table another tool
  // owns (never created by any migration in the chain) with `relation "x" does
  // not exist`. `ALTER TABLE IF EXISTS` closes that gap.
  test("drop-fk", () => {
    const changes: Change[] = [{ kind: "drop-fk", table: "weeks", fk: "weeks_program_id_fk", status: ALLOWED }];
    const { up } = emit(changes, { dialect: "postgres" });
    expect(norm(up)).toBe(`ALTER TABLE IF EXISTS "weeks" DROP CONSTRAINT IF EXISTS "weeks_program_id_fk";`);
  });
});

describe("renderPostgres — statement ordering", () => {
  test("create tables before column adds; drop tables last", () => {
    const newTable: TableDescriptor = table("new_t", [
      { name: "id", sqlType: { kind: "integer", bits: 64 }, nullable: false, identity: "increment" },
    ], ["id"]);
    const changes: Change[] = [
      { kind: "drop-table", table: "old_t", status: ALLOWED },
      { kind: "add-column", table: "users", column: { name: "phone", sqlType: { kind: "text" }, nullable: true }, status: ALLOWED },
      { kind: "create-table", table: newTable, status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    const idxCreate = up.indexOf("CREATE TABLE");
    const idxAdd = up.indexOf("ADD COLUMN");
    const idxDrop = up.indexOf("DROP TABLE");
    expect(idxCreate).toBeLessThan(idxAdd);
    expect(idxAdd).toBeLessThan(idxDrop);
  });

  // #255 — a DROP CONSTRAINT for an FK still referencing a column must run
  // before that column's DROP COLUMN, or Postgres refuses at apply time with
  // "cannot drop column … because other objects depend on it".
  test("drop-fk runs before drop-column for the column it references (#255)", () => {
    const changes: Change[] = [
      { kind: "drop-column", table: "weeks", column: "program_id", status: ALLOWED },
      { kind: "drop-fk", table: "weeks", fk: "weeks_program_id_fk", status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    const idxDropConstraint = up.indexOf("DROP CONSTRAINT");
    const idxDropColumn = up.indexOf("DROP COLUMN");
    expect(idxDropConstraint).toBeGreaterThanOrEqual(0);
    expect(idxDropColumn).toBeGreaterThanOrEqual(0);
    expect(idxDropConstraint).toBeLessThan(idxDropColumn);
  });

  // Same invariant for drop-check — a CHECK constraint on a column must be
  // dropped before that column is dropped.
  test("drop-check runs before drop-column for the column it constrains (#255)", () => {
    const changes: Change[] = [
      { kind: "drop-column", table: "orders", column: "qty", status: ALLOWED },
      { kind: "drop-check", table: "orders", check: "orders_qty_chk", status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    const idxDropConstraint = up.indexOf("DROP CONSTRAINT");
    const idxDropColumn = up.indexOf("DROP COLUMN");
    expect(idxDropConstraint).toBeGreaterThanOrEqual(0);
    expect(idxDropColumn).toBeGreaterThanOrEqual(0);
    expect(idxDropConstraint).toBeLessThan(idxDropColumn);
  });

  // add-fk must still run AFTER column mutation (the referenced column must
  // already exist) — only the DROP direction was hoisted.
  test("add-fk still runs after add-column (adds are unaffected by #255)", () => {
    const changes: Change[] = [
      { kind: "add-fk", table: "weeks",
        fk: { name: "weeks_program_id_fk", columns: ["program_id"], refTable: "programs", refColumns: ["id"] },
        status: ALLOWED },
      { kind: "add-column", table: "weeks", column: { name: "program_id", sqlType: { kind: "integer", bits: 64 }, nullable: true }, status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    const idxAddColumn = up.indexOf("ADD COLUMN");
    const idxAddConstraint = up.indexOf("ADD CONSTRAINT");
    expect(idxAddColumn).toBeGreaterThanOrEqual(0);
    expect(idxAddConstraint).toBeGreaterThanOrEqual(0);
    expect(idxAddColumn).toBeLessThan(idxAddConstraint);
  });

  // #255 (generalized) — dropping a column that has a backing index (e.g. a
  // UNIQUE index also targeted by another table's FK) auto-cascades that
  // index away in Postgres, so a standalone DROP INDEX emitted AFTER the
  // DROP COLUMN fails ("index … does not exist"). drop-index must run before
  // drop-column, same as drop-fk/drop-check.
  test("drop-index runs before drop-column for the column it indexes (#255)", () => {
    const changes: Change[] = [
      { kind: "drop-column", table: "programs", column: "code", status: ALLOWED },
      { kind: "drop-index", table: "programs", index: "uniqueCode", status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    const idxDropIndex = up.indexOf("DROP INDEX");
    const idxDropColumn = up.indexOf("DROP COLUMN");
    expect(idxDropIndex).toBeGreaterThanOrEqual(0);
    expect(idxDropColumn).toBeGreaterThanOrEqual(0);
    expect(idxDropIndex).toBeLessThan(idxDropColumn);
  });

  // #255 (sub-ordering within the drops group) — an FK constraint depends on
  // the unique/PK index backing its target column (that's how Postgres
  // enforces the target must be unique), so dropping the index BEFORE the FK
  // that depends on it fails: "cannot drop index … because other objects
  // depend on it" / "constraint … depends on index …". drop-fk must run
  // before drop-index, not just before drop-column.
  test("drop-fk runs before drop-index that backs its target column (#255)", () => {
    const changes: Change[] = [
      { kind: "drop-index", table: "programs", index: "uniqueCode", status: ALLOWED },
      { kind: "drop-fk", table: "weeks", fk: "weeks_program_code_fk", status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    const idxDropConstraint = up.indexOf("DROP CONSTRAINT");
    const idxDropIndex = up.indexOf("DROP INDEX");
    expect(idxDropConstraint).toBeGreaterThanOrEqual(0);
    expect(idxDropIndex).toBeGreaterThanOrEqual(0);
    expect(idxDropConstraint).toBeLessThan(idxDropIndex);
  });

  // add-index must still run AFTER column mutation (the indexed column must
  // already exist) — only the DROP direction was hoisted.
  test("add-index still runs after add-column (adds are unaffected by #255)", () => {
    const changes: Change[] = [
      { kind: "add-index", table: "users",
        index: { name: "users_phone_idx", columns: ["phone"], unique: false },
        status: ALLOWED },
      { kind: "add-column", table: "users", column: { name: "phone", sqlType: { kind: "text" }, nullable: true }, status: ALLOWED },
    ];
    const { up } = emit(changes, { dialect: "postgres" });
    const idxAddColumn = up.indexOf("ADD COLUMN");
    const idxCreateIndex = up.indexOf("CREATE INDEX");
    expect(idxAddColumn).toBeGreaterThanOrEqual(0);
    expect(idxCreateIndex).toBeGreaterThanOrEqual(0);
    expect(idxAddColumn).toBeLessThan(idxCreateIndex);
  });
});

describe("renderPostgres — down statements", () => {
  test("create-table down → drop-table", () => {
    const cols: ColumnDescriptor[] = [
      { name: "id", sqlType: { kind: "integer", bits: 64 }, nullable: false },
    ];
    const { down } = emit([{ kind: "create-table", table: table("u", cols, ["id"]), status: ALLOWED }], { dialect: "postgres" });
    expect(down).toContain('DROP TABLE "u"');
  });

  test("rename-column down → reverse rename", () => {
    const { down } = emit([{ kind: "rename-column", table: "u", from: "old", to: "new", status: ALLOWED }], { dialect: "postgres" });
    expect(down).toContain('RENAME COLUMN "new" TO "old"');
  });

  test("change-column-type down → ALTER TYPE back to from", () => {
    const { down } = emit([{
      kind: "change-column-type", table: "u", column: "n",
      from: { kind: "integer", bits: 32 }, to: { kind: "integer", bits: 64 },
      status: ALLOWED,
    }], { dialect: "postgres" });
    expect(down).toContain('ALTER COLUMN "n" TYPE INTEGER');
  });

  test("drop-column down → WARNING comment (no data extraction)", () => {
    const { down } = emit([{ kind: "drop-column", table: "u", column: "x", status: ALLOWED }], { dialect: "postgres" });
    expect(down).toContain("WARNING");
    expect(down).toContain('"x"');
  });

  test("drop-table down → WARNING comment", () => {
    const { down } = emit([{ kind: "drop-table", table: "old", status: ALLOWED }], { dialect: "postgres" });
    expect(down).toContain("WARNING");
    expect(down).toContain("old");
  });

  test("down statement order is reverse of up", () => {
    const cols: ColumnDescriptor[] = [{ name: "id", sqlType: { kind: "integer", bits: 64 }, nullable: false }];
    const { up, down } = emit([
      { kind: "create-table", table: table("a", cols, ["id"]), status: ALLOWED },
      { kind: "create-table", table: table("b", cols, ["id"]), status: ALLOWED },
    ], { dialect: "postgres" });
    // Up: create a, then b. Down: drop b, then a.
    const upA = up.indexOf('CREATE TABLE "a"');
    const upB = up.indexOf('CREATE TABLE "b"');
    const downA = down.indexOf('DROP TABLE "a"');
    const downB = down.indexOf('DROP TABLE "b"');
    expect(upA).toBeLessThan(upB);
    expect(downB).toBeLessThan(downA);
  });
});

// A column changes type IN PLACE only along an assignment cast. jsonb → text[],
// text[] → jsonb, text → text[] and boolean → integer have none, so the bare
// `ALTER … TYPE` was refused by Postgres on every one of them ("cannot be cast
// automatically") — a migration `meta migrate` wrote and nothing could apply.
describe("change-column-type — the USING clause a cross-kind change needs", () => {
  type TypeChange = Extract<Change, { kind: "change-column-type" }>;
  const HELPER = `"metaobjects_jsonb_array_to_text_array"`;
  const NARROW = `"metaobjects_array_to_scalar"`;
  const typeChange = (
    from: TypeChange["from"], to: TypeChange["to"],
    extra: Partial<Pick<TypeChange, "schema" | "column" | "fromDefault" | "toDefault">> = {},
  ): TypeChange => ({ kind: "change-column-type", table: "t", column: "c", from, to, status: ALLOWED, ...extra });
  const JSON_T = { kind: "json" } as const;
  const TEXT = { kind: "text" } as const;
  const INT = { kind: "integer", bits: 32 } as const;
  const arrayOf = (element: TypeChange["from"]): TypeChange["from"] => ({ kind: "array", element });
  const count = (s: string, needle: string): number => s.split(needle).length - 1;

  test("jsonb → text[] unpacks through a helper created before and dropped after; the down is to_jsonb", () => {
    const { up, down } = emit([typeChange(JSON_T, arrayOf(TEXT))], { dialect: "postgres" });
    expect(up.split("\n\n")).toEqual([
      `CREATE OR REPLACE FUNCTION ${HELPER}(j jsonb) RETURNS text[] LANGUAGE sql IMMUTABLE AS $$ `
        + "SELECT CASE WHEN j IS NULL OR jsonb_typeof(j) = 'null' THEN NULL "
        + "ELSE ARRAY(SELECT e FROM jsonb_array_elements_text(j) WITH ORDINALITY AS x(e, i) ORDER BY i) END $$;",
      `ALTER TABLE "t" ALTER COLUMN "c" TYPE TEXT[] USING ${HELPER}("c");`,
      `DROP FUNCTION IF EXISTS ${HELPER}(jsonb);`,
    ]);
    expect(down).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE JSONB USING to_jsonb("c");`);
  });

  test("jsonb → double precision[] casts the helper's text[] to the element type", () => {
    const { up } = emit([typeChange(JSON_T, arrayOf({ kind: "real" }))], { dialect: "postgres" });
    expect(up).toContain(`TYPE DOUBLE PRECISION[] USING ${HELPER}("c")::DOUBLE PRECISION[];`);
  });

  // Not pg_temp: a database that revokes TEMP from PUBLIC refuses a temporary function,
  // while CREATE on the table's schema is a privilege the migration already needs.
  test("the helper lives in the table's schema, once per schema however many columns convert", () => {
    const { up } = emit([
      typeChange(JSON_T, arrayOf(TEXT), { column: "a", schema: "s" }),
      typeChange(JSON_T, arrayOf(TEXT), { column: "b", schema: "s" }),
      typeChange(JSON_T, arrayOf(TEXT), { column: "c" }),
    ], { dialect: "postgres" });
    expect(count(up, `CREATE OR REPLACE FUNCTION "s".${HELPER}(`)).toBe(1);
    expect(count(up, `CREATE OR REPLACE FUNCTION ${HELPER}(`)).toBe(1);
    expect(up).toContain(`ALTER TABLE "s"."t" ALTER COLUMN "a" TYPE TEXT[] USING "s".${HELPER}("a");`);
    expect(count(up, "DROP FUNCTION IF EXISTS")).toBe(2);
  });

  test("the down of array → jsonb needs the helper, so the DOWN creates and drops it", () => {
    const { up, down } = emit([typeChange(arrayOf(TEXT), JSON_T)], { dialect: "postgres" });
    expect(up).not.toContain("FUNCTION");
    expect(down).toContain(`CREATE OR REPLACE FUNCTION ${HELPER}(`);
    expect(down).toContain(`TYPE TEXT[] USING ${HELPER}("c");`);
  });

  test("text → integer casts explicitly; the down to text stays bare", () => {
    const { up, down } = emit([typeChange(TEXT, INT)], { dialect: "postgres" });
    expect(up).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE INTEGER USING "c"::INTEGER;`);
    expect(down).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE TEXT;`);
  });

  test("boolean → integer casts explicitly", () => {
    const { up } = emit([typeChange({ kind: "boolean" }, INT)], { dialect: "postgres" });
    expect(up).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE INTEGER USING "c"::INTEGER;`);
  });

  test("text[] → integer[] casts the array explicitly", () => {
    const { up } = emit([typeChange(arrayOf(TEXT), arrayOf(INT))], { dialect: "postgres" });
    expect(up).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE INTEGER[] USING "c"::INTEGER[];`);
  });

  // An explicit `::TEXT[]` PARSES the value as an array literal: '{a,b}' silently becomes
  // two elements and 'hello' fails as a malformed literal.
  test("scalar → array makes the value the array's one element; the down narrows it back", () => {
    const { up, down } = emit([typeChange(TEXT, arrayOf(TEXT))], { dialect: "postgres" });
    expect(up).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE TEXT[] USING (CASE WHEN "c" IS NULL THEN NULL ELSE ARRAY["c"] END);`);
    expect(down.split("\n\n")).toEqual([
      `CREATE OR REPLACE FUNCTION ${NARROW}(a anyarray) RETURNS anyelement LANGUAGE plpgsql IMMUTABLE AS $$ `
        + "BEGIN IF cardinality(a) > 1 THEN RAISE EXCEPTION "
        + "'metaobjects: cannot narrow an array of % elements to one value', cardinality(a); "
        + "END IF; RETURN a[1]; END $$;",
      `ALTER TABLE "t" ALTER COLUMN "c" TYPE TEXT USING ${NARROW}("c");`,
      `DROP FUNCTION IF EXISTS ${NARROW}(anyarray);`,
    ]);
  });

  // `"c"[1]` would silently keep the first element of a longer row, and the bare
  // assignment cast to text would store the literal '{a,b}' as the value.
  test("removing isArray narrows through the refusing helper, casting where the element needs it", () => {
    const { up } = emit([typeChange(arrayOf(TEXT), INT)], { dialect: "postgres" });
    expect(up).toContain(`ALTER TABLE "t" ALTER COLUMN "c" TYPE INTEGER USING ${NARROW}("c")::INTEGER;`);
    expect(up).toContain(`DROP FUNCTION IF EXISTS ${NARROW}(anyarray);`);
  });

  // An explicit cast to VARCHAR(n) TRUNCATES an over-length value silently, where the
  // assignment cast a bare ALTER uses refuses it.
  test("to a bounded VARCHAR stays bare, so an over-length value is refused, not truncated", () => {
    const { up } = emit([typeChange(INT, { kind: "text", maxLength: 5 })], { dialect: "postgres" });
    expect(up).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE VARCHAR(5);`);
  });

  // Postgres converts a DEFAULT by assignment cast and never through USING, so
  // `varchar DEFAULT 'DRAFT'` → `INTEGER USING …` failed even on an empty table.
  test("a default in the way of a converting change is dropped first and set again after", () => {
    const { up, down } = emit([typeChange(TEXT, INT, {
      fromDefault: { kind: "literal", value: "DRAFT" }, toDefault: { kind: "expr", value: "5" },
    })], { dialect: "postgres" });
    expect(up.split("\n")).toEqual([
      `ALTER TABLE "t" ALTER COLUMN "c" DROP DEFAULT;`,
      `ALTER TABLE "t" ALTER COLUMN "c" TYPE INTEGER USING "c"::INTEGER;`,
      `ALTER TABLE "t" ALTER COLUMN "c" SET DEFAULT 5;`,
    ]);
    expect(down.split("\n")).toEqual([
      `ALTER TABLE "t" ALTER COLUMN "c" DROP DEFAULT;`,
      `ALTER TABLE "t" ALTER COLUMN "c" TYPE TEXT;`,
      `ALTER TABLE "t" ALTER COLUMN "c" SET DEFAULT 'DRAFT';`,
    ]);
  });

  test("an unchanged default on a change Postgres converts itself stays one statement", () => {
    const zero = { kind: "expr", value: "0" } as const;
    const { up } = emit([typeChange(INT, { kind: "integer", bits: 64 }, { fromDefault: zero, toDefault: zero })],
      { dialect: "postgres" });
    expect(up).toBe(`ALTER TABLE "t" ALTER COLUMN "c" TYPE BIGINT;`);
  });
});
