// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Exercise (Exercise)
// Customize via Exercise.extra.ts in this directory (additional queries, custom logic).
import { eq, sql } from "drizzle-orm";

import { db } from "~/server/db";
import { type Exercise, ExerciseInsertSchema, exercises } from "./Exercise";
const findExerciseByIdBase = db
  .select()
  .from(exercises)
  .where(eq(exercises.id, sql.placeholder("id")));
const findExerciseByIdPrepared = findExerciseByIdBase.prepare();

export async function findExerciseById(id: number): Promise<Exercise | null> {
  const [exercise] = await findExerciseByIdPrepared.execute({ id });
  return exercise ?? null;
}
export async function listExercises(opts?: {
  limit?: number;
  offset?: number;
}): Promise<Exercise[]> {
  let q = db.select().from(exercises).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createExercise(data: unknown): Promise<Exercise> {
  const validated = ExerciseInsertSchema.parse(data);
  const [exercise] = await db.insert(exercises).values(validated).returning();
  return exercise!;
}
export async function updateExercise(
  id: number,
  data: unknown,
): Promise<Exercise | null> {
  const validated = ExerciseInsertSchema.partial().parse(data);
  const [exercise] = await db
    .update(exercises)
    .set(validated)
    .where(eq(exercises.id, id))
    .returning();
  return exercise ?? null;
}
export async function deleteExerciseById(id: number): Promise<boolean> {
  const result = await db.delete(exercises).where(eq(exercises.id, id));
  // SQLite (libsql/Turso) returns { rowsAffected }; postgres returns array from .returning()
  return (
    ("rowsAffected" in result
      ? result.rowsAffected
      : (result as unknown as unknown[]).length) > 0
  );
}
