// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Tag (Tag)
// Customize via Tag.extra.ts in this directory (additional queries, custom logic).
import { eq } from "drizzle-orm";

import type { BaseSQLiteDatabase } from "drizzle-orm/sqlite-core";
type Db = BaseSQLiteDatabase<
  "sync" | "async",
  unknown,
  Record<string, unknown>
>;

import {
  type Tag,
  TagInsertSchema,
  type TagPatch,
  tags,
  TagUpdateSchema,
} from "./Tag";
export async function findTagById(db: Db, id: number): Promise<Tag | null> {
  const [tag] = await db.select().from(tags).where(eq(tags.id, id)).limit(1);
  return tag ?? null;
}
export async function listTags(
  db: Db,
  opts?: { limit?: number; offset?: number },
): Promise<Tag[]> {
  let q = db.select().from(tags).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createTag(db: Db, data: unknown): Promise<Tag> {
  const validated = TagInsertSchema.parse(data);
  const [tag] = await db.insert(tags).values(validated).returning();
  return tag!;
}
export async function updateTag(
  db: Db,
  id: number,
  patch: TagPatch,
): Promise<Tag | null> {
  const validated = TagUpdateSchema.parse(patch);
  // PATCH-5: an empty patch is a no-op — return the current row rather than let
  // Drizzle throw on an empty SET clause.
  if (Object.keys(validated).length === 0) {
    return findTagById(db, id);
  }
  const [tag] = await db
    .update(tags)
    .set(validated)
    .where(eq(tags.id, id))
    .returning();
  return tag ?? null;
}
export async function deleteTagById(db: Db, id: number): Promise<boolean> {
  // Use .returning() unconditionally — supported on SQLite ≥3.35 (covers D1, libsql/Turso)
  // and Postgres. Result is an array of deleted rows; presence implies success.
  const deleted = await db.delete(tags).where(eq(tags.id, id)).returning();
  return deleted.length > 0;
}
