// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Video (Video)
// Extend in your own module (e.g. Video.extra.ts) — nothing imports it for you.
import { db } from "~/server/db";
import {
  Video,
  VideoFilterAllowlist,
  VideoInsertSchema,
  videos,
  VideoSortAllowlist,
  VideoUpdateSchema,
} from "./Video";
import { mountCrudRoutes } from "@metaobjectsdev/runtime-ts/drizzle-fastify";
import type { FastifyInstance } from "fastify";

/**
 * Mount the 5 standard REST endpoints for Video using Drizzle directly.
 *
 * Customize: register this as-is for stock CRUD, OR import the per-verb
 * helpers (mountListRoute, mountGetRoute, ...) from
 * @metaobjectsdev/runtime-ts/drizzle-fastify and mix with your own handlers
 * (auth, side effects, etc.).
 *
 * Auth: these endpoints are unauthenticated. Register this inside a scope that
 * carries your hook and every verb below is guarded — routes outside that scope
 * are not:
 *
 *     app.register(async (s) => {
 *       s.addHook("preHandler", requireAuth);
 *       await videoRoutes(s);
 *     });
 *
 * A row-ownership rule ("only the owner may read this row") is not expressible in a
 * mount. Hand-write those verbs and narrow this file with
 * routesFile({ expose: ["list", "get"] }) rather than mounting them open.
 */
export async function videoRoutes(fastify: FastifyInstance) {
  mountCrudRoutes({
    fastify,
    path: Video.$path,
    db,
    table: videos,
    insertSchema: VideoInsertSchema,
    updateSchema: VideoUpdateSchema,
    filterAllowlist: VideoFilterAllowlist,
    sortAllowlist: VideoSortAllowlist,
    dialect: "sqlite",
  });
}
