// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: Video (Video)
// Customize via Video.extra.tsx (custom layouts, per-field components, etc.).
import { Video, VideoInsertSchema, VideoUpdateSchema } from "./Video";
import type { Video as VideoRow } from "./Video";
import { useEntityForm } from "@metaobjectsdev/react";
import type { ReactElement } from "react";
import type { SubmitHandler } from "react-hook-form";

const BLANK_OPTIONAL_FIELDS = ["title", "durationSeconds"] as const;

/**
 * Normalize blank optional inputs on the way out of the form (#223).
 * On create a blank field is OMITTED (the column defaults); on edit it is sent as
 * explicit `null` (present-null clears, per the FR-035 PATCH tristate).
 */
function normalizeBlankOptionals(values: Record<string, unknown>, isEdit: boolean): Record<string, unknown> {
  const out: Record<string, unknown> = { ...values };
  for (const key of BLANK_OPTIONAL_FIELDS) {
    if (out[key] !== "") {
      continue;
    }
    if (isEdit) {
      out[key] = null;
    } else {
      delete out[key];
    }
  }
  return out;
}

export interface VideoFormProps {
  onSubmit: SubmitHandler<Partial<VideoRow>>;
  defaultValues?: Partial<VideoRow>;
  submitLabel?: string;
  className?: string;
}

/**
 * Generated React form for Video. All field metadata (name, label,
 * placeholder, html input type, RHF validation rules) comes from the
 * Video constants emitted alongside this file. Validation uses the
 * generated Zod schema, shared with the server-side Fastify route.
 *
 * Customize: this file is regenerated on every `forge gen`. If you need a
 * custom layout, write your own component using useEntityForm + the
 * Video constants directly.
 */
export function VideoForm(props: VideoFormProps): ReactElement {
  const form = useEntityForm(
    Video,
    props.defaultValues !== undefined ? VideoUpdateSchema : VideoInsertSchema,
    props.defaultValues !== undefined ? { defaultValues: props.defaultValues } : {},
  );
  return (
    <form
      className={props.className ?? "metaobjects-form"}
      data-entity={Video.$entity}
      onSubmit={form.handleSubmit(
        ((values: Record<string, unknown>, event?: unknown) =>
          props.onSubmit(
            normalizeBlankOptionals(values, props.defaultValues !== undefined) as never,
            event as never,
          )) as never,
      )}
    >
      <div className="metaobjects-field" key="exerciseId">
        <label className="metaobjects-field-label" htmlFor={Video.exerciseId.name}>{Video.exerciseId.label}</label>
        <input className="metaobjects-field-input" {...form.input.exerciseId} />
        {form.formState.errors.exerciseId !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.exerciseId?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="url">
        <label className="metaobjects-field-label" htmlFor={Video.url.name}>{Video.url.label}</label>
        <input className="metaobjects-field-input" {...form.input.url} />
        {form.formState.errors.url !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.url?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="title">
        <label className="metaobjects-field-label" htmlFor={Video.title.name}>{Video.title.label}</label>
        <input className="metaobjects-field-input" {...form.input.title} />
        {form.formState.errors.title !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.title?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-field" key="durationSeconds">
        <label className="metaobjects-field-label" htmlFor={Video.durationSeconds.name}>
          {Video.durationSeconds.label}
        </label>
        <input className="metaobjects-field-input" {...form.input.durationSeconds} />
        {form.formState.errors.durationSeconds !== undefined && (
          <span className="metaobjects-field-error" role="alert">
            {String(form.formState.errors.durationSeconds?.message ?? "")}
          </span>
        )}
      </div>
      <div className="metaobjects-form-actions">
        <button className="metaobjects-form-submit" type="submit" disabled={form.formState.isSubmitting}>
          {props.submitLabel ?? "Submit"}
        </button>
      </div>
    </form>
  );
}
