// @generated by @metaobjects/codegen-ts — DO NOT EDIT.
// Source metadata: Week (Week)
// Customize via Week.extra.ts in this directory (additional queries, custom logic).
import { eq, sql } from "drizzle-orm";

import { db } from "~/server/db";
import { type Week, WeekInsertSchema, weeks } from "./Week";
const findWeekByIdBase = db
  .select()
  .from(weeks)
  .where(eq(weeks.id, sql.placeholder("id")));
const findWeekByIdPrepared = findWeekByIdBase.prepare();

export async function findWeekById(id: number): Promise<Week | null> {
  const [week] = await findWeekByIdPrepared.execute({ id });
  return week ?? null;
}
export async function listWeeks(opts?: {
  limit?: number;
  offset?: number;
}): Promise<Week[]> {
  let q = db.select().from(weeks).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createWeek(data: unknown): Promise<Week> {
  const validated = WeekInsertSchema.parse(data);
  const [week] = await db.insert(weeks).values(validated).returning();
  return week!;
}
export async function updateWeek(
  id: number,
  data: unknown,
): Promise<Week | null> {
  const validated = WeekInsertSchema.partial().parse(data);
  const [week] = await db
    .update(weeks)
    .set(validated)
    .where(eq(weeks.id, id))
    .returning();
  return week ?? null;
}
export async function deleteWeekById(id: number): Promise<boolean> {
  const result = await db.delete(weeks).where(eq(weeks.id, id));
  // SQLite (libsql/Turso) returns { rowsAffected }; postgres returns array from .returning()
  return (
    ("rowsAffected" in result
      ? result.rowsAffected
      : (result as unknown as unknown[]).length) > 0
  );
}
