// @generated by @metaobjectsdev/codegen-ts — DO NOT EDIT.
// Source metadata: WorkoutEvent (WorkoutEvent)
// Customize via WorkoutEvent.extra.ts in this directory (additional queries, custom logic).
import { eq, sql } from "drizzle-orm";

import { db } from "~/server/db";
import {
  type WorkoutEvent,
  WorkoutEventInsertSchema,
  workoutEvents,
} from "./WorkoutEvent";
const findWorkoutEventByIdBase = db
  .select()
  .from(workoutEvents)
  .where(eq(workoutEvents.id, sql.placeholder("id")));
const findWorkoutEventByIdPrepared = findWorkoutEventByIdBase.prepare();

export async function findWorkoutEventById(
  id: number,
): Promise<WorkoutEvent | null> {
  const [workoutEvent] = await findWorkoutEventByIdPrepared.execute({ id });
  return workoutEvent ?? null;
}
export async function listWorkoutEvents(opts?: {
  limit?: number;
  offset?: number;
}): Promise<WorkoutEvent[]> {
  let q = db.select().from(workoutEvents).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  return q;
}
export async function createWorkoutEvent(data: unknown): Promise<WorkoutEvent> {
  const validated = WorkoutEventInsertSchema.parse(data);
  const [workoutEvent] = await db
    .insert(workoutEvents)
    .values(validated)
    .returning();
  return workoutEvent!;
}
export async function updateWorkoutEvent(
  id: number,
  data: unknown,
): Promise<WorkoutEvent | null> {
  const validated = WorkoutEventInsertSchema.partial().parse(data);
  const [workoutEvent] = await db
    .update(workoutEvents)
    .set(validated)
    .where(eq(workoutEvents.id, id))
    .returning();
  return workoutEvent ?? null;
}
export async function deleteWorkoutEventById(id: number): Promise<boolean> {
  const result = await db.delete(workoutEvents).where(eq(workoutEvents.id, id));
  // SQLite (libsql/Turso) returns { rowsAffected }; postgres returns array from .returning()
  return (
    ("rowsAffected" in result
      ? result.rowsAffected
      : (result as unknown as unknown[]).length) > 0
  );
}
