// @generated by @metaobjectsdev/codegen-ts — hand edits are kept by a three-way merge on regeneration; meta verify --codegen checks only the generated parts.
// Source metadata: WorkoutEvent (WorkoutEvent)
// Extend in your own module (e.g. WorkoutEvent.extra.ts) — nothing imports it for you.
import {
  type InferInsertModel,
  type InferSelectModel,
  relations,
  sql,
} from "drizzle-orm";
import {
  type AnySQLiteColumn,
  integer,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";
import { z } from "zod";
import { subscribers } from "./Subscriber";
import { workouts } from "./Workout";

export const workoutEvents = sqliteTable("workout_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  subscriberId: integer("subscriber_id")
    .notNull()
    .references((): AnySQLiteColumn => subscribers.id),
  workoutId: integer("workout_id")
    .notNull()
    .references((): AnySQLiteColumn => workouts.id),
  completedAt: text("completed_at").notNull().default(sql`CURRENT_TIMESTAMP`),
  durationMinutes: integer("duration_minutes"),
});
export const workoutEventsRelations = relations(workoutEvents, ({ one }) => ({
  subscriber: one(subscribers, {
    fields: [workoutEvents.subscriberId],
    references: [subscribers.id],
  }),
  workout: one(workouts, {
    fields: [workoutEvents.workoutId],
    references: [workouts.id],
  }),
}));
export type WorkoutEvent = InferSelectModel<typeof workoutEvents>;
export type WorkoutEventInsert = InferInsertModel<typeof workoutEvents>;
export type WorkoutEventUpdate = Partial<WorkoutEventInsert>;
/** A zoned field.timestamp value in its instant's toISOString() spelling; a naive one as sent.
 *  SQLite/D1 compare timestamps as text, so zoned values are stored in UTC. Generated. */
function utcIsoTimestamp(v: string): string {
  const m =
    /^(\d{4}-\d{2}-\d{2})[Tt ](\d{2}:\d{2})(?::(\d{2})(?:\.(\d+))?)?(?:([Zz])|([+-]\d{2}):?(\d{2})?)$/.exec(
      v,
    );
  if (m === null) {
    return v;
  }
  const t = Date.parse(
    `${m[1]}T${m[2]}:${m[3] ?? "00"}.${(m[4] ?? "").slice(0, 3).padEnd(3, "0")}${
      m[5] === undefined ? `${m[6]}:${m[7] ?? "00"}` : "Z"
    }`,
  );
  return Number.isNaN(t) ? v : new Date(t).toISOString();
}

export const WorkoutEventInsertSchema = z.object({
  subscriberId: z.number().int(),
  workoutId: z.number().int(),
  completedAt: z
    .string()
    .regex(
      /^(?:\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|02-(?:0[1-9]|1\d|2[0-8]))|(?:\d{2}(?:0[48]|[2468][048]|[13579][26])|(?:[02468][048]|[13579][26])00)-02-29)(?:[Tt ](?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:[Zz]|[+-](?:[01]\d|2[0-3])(?::?[0-5]\d)?)?)?$/,
      "must be an ISO 8601 timestamp (YYYY-MM-DD[THH:MM[:SS[.fff]]][Z|±HH:MM])",
    )
    .transform(utcIsoTimestamp)
    .optional(),
  durationMinutes: z.number().int().optional(),
});

export const WorkoutEventUpdateSchema = z.object({
  subscriberId: z.number().int().optional(),
  workoutId: z.number().int().optional(),
  completedAt: z
    .string()
    .regex(
      /^(?:\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|02-(?:0[1-9]|1\d|2[0-8]))|(?:\d{2}(?:0[48]|[2468][048]|[13579][26])|(?:[02468][048]|[13579][26])00)-02-29)(?:[Tt ](?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:[Zz]|[+-](?:[01]\d|2[0-3])(?::?[0-5]\d)?)?)?$/,
      "must be an ISO 8601 timestamp (YYYY-MM-DD[THH:MM[:SS[.fff]]][Z|±HH:MM])",
    )
    .transform(utcIsoTimestamp)
    .optional(),
  durationMinutes: z.number().int().optional().nullable(),
});

/** Typed create shape for WorkoutEvent: the insert schema's INPUT (pre-transform) type. A
 * renamed/dropped/misspelt field is a compile error at every `createWorkoutEvent` call site;
 * the schema still validates at runtime. */
export type WorkoutEventCreate = z.input<typeof WorkoutEventInsertSchema>;

/** Typed patch shape for WorkoutEvent: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updateWorkoutEvent` call site. */
export type WorkoutEventPatch = z.input<typeof WorkoutEventUpdateSchema>;
/**
 * Metadata constants for WorkoutEvent.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, an htmlType where the field's view maps to one, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * placeholder and helpText are NOT emitted — no provider registers an attribute
 * for them, so nothing here could derive one. (htmlType is emitted, but derived
 * from the view subtype; the @htmlType override was removed for the same reason.)
 * useEntityForm still honours placeholder if you add it: this file is generated,
 * hand edits inside it survive regeneration through the three-way merge, and the
 * consumers read this const rather than the metadata. That is the intended way
 * to set it.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(WorkoutEvent, WorkoutEventInsertSchema);
 *   <input {...form.input.id} />
 */
export const WorkoutEvent = {
  $entity: "WorkoutEvent",
  $table: "workout_events",
  $path: "/workout_events",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  subscriberId: {
    name: "subscriberId",
    label: "Subscriber Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Subscriber Id is required" },
  },
  workoutId: {
    name: "workoutId",
    label: "Workout Id",
    view: "number",
    htmlType: "number",
    rules: { required: "Workout Id is required" },
  },
  completedAt: {
    name: "completedAt",
    label: "Completed At",
    view: "date",
    htmlType: "datetime-local",
    rules: { required: "Completed At is required" },
  },
  durationMinutes: {
    name: "durationMinutes",
    label: "Duration Minutes",
    view: "number",
    htmlType: "number",
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const WorkoutEventFilterAllowlist =
  {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const WorkoutEventSortAllowlist = {} as const satisfies SortAllowlist;
export type WorkoutEventFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: WorkoutEventFilter[];
  and?: WorkoutEventFilter[];
};
