// @generated by @metaobjectsdev/codegen-ts — hand edits are kept by a three-way merge on regeneration; meta verify --codegen checks only the generated parts.
// Source metadata: Brewer (Brewer)
// Extend in your own module (e.g. Brewer.extra.ts) — nothing imports it for you.
import type { InferInsertModel, InferSelectModel } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { z } from "zod";

export const brewers = sqliteTable("brewers", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  displayName: text("display_name").notNull(),
  email: text("email").notNull(),
  createdAt: text("created_at")
    .notNull()
    .$defaultFn(() => new Date().toISOString()),
});
export type Brewer = InferSelectModel<typeof brewers>;
export type BrewerInsert = InferInsertModel<typeof brewers>;
export type BrewerUpdate = Partial<BrewerInsert>;
/** A field.timestamp instant in UTC (`YYYY-MM-DDTHH:MM:SS[.fff]Z`): a value already spelled so is kept
 *  as sent, an offset is applied, a zoneless value is UTC and a date alone is midnight UTC.
 *  SQLite/D1 compare timestamps as text, so instants are stored in UTC. Generated. */
function utcIsoTimestamp(v: string): string {
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(v)) {
    return v;
  }
  const m =
    /^(\d{4}-\d{2}-\d{2})(?:[Tt ](\d{2}:\d{2})(?::(\d{2})(?:\.(\d+))?)?(?:([Zz])|([+-]\d{2}):?(\d{2})?)?)?$/.exec(
      v,
    );
  if (m === null) {
    return v;
  }
  const t = Date.parse(
    `${m[1]}T${m[2] ?? "00:00"}:${m[3] ?? "00"}.${(m[4] ?? "").slice(0, 3).padEnd(3, "0")}${
      m[6] === undefined ? "Z" : `${m[6]}:${m[7] ?? "00"}`
    }`,
  );
  return Number.isNaN(t)
    ? v
    : new Date(t).toISOString().replace(/\.?0+Z$/, "Z");
}

export const BrewerInsertSchema = z.object({
  displayName: z.string().min(1).max(80),
  email: z.string().min(1),
  createdAt: z
    .string()
    .optional()
    .transform(() => new Date().toISOString()),
});

export const BrewerUpdateSchema = z.object({
  displayName: z.string().min(1).max(80).optional(),
  email: z.string().min(1).optional(),
});

/** Typed create shape for Brewer: the insert schema's INPUT (pre-transform) type. A
 * renamed/dropped/misspelt field is a compile error at every `createBrewer` call site;
 * the schema still validates at runtime. */
export type BrewerCreate = z.input<typeof BrewerInsertSchema>;

/** Typed patch shape for Brewer: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updateBrewer` call site. */
export type BrewerPatch = z.input<typeof BrewerUpdateSchema>;

/** Insert-shape for import / restore / replication of Brewer: identical to
 * BrewerInsertSchema, but the @autoSet timestamp columns are written VERBATIM
 * (no create-time now() stamp) so the caller's original values are preserved. */
export const BrewerInsertPreservingSchema = z.object({
  displayName: z.string().min(1).max(80),
  email: z.string().min(1),
  createdAt: z
    .string()
    .regex(
      /^(?:\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|02-(?:0[1-9]|1\d|2[0-8]))|(?:\d{2}(?:0[48]|[2468][048]|[13579][26])|(?:[02468][048]|[13579][26])00)-02-29)(?:[Tt ](?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:[Zz]|[+-](?:[01]\d|2[0-3])(?::?[0-5]\d)?)?)?$/,
      "must be an ISO 8601 timestamp (YYYY-MM-DD[THH:MM[:SS[.fff]]][Z|±HH:MM])",
    )
    .transform(utcIsoTimestamp),
});

/** Typed input of `insertPreservingBrewer` — BrewerInsertPreservingSchema's pre-transform shape. */
export type BrewerCreatePreserving = z.input<
  typeof BrewerInsertPreservingSchema
>;
/**
 * Metadata constants for Brewer.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, an htmlType where the field's view maps to one, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * placeholder and helpText are NOT emitted — no provider registers an attribute
 * for them, so nothing here could derive one. (htmlType is emitted, but derived
 * from the view subtype; the @htmlType override was removed for the same reason.)
 * useEntityForm still honours placeholder if you add it: this file is generated,
 * hand edits inside it survive regeneration through the three-way merge, and the
 * consumers read this const rather than the metadata. That is the intended way
 * to set it.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(Brewer, BrewerInsertSchema);
 *   <input {...form.input.id} />
 */
export const Brewer = {
  $entity: "Brewer",
  $table: "brewers",
  $path: "/brewers",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  displayName: {
    name: "displayName",
    label: "Display Name",
    view: "text",
    htmlType: "text",
    rules: {
      required: "Display Name is required",
      maxLength: { value: 80, message: "Must be 80 characters or fewer" },
    },
  },
  email: {
    name: "email",
    label: "Email",
    view: "text",
    htmlType: "text",
    rules: { required: "Email is required" },
  },
  createdAt: {
    name: "createdAt",
    label: "Created At",
    view: "date",
    htmlType: "datetime-local",
    rules: { required: "Created At is required" },
  },
} as const;
export type BrewerFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: BrewerFilter[];
  and?: BrewerFilter[];
};
