// @generated by @metaobjectsdev/codegen-ts — hand edits are kept by a three-way merge on regeneration; meta verify --codegen checks only the generated parts.
// Source metadata: Carrier (Carrier)
// Extend in your own module (e.g. Carrier.extra.ts) — nothing imports it for you.
import { z } from "zod";

export interface Carrier {
  id?: number | undefined;
  partyType?: CarrierPartyType | null | undefined;
  label: string;
  fleetSize?: number | null | undefined;
}
export type CarrierPartyType = "Carrier";
export const CarrierPartyTypeEnum = z.enum(["Carrier"]);
export const CarrierSchema = z.object({
  id: z.number().int(),
  partyType: z.literal("Carrier"),
  label: z.string().min(1),
  fleetSize: z.number().int().nullable(),
});
export const CarrierInsertSchema = z.object({
  partyType: z.literal("Carrier"),
  label: z.string().min(1),
  fleetSize: z.number().int().optional(),
});

export const CarrierUpdateSchema = z.object({
  label: z.string().min(1).optional(),
  fleetSize: z.number().int().optional().nullable(),
});

/** Typed create shape for Carrier: the insert schema's INPUT (pre-transform) type. A
 * renamed/dropped/misspelt field is a compile error at every `createCarrier` call site;
 * the schema still validates at runtime. */
export type CarrierCreate = z.input<typeof CarrierInsertSchema>;

/** Typed patch shape for Carrier: every settable field, optional (FR-035 PATCH). A
 * renamed/dropped field is a compile error at every `updateCarrier` call site. */
export type CarrierPatch = z.input<typeof CarrierUpdateSchema>;
/**
 * Metadata constants for Carrier.
 *
 * Use these instead of magic strings so TS catches typos and refactors stay
 * coherent. Each non-dollar-prefixed key is a per-field object carrying
 * name, label, view, an htmlType where the field's view maps to one, and the
 * RHF-shaped validation rules derived from the field's validator children.
 *
 * placeholder and helpText are NOT emitted — no provider registers an attribute
 * for them, so nothing here could derive one. (htmlType is emitted, but derived
 * from the view subtype; the @htmlType override was removed for the same reason.)
 * useEntityForm still honours placeholder if you add it: this file is generated,
 * hand edits inside it survive regeneration through the three-way merge, and the
 * consumers read this const rather than the metadata. That is the intended way
 * to set it.
 *
 * Typical usage with the metaobjects React form helper:
 *
 *   import { useEntityForm } from '@metaobjectsdev/react';
 *   const form = useEntityForm(Carrier, CarrierInsertSchema);
 *   <input {...form.input.id} />
 */
export const Carrier = {
  $entity: "Carrier",
  $table: "parties",
  $path: "/parties/carrier",
  id: { name: "id", label: "Id", view: "number", htmlType: "number" },
  partyType: {
    name: "partyType",
    label: "Party Type",
    view: "dropdown",
    options: ["Carrier"] as const,
  },
  label: {
    name: "label",
    label: "Label",
    view: "text",
    htmlType: "text",
    rules: { required: "Label is required" },
  },
  fleetSize: {
    name: "fleetSize",
    label: "Fleet Size",
    view: "number",
    htmlType: "number",
  },
} as const;
import type { FilterAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const CarrierFilterAllowlist = {} as const satisfies FilterAllowlist;
import type { SortAllowlist } from "@metaobjectsdev/runtime-ts/drizzle-fastify";

export const CarrierSortAllowlist = {} as const satisfies SortAllowlist;
export type CarrierFilter = {
  limit?: number;
  offset?: number;
  sort?: string;
  or?: CarrierFilter[];
  and?: CarrierFilter[];
};
