// @generated by @metaobjectsdev/codegen-ts — hand edits are kept by a three-way merge on regeneration; meta verify --codegen checks only the generated parts.
// Source metadata: Party (Party) — TPH discriminator base
// Extend in your own module (e.g. Party.extra.ts) — nothing imports it for you.
import { and, eq } from "drizzle-orm";
import type { z } from "zod";
import { type Carrier, CarrierInsertSchema, CarrierSchema } from "./Carrier.js";
import { parseParty, parties, type Party } from "./Party.js";

import type { BaseSQLiteDatabase } from "drizzle-orm/sqlite-core";
type Db = BaseSQLiteDatabase<
  "sync" | "async",
  unknown,
  Record<string, unknown>
>;
export async function findPartyById(db: Db, id: number): Promise<Party | null> {
  const [row] = await db
    .select()
    .from(parties)
    .where(eq(parties.id, id))
    .limit(1);
  return row ? parseParty(row) : null;
}

export async function listParties(
  db: Db,
  opts?: { limit?: number; offset?: number },
): Promise<Party[]> {
  let q = db.select().from(parties).$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  const rows = await q;
  return rows.map((r) => parseParty(r));
}
export async function listCarriers(
  db: Db,
  opts?: { limit?: number; offset?: number },
): Promise<Carrier[]> {
  let q = db
    .select()
    .from(parties)
    .where(eq(parties.partyType, "Carrier"))
    .$dynamic();
  if (opts?.limit !== undefined) {
    q = q.limit(opts.limit);
  }
  if (opts?.offset !== undefined) {
    q = q.offset(opts.offset);
  }
  const rows = await q;
  return rows.map((r) => CarrierSchema.parse(r));
}

export async function findCarrierById(
  db: Db,
  id: number,
): Promise<Carrier | null> {
  const [row] = await db
    .select()
    .from(parties)
    .where(and(eq(parties.id, id), eq(parties.partyType, "Carrier")))
    .limit(1);
  return row ? CarrierSchema.parse(row) : null;
}

export async function createCarrier(
  db: Db,
  data: z.input<typeof CarrierInsertSchema>,
): Promise<Carrier> {
  const validated = CarrierInsertSchema.parse(data);
  const [row] = await db
    .insert(parties)
    .values({ ...validated, partyType: "Carrier" })
    .returning();
  return CarrierSchema.parse(row!);
}

export async function updateCarrierById(
  db: Db,
  id: number,
  data: Partial<z.input<typeof CarrierInsertSchema>>,
): Promise<Carrier | null> {
  const validated = CarrierInsertSchema.partial().parse(data) as Record<
    string,
    unknown
  >;
  // The discriminator is immutable — a Carrier can never become another subtype.
  const { ["partyType"]: _disc, ...safe } = validated;
  const [row] = await db
    .update(parties)
    .set(safe)
    .where(and(eq(parties.id, id), eq(parties.partyType, "Carrier")))
    .returning();
  return row ? CarrierSchema.parse(row) : null;
}

export async function deleteCarrierById(db: Db, id: number): Promise<boolean> {
  const deleted = await db
    .delete(parties)
    .where(and(eq(parties.id, id), eq(parties.partyType, "Carrier")))
    .returning();
  return deleted.length > 0;
}
