// @generated by @metaobjectsdev/codegen-ts-tanstack — DO NOT EDIT.
// Source metadata: Program (Program)
import { Program } from "./Program";
import type { Program as ProgramRow } from "./Program";
import { buildFilterQs } from "@metaobjectsdev/runtime-web";
import { useEntityFetcher } from "@metaobjectsdev/tanstack";
import { useQuery } from "@tanstack/react-query";
import type {
  ColumnFiltersState,
  PaginationState,
  SortingState,
} from "@tanstack/react-table";
import { useMemo, useState } from "react";

export function useProgramDefaultGrid() {
  const [sorting, setSorting] = useState<SortingState>([]);
  const [pagination, setPagination] = useState<PaginationState>({
    pageIndex: 0,
    pageSize: 25,
  });
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
  const [search, setSearch] = useState<string>("");

  const fetcher = useEntityFetcher();

  const qs = useMemo(() => {
    const filterObj: Record<string, unknown> = {};
    for (const f of columnFilters) {
      filterObj[f.id] = f.value as unknown;
    }
    const sortEntry = sorting[0];
    const sort = sortEntry
      ? `${sortEntry.id}:${sortEntry.desc ? "desc" : "asc"}`
      : undefined;
    return buildFilterQs({
      ...filterObj,
      ...(sort !== undefined ? { sort } : {}),
      limit: pagination.pageSize,
      offset: pagination.pageIndex * pagination.pageSize,
      ...(search !== "" ? { search } : {}),
      withCount: 1,
    });
  }, [sorting, pagination, columnFilters, search]);

  const query = useQuery<{ rows: ProgramRow[]; total: number }>({
    queryKey: ["program", "grid", "default", qs],
    queryFn: () =>
      fetcher<{ rows: ProgramRow[]; total: number }>(
        `${Program.$apiPrefix}${Program.$path}?${qs}`,
      ),
  });

  return {
    data: query.data?.rows ?? [],
    rowCount: query.data?.total ?? 0,
    state: { sorting, pagination, columnFilters },
    onSortingChange: setSorting,
    onPaginationChange: setPagination,
    onColumnFiltersChange: setColumnFilters,
    search,
    onSearchChange: setSearch,
    isLoading: query.isLoading,
    error: query.error,
  };
}
export function useProgramCompactGrid() {
  const [sorting, setSorting] = useState<SortingState>([]);
  const [pagination, setPagination] = useState<PaginationState>({
    pageIndex: 0,
    pageSize: 50,
  });
  const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);
  const [search, setSearch] = useState<string>("");

  const fetcher = useEntityFetcher();

  const qs = useMemo(() => {
    const filterObj: Record<string, unknown> = {};
    for (const f of columnFilters) {
      filterObj[f.id] = f.value as unknown;
    }
    const sortEntry = sorting[0];
    const sort = sortEntry
      ? `${sortEntry.id}:${sortEntry.desc ? "desc" : "asc"}`
      : undefined;
    return buildFilterQs({
      ...filterObj,
      ...(sort !== undefined ? { sort } : {}),
      limit: pagination.pageSize,
      offset: pagination.pageIndex * pagination.pageSize,
      ...(search !== "" ? { search } : {}),
      withCount: 1,
    });
  }, [sorting, pagination, columnFilters, search]);

  const query = useQuery<{ rows: ProgramRow[]; total: number }>({
    queryKey: ["program", "grid", "compact", qs],
    queryFn: () =>
      fetcher<{ rows: ProgramRow[]; total: number }>(
        `${Program.$apiPrefix}${Program.$path}?${qs}`,
      ),
  });

  return {
    data: query.data?.rows ?? [],
    rowCount: query.data?.total ?? 0,
    state: { sorting, pagination, columnFilters },
    onSortingChange: setSorting,
    onPaginationChange: setPagination,
    onColumnFiltersChange: setColumnFilters,
    search,
    onSearchChange: setSearch,
    isLoading: query.isLoading,
    error: query.error,
  };
}
