// canonical-schema.ts — produce the canonical persistence-conformance schema DDL.
//
// TS is the single producer of one schema artifact that every port's
// query-scenario runner executes verbatim (see
// docs/superpowers/specs/2026-05-30-ts-schema-authority-consolidation-design.md).
//
// The DDL is a full-CREATE emit for the empty→expected diff: every base table,
// index, and FK, plus the projection views (v_program, v_program_stat). It is
// the exact same SQL the TS query-runner previously synthesized inline — now
// frozen to fixtures/persistence-conformance/canonical/schema.postgres.sql and
// drift-checked, so the committed artifact stays honest.
//
// Postgres only (Decision 1 in the design): one schema.postgres.sql serves all
// five ports' query scenarios against Testcontainers Postgres.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  type ColumnNamingStrategy,
  type MetaRoot,
} from "@metaobjectsdev/metadata";
import { buildExpectedSchema, diff, emit, type Dialect } from "@metaobjectsdev/migrate-ts";
import { buildProjectionViews } from "@metaobjectsdev/codegen-ts";

import { CANONICAL_DIR } from "./paths.ts";

/**
 * The dialect of the committed cross-port schema artifact. Postgres only —
 * every JVM/C#/Python conformance query run executes against Testcontainers
 * Postgres, and TS view synthesis emits the correlated-subquery view bodies
 * that match what introspection sees there.
 */
export const CANONICAL_SCHEMA_DIALECT: Dialect = "postgres";

/**
 * Column-naming strategy for the canonical schema. Pinned to "literal" so the
 * generated column names match the ObjectManager's runtime strategy the query
 * runners use (the runner constructs ObjectManager with `columnNamingStrategy:
 * "literal"`). A mismatch would yield a schema whose columns the runtime can't
 * address.
 */
export const CANONICAL_COLUMN_NAMING: ColumnNamingStrategy = "literal";

/** Absolute path to the committed canonical Postgres schema artifact. */
export const CANONICAL_SCHEMA_SQL_PATH = resolve(CANONICAL_DIR, "schema.postgres.sql");

const HEADER_LINES: readonly string[] = [
  "-- @generated by @metaobjectsdev/integration-tests — DO NOT EDIT.",
  "-- Canonical persistence-conformance schema (Postgres).",
  "-- Produced by TypeScript from canonical/meta.fitness.json; every port's",
  "-- query-scenario runner executes this file verbatim to provision its test DB.",
  "-- Regenerate: `bun run gen:schema` in this package. Drift-checked by",
  "-- schema-artifact.test.ts (CI fails if this file diverges from metadata).",
];

/**
 * Generate the canonical Postgres schema DDL from a loaded metadata root.
 *
 * Mirrors the (now-retired) inline synthesis in query-scenario.ts: build the
 * expected schema (tables + projection views), diff against an empty database,
 * and emit the full-CREATE `up` SQL. Deterministic given the same metadata —
 * table/view order follows declaration order; emit() applies a stable stage
 * sort — so the committed file does not churn.
 */
export async function generateCanonicalSchemaSql(root: MetaRoot): Promise<string> {
  const expected = buildExpectedSchema(root, {
    dialect: CANONICAL_SCHEMA_DIALECT,
    columnNamingStrategy: CANONICAL_COLUMN_NAMING,
    views: buildProjectionViews(root, {
      dialect: CANONICAL_SCHEMA_DIALECT,
      columnNamingStrategy: CANONICAL_COLUMN_NAMING,
    }),
  });
  const r = await diff({ expected, actual: { tables: [], views: [] } });
  const { up } = emit(r.changes, { dialect: CANONICAL_SCHEMA_DIALECT });
  return `${HEADER_LINES.join("\n")}\n\n${up}\n`;
}

/** Read the committed canonical Postgres schema artifact. */
export function readCanonicalSchemaSql(): string {
  return readFileSync(CANONICAL_SCHEMA_SQL_PATH, "utf8");
}

/**
 * What regeneration is about to replace, or undefined when it replaces nothing of
 * interest (no file yet, or the artifact is already current).
 *
 * WHY THIS IS NOT THE OVERWRITE POLICY. `meta gen` refuses to overwrite a generated file
 * that has diverged, because for adopter code the divergence is someone's work. Applying
 * that rule here would be actively wrong: this artifact's contract is generated-wins, and
 * refusing would block the very command that repairs a red drift gate. It is also
 * committed, so `git diff` already records what changed.
 *
 * What was actually missing is smaller: the replacement happened without a word. In
 * `553782a97` two hand-added lines explaining an int-backed enum's CHECK were discarded by
 * a regeneration, and the explanation was real content that belonged in the design doc.
 * Saying so at the moment of replacement is the whole fix.
 *
 * The line count is what distinguishes "I edited this file" from "the metadata moved on",
 * without pretending to diff semantically.
 */
export function describeRegenReplacement(
  existing: string | undefined,
  fresh: string,
): string | undefined {
  if (existing === undefined || existing === fresh) return undefined;

  const freshLines = new Set(fresh.split("\n"));
  const lost = existing.split("\n").filter((l) => !freshLines.has(l) && l.trim() !== "");
  const n = lost.length;
  // Nothing was LOST — the artifact merely grew (a table added to the metadata), so
  // every existing line still appears in fresh output. Saying "0 lines replaced" and
  // then advising the reader to move their reasoning into the design doc is noise on a
  // purely additive regeneration where nobody wrote anything.
  if (n === 0) return undefined;
  const noun = n === 1 ? "1 line" : `${n} lines`;
  const sample = lost.slice(0, 3).map((l) => `    ${l}`).join("\n");

  return (
    `NOTE: the file on disk differed from freshly generated output — ${noun} replaced:\n` +
    `${sample}${n > 3 ? `\n    …and ${n - 3} more` : ""}\n` +
    `  If that content was deliberate, it does not survive here: this artifact is\n` +
    `  regenerated from metadata. Move the reasoning into the design doc or CHANGELOG.`
  );
}
