// canonical-schema.ts — produce the canonical persistence-conformance schema DDL.
//
// TS is the single producer of one schema artifact that every port's
// query-scenario runner executes verbatim (see
// docs/superpowers/specs/2026-05-30-ts-schema-authority-consolidation-design.md).
//
// The DDL is a full-CREATE emit for the empty→expected diff: every base table,
// index, and FK, plus the projection views (v_program, v_program_stat). It is
// the exact same SQL the TS query-runner previously synthesized inline — now
// frozen to fixtures/persistence-conformance/canonical/schema.postgres.sql and
// drift-checked, so the committed artifact stays honest.
//
// Postgres only (Decision 1 in the design): one schema.postgres.sql serves all
// five ports' query scenarios against Testcontainers Postgres.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  type ColumnNamingStrategy,
  type MetaRoot,
} from "@metaobjectsdev/metadata";
import { buildExpectedSchema, diff, emit, type Dialect } from "@metaobjectsdev/migrate-ts";
import { buildProjectionViews } from "@metaobjectsdev/codegen-ts";

import { CANONICAL_DIR } from "./paths.ts";

/**
 * The dialect of the committed cross-port schema artifact. Postgres only —
 * every JVM/C#/Python conformance query run executes against Testcontainers
 * Postgres, and TS view synthesis emits the correlated-subquery view bodies
 * that match what introspection sees there.
 */
export const CANONICAL_SCHEMA_DIALECT: Dialect = "postgres";

/**
 * Column-naming strategy for the canonical schema. Pinned to "literal" so the
 * generated column names match the ObjectManager's runtime strategy the query
 * runners use (the runner constructs ObjectManager with `columnNamingStrategy:
 * "literal"`). A mismatch would yield a schema whose columns the runtime can't
 * address.
 */
export const CANONICAL_COLUMN_NAMING: ColumnNamingStrategy = "literal";

/** Absolute path to the committed canonical Postgres schema artifact. */
export const CANONICAL_SCHEMA_SQL_PATH = resolve(CANONICAL_DIR, "schema.postgres.sql");

const HEADER_LINES: readonly string[] = [
  "-- @generated by @metaobjectsdev/integration-tests — DO NOT EDIT.",
  "-- Canonical persistence-conformance schema (Postgres).",
  "-- Produced by TypeScript from canonical/meta.fitness.json; every port's",
  "-- query-scenario runner executes this file verbatim to provision its test DB.",
  "-- Regenerate: `bun run gen:schema` in this package. Drift-checked by",
  "-- schema-artifact.test.ts (CI fails if this file diverges from metadata).",
];

/**
 * Generate the canonical Postgres schema DDL from a loaded metadata root.
 *
 * Mirrors the (now-retired) inline synthesis in query-scenario.ts: build the
 * expected schema (tables + projection views), diff against an empty database,
 * and emit the full-CREATE `up` SQL. Deterministic given the same metadata —
 * table/view order follows declaration order; emit() applies a stable stage
 * sort — so the committed file does not churn.
 */
export async function generateCanonicalSchemaSql(root: MetaRoot): Promise<string> {
  const expected = buildExpectedSchema(root, {
    dialect: CANONICAL_SCHEMA_DIALECT,
    columnNamingStrategy: CANONICAL_COLUMN_NAMING,
    views: buildProjectionViews(root, {
      dialect: CANONICAL_SCHEMA_DIALECT,
      columnNamingStrategy: CANONICAL_COLUMN_NAMING,
    }),
  });
  const r = await diff({ expected, actual: { tables: [], views: [] } });
  const { up } = emit(r.changes, { dialect: CANONICAL_SCHEMA_DIALECT });
  return `${HEADER_LINES.join("\n")}\n\n${up}\n`;
}

/** Read the committed canonical Postgres schema artifact. */
export function readCanonicalSchemaSql(): string {
  return readFileSync(CANONICAL_SCHEMA_SQL_PATH, "utf8");
}
